### ISSUE TITLE
values dropped but it still reach  "max-values-per-tag"

### ISSUE THREAD

**Issue by zngj** [influxdata/influxdb#10018]
__System info:__     InfluxDB 1.4.3

__Steps to reproduce:__

I am using logstash to write data into influxdb. 

but suffered "max-values-per-tag limit exceeded" error, it told me tag values exceed 100000.

but when I use "SHOW TAG VALUES", it told me only 1 record inside.

Per check, my tag "uri" contains timestamp info, so it possible to exceed 100000 after a long run.(bad tag)

but per retention policy,  it only keep 1 day's data, I guess the internal counter won't decrease after the whole tag removed...  so it leads to "max-values-per-tag limit exceeded" but actually not exceed at the time

--
[2018-06-29T12:38:45,564][WARN ][logstash.outputs.influxdb] Non recoverable exception while writing to InfluxDB {:exception=>#<InfluxDB::Error: {"error":"partial write: max-values-per-tag limit exceeded (100000/100000): measurement=\"ad_detail\" tag=\"uri\" value=\"userBookMeal.html?t=1530247123912\" dropped=1"}

SHOW TAG VALUES FROM ad_detail with key = "uri" 
name: ad_detail
key value
--- -----
uri xxxxx.html

**Comment by e-dard** [comment]
@zngj are you sure that the shards that are older than one day have actually been dropped? We have an "expiration" period, that actually defines when they're removed from the system. Only then will the index be updated and the tag values count for a tag key be reduced. 

Can you confirm with `SHOW SHARDS` and on disk that they have actually been removed?

**Comment by benbjohnson** [comment]
@e-dard The `inmem.Index` currently checks against [`Index.TagValueN()`](https://github.com/influxdata/influxdb/blob/master/tsdb/index/inmem/inmem.go#L342-L352) which calculates cardinality across the whole database.

If we want to calculate per-shard then we'll need to maintain bitsets for every measurement on every shard. Is that an acceptable overhead? /cc @rbetts

**Comment by e-dard** [comment]
@benbjohnson `TagValueN` is doing the right thing currently, because this limit is a per-database one.

The issue here would be if dropping a shard with unique series in it does not update the value returned by `TagValueN`. Or possibly the limit is being cached and not updated when series are removed from the index?

If it’s neither of those cases then my feeling is that in this case the shard hasn’t been expired from the system yet. 

We can repro this by dropping a shard with unique series in and monitoring the impact on the max tags limit.

Another thought is - when we drop a shard due to retention, do we remove the series from the index then, or do we wait until the shard is physically removed from the system?

**Comment by benbjohnson** [comment]
I investigated this further and it looks like `1.5.x` regresses further and `SHOW TAG VALUES` caches values as well as `TagValueN()`. The tag values are no longer being tracked per-shard in `inmem` and it will require some rework to support it. Marking this as `medium` difficulty and to be prioritized.

**Comment by fdhex** [comment]
In a similar fashion, I am seeing about ~1000 tags with `SHOW TAG VALUES ...` but the DB is complaining that it's reaching its 100000 limit. What is the recommendation? Simply increasing the limit?

**Comment by korjavin** [comment]
We had the same recently. Only purging and influx restart helped

**Comment by e-dard** [comment]
I don't think we will be fixing this issue. Changing to the TSI index should resolve this.
