### ISSUE TITLE
Many Influxd processes with high CPU Load 

### ISSUE THREAD

**Issue by touatily** [influxdata/influxdb#10041]
__System info:__ [X-Influxdb-Version: 1.4.2, UBUNTU 14.04]

__Actual behavior:
High CPU load !

![image](https://user-images.githubusercontent.com/27826148/42317389-8daf2bb8-804c-11e8-833b-181165cd70f5.png)

__Additional info:__ [Include gist of relevant config, logs, etc.]

tail influxd.log gives 
```
[I] 2018-07-05T10:12:25Z Snapshot for path /var/lib/influxdb/data/_internal/monitor/239 written in 11.091µs engine=tsm1
[I] 2018-07-05T10:12:25Z error writing snapshot: error opening new segment file for wal (1): write /var/lib/influxdb/wal/_internal/monitor/239/_00032.wal: no space left on device engine=tsm1
[I] 2018-07-05T10:12:26Z Snapshot for path /var/lib/influxdb/data/_internal/monitor/239 written in 15.813µs engine=tsm1
[I] 2018-07-05T10:12:26Z error writing snapshot: error opening new segment file for wal (1): write /var/lib/influxdb/wal/_internal/monitor/239/_00032.wal: no space left on device engine=tsm1
[I] 2018-07-05T10:12:27Z Snapshot for path /var/lib/influxdb/data/_internal/monitor/239 written in 12.88µs engine=tsm1
[I] 2018-07-05T10:12:27Z error writing snapshot: error opening new segment file for wal (1): write /var/lib/influxdb/wal/_internal/monitor/239/_00032.wal: no space left on device engine=tsm1
[I] 2018-07-05T10:12:28Z Snapshot for path /var/lib/influxdb/data/_internal/monitor/239 written in 11.937µs engine=tsm1
[I] 2018-07-05T10:12:28Z error writing snapshot: error opening new segment file for wal (1): write /var/lib/influxdb/wal/_internal/monitor/239/_00032.wal: no space left on device engine=tsm1
[I] 2018-07-05T10:12:29Z Snapshot for path /var/lib/influxdb/data/_internal/monitor/239 written in 12.409µs engine=tsm1
[I] 2018-07-05T10:12:29Z error writing snapshot: error opening new segment file for wal (1): write /var/lib/influxdb/wal/_internal/monitor/239/_00032.wal: no space left on device engine=tsm1
```

```
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"  
iostat -xd 1 30 > iostat.txt
```

**Comment by smallfish** [comment]
`no space left on device` ?

**Comment by touatily** [comment]
Actually there is space left in disk.
I upgraded influxdb to the most recent version, after that  there no error in log file, but the CPU is still used at almost 100%
Next day, the CPU usage became normal without changing anything !

**Comment by zxyz** [comment]
Hello,
I've got a similar problem. Database size is only 67 GB, influxdb 1.6.1 on RHEL 7.4.

![influx](https://user-images.githubusercontent.com/14958508/44035557-101b8f42-9f10-11e8-9ccf-cdcc4fbfdf3b.png)

It started last week after an update and the following restart, I cannot tell if it correlates to the restart or the upgrade.

![influx2](https://user-images.githubusercontent.com/14958508/44035577-17650c24-9f10-11e8-81ff-24305cea56e2.png)
On the far left side of the image the normal heap acitve and idel status can be seen, between 8/7 and 8/8 the problem came up for the first time. I restarted influxdb between 8/8 and 8/9 which brought some relieve (only ~ 2 cores constantly at 100%) but it ramped itself up again. Between 8/9 and 8/10 I restartet influxdb again and let it run over the weekend. Today (after 8/13) I did two restarts.

[profiles.tar.gz](https://github.com/influxdata/influxdb/files/2283182/profiles.tar.gz)
[vars.txt](https://github.com/influxdata/influxdb/files/2283183/vars.txt)

No error messages in the logs.
Thanks for your help!

**Comment by zxyz** [comment]
After two more days of high load, I decided to try some things. Relieve was brought by doing a backup of all databases, deleting the databases and restoring them. Now the high CPU load is gone.

Interesting fact: before the deletion the dir size was around 67GB, afterwards around 2.8 GB!? Any ideas about this? 
I've got icinga2 filling the database, it's exporter doesn't allow to filter the data going to influxdb. Therefore I run a cron job to delete the unwanted data:

` /usr/bin/influx -execute "DROP SERIES WHERE series != 'whatever'" -database="icinga2" `

Might this is correlated?

**Comment by qiuker521** [comment]
![2018-11-04 02-59-34](https://user-images.githubusercontent.com/22740352/47956331-be672f80-dfdd-11e8-863f-aaee5c92ca52.png)

+1 high CPU  load on 1.6.4.

But in my situtation, the influxd seems used up a single core, and then blocks all query/operation.

(the /var/lib/influxdb is only 50MB).

I am now trying to use the source code...

**Comment by djsomi** [comment]
For some strange reason my solution was to stop service, start influxd by hand, let it run for a while, and high cpu load went. :D
