### ISSUE TITLE
Incorrect time values, microseconds instead of milliseconds

### ISSUE THREAD

**Issue by bunghi** [influxdata/influxdb#10060]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
InfluxDB 1.5.2 running on Debian Linux 8.8
__Steps to reproduce:__

I use Icinga2 for data collection but the values in database are different than the ones that Icinga is sending:

![image](https://user-images.githubusercontent.com/31234197/42513832-9888f4de-8460-11e8-8313-037263c94d1b.png)

I queried the data in DB and values are different (microseconds instead of milliseconds):

![image](https://user-images.githubusercontent.com/31234197/42513913-d19caffe-8460-11e8-9542-66ce16f97a39.png)

Any idea? 

Thanks

**Comment by hsadeghilam** [comment]
I feel like I'm having a similar issue: I'm using Node-Red to save data from MQTT to Influxdb. The problem is when I look at my saved data in Influxdb I see some data points are missing. I save data at 1 kHz sampling rate, i.e. 1 ms time step. Could it be that influxdb is saving new data on top of old data?
