### ISSUE TITLE
Add /version REST endpoint

### ISSUE THREAD

**Issue by dp1140a** [influxdata/influxdb#10064]
__Proposal:__ [Description of the feature]

__Current behavior:__ [What currently happens]
Nothing

__Desired behavior:__ [What you would like to happen]
When a user makes a request to the /version endpoint it will return the version of the current server: influxd not necessarily influx

__Use case:__ [Why is this important (helps with prioritizing requests)]
This will help with maintenance and operation of a cluster or single instance

**Comment by kaspergrubbe** [comment]
I think the `/ping`-endpoint exposes the version in its response-headers, or won't that work for you? Does the `/version` need to be implemented differently?

**Comment by dp1140a** [comment]
Well theres a bit of an easter egg for you. How did you find that?  Interesting place to get the version info from.  It would work, however I still think having a /version endpoint would be beneficial.

**Comment by kaspergrubbe** [comment]
By accident really, I was debugging some stuff with the Ruby library and did `client.ping` and debugged the response, but it is documented here: http://docs.influxdata.com/influxdb/v1.5/tools/api/#ping

As far as I know, this endpoint can't be used by systems like Kubernetes because it responds with no body, so it will need an overhaul anyway.
