### ISSUE TITLE
Group by clause returns incorrect date

### ISSUE THREAD

**Issue by Fenwyr** [influxdata/influxdb#10165]
__System info:__ [InfluxDB 1.6]

__Steps to reproduce:__

1. Have one entry of datas
2. Request this data with mean() function, and group by time(720h) or group by time(30d) (trying to group the results by month, have tried (4w) too but bad results)

__Expected behavior: Should return the mean(data) and the dateTime of the data

__Actual behavior:__ Returns proper values, but dateTime is off. (Data is on 1st August, returned dateTime is 17 July

My background is that i'm trying to set up a graphic to show datas per day, months and year.
Other functions works fine ; i'm using the same logic as Days and Months (days is group by 1h, month is group by 24h).

When trying to access data and group by 720h or 30d, which are equals, returned dateTime is wrong.

I confirmed that there is no data on 17July, but still getting this date in return.

NB : when i was trying with group by date (4w), i had different result and date.
My guesses are that 4w equals to 28 days, different from 30 days of course, and that the returned date is actually kind of averaging the date with the actual date of the data, and the date that is reached with the 30 days (reminder : i have data 1st August, and the returned date is 17 July, so 1st august minus 15 days is 17 July...)

Maybe i misunderstood some of InfluxDB functionalities as i'm beginning with this tech, but i can't find a way to make it work properly. I think with full datas every day i would display correctly, but i'm not even sure.

Also excuse my english if it's not perfect, i'm a foreigner ;)

**Comment by Fenwyr** [comment]
Hello again, since i don't have any answer yet i figured out i should give you the actual request ;)

select mean(SO2Value),mean(NO2Value),mean(PM10Value),mean(PM25Value),mean(ZNOValue),mean(ZNOXValue),mean(ZO3Value) from airDB WHERE emplacement='"+stationName+"' AND time>='"+startDate.toISOString()+"' and time<'"+endDate.toISOString()+"' group by time(720h,"+startDate.getTimezoneOffset()+"m)  fill(none)

**Comment by cawak** [comment]
Hi, I'm facing the same issue (with the 30d aggregation). As I understood, the time intervals or the time buckets are pre-defined by the time argument (in our case 30d) of the GROUP BY. The WHERE clause just filters the aggregated data, but the time intervals remains the same. I believe it has to do with the architectural decision they made to boost optimizations. 
In the documentation they mention 'preset time boundary' but again, when we deal with hours, they are easy to be foreseen - the midnight of each day (and that's why the offset param can help us here). But what how does influxdb choose time buckets for aggregation which are bigger than, let's say 1 week? It's strange that the documentation didn't address such scenarios.

**Comment by hardiksondagar** [comment]
@cawak I run into the same issue when group by more than 1d, documentation stats that it'll use present-time boundary, didn't say how this present time boundary will be calculated. 

If documentation specifies the how boundary is calculated then we can pass offset accordingly.
