### ISSUE TITLE
 LIMIT doesn't limit results when using GROUP BY

### ISSUE THREAD

**Issue by vakarami** [influxdata/influxdb#10452]
I stored a tag tag1 with bunch of fields in Influxdb 1.6. 
I want to select last 10 field1 values grouped by tag1 values. So I wrote this query

`SELECT LAST(field1) FROM <source> GROUP BY tag1 LIMIT 10`

But surprisingly it returns all rows.

Before that I wrote a query like below to return recent records:

`SELECT tag1, field1, field2, field3 FROM <source> GROUP BY tag1 ORDER BY time DESC LIMIT 1 SLIMIT 10`

But it returns nothing while it's supposed to return first 10 series. 
In this case when I increase SLIMIT to a big number like 1000 it has results.

Do I miss something? or Do these queries return correct values?

**Comment by jsternberg** [comment]
I think you might be able to do this for the first query:

```
SELECT field1 FROM (SELECT last(field1) AS field1 FROM <source> GROUP BY tag1)
```

The reason why you see all rows is because limit will limit per series and not for the entire query so last already only returns one row so limit is kind of useless. The subquery above causes it to group all of the returned points together so it operates more how might be expected.

`SLIMIT` is probably broken, but it would be the correct thing to use in this circumstance for what you want if it wasn't. I am also not if `SLIMIT` does that limit before or after it has grouped the series. It makes sense to me that it should limit things after they are grouped, but I can't confirm that off the top of my head.
