### ISSUE TITLE
promethus remote storage influxdb high memory usage problem

### ISSUE THREAD

**Issue by yineima** [influxdata/influxdb#10510]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
linux centos 7 16G memory   500G HHd disk
influxdb 1.7.0

__Steps to reproduce:__

1. promethus collect metrics ，native write to influxdb ，about 200qps
  refer: https://docs.influxdata.com/influxdb/v1.7/supported_protocols/prometheus
2. when the influxdb data dir come to 15G or higher, memory usage problem become very obviously.
my machine have 16G memory, the influxdb may restart to occupy 7-8G, then it consume more and more memory as promethus keep writing data into it unit it OOM killed by OS.
![image](https://user-images.githubusercontent.com/7900766/48817887-7a1cb300-ed83-11e8-81c5-559eb1ef33a7.png)

3. I already configure influxdb.conf to reduce memory usage. but it seems no effect.
 index-version = "tsi1"  
this TSI feature has been released  in version 1.3.0 and kept optimizating to version 1.7.0

![image](https://user-images.githubusercontent.com/7900766/48820651-df2ad580-ed90-11e8-87d3-f278be9409a9.png)

by this blog: https://www.influxdata.com/blog/path-1-billion-time-series-influxdb-high-cardinality-indexing-ready-testing/

__Expected behavior:__ [What you expected to happen]

reduce memory usage 

__Actual behavior:__ [What actually happened]

memory usage too high to be OOM killed by os

__Additional info:__ [Include gist of relevant config, logs, etc.]

I investigated that all labels in promethus's metrics will be stored as tags in influxdb which will cost too much memory because of  the inverted index was an in-memory data structure build for fast queries.
(refer: http://puyuan.github.io/influxdb-tag-cardinality-memory-performance)
but after look into this blog
(https://www.influxdata.com/blog/path-1-billion-time-series-influxdb-high-cardinality-indexing-ready-testing/), I assume my memory could go down, but accutally it not.

Here is my  SERIES CARDINALITY. Could someone point out my problem?

prometheus is the db; 
news_retrieval_user_total/push_agent_receive_counts and the others are measurments.

SHOW SERIES CARDINALITY ON prometheus;
cardinality estimation
527786

> SHOW SERIES CARDINALITY from news_retrieval_user_total;
name: news_retrieval_user_total
count
55914
> 
> SHOW SERIES CARDINALITY from news_retrieval_user_count;
name: news_retrieval_user_count
count
2557
> SHOW SERIES CARDINALITY from push_agent_receive_counts;
name: push_agent_receive_counts
count
160319

name: push_agent_receive_counts
count
160269

name: push_agent_send_counts
count
160190

name: push_consume_kafka_counts
count
12922

name: push_exquisite_monitor_info
count
4656

name: push_gray_monitor_info
count
97242

@pauldix @otoolep @jwilder @jvshahid  @corylanou @benbjohnson @jsternberg @e-dard @dgnorton @toddboom

**Comment by dgnorton** [comment]
@yineima thanks for reporting the issue but for future issues it's best not to @-mention specific devs. That usually results in them receiving emails / notifications. We monitor issues, prioritize and assign them to the best suited dev.

**Comment by aslobodskoy-fiksu** [comment]
Looks like I've similar issue
![image](https://user-images.githubusercontent.com/26899892/49097547-a057bc80-f275-11e8-845e-94413f2a5dd9.png)

**Comment by sbengo** [comment]
Hi guys,

We have just started a track to store prometheus metrics into our InfluxDB server:
__InfluxDB-Build:__ `OOS`
__InfluxDB-Version:__ `1.6.4`
__SO:__ `Red Hat Enterprise Linux Server release 7.5 (Maipo)`
__Prometheus version__: `2.4.3`

The server is full dedicated on retrieve Prometheus metrics and we are experimenting the same behaviour seen on the above comments:

### Memory consumption

![image](https://user-images.githubusercontent.com/13196237/49221396-4839cb00-f3d9-11e8-8e03-5d0e4c477892.png)


### Volumetry

Average workload: `200K metrics / min`
Cardinality estimation (not exact): `505603`
Number of Shard Groups: `26`

![image](https://user-images.githubusercontent.com/13196237/49221373-30624700-f3d9-11e8-97f3-a813c79191e1.png)

![image](https://user-images.githubusercontent.com/13196237/49221538-b7afba80-f3d9-11e8-850d-0bdde0f76d4a.png)


### Relevant configuration

__RP Shard duration__: `6h`

#### influxdb.conf
````
...
[data]
  dir = "/data/influxdata/data"
  wal-dir = "/opt/influxwal/wal"
  index-version = "tsi1"
  cache-max-memory-size = "1g"
  cache-snapshot-memory-size = "25m"
  cache-snapshot-write-cold-duration = "10m"
  compact-full-write-cold-duration = "24h"

[coordinator]
   write-timeout = "10s"
   max-concurrent-queries = 30
   query-timeout = "15s"
   log-queries-after = "10s"
   max-select-point = 0
   max-select-series = 10000
   max-select-buckets = 0
...
````




Thanks,
Regards!

**Comment by sbengo** [comment]
Hi again,

The InfluxDB has entered in a unstable state, and the process is being killed by OOM each try its getting to start:

![image](https://user-images.githubusercontent.com/13196237/49792286-a4ceab80-fd32-11e8-8518-4bb908bf6564.png)

Running `influx_inspect reporttsi -db-path` seems that the DB reached to `Cardinality (exact): 999985`.
Also, the command seems to consume all available memory, similar behaviour seen on each InfluxDB re/start:

![image](https://user-images.githubusercontent.com/13196237/49794425-ce3e0600-fd37-11e8-9df5-459ecf46875e.png)

We are stopped on our project as we cannot save our K8s metrics (using Prometheus scrapper) into InfluxDB, so, please:

- As we have seen on the issue #10468 , upgrading to 1.7.1 can help. Do we upgrade?
- Do you need more information?

Thanks,
Regards

**Comment by sbengo** [comment]
Hi,

Sorry for the late response. @aslobodskoy-fiksu , we  have upgraded to 1.7.2.

With 1.7.2 version, the DB we had up to 1 month, but the memory has progressively increased until OOM again, being unresponsive.

## Changes to prior comments:

**InfluxDB-Version:** `1.6.2` --> `1.7.2`
**Average workload:** `200K metrics / min` --> `320K metrics / min`
**Cardinality estimation (not exact):** `505603` --> `7000000 (7M)`
**Number of Shard Groups:** `26` --> `23`

This time, the memory was released each time InfuxDB was killed by OOM, but after a monoth, the DB entered on an unresponsive state, **even if we restart it**

![image](https://user-images.githubusercontent.com/13196237/52561919-1394b780-2dfd-11e9-86a3-109183b788c7.png)

## Questions

- How much memory does InfluxDB needs to handle this high cardinality?
- If we increase our memory, will InfluxDB consume all our memory after time?
- Are there some parameters in order to improve TS1 engine or memory consumption?

## More info:

`write request` on the last 30d:

![image](https://user-images.githubusercontent.com/13196237/52561948-2c04d200-2dfd-11e9-9d28-cd3ed190597a.png)

`points written` on the last 30d:

![image](https://user-images.githubusercontent.com/13196237/52562019-679f9c00-2dfd-11e9-9be1-113843bb916d.png)

**Comment by danielllek** [comment]
I'm on 1.7.4 and have the same problem. 
Series cardinality ~500K, memory footprint 14GB with peaks up to 32GB resulting in OOM :-/

**Comment by danhul** [comment]
I run 1.7.6 on a server with 16GB RAM and multiple influxdb databses. The moment the total size of the DBs gets higher than 15GB influxdb starts using the whole RAM and the process gets killed. Has there been any solution on this issue?

**Comment by e-dard** [comment]
Hi, I’m one of the storage team engineers. Would somebody be able to provide a heap profile at a time close to when the server is going to OOM? They’re easy to get, and we have a handy url you can use in the issue creation template.

**Comment by smith-30** [comment]
@e-dard 
I am also troubled by something similar.
Zabbix is ​​showing such memory transition.

When I keep writing data for a long time, db seems to use up a lot of memory suddenly.

<img width="1360" alt="スクリーンショット_2019-06-27_17_30_54" src="https://user-images.githubusercontent.com/13186083/60311850-f7507c00-9993-11e9-97c0-d57785c1dae3.png">


**influx version**

1.7.4

**our settings**
Please let me know if you have other necessary information.

```
[data]
  dir = "/data/influxdb/data"
  wal-dir = "/data/influxdb/wal"
  index-version = "inmem"
  query-log-enabled = true
  cache-max-memory-size = "8g"
  cache-snapshot-memory-size = "200m"
  cache-snapshot-write-cold-duration = "10m"
  compact-full-write-cold-duration = "4h"
  max-concurrent-compactions = 1
  compact-throughput = "48m"
  compact-throughput-burst = "48m"
  max-values-per-tag = 100000
  series-id-set-cache-size = 100
```

**System info: **

```
ec2 r5.large

RAM:  16gb
CPU: vCPU 2
IOPS: 1500

`/data`
IOPS: `1500`
disk size: `500GiB`
```

These are the profiles obtained when the memory is down.
(result of `http://localhost:8086/debug/pprof/all?cpu=true`)

[0627_1525_profile.tar.gz](https://github.com/influxdata/influxdb/files/3337265/0627_1525_profile.tar.gz)

**Comment by e-dard** [comment]
@smith-30 hi, thanks for the profiles. Can I get more context on them? According to the profiles your system had been up almost two weeks without restarting, and you took the profiles at `06:26 AM UTC`.

As I don't know what timezone you're in I can't match the profiles to the screen shot you pasted in your comment. Where on the screen shot did you grab these profiles?

Can you confirm if the system was very low on memory when you took the profiles, because the profiles don't show much memory usage at all, in terms of the Go heap (only ~2GB).

**Comment by e-dard** [comment]
@smith-30 another thing... Can you get me the logs that cover the period above where the memory usage suddenly shoots up? Feel free to email these to me directly if you don't want them on Github. My email is `edd at database_name.com`

**Comment by smith-30** [comment]
@e-dard thanks for your comment.
sorry, my screen shot timezone is `JST`, but db instance timezone is `UTC`.
At this time, db kept running and did not reach to the end of the process in oom.

>As I don't know what timezone you're in I can't match the profiles to the screen shot you pasted in your comment. Where on the screen shot did you grab these profiles?

profile was acquired at utc 06:26. so in the screenshot, it's around 15:26

> Can you confirm if the system was very low on memory when you took the profiles, because the profiles don't show much memory usage at all, in terms of the Go heap (only ~2GB).

I also attached the results of heap profile when memory was being consumed in large quantities.
[heap.txt](https://github.com/influxdata/influxdb/files/3338664/heap.txt)
This is what I got with curl at around 15:27 minutes in the screenshot.
Is this useful?

**Comment by e-dard** [comment]
@smith-30 it looks like most of your heap is being spent on a query that needs to merge together lots of overlapping TSM blocks. Can you turn on query/trace logging and provide logs for periods when it's happening? And to confirm - how are you querying influx?

**Comment by pracplayopen** [comment]
we've also been seeing this repeatedly since archving prometheus metrics to influxd.

saw recommendation here to use version 1.7, seemed to improve somewhat but still happening.

we only use influx two ways atm- write: prometheus, read: grafana.   at moment process being hupped around once a week to keep system stable.   otherwise it seems like influx tries to use all free memory??

from reading release notes of newer versions... it seems like v2 may have some memory improvements.   

i've read the upgrade docs, is it recommended to upgrade to 1.9 (or something > 1.7.5) before running 'influxd upgrade' w/v2?
