### ISSUE TITLE
InfluxDB 2.0 and Debian

### ISSUE THREAD

**Issue by aviau** [influxdata/influxdb#10638]
Hello!

This repository is a dependency for InfluxDB 1.7, I am almost done packaging all dependencies in Debian (that was 17 new packages).

My primary goal was getting 1.7 to build in Debian but this means that we could also ship 2.0 any time now.

I wanted to ask, how do you think the 2.0 release should be handled? I notice that you guys don't publish 2.0 builds on your website yet.

This issue could be our point of contact until InfluxDB 2.0 is considered ready to be shipped.

Will there be backwards compatibility? Should influxdb 2.0 be a new package or should it replace the older version? If you guys support plan to support 1.X for a while when we might want to consider having both 1.X and 2.X available.

**Comment by biva** [comment]
Hello, is there any news on this? Does Debian plan to integrate influxdb2 into its own repository @aviau ?

**Comment by aviau** [comment]
I personally don't plan to spend any time on it for now.

**Comment by biva** [comment]
Thanks for your quick answer! Just to be sure to understand, does it mean that Debian won't update its repository for now? Or is it just you? In this case, would you know how to have a feedback from Debian?

And for reference, I also posted a message in the forum: https://community.influxdata.com/t/debian-official-repository-for-influxdb2/23738

**Comment by mhall119** [comment]
Below is my reply from the forum:

--------------------

Hi Biva,

The package in the default Debian repository isn't actually provided or maintained by InfluxData. It's built by the Debian Go Maintainers team using the source code in our Git repository. It's up to them to update it to the latest version (and to provide a new package for `influxdb2`). 

Unfortunately they use an entirely different build system than we do, so it's not just a matter of them cloning our Git repo and building their own packages. They will need to update their build configurations to get the latest version of InfluxDB's source code and any dependencies. It's likely they they simply don't have the time or know of the demand for them to provide an updated version.

InfluxData does support Debian user directly, by hosting our own APT repository and publishing updated packages there as part of our regular release process. You can add our repository and install InfluxDB from there using the following commands:
```
wget -qO- https://repos.influxdata.com/influxdb.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdb.gpg > /dev/null
export DISTRIB_ID=$(lsb_release -si); export DISTRIB_CODENAME=$(lsb_release -sc)
echo "deb [signed-by=/etc/apt/trusted.gpg.d/influxdb.gpg] https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list > /dev/null

sudo apt-get update && sudo apt-get install influxdb2
```

If you're not familiar with these commands they will:
1. Download InfluxData's GPG key, which we use to cryptographically sign all of our packages, so that apt can verify them
1. Add the InfluxData APT repository to your list of repositories that Debian will check for new packages
1. Install the latest version of the `influxdb2` package. In keeping with Debian's practices we use a different package name for version 2 because it is a significant change from version 1.
