### ISSUE TITLE
cli: support non-interactive onboarding

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#10684]
During development, I frequently want to start fresh without any data, and I always use the same values during onboarding. It would be more convenient if I could specify all the arguments as command line flags or pass in a config file, rather than having to interactively type in each argument every time I run `influx setup`.

**Comment by jacobmarble** [comment]
(almost created a duplicate bug for this; here's some added detail)

The `influx setup` subcommand is interactive, which makes automated or repeatable setup difficult. We need an automated setup for things like CI and development.

Add flags to the setup subcommand to answer the interactive questions (user, password, org, bucket, retention) without interactive prompt.

For added convenience in automated setup, also add a flag to set the token to a user-specified value, rather than generate a token.

@goller
