### ISSUE TITLE
error: table builder already has column with label type

### ISSUE THREAD

**Issue by kelwang** [influxdata/influxdb#11054]
Influxdb 2.0

this issue happens, when there are a lot of tags.
query is 
```
{
    "dialect": {
        "annotations": ["group", "datatype", "default"]},
    "query": "from(bucket: \"scraper2\") |> range(start: -30d)  |> keys(except: [\"_time\", \"_start\", \"_stop\", \"_value\"])  |> group()  |> distinct()  |> keep(columns: [\"_value\"])  |> limit(n: 200)",
    "type": "flux"
}
```

error we got
```
#group,true,true
#datatype,string,string
#default,,
,error,reference
,table builder already has column with label type,
```

Steps to reproduce this issue.
1. run influxdb 2.0 locally
2. create 2 buckets, call them scraper1, scraper2.
3. run docker, with docker run --name prometheus -d -p 127.0.0.1:9090:9090 prom/prometheus
4. create 2 scraper target, with endpoint http://localhost:9999/api/v2/scrapertargets
```
{
    "name":"scraper1",
    "type":"prometheus",
    "url":"http://localhost:9090/metrics", // local docker 
    "orgID":"0337cfa50f796000",
    "bucketID":"033b844993917000" // id of scraper1
}
```

```
{
    "name":"scraper2",
    "type":"prometheus",
    "url":"http://localhost:9999/metrics", // influxdb 2.0 metrics
    "orgID":"0337cfa50f796000",
    "bucketID":"033b844993917000" // id of scraper2
}
```
5. run the query above.
result of scraper1, which is correct
```
#group,false,false,false
#datatype,string,long,string
#default,_result,,
,result,table,_value
,,0,_field
,,0,_measurement
,,0,type
,,0,handler
,,0,slice
,,0,dialer_name
,,0,listener_name
,,0,code
,,0,version
,,0,call
,,0,endpoint
,,0,reason
,,0,event
,,0,role
,,0,branch
,,0,goversion
,,0,revision
```
result of scraper2, which has a lot of tags

```
#group,true,true
#datatype,string,string
#default,,
,error,reference
,table builder already has column with label type,
```

**Comment by jsternberg** [comment]
This also occurs if you just do `from() |>  range()`.

**Comment by jsternberg** [comment]
Here are the related metrics:

```
storage_tsi_index_files_total{index_partition="2",type="index"} 0
storage_tsi_index_files_total{index_partition="2",type="log"} 1
storage_tsi_index_files_total{index_partition="3",type="index"} 0
storage_tsi_index_files_total{index_partition="3",type="log"} 1
storage_tsi_index_files_total{index_partition="4",type="index"} 0
storage_tsi_index_files_total{index_partition="4",type="log"} 1
storage_tsi_index_files_total{index_partition="5",type="index"} 0
storage_tsi_index_files_total{index_partition="5",type="log"} 1
storage_tsi_index_files_total{index_partition="6",type="index"} 0
storage_tsi_index_files_total{index_partition="6",type="log"} 1
storage_tsi_index_files_total{index_partition="7",type="index"} 0
storage_tsi_index_files_total{index_partition="7",type="log"} 1
```

Is there any chance that "type" is explicitly added somewhere that may conflict with the type tag here?

**Comment by e-dard** [comment]
@jsternberg yes, `type` is explicitly added [here](https://github.com/influxdata/influxdb/blob/master/tsdb/tsi1/metrics.go#L127-L137).

**Comment by jsternberg** [comment]
I'm handing this off to @goller because I think this is an issue with somewhere between the scraper and storage engine.

What seems to be happening is that the scraper seems to be producing a point with two tags that have the same name. The `models` package doesn't forbid this (for efficiency). This point is then sent downstream until it reaches the storage engine. I'm not sure if the point gets stored on disk or what happens, but it reaches somewhere that is queryable. The storage engine then produces a table that has two columns with the same name. When flux tries to process this table by copying the table schema, our table builder catches it with a very opaque error message.

While we could improve the error message, the storage engine is not supposed to produce a table with duplicate column names. The scraper should have probably received an error that it produced a bad point and the scraper shouldn't have produced the bad point to begin with.
