### ISSUE TITLE
Average "gauges"

### ISSUE THREAD

**Issue by abh** [influxdata/influxdb#1115]
I have some metrics for the current temperature. The measurement data comes in at odd intervals rather than every minute or similar.

It'd be nice if there was a way to have InfluxDB do the right thing when calculating averages etc for data like:

0:00  19
0:02  18
0:04  19
0:05  20
0:08  19
0:12  26
1:00  25

In this case for the hour of "0" 80% of the time had "26" as the value, but doing an average right now it'll trend much lower. Does my wishlist item here make sense?

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by pauldix** [comment]
The function to interpolate series (#5040) would solve this problem. Still on the roadmap, but not scheduled for development yet.
