### ISSUE TITLE
Simple aggregating task using mean errors

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#11488]
Repro Steps

1. Setup an instance
1. Start scraping `localhost:9999/metrics`
2. Create a second bucket
3. Use the Data Explorer to create a task that takes the mean of a single field and writes it to the new bucket
4. Notice error in logs related to task
5. Notice that field doesn't appear in the new bucket

**corresponding log message**
```
2019-01-23T04:09:30.066313Z    info    Error exhausting result iterator    {"log_id": "0DAE7ox0000", "service": "task-executor", "task_id": "034a38b03a7d2000", "run_id": "034a38dd313d2000", "trace_id": "0DAEDppG000", "op_name": "execute", "error": "no time column detected", "name": "to8"}
```

**example task**
```
option task = { 
  name: "bar",
  every: 30s,
}



timeRangeStart = -1h
windowPeriod = 10000ms

from(bucket: "tele")
  |> range(start: timeRangeStart)
  |> filter(fn: (r) => r._measurement == "boltdb_reads_total")
  |> filter(fn: (r) => r._field == "counter")
  |> window(period: windowPeriod)
  |> mean()
  |> group(columns: ["_value", "_time", "_start", "_stop"], mode: "except")
  |> yield(name: "mean")
  |> to(bucket: "so", org: "org")
```

**Comment by mark-rushakoff** [comment]
The error message includes `"error": "no time column detected", "name": "to8"`. 

You've grouped with `except _time`. Maybe there's a way to keep it, or maybe you have to provide timeColumn per the spec: https://github.com/influxdata/flux/blob/master/docs/SPEC.md#to

I haven't used window enough to offer an experienced answer.

**Comment by pauldix** [comment]
Yeah, I think you might need to `duplicate(column: "_start", as: "_time")`

**Comment by nathanielc** [comment]
@pauldix Yep, was just going to suggest that. The aggregate functions (mean in this case) remove the _time column, so it needs to be added back on from one of the grouped columns. 

This is what the aggregateWindow function does for you.

And I recommend using `_stop` instead of `_start`

`duplicate(column: "_stop", as: "_time")`

**Comment by russorat** [comment]
@pauldix @nathanielc it's not obvious to me (or the other people i asked) that we needed the dup column. Could we improve the to function to either accept a time column or have an ordering, so it checks for _time first, then _stop, then _start?

**Comment by nathanielc** [comment]
Alternatively you can use the `timeColumn` argument to the `to` function. The SPEC [documents](https://github.com/influxdata/flux/blob/master/docs/SPEC.md#to) it as defaulting to `_time`, but you could specify it to use `_stop` intsead.

The above would become:
```


option task = { 
  name: "bar",
  every: 30s,
}



timeRangeStart = -1h
windowPeriod = 10000ms

from(bucket: "tele")
  |> range(start: timeRangeStart)
  |> filter(fn: (r) => r._measurement == "boltdb_reads_total")
  |> filter(fn: (r) => r._field == "counter")
  |> window(period: windowPeriod)
  |> mean()
  |> group(columns: ["_value", "_time", "_start", "_stop"], mode: "except")
  |> to(bucket: "so", org: "org", timeColumn:"_stop")

```

**Comment by nathanielc** [comment]
@russorat To address this question directly 

> Could we improve the to function to either accept a time column or have an ordering, so it checks for _time first, then _stop, then _start?

No, the reason is that Flux has chosen a different model for how to handle that case. Instead of choosing multiple fall backs and encoding that behavior into every function that expects a _time column, all functions that expect a _time column have an argument with a default value of `_time`. The argument name is also consistently called `timeColumn`, unless there is a need for multiple time columns.  The idea here is that the argument's existence and default value document the expectation of a time column existing. If the time column does not exist or is not named _time then the user can create the column (i.e. use duplicate) or change the timeColumn argument (i.e timeColumn: "_stop").

This default arguments model is at the core of Flux's design and extends to more things than just _time columns. This pattern is repeated in nearly every Flux function.

Perhaps we need to communicate this design choice better and make the default values to function arguments more visible?

**Comment by russorat** [comment]
@nathanielc thanks for the background. Maybe the difficulty lies more in the fact that it's hard for me as a user to know that `mean` does not return a _time column.

i understand that a mean is calculated over a `_start` and `_stop`, but in my opinion (and this is why we chose `_stop` in the UI for viz) there is a specific `_time` when that `mean` value is accurate. You've even said we should use the `_stop` time for writing the data and I would argue that the `mean` function should return an `_time` column, which would be the "point in time when that mean is accurate".

**Comment by nathanielc** [comment]
@russorat These are good questions.

The `mean` function does not understand the concept of time. It doesn't know about the `_start` or `_stop` or even the `_time` columns. It only understands two things. 1. The group key 2. the column it is supposed to aggregate. 

All aggregate functions `mean` included, preserve what ever columns are in the group key. Then the perform their aggregate method against all the data in the column to be aggregated. This process always results in a single row that has the group key columns plus one more column for the aggregated value.

Our uses  of the mean function often involve means over times. In these cases by convention we make sure that the `_start` and `_stop` columns are part of the group key, this ensures that they exist after the `mean` is computed. All other columns are lost, this includes the `_time` column since it cannot be part of the group key since you are aggregating data over time. 

The result is that the `_time` column is lost. These reasons are why we created the `aggregateWindow` helper function, since it applies our assumptions about how aggregates over time should work. Where as the mean function by itself makes no assumptions about time.

By removing time based assumptions from the aggregate functions it lets you compute aggregates across dimensions that are not time based. For example you can compute the sum of all received network packets across all interfaces of a host for a single instance in time. InfluxQL uses subqueries to do this, where if you leave the group by time the same in the inner query versus the outer query then the aggregate is over the tag dimensions that change. In Flux it is a matter of simply changing the group key to change how aggregates perform.

**Comment by desa** [comment]
@nathanielc great explanation.

Does `aggregateWindow` pick `_start` or `_stop` as the `_time`?

When I do

```
|> to(bucket: "so", org: "org")
```

for a table with `_start` and `_stop`, what happens to the `_stop` and `_start` columns? Are they preserved on disk?

**Comment by nathanielc** [comment]
> Does aggregateWindow pick _start or _stop as the _time?

It picks `_stop` by default, it can be changed with the `timeSrc` parameter.  Code if you are curious https://github.com/influxdata/flux/blob/master/stdlib/universe/universe.flux#L86


The `to` function ignores the `_start` and `_stop` columns because they are not string columns. The `to` functions uses all string columns as the tags when writing the data. https://github.com/influxdata/flux/blob/master/docs/SPEC.md#to

**Comment by desa** [comment]
@russorat seems like a temporary solution to this issue is to do what Nathaniel proposed here

https://github.com/influxdata/influxdb/issues/11488#issuecomment-456865548

Which is to use `_stop` as the time column for tasks generated from the `Save As Task` feature in the UI. I believe this would be the intended functionality for both selectors and aggregates.

**Comment by desa** [comment]
Long term would be to use `aggregateWindow` once it supports selectors and aggregators.
