### ISSUE TITLE
Historical metadata never shows in query builder

### ISSUE THREAD

**Issue by tgisg** [influxdata/influxdb#11535]
Organizations > org > Buckets > add data > line protocol > Enter Manually

Clicking through to this option and then pasting in several rows of line protocol then clicking "continue" produces a message that says "Data Written Successfully!" but when I check for the measurements associated with that bucket, there are none, and it appears that there is no data in the bucket.

**Comment by tgisg** [comment]
I discovered that the issue is that with timestamps older than 30 days, the measurement will not show up in the search box, so it appears that it the bucket hasn't been populated with the data. With newer data, the measurement shows up in the search box, and then you can update the time range in the script editor to see even the older data.

**Comment by chnn** [comment]
@tgisg Thanks for investigating. This sounds like the same issue as https://github.com/influxdata/chronograf/issues/4821

We only look at data from the past 30 days to populate the tag selection UI. Since your data was outside of that window, no tags showed up.

For performance reasons, we need to have _some_ limit to how far back we look for tag data, though 30 days is a bit arbitrary.

It sounds like we need to communicate this limit in the UI, and perhaps make it configurable. @russorat thoughts?

**Comment by russorat** [comment]
- update the meta queries in the explorer panel to use the time range selected
 - update the message when no tags are displayed to say "Try expanding your time range"
