### ISSUE TITLE
Redesign units & scale options for visualizations

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#11537]
Instead of offering a generic `suffix` and `prefix` option we can include a `units` dropdown with (initially) some standard options. This way we can remove the `K/M/G` option and offer something more intuitive

**Comment by canimus** [comment]
I tend to get data out of InfluxDB just to plot various series in a standarized scale, perhaps a function or a switch that instead of scaling new query windows with the same scale, allows you to simply overlay one after the other. This could be equivalent or a time saver for having to normalize (MinMaxScaler) regreesor to all your series.

**Comment by chnn** [comment]
@canimus Are you plotting multiple series with different units with same scale? Or are you normalizing each series so that they have the same units first?

If it's the former, do you care if the y axis displays units at all? Would you want multiple y axes, each with its own units?
