### ISSUE TITLE
last update of influxdb(1.7.3) wiped the _internal db

### ISSUE THREAD

**Issue by gowrisankar22** [influxdata/influxdb#11643]
Hello Colleagues,
We have updated the influxdb(1.7.3) recently. It wiped all the historic data from _internal db. Any idea?
BRs, Gowrisankar

**Comment by gowrisankar22** [comment]
@e-dard I guess the problem with RETENTION POLICIES.
q=SHOW RETENTION POLICIES ON _internal"
```
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
monitor 168h0m0s       24h0m0s           1        true
```
example: for memory usage:
```
SELECT moving_average(mean("HeapInUse"), 10) AS "Heap Active", moving_average(mean("HeapIdle"), 10) AS "Heap Idle", moving_average(mean("Sys"), 10) AS "Total Memory Usage" FROM "monitor"."runtime" WHERE $timeFilter GROUP BY time($interval) fill(null)
```
![image](https://user-images.githubusercontent.com/20590107/52107396-37e1de80-261c-11e9-9554-8db4fe0922d4.png)

**Comment by e-dard** [comment]
@gowrisankar22 you have a daily shard group duration, and each day's shard is removed from the system after 7 days. It looks like your data for 25/1 has simply been removed by your retention policy.

Do you think that's what's happening?

**Comment by e-dard** [comment]
@gowrisankar22 if you're using the TSI index then you can have a long shard duration. Weeks, months is fine generally. Your retention period is a function of how long you want to keep the data around for.

Since there is no longer an actionable bug here, I'm closing this issue. [InfluxData community site](https://community.influxdata.com) if you have further questions. We would be happy to help there.

Thanks.
