### ISSUE TITLE
Update Transpiler design doc to use helper function

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#11658]

**Comment by jsternberg** [comment]
I think @aanthony1243 is currently working on this.

**Comment by aanthony1243** [comment]
My idea for helpers is so different from what's happening in the README that I didn't want to just edit it.  Here's my thinking: 

The current transpiler is too data-centric, gathering data in single columns and arranging many joins to achieve results.  Now that the transpiler can make use of helper functions, we should have flux doing more of the work.  My proposal is to implement a series of helper functions and possibly new flux features that will enable us to keep most of the logic and effort for the transpiler on the `flux` side of the code base, rather than on the `influxdb` side of the code base.  This will make the transpiler work more maintainable, allow us to write more granular unit and e2e tests for different operations, and will also let us make use of flux features for which we'd otherwise be writing `go` code to achieve.  

My summary argument is that the transpiler should be entirely naive.  This component is merely a bridge into 2.0 and so any data manipulation of any kind should be occurring in pure flux as much as possible (push-downs to storage allowed, of course).  There is a logical progression to produce helper functions according to the influxQL spec: https://docs.influxdata.com/influxdb/v1.7/query_language/spec/

Some features to implement that will help us in transpiling: 
1.  `contains`/`in` :  will help us quickly specify which fields we want, e.g., `contains(value: r._field, ["usage_user", "usage_system"]`

???
2.  `where` :  an op-spec that generates a filter procedure from an object type:
```
where(clauses: {usage_user: ">0.9", usage_system: "==0"})
```
justification:  where clauses may be non-trivial to parse into a filter.  This may make it easier, not sure. 

alternative:  stringToExpression:  the transpiler should not be parsing an expression and generating the AST. this limits the transpiler from using new features in flux.  
???




1.  Meta-queries:  helper functions already exist for the meta queries we wish to implement.  Executing these queries is merely a process of pattern matching and filling in the required parameters for the equivalent flux call. One thing we had to do in the old transpiler was instantiate the full query.  we should be able to hide all of the work behind a helper, e.g.  

`SHOW DATABASES  ==>  v1.showDatabases()`
`SHOW RETENTION POLICIES ==> v1.showRetentionPolicies(db: db)`
`SHOW TAG KEYS ==> v1.showTagKeys(db: db, measurement: m, filter: f)`
`SHOW TAG VALUES ==> v1.showTagValues(db:db, measurement: m, withKey: keys, filter: f)`

The initial data table is identified by : 

-  Columns needed (can handle REGEX, sets of size N and also *).   Also need to submit the columns referenced in the WHERE clause, and GROUP BY if they are not in the select statement.  
-  Time range.  If none given, we set a large bounded range.  
:  `v1.Select(measurement, fields, hiddenFields)` -- hidden fields is because we may need some fields for filtering/calculation and will drop them later.  

Most select statements include a WHERE clause. Using above suggestion, we can have a query like: 
`from(db: db) |> v1.select(measurement: m, fields: [f1, f2], hiddenFields: [f3]) |> v1.Where(clauses: {f1: "> 10", f2: '=="B"')'

group by, we will easily solve by a regular group by function: 

`from(db: db) |> v1.select(measurement: m, fields: [f1, f2], hiddenFields: [f3]) |> v1.Where(clauses: {f1: "> 10", f2: '=="B"') |> group(columns:[t1])`

grouping by time(INTERVAL) and OFFSET are solved with a window call: 
`from(db: db) |> v1.select(measurement: m, fields: [f1, f2], hiddenFields: [f3]) |> v1.Where(clauses: {f1: "> 10", f2: '=="B"') |> group(columns:[t1]) |> window(every: INTERVAL, offset: OFFSET)`

applying aggregates and arithmetic is best served with a helper-wrapper around map: 
`|> aggregateCols(m: {f1: sum, f2: mean, f3: count})`  
the above call will retain the group key, apply each function, drop any non-key non-agg columns, and rename the columns to something clear and predictable (e.g.,  f1_sum).  

Applying selectors is straightforward since they behave the same as in invfluxql: 
`|> max(column: "usage_user")`

Similarly, `limit` and `order by`  are solved by flux's  `limit` and `sort`, respectively: 
`|> sort(columns: [T1, T2], desc: false) |>  limit(n: 100)`

Applying arithmetic is best achieved using a map: 
`|>  map(fn: (r) => ({ AS_1: r.f1_sum /r.f3_count,  AS_2: r.f2_mean})`

the transpiler should be able to scan a query and know which fields/calculated columns should be kept.  If the above  names are all established as output of the helper transformation, then the final formatting/naming will be a `keep` call: 
`|> keep(columns: [AS_1, AS_2])`  
NOTE: we need to be able to keep all tags without enumerating their values.  needs more work.

**Comment by nathanielc** [comment]
@aanthony1243 This looks good. I agree that the transpiler should farm off its work to Flux where possible. Although I disagree with the use of the `where` function. I don't understand the value of the simplified `where` function. If the implementation of `where` can convert that into a `filter` function then why not have that be part of the transpiler logic itself. In either case it is likely Go code and the standalone `where` function does not look like it would get much use outside the transpiler. So in this case it seems like we are creating more complexity instead of simplifying the transpiler, since we have to design and implement the API of the `where` function.

 If I am missing something please call it out.

Overall I agree with breaking down the structure of the InfluxQL query into its parts that represent the basics of how InfluxQL's query engine operates.

**Comment by aanthony1243** [comment]
no, that's valid.  I wrote `where`, kind of liked it, then I didn't like it but decided to leave it in for discussion (hence the ???'s).  

However, I do think that something that can convert a string to a function expression would be valuable.  Currently we are parsing out the WHERE clauses and building up a custom AST.  It's not the highest priority of the above work, however I do think that creating AST for a filter is a bit brittle in terms of the AST being potentially changed or improved in later iterations.  I'd like to see the transpiler generating as little AST as possible.

**Comment by nathanielc** [comment]
Are you worroed about the Flux AST changing of the InfluxQL AST changing? The Flux AST is part of the public API for the Flux package. It will be considered a breaking change to change it once we hit 1.0. We want people to be able to confidently develop tooling around Flux using the AST.

Also the way the InfluxQL parser is written it is not possible to parse just WHERE expressions independently. This makes delaying their parsing very difficult.

**Comment by aanthony1243** [comment]
yeah, I'm probably over-thinking it.  certainly not a part of the design I'm fighting for. As you said, the primary theme here is that we should build elements of flux that match the conceptual flow of data in  InfluxQL as defined in the InfluxQL spec, which is distinct from the actual flow of data in the original InfluxQL implementation.
