### ISSUE TITLE
task: task name is not being updated when update is called with new name

### ISSUE THREAD

**Issue by Palakp41** [influxdata/influxdb#11670]
Trying to update a task with a new name but the update api is not updating the name. The response comes back with the old task name when update is called and doesn't throw any errors.

**Comment by mark-rushakoff** [comment]
Can you provide specifics about what API requests you're making, and the exact details of what is returned and how it differs from what you expect?

**Comment by Palakp41** [comment]
@mark-rushakoff : I am trying to update name for a particular task. I am making a call to the patch request for tasks and passing in task id and task object with a new name.  The response returns the task object with old name instead of the new name. I am expecting the response to come back with the new name of the task to see that the task is being updated.

**Comment by mark-rushakoff** [comment]
Tracked down the root cause to a typo in the JSON tags on the task update object:

https://github.com/influxdata/influxdb/blob/bf34b35fb4cf980db00e18278cc537f72c2d1b9e/task.go#L117 https://github.com/influxdata/influxdb/blob/bf34b35fb4cf980db00e18278cc537f72c2d1b9e/task.go#L157

They should be `"name"`, not `"options"`.
