### ISSUE TITLE
Error while retrieving tasks using 'after' or 'user' query params.

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#11820]
Using get tasks endpoint with `after` or `user` query param will return an error:
```
{u'message': u'failed to decode request', u'code': u'invalid', u'error': u'id must have a length of 16 bytes'}
```

- Create couple of tasks using `influx` command:
`./influx task create 'option task = {name:"n_3",every:1h} from(bucket:"b_1") |> range(start: -1h)' --org-id "0364b4fc0d6fa000" -t "OuNJYaSH5Vqdy3Jd8aZ7ID9C3VKynUket8EmzLR3ILNcJpvbjRZFkt1DDnFNoAs1BYEGUuG-zIPUvxYSxVidzA=="`

- Get all of the existing tasks using `influx` command:
`./influx task find -t "OuNJYaSH5Vqdy3Jd8aZ7ID9C3VKynUket8EmzLR3ILNcJpvbjRZFkt1DDnFNoAs1BYEGUuG-zIPUvxYSxVidzA=="`

The above command returns : 
```
ID			Name	OrganizationID		Organization	Status	Every	Cron
0364b59ea340e000	n_1	0364b4fc0d6fa000	test_1		active	1h0m0s	
0364b5e11600e000	n_1	0364b4fc0d6fa000	test_1		active	1h0m0s	
0364b5f13400e000	n_2	0364b4fc0d6fa000	test_1		active	1h0m0s	
0364b5f7ea00e000	n_3	0364b4fc0d6fa000	test_1		active	1h0m0s	
```

- Use get tasks REST API with `after` or `user` query param:
`curl -GET "http://localhost:9999/api/v2/tasks?after='0364b59ea340e000'" -H "Authorization:Token OuNJYaSH5Vqdy3Jd8aZ7ID9C3VKynUket8EmzLR3ILNcJpvbjRZFkt1DDnFNoAs1BYEGUuG-zIPUvxYSxVidzA=="`

The error is returned:
`{"code":"invalid","message":"failed to decode request","error":"id must have a length of 16 bytes"}`

**Comment by zhulongcheng** [comment]
looks like the length of `after` or  `user` param is incorrect, 
and the correct param length should be equal to 16 bits.

Of course, there is a small problem with the `after` param:
`http://localhost:9999/api/v2/tasks?after=0364b59ea340e001`
returns
 `[task-0364b5f13400e000, task-0364b5f7ea00e000]`,
should return
 `[task-0364b5e11600e000, task-0364b5f13400e000, task-0364b5f7ea00e000]`

will be fixed in #12103
