### ISSUE TITLE
Tasks: /tasks/{taskID}/runs api call is returning response error

### ISSUE THREAD

**Issue by Palakp41** [influxdata/influxdb#11974]

**Comment by Palakp41** [comment]
The response error I get is "your authorizer is not supported, please use *platform.Authorization as authorizer"

<img width="714" alt="screen shot 2019-02-19 at 9 53 30 am" src="https://user-images.githubusercontent.com/26464594/53037121-355df200-342e-11e9-9737-d0b6f06fb4cc.png">

**Comment by mark-rushakoff** [comment]
It looks like this error is coming from the task validator, which currently ensures that we're using an Authorization (here and a couple other places in that file): https://github.com/influxdata/influxdb/blob/f265dd3d3319f4bbb17e6df17dda54469e753d78/task/backend/query_logreader.go#L53-L60

Because the query.Request expects a `*Authorization`, not an `Authorizer`: https://github.com/influxdata/influxdb/blob/f265dd3d3319f4bbb17e6df17dda54469e753d78/query/request.go#L13-L25

I need to follow up to see if we can use an Authorizer interface there.

**Comment by mark-rushakoff** [comment]
Our solution for now will be:

1. Ensure the Session is allowed to read the target task.
2. If so, use that task's Authorization when constructing the query.Request.

This approach means we don't have to change anything in the query package for now. I'm guessing that eventually the query.Request will accept an Authorizer instead of an Authorization, but that's outside the scope of this issue now.
