### ISSUE TITLE
No rpms for SUSE Linux Enterprise Server 11

### ISSUE THREAD

**Issue by kshitijpatel** [influxdata/influxdb#1197]
Are there rpms available for SLES11SP1 64 bit?
With serious restrictions and behind firewall, it's impossible to build influxdb. I tried installing influxdb-latest-1.x86_64.rpm but fails to start influxdb with following error.
./influxdb: /lib64/libpthread.so.0: version `GLIBC_2.12' not found (required by ./influxdb)

Any suggestions?

**Comment by darix** [comment]
For the waiting time:
```
https://build.opensuse.org/package/rdiff/devel:languages:go/go-influxdb?linkrev=base&rev=4 … install from http://software.opensuse.org/download.html?project=devel:languages:go&package=influxdb … once the OBS is done @jpmens 
```

**Comment by beckettsean** [comment]
See https://github.com/influxdb/influxdb.com/pull/322 for possible help

**Comment by beckettsean** [comment]
We are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/6454) for all packaging requests, so that we can close this issue until we are ready to work on it.

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
