### ISSUE TITLE
influxdb can't start, runs out of memory 

### ISSUE THREAD

**Issue by vasa-chi** [influxdata/influxdb#12902]
I have a small influxdb instance on RaspberryPI, where I store a small amount of metrics.
After last upgrade influxdb service keeps restarting with this error:

```
мар 26 21:26:29 raspberrypi influxd[7774]: ts=2019-03-26T18:26:29.042383Z lvl=info msg="Reading file" log_id=0EQomhVW000 engine=tsm1 service=cacheloader path=/var/lib/influxdb/wal/_internal/monitor/561/_00616.wal size=226653
мар 26 21:26:29 raspberrypi influxd[7774]: runtime: out of memory: cannot allocate 1843200-byte block (561053696 in use)
мар 26 21:26:29 raspberrypi influxd[7774]: fatal error: out of memory
мар 26 21:26:29 raspberrypi influxd[7774]: runtime stack:
мар 26 21:26:29 raspberrypi influxd[7774]: runtime.throw(0xbdea24, 0xd)
мар 26 21:26:29 raspberrypi influxd[7774]:         /usr/local/go/src/runtime/panic.go:608 +0x5c
мар 26 21:26:29 raspberrypi influxd[7774]: runtime.largeAlloc(0x1c1b9c, 0x101, 0x1609d00)
мар 26 21:26:29 raspberrypi influxd[7774]:         /usr/local/go/src/runtime/malloc.go:1021 +0x120
мар 26 21:26:29 raspberrypi influxd[7774]: runtime.mallocgc.func1()
мар 26 21:26:29 raspberrypi influxd[7774]:         /usr/local/go/src/runtime/malloc.go:914 +0x38
мар 26 21:26:29 raspberrypi influxd[7774]: runtime.systemstack(0x6bd40)
мар 26 21:26:29 raspberrypi influxd[7774]:         /usr/local/go/src/runtime/asm_arm.s:354 +0x84
мар 26 21:26:29 raspberrypi influxd[7774]: runtime.mstart()
мар 26 21:26:29 raspberrypi influxd[7774]:         /usr/local/go/src/runtime/proc.go:1229
мар 26 21:26:29 raspberrypi systemd[1]: influxdb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
мар 26 21:26:29 raspberrypi systemd[1]: influxdb.service: Unit entered failed state.
мар 26 21:26:29 raspberrypi systemd[1]: influxdb.service: Failed with result 'exit-code'.
мар 26 21:26:29 raspberrypi systemd[1]: influxdb.service: Service hold-off time over, scheduling restart.
мар 26 21:26:29 raspberrypi systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
мар 26 21:26:29 raspberrypi systemd[1]: Started InfluxDB is an open-source, distributed, time series database.
```

After wich it starts reading WAL until it runs out of memory again.
What can I do to restore my database now?

```
$ sudo dpkg -l | grep influx
ii  influxdb                        1.7.4-1                      armhf        Distributed time-series database.
```

**Comment by stijnbosse** [comment]
I noticed the same issue this morning but I have no fix found.

**Comment by vasa-chi** [comment]
Is there maybe some way for us to provide a more detailed information for InfluxDB teem to analyse? Because I don't want to lose my data if it can be restored.

**Comment by marcpeyer** [comment]
I have exatly the same issue here. Does a reply to this reopens this issue? -> if so I'll edit the reply afterwards...

**Comment by marcpeyer** [comment]
Hi
What it looks I have exactly the same issue here. First thought it couldn't start at all, but then found every ~40 seconds influx quickly is online for few secs before it again restarts.
Tried now several things since hours with no luck:
- upgraded from 1.6.2 to 1.7.7
  -> still same issue
- tried to increase vm.max_map_count
  -> still same issue
- tried to switch to TSI instead of in-mem
  -> still same issue

attached log files of output of /debug/vars before and after the switch to TSI
[debug_vars_inmem.txt](https://github.com/influxdata/influxdb/files/3494802/debug_vars_inmem.txt)
[debug_vars_tsi1.txt](https://github.com/influxdata/influxdb/files/3494803/debug_vars_tsi1.txt)

and also attached the logs
[influxdb.log](https://github.com/influxdata/influxdb/files/3494804/influxdb.log)

my setup:
- RaspberryPi
- influxdb installed initially with V 1.6.2 around 10 months ago using default settings / configuration

Can someone help? I am really lost here.

**Comment by dubs69** [comment]
Same issue on cluster of 5 raspberry PI, try to go back to previous version, nothing worked.
Already applied the stuff about TSI, it's the second time I have this problem and I never find the solution. I tryed influxdb because it's by default used by many docker app but my old mysql db never make that kind of problem.

my setup:
5 RPI 4Go in a swarm cluster
1 USB 256Go attached to first RPI where the influxdb start on the node01

the logs :
020-04-09T20:03:06.031175Z lvl=info msg="Executing query" log_id=0M48M160000 service=query query="SELECT sum(value) FROM telegraf.autogen.mqtt_consumer WHERE topic = '/ESP/SDB/PIR/State' AND time > now() - 1m GROUP BY time(50ms)"


[httpd] 10.255.0.2 - pi [09/Apr/2020:20:03:04 +0000] "GET /query?db=telegraf&epoch=s&q=SELECT+sum%28%22value%22%29+FROM+%22autogen%22.%22mqtt_consumer%22+WHERE+%22topic%22+%3D+%27%2FESP%2FChambre%2FPIR%2FState%27+AND+time+%3E+now%28%29+-+1m+GROUP+BY+time%2850ms%29 HTTP/1.1" 200 57 "-" "Grafana" 1fb863ec-7a9d-11ea-8002-000000000000 1617547


[httpd] 10.255.0.2 - pi [09/Apr/2020:20:03:05 +0000] "GET /query?db=telegraf&epoch=s&q=SELECT+sum%28%22value%22%29+FROM+%22autogen%22.%22mqtt_consumer%22+WHERE+%22topic%22+%3D+%27%2FESP%2FSDB%2FPIR%2FState%27+AND+time+%3E+now%28%29+-+1m+GROUP+BY+time%2850ms%29 HTTP/1.1" 200 57 "-" "Grafana" 201cb99d-7a9d-11ea-8004-000000000000 970496


[httpd] 10.255.0.2 - pi [09/Apr/2020:20:03:06 +0000] "GET /query?db=telegraf&epoch=s&q=SELECT+sum%28%22value%22%29+FROM+%22autogen%22.%22mqtt_consumer%22+WHERE+%22topic%22+%3D+%27%2FESP%2FSDB%2FPIR%2FState%27+AND+time+%3E+now%28%29+-+1m+GROUP+BY+time%2850ms%29 HTTP/1.1" 200 57 "-" "Grafana" 20660e62-7a9d-11ea-8006-000000000000 490654


ts=2020-04-09T20:03:06.602760Z lvl=info msg="Snapshot for path written" log_id=0M48M160000 engine=tsm1 trace_id=0M48TJPW000 op_name=tsm1_cache_snapshot path=/var/lib/influxdb/data/udp/autogen/7 duration=1924.625ms


ts=2020-04-09T20:03:06.603079Z lvl=info msg="Cache snapshot (end)" log_id=0M48M160000 engine=tsm1 trace_id=0M48TJPW000 op_name=tsm1_cache_snapshot op_event=end op_elapsed=1924.894ms


tal error: out of memory
