### ISSUE TITLE
AddResourceDropdown should use the `Link` tag provided by `react-router` for redirecting the user to overlays.

### ISSUE THREAD

**Issue by bthesorceror** [influxdata/influxdb#12944]

**Comment by 121watts** [comment]
Unfortunately, just inserting a `Link` component isn't as straightforward as it seems.  The issue then becomes, that the anchor (`<a/>`) tag that `Link` renders does not occupy the entire width and height of its parent `div` making part of the dropdown list item  unclickable:

![Kapture 2019-04-24 at 12 25 36](https://user-images.githubusercontent.com/7582765/56687905-24c73380-668c-11e9-95d8-4a1263dd228a.gif)

Solving this problem requires that clockface `Dropdown.Item` take custom styles, class names, or both.  Since, all this story is doing is saving us the trouble of passing a couple of callbacks that fire `router.push` I say this story is fine to hold off until this occurs in clockface.
