### ISSUE TITLE
Determine how to label new templates

### ISSUE THREAD

**Issue by OfTheDelmer** [influxdata/influxdb#12962]
As part of #12907 a user should be able to see labels associated with a newly created template.

We need to determine the following:

- What labels should we automatically apply to a template, i.e. a `system` or `autogenerated` label
- Can users add/remove labels to a template in the export overlay before saving

**Comment by ebb-tide** [comment]
We've decided on the prefix `@influxdata` for labels that should not be visible to user. 
What should we use to indicate that a label was added automatically by ui?

**Comment by alexpaxton** [comment]
I don't have a strong opinion on how this works, but my gut feeling is to use the `properties` key instead of relying on prefixes in the label's name. Only argument for this is we wouldn't have to keep track of the string to filter on, and can instead have a key like `type: 'system' | 'user'`. I think we can also use properties to store any meta information about how and why the label was created

**Comment by OfTheDelmer** [comment]
@alexpaxton Properties are schemaless to help capture new concerns like these and other that might develop later as result.  Serializing this information into the name might not be as flexible going forward.

If we choose a `properties` key like `type`  we could display an Influx icon on labels that are autogenerated to make it clear we generated it. The label name could focus on capturing info about the thing being monitored `system`, `redis`, `kubernetes`, etc.

**Comment by ebb-tide** [comment]
This has been addressed in https://github.com/influxdata/influxdb/issues/14081
