### ISSUE TITLE
Design capabilities API for query planner

### ISSUE THREAD

**Issue by jlapacik** [influxdata/influxdb#13055]
A storage read source should expose a capabilities API so that any planner rewrite rule that involves push-downs to storage should be able consult this API to determine if the rewrite/push-down can be performed.

As an initial sketch, a storage read source should implement the following interface:
```go
type Source interface {
    Capabilities
}
```

where the Capabilities API is defined something like this:
```go
type Capabilities interface {
    SupportsTagKeyPushDowns() bool
    SupportsTagValuePushDowns() bool
    SupportsAggregatePushDowns() bool
    ...
}
```

A procedure spec for a physical read operation should then be associated with a particular source (like InfluxDB). Perhaps implementing an interface such as:
```go
type StorageReader interface {
    Source() Source
}
```

This means that every such procedure spec would have a method for obtaining its associated `Source`. Take the following query as an example:

    from |> range |> filter |> sum

The physical planner will rewrite this query in the form:

    FromFilter |> sum

where `FromFilter` is a storage read operation. In order to push `sum` down to storage we need to know if our particular source supports aggregate pushdowns (or perhaps even more specifically `sum` pushdowns). Hence the rewrite rule for this query pattern will be implemented something like this:
```go
...
spec := fromFilter.ProcedureSpec()
if n, ok := spec.(StorageReader); ok {
    // if the underlying storage source doesn't support pushing down
    // aggregates, then return false. We can't perform the rewrite.
    if !n.Source().SupportsAggregatePushDowns() {
        return false
    }
}
...
```

Outstanding questions:
* How to register a particular `Source` with a physical procedure spec?

**Comment by nathanielc** [comment]
A couple of questions:

* How do we deal with sources that are not InfluxDB? For example SQL sources etc.
* Should we separate out the capabilities from the source interface? Meaning do we have to have an instance of the source in order to know its capabilities? If so is it easy for the planner to have access to that instance?

**Comment by jlapacik** [comment]
Capabilities would need to be tied to an instance of a source. In the case of a SQL source with a driver that implements a capabilities API, different versions of the database might have different capabilities. A connection will need to be established during planning in order to determine which operations can be pushed down.

However, there might not be a need for a `Source` interface. Perhaps the procedure spec looks like this:

```go
type FromSQLProcedureSpec struct {
    source Capabilities
    ...
}
```

And the concrete type looks like this:

```go
type sqlSource struct {
    db *driver.Database
}

func (s *sqlSource) SupportsAggregatePushDowns() bool {
    return s.db.Capabilities().SupportsAggregates()
}
...
```

A connection to the database would be established when the procedure spec is instantiated. The rewrite rule would then call `spec.source.SupportsAggregatePushDowns()` to see if it could perform the rewrite.

**Comment by wolffcm** [comment]
I see the purpose of the capabilities API serving to tell `queryd`'s planner which RPCs are currently available.  Or maybe, since we may contact several storage nodes to fulfill a query, which RPCs are supported by all the nodes.  

Maybe we could treat the capabilities API similarly to how we deal with dependencies for `from`/`to`/`buckets`.  It doesn't necessarily need to be standard across different kinds of sources.  Maybe rules could use capabilities something like this:
```go
...
spec := fromFilter.ProcedureSpec()
if n, ok := spec.(StorageReader); ok {
    // if the underlying storage source doesn't support the readFilter RPC,
    // we can't do the rewrite.
    if !n.SupportedRPCs["readFilter"] {
        return false
    }
}
...
```
Since the physical specs will be specific to each source, and each source might have a different data model, etc, maybe a more ad hoc approach is warranted to enable the specific optimizations available.
