### ISSUE TITLE
InfluxDB 2.0: The "GET" method of "/dashboards/{dashboardID}/cells/{cellID}/view" should return "cell not found" for a cell that doesn't exists [area/api]

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#13083]
The `/dashboards/{dashboardID}/cells/{cellID}/view` should return `cell not found` for a cell that doesn't exists:

```bash
-> GET 
-> http://127.0.0.1:9999/api/v2/dashboards/03a3789a6a393000/cells/ffffffffffffffff/view 

<- 404 
<- Not Found
<- {
	"code": "not found",
	"message": "view not found",
	"error": {
		"code": "not found",
		"message": "view not found"
	}
}
```

**Comment by kelwang** [comment]
Hey @desa, needs your inputs here. I interpret this issue as "view not found" could be a little confusing.  

in order to achieve what @bednar asked, we could do a dashboard search first, then change the "view not found" error to "cell not found" error. 

as well as update, delete, patch for the view.

**Comment by desa** [comment]
`cell not found` seems like the correct error to return to me.
