### ISSUE TITLE
Does Chronograf support string display like Grafana?

### ISSUE THREAD

**Issue by nbosco** [influxdata/influxdb#13124]
<img width="365" alt="screen shot 2018-01-24 at 10 58 53 am" src="https://user-images.githubusercontent.com/8681317/35351407-aa8c2992-00f5-11e8-90b7-710cbf6ef7f0.png">

It looks like Chronograf only supports integer display, if I'm wrong please clarify, otherwise let's add that feature.

**Comment by bmitchell-cfs** [comment]
Re-opening this issue. I came across this today expecting this to work since strings are supported field and tag datatypes. Using the "Single Stat" visualization type in Chronograf (version 1.8 of TICK stack), strings are displayed as "NaN".

Better boolean support would also be great. Right now, the "Single Stat" visualization type displays booleans as "0" or "1". An round LED type of display would be awesome.

**Comment by hoegge** [comment]
Yes - would be great. If strings are equally valid measures as numbers, they should also be shown in Chronograf

**Comment by thevlab** [comment]
yes, hope they can add this feature. support string display like grafana

**Comment by thevlab** [comment]
how to reopen this issue? anyone please advise

**Comment by Gill-Bates** [comment]
Really bad. The map() Function of Flux is very powerful but cannot be used in combination with Strings when using Influx/Chronograf Dashboards.
