### ISSUE TITLE
The UI should display easy to understand notifications on rate/limiting errors for queries

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#13422]
As a user makes a query or series of queries that exceed usage rates- the backend will reject the request with an HTTP 429 [#3109](https://github.com/influxdata/idpe/issues/3109)

The UI should display a notification that is easy for the user to understand that a rate limit has been reached.

In particular, let's test a dashboard in expectation that it may be easy for users to exceed max: 2 concurrency limits on queries. 

Check: data explorer and dashboard View Editor Overlays

**Comment by bpalani** [comment]
Got this from @lukevmorris.
- When they can't create a bucket, they get a message saying they're at maximum buckets
- When they submit a query that is denied because they're over their query limit, they get a message saying so and telling them to try again later
Confirmed that these are the behavior I would like to see in UI. On the query side we have set the query concurrent limit as 2 which I think is problematic given a dashboard can have more than 2 cells which could in theory all refresh at the same time and cause issues. Will need to watch this behavior and adjust either the limit or find another solution.

**Comment by ebb-tide** [comment]
As per our discussion this morning- UI will display a "you have exceeded limits" notification on index pages of dashboards/buckets/tasks/users if user is at max limit.

**Comment by ebb-tide** [comment]
(on cloud only)
- [ ] On dashboard and data explorer mount, query for read / write / concurrency limits, and display banner notification if limited. 
- [ ] On dashboard page or data explorer page, if a query returns 429 status code, display error notification and error string in place of visualization.
