### ISSUE TITLE
fix flaky onboarding e2e test

### ISSUE THREAD

**Issue by AlirieGray** [influxdata/influxdb#13565]
The e2e test for onboarding sometimes fails at "can onboard to advanced" at this line:

```
//wait for new page to load
      cy.location('pathname').should('match', /orgs\/.*\/buckets/)
```

Instead of going to the buckets page, sometimes the app gets stuck on the home page and the test fails.

**Comment by karel-rehor** [comment]
I've tried running this test in a loop in a bash script 

```bash
#!/bin/bash

for (( x=1; x <= 50; x += 1 ))
do
  ./node_modules/.bin/cypress run --spec cypress/e2e/onboarding.test.ts
  echo $? >> results.txt
done
```
It appears that one test run out of roughly thirty runs onto this issue. 

```
CypressError: Timed out retrying: expected '/orgs/03bff3ba7917a000' to match /orgs\/.*\/buckets/
```
My hunch is that it is likely a race like issue with the UI.  Each button on the completion page has its own data-testid (`data-testid="button--quick-start"`, `data-testid="button--advanced"`, `data-testid="button--conf-later"`), so there should be no confusion in Cypress about which one will be pressed.

I'm less confident about how reliable should be `router.push` from react-router, but this is partly due to lack of familiarity with react-router API.
