### ISSUE TITLE
Cardinality metrics disagree with each other

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#13690]
`storage_series_file_series_total` disagrees with `storage_store_series_active`.

Ideally they should report the same cardinality value as the Series File and TSI index should be in sync.

I'm seeing dramatic differences in the values. My hunch is that the series file metric is still counting series that have been deleted, and the TSI index one is not.

**Comment by benbjohnson** [comment]
Update: The tombstones are not being included in `SeriesIndex.Count()`. I'm trying to fix that but I'm working through issues in the unit test where I'm getting unexpected results.

Another issue is that `Store.monitorShardCardinality()` updates `storage_store_series_active` every `MonitorCardinalityInterval` (`10s` by default). However, the `storage_series_file_series_total` only seems to be updated on `Open()` so that number will lag behind. @e-dard Do we want this updated on an interval in a goroutine or can I update the value whenever the count changes?

**Comment by e-dard** [comment]
@benbjohnson what are the tradeoffs of each approach? Given the TSI one (`storage_store_series_active`) is only updated and observed periodically, I wonder if we can do the same with the series file metric.

**Comment by benbjohnson** [comment]
I'm not sure there's strong tradeoffs either way. It's probably better to keep it consistent with the other metric and throw it in a goroutine.

**Comment by benbjohnson** [comment]
Fixed by #13770. Additional goroutine unnecessary as series are incrementally tracked here: 

- Add: https://github.com/influxdata/influxdb/blob/a181e60d70c02a3eed360a9414d90f07051f3665/tsdb/series_partition.go#L305
- Delete: https://github.com/influxdata/influxdb/blob/a181e60d70c02a3eed360a9414d90f07051f3665/tsdb/series_partition.go#L380
