### ISSUE TITLE
Remove builder-configs when exporting dashboards

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#13722]
builder config blocks are not required for exports and can actually cause issues when another user imports a dashboard and then edits a cell. We should remove them from all exports and templates.

**Comment by Adrenaline1554** [comment]
`h`

**Comment by ebb-tide** [comment]
There are two ways to solve this.
One is to sanitize queries when exporting, so that a saved dashboard has a builderConfig, but an exported dashboard does not. This is pretty easy to do.  
The other is to remove builderConfigs upon saving a dashboard. This is also easy but I do not have context on its implications. The QueryBuilder has logic that assumes a builderConfig exists if view is not new. Should we be resetting the QueryBuilder to defaults on saving a cell?

**Comment by chnn** [comment]
@russorat @ebb-tide  What issues are caused by the presence of a builder config? It might have a totally different solution that removing the `builderConfig`, which seems unnecessary to me, or like something else is wrong if that is indeed a solution.



If you open a cell and want to edit it with the query builder, then the `builderConfig` needs to exist but the `text` does not. Conversely, if you open a cell and want to edit it with the script editor, then the `text` needs to exist but the `builderConfig` does not. Whether you want a cell to be editable with the builder or script editor is specified by the `editMode` field.

Another way of putting this is that currently our `DashboardQuery` type looks like this:
```
interface DashboardQuery {
  text: string
  editMode: QueryEditMode
  builderConfig: BuilderConfig
  name: string
}
```
But really this is the interface we conform to:
```
type DashboardQuery = 
  | {editMode: QueryEditMode.Advanced, text: string, name: string}
  | {editMode: QueryEditMode.Builder, builderConfig: BuilderConfig, name: string}
```

So I guess a question is: do you want cells in an imported dashbord to be editable with the builder or with the script editor? I suspect some queries will be editable by the script editor only.

**Comment by ebb-tide** [comment]
Ok- after looking at this more carefully @chnn is completely right that the builderConfig contains the state we would like to return the user to after navigating away from query builder, and it's appropriate for saved dashboards to contain builderConfig. 

Except in the case of an imported dashboard where the query is just a little bit 
'wrong', like if the bucket / tags or measurements etc don't exist-- the UI does not fail in a way that allows user to fix the problem. Time Machine opens in builder mode, but bucket/measurement/tags can not be found, there is an error message in the cell view. Navigating to scriptView erases the script text. 

With the PR above, I've made it so templates are always exported in editMode:'advanced' with builderConfigs returned to defaults, so that even if the query does not work in new context, user has chance to modify query and potentially make it work.
