### ISSUE TITLE
Add more configuration options for line graph interpolation

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb#13762]
Depends on #13736

We should add more configuration options for line graph interpolation here:

![smoothing](https://user-images.githubusercontent.com/638955/57107430-d1d12a00-6ce4-11e9-9712-e37d9e13a591.gif)

The available options are:

```
type LineInterpolation =
  | 'linear'
  | 'monotoneX'
  | 'monotoneY'
  | 'cubic'
  | 'step'
  | 'stepBefore'
  | 'stepAfter'
  | 'natural'

```

We should persist this option in the `geom` field of an `XYView`.

**Comment by adbugger** [comment]
Please expose the stepBefore / stepAfter (whatever is the behaviour in influx1.7) in influx_v2. Currently, the line graph shows the 'step' at the midpoint of 2 adjacent timestamps, whereas earlier the 'step' was at the new timestamp. This feature would be helpful in viewing exactly when a change occurred without the user having to hover on the series and use the tooltip.

P.S. Since this issue is closed, is a new feature request more appropriate for this?
