### ISSUE TITLE
Zero in the top right corner of the line graph on hover

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#13942]
I see a little zero in the top left corner of the graph (probably the hover legend). and i can't seem to find any points on the graph.

![image](https://user-images.githubusercontent.com/4805997/57867939-e0c0dd80-77b6-11e9-8b4f-437d78c6888b.png)

[2019-05-16-08-44 Chronograf Data.csv.zip](https://github.com/influxdata/influxdb/files/3187882/2019-05-16-08-44.Chronograf.Data.csv.zip)

**Comment by chnn** [comment]
@russorat That data set contains 143 series, each containing a single point. What would you expect to see instead? Something like a scatterplot?

I'm thinking that maybe line graphs should show the individual points if there's enough space. What do you think?

As for the 0 appearing in the top left: I think that's fixed in @influxdata/vis 0.7.0, which I integrated into the UI last night. Let me know if you still see it with the lastest influxdb master (I am not able to reproduce it).

**Comment by russorat** [comment]
@chnn I'd like to see the 143 series shown as dots on the screen somewhere.

**Comment by chnn** [comment]
@russorat Open https://github.com/influxdata/vis/issues/54 as a proposed solution.

**Comment by russorat** [comment]
closing in favor of https://github.com/influxdata/vis/issues/54
