### ISSUE TITLE
TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#14076]
Trying to set up and use a variable in my dashboard. The query works when in the veo, but when i save and go back to my dashboard, it throws this error.

![Kapture 2019-06-06 at 10 17 25](https://user-images.githubusercontent.com/4805997/59052661-62e77380-8844-11e9-8440-42152e01a2fc.gif)

![image](https://user-images.githubusercontent.com/4805997/59052383-db016980-8843-11e9-9d5e-b11281d16251.png)

**Comment by russorat** [comment]
this happens to any variable that has other variables.

**Comment by chnn** [comment]
Not sure I am able to reproduce this exactly. I created a few variables (with dependencies on each other) and used them in various ways with the VEO. I did manage to see the crash that you are seeing the variable control bar, and have a fix for it in https://github.com/influxdata/influxdb/pull/14113.

The crash happens whenever a variable fails to populate its values. So it looks like the `city_name` variable is populating in the VEO successfully, but not on the dashboard. This could be the case if the `city_name` variable depends on a certain other variable selection being made to populate successfully, since the selections in the VEO and on the dashboard are separate.

Can I log into your account to take a look at this dashboard? And would you mind posting some steps to reproduce?

**Comment by russorat** [comment]
i'm having a tough time repro'ing as well now. i will close and reopen if i see it again.
