### ISSUE TITLE
Do not push empty string comparisons down to storage

### ISSUE THREAD

**Issue by jlapacik** [influxdata/influxdb#14093]
InfluxDB does not support the empty string as a tag value. Instead storage uses the empty string in testing for the existence of tag keys as part of a predicate (#13880). As a result the `PushDownFilterRule` should not push down comparisons against the empty string but instead evaluate them on the Flux side.

**Comment by nathanielc** [comment]
@jlapacik and I revisited this  and decided that it should be an error instead of being implemented on the Flux side.

> As a result the PushDownFilterRule should not push down comparisons against the empty string but instead evaluate them on the Flux side.

This is because the condition `r.t0 == ""` is semantically always false if it is in a position to be pushed down to storage. As such it is likely that the user made an error vs that they do not want any data from storage. The error should suggest that the user employ the `exists` function if they just want to ensure that the tag `t0` exists on the data.

In contrast `r.t0 == ""` is valid in contexts where it is not pushed down to storage.

**Comment by jlapacik** [comment]
I agree with you @nathanielc , if the planner determines that a user is pushing down an empty string comparison, an error suggesting they use `exists` represents the most helpful option.

**Comment by jsternberg** [comment]
An error likely isn't correct because then it changes the behavior so that the pushed down version returns a different result than the one that does not push anything down.

I agree that an empty string comparison won't return any results ever and there's no valid reason to query for that, but it seems to me like that just means you get no results.

Also, I was thinking about it and `!= ""` does actually end up meaning something that's fairly interesting. While the storage engine cannot return an empty tag, it can return null for a series and that expression evaluates to false if the tag is empty which is the same behavior as if it returned an empty string. So we can likely pass through `!= ""` as-is.

**Comment by nathanielc** [comment]
@jsternberg I agree, you could argue that it doesn't change semantic equivalence because the error condition is just an additional safety check after all the planner rules have been applied. But that feels like too much of a rationalization. I asked my self under what circumstances would a user want to make a `r.t0 == ""` query to storage and actually came up with a reasonable example.

Say that you have a function that accepts a parameter `v0` and you use it in a filter like `r.t0 == v0`. It would be inconsistent and potentially breaking to error in cases where `v0 = ""` and not error when `v0 = "a"` for example.

**Comment by jlapacik** [comment]
I spoke too hastily. Preserving semantic equivalence is fundamental to query optimization and though this seems like a nice compromise for the user and fairly contained, it could possibly have unintended consequences. I think I agree with @jsternberg, semantic equivalence of rewrites should be an invariant that we do not compromise under any circumstances.

**Comment by jsternberg** [comment]
This was done as part of #14538 and will be tracked with #14092.
