### ISSUE TITLE
can not access influxdb database with curl

### ISSUE THREAD

**Issue by jhx2002** [influxdata/influxdb#14115]
Please read this post:

https://stackoverflow.com/questions/56453622/how-to-access-influxdb-database-with-curl

**Comment by jhx2002** [comment]
could any one help me?

**Comment by jhx2002** [comment]
no one resolve the problem?

**Comment by bogski87** [comment]
Its because you're sending an http request, Run it with HTTPS

curl --tlsv1.2 -o tmp.txt -G 'https://localhost:8086/db/tmpdb/series?u=root&p=root'

I noticed on the stackover question it mentioned self signed certificates. You will most likely need to specify -ssl and -unsafeSsl to use SSL and trust your unsigned cert. 

Hopefully this [documentation](https://docs.influxdata.com/kapacitor/v1.5/administration/security/) will help, but if not you might have better luck over on the InfluxData community forums. 

[Community](https://community.influxdata.com/)

There are some good people on there who will probably be able to help also.

**Comment by jhx2002** [comment]
I test the case after your suggestion. But still not work.

**Comment by russorat** [comment]
this would be better for https://community.influxdata.com . We try to keep github for bugs and feature requests.
