### ISSUE TITLE
Support lag variables

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#142]
We should support bringing in lag variables so people can calculate changes and things like that. For example you have the following data:

```
time, value:
1, 6
2, 7
3, 4
```

And you run this query: `select value, lag(value, 1) from some_series` you would get:

```
time, value, value_lag_1
1, 6, null
2, 7, 6
3, 4, 7
```

So then you could do a query like: `select value - lag(value, 1) as change from some_series`:

```
time, change
1, 6
2, 1
3, -3
```

The argument to the lag function tells it how many lagging points you want to include. For example if you do `select value, lag(value, 2)` you'd get:

```
time, value, value_lag_1, value_lag_2
1, 6, null, null
2, 7, 6, null
3, 4, 7, 6
```

**Comment by phagedorn** [comment]
:+1:

**Comment by mattchurchy** [comment]
Yes please! :-)

**Comment by rmoff** [comment]
+1 for this. Would be excellent for being able to look at metrics compared to previous (day|week|etc).

**Comment by exabrial** [comment]
Just curious, What's the difference between this and `difference(value)` function?

Also, will either the `lag(value)` function or the `difference(value)` function support extrapolating to regular intervals?

so if my data is 

Time, Value
1,5
3,3

Is it possible to normalize the time values:
1,5
2,4.5
3,3
etc...

**Comment by 3fr61n** [comment]
It would be great to have a way to calculate 'real delta' using lag or any other similar function that only calculate the increment between a sample and it predecessor

I don't like to use difference(value) because you are forced to aggregate using groups, and you miss information when aggregate

For instance, in the following time series, each minute it increases 10, so the series looks like

Time, Value, 
0,  10, 
1,  20, 
2,  30, 
3,  40, 

When doing 'difference(value) and group(2m)'  the result looks like

Time, Value, 
0,  10,   <--- This is the difference between samples at min 1 and 0
2,  10,  <--- This is the difference between samples at min 2 and 3

Which seems ok, but you are missing the delta between min 2 and min 1, and in some scenarios this is not acceptable :(

Does anyone have any other idea about how to perform 'delta' between each 2 consecutive samples? or do we have any timeline when 'lag' function will be available?

Thanks in advance.

**Comment by timgriffiths** [comment]
+1

**Comment by beckettsean** [comment]
@jwilder does the derivative function without a GROUP BY effectively give us the lag feature as described?

**Comment by jwilder** [comment]
@beckettsean No.  Lag looks different at first glance.

**Comment by ivanscattergood** [comment]
Will this lag function work on the Time column? I need to calculate the time difference between events so I can calculate the length of time a metric stays in a certain state. 

At the moment my best solution is to write this time difference back to the previous record, BUT a lag function would be more elegant

**Comment by cory-p-oncota** [comment]
Would love to see full support of windowing functions (lag, lead, rolling average/sum, etc) since they would all likely utilize similar internals. Full-fledged syntax would definitely be preferred (e.g. SELECT time, cluster, node, val, LAG(val, 1) OVER(PARTITION BY cluster, node ORDER BY time) FROM series) where partitioning is optional and the ordering defaults to time but allows other tags.

**Comment by huhongbo** [comment]
+1

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by maxsivanov** [comment]
This can be used as stop gap solution
https://github.com/maxsivanov/influxdb-timeshift-proxy

**Comment by ChampionL** [comment]
+1
