### ISSUE TITLE
Syslog cluttered with loglines containing two numbers in Influx 1.7.7 OSS Debian 8 

### ISSUE THREAD

**Issue by BerndWi** [influxdata/influxdb#14265]
Hi,

we have upgraded to influxdb 1.7.7 on Debian 8 from your repositories. 
After starting the new version, we get more than 8000 loglines per second of just two numbers. It seems that a debug output hasn't been stripped before this release.

The lines look like the following:

`Jul  5 09:47:54 influx3 influxd[160290]: 1674 1674
Jul  5 09:47:54 influx3 influxd[160290]: 2510 2510
Jul  5 09:47:54 influx3 influxd[160290]: 1650 1650
Jul  5 09:47:54 influx3 influxd[160290]: 2474 2474
Jul  5 09:47:54 influx3 influxd[160290]: 1650 1650
Jul  5 09:47:54 influx3 influxd[160290]: 2474 2474
`
Has anyone else seen this behaviour? I couldn't find anything in the config where debug logs are enabled.

Best regards,
Bernd

**Comment by mark-rushakoff** [comment]
Thanks for raising this issue @BerndWi. You're right, I looked at the diff between v1.7.6 and v1.7.7, and I noticed this line: https://github.com/influxdata/influxdb/blob/f8fdf652f348fc9980997fe1c972e2b79ddd13b0/tsdb/engine/tsm1/batch_string.go#L41

Looks like that was introduced to the 1.7 line in https://github.com/influxdata/influxdb/pull/14083. Same `fmt.Println` was included in the 1.8 line PR https://github.com/influxdata/influxdb/pull/13699.

I don't think there's any simple way we can turn that off without cutting a v1.7.8 release. I think in (almost?) all cases the numbers will be the same, so you could grep out the lines with `grep -v -E '^([[:digit:]]+) \1$'` in the meantime.

I'll raise this with the product team so that we can get this prioritized in a release asap.

**Comment by russorat** [comment]
this fix is in 1.7.8 which is in rc0 at the moment.

**Comment by JNCone** [comment]
Hi, 
are there any config changes needed? I updated to 1.7.9 and I still have this behavior in my logfiles.

best
Chris

**Comment by russorat** [comment]
@JNCone thanks! that specific line is definitely not in the 1.7.9 code, so either the message is coming from somewhere else or you are still running an older version of InfluxDB. Can you confirm it's not the latter and then we can reopen this issue?

**Comment by JNCone** [comment]
@russorat thanks for fast answer! It was a mistake from my side, I didn't restart the process after the upgrade. No more messages since the restart, so all good. Thanks a lot.
