### ISSUE TITLE
Check in updated swagger API contract for checks to influxdb

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#14284]
Swagger API contract needs to be in influxdb master in order to generate types for influxdb js client.

**Comment by chnn** [comment]
It seems like the alerts + notifications work will generate a steady stream of API changes, and it would be exhausting to have each change go through the whole cycle:

1. Checkout client
2. Regenerate swagger
3. Open client PR and get it reviewed
4. Merge client PR
5. Publish new version
6. Open PR in InfluxDB to integrate new client version + get it reviewed

This might be a good time to rethink this workflow. We talked at retro recently about moving the client back into the influxdb repo, since it's so painful / slow to keep it separate.

Also somewhat unrelated, but the types generated by `openapi-generator` are really poor—especially when it comes to OpenAPI enum types, of which there are many in the alerts + notifications API. Since we rely on types so much now for correctness and to catch breaking changes, I think it would be worthwhile to see if we can improve the type generation. I spiked on a OpenAPI spec to types generator a while back and it seemed pretty straightforward.

@ebb-tide @121watts Thoughts?

Connect https://github.com/influxdata/influxdb/issues/14285

**Comment by 121watts** [comment]
@chnn I would love to move the client into `influxdb`.  The problems it solved are outweighed by the costs of its maintenance.  Are you suggesting rolling our own types generator based on the OpenAPI spec?

**Comment by chnn** [comment]
> Are you suggesting rolling our own types generator based on the OpenAPI spec?

Yep. I think there's two pain points right now:

1. We generate the client from the API spec in a separate repo, which complicates our workflow
2. The API generation isn't very good, so we (shoddily) wrap the generated output with handwritten types and utilities

I think our own generator would solve #2 only, but it is by no means necessary for solving #1.
