### ISSUE TITLE
Support lead variables

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#143]
Should work the same as #142 but for leading data points. `select value, lead(value, 1) from some_series`

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
