### ISSUE TITLE
Connecting multiple Collectd to one  influxdb instance

### ISSUE THREAD

**Issue by makutamatey** [influxdata/influxdb#14490]
Please, it is possible to connect multiple collectd instances to influxdb?

**Comment by dgnorton** [comment]
@makutamatey Do you want instances of `collectd` running on multiple servers to be able to write to one InfluxDB instance? If so, that is already supported. Just point them at an instance of InfluxDB that has `collectd` configured.

Or, are you asking for one instance of InfluxDB to support multiple `collectd` configurations (port, database, retention policy, etc.)? That is also supported. You can add multiple `[[collectd]]` sections to the config. InfluxDB uses `toml` as its configuration format. In `toml`, the `[[...]]` denotes an [array of tables](https://github.com/toml-lang/toml#array-of-tables). So, in the config file...
```
[[collectd]]
<settings for 1st instance>

[[collectd]]
<settings for 2nd instance>

etc.
```

**Comment by nick2k3** [comment]
Hi, sorry to reopen this issue but I would like to ask something similar to OP.
I have one configuration of collectd that writes on a database named "collectd":
```
[[collectd]]
  enabled = true
  bind-address = ":25826"
  database = "collectd"
#  retention-policy = ""
#  batch-size = 5000
#  batch-pending = 10
#  batch-timeout = "10s"
#  read-buffer = 0
  typesdb = "/var/lib/influxdb/types.db"
#  security-level = "none"
#  auth-file = "/etc/collectd/auth_file"
#  parse-multivalue-plugin = "split"
```

I can have several server write to that database but unfortunately they all tag the data with "hostname" = localhost

Is there a way to differentiate the way data are tagged in collectd? Or perhaps add some config entry in influx to add a tag with the source IP?

One alternative would be to have three configuration entries and have them all writing to three different databases, but I don't like it a lot because would make the very hard to graph data from different hosts at the same time in grafana or chronograf.
