### ISSUE TITLE
Add created by and owner id to all user created resources

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#14671]
every user created resource in the system should store a created by and owner id in it's metadata.

- [ ] Audit all resources to find any without created by and owner id
- [ ] Create issues to address them.

**Comment by pauldix** [comment]
Should be `createdByID` and `ownerID`

**Comment by rbetts** [comment]
Let’s make the minimal swagger changes to get this working on the new alerting resources. We will schedule the comprehensive change for after marketing release. I’d prefer not to embark on changing all the API resources mid alerts epic.

Need to consider swagger, clients, QA litmus tests, new tests that the createdBy fields are immutable, explanation of what happens when either user is deleted (when that’s supported).

**Comment by goller** [comment]
I'd like to see a more comprehensive approach to "audit"-style information.  We've done this work piecemeal with modification by, modification time, created time etc.

I'd like to see a more higher-level goals rather than field nsame for this type of data so we can deliver a well designed API.
