### ISSUE TITLE
Plan work for all writes through `gatewayd` in idpe

### ISSUE THREAD

**Issue by GeorgeMac** [influxdata/influxdb#14921]
In order to deliver the behavior described within the write accounting RFC (found here https://github.com/influxdata/idpe/pull/4260) it has been decided that writes made by the `to` function, `taskd` run logs and any other storage writes will go through gatewayd using the [influxdb-client-go](https://github.com/influxdata/influxdb-client-go) library.

This issue is intended to track the work done to plan this change.
The product of this card should be a set of issues outlining the changes required in the following components:
- idpe
  - gatewayd
  - taskd
- influxdb-client-go

**Comment by stuartcarnie** [comment]
@GeorgeMac going to alter the title so that it represents all writes through gateway. Currently we use a PointsWriter in `taskd` to write the run logs when a task executes. This too needs to direct writes to `gatewayd`. Hopefully we can create a new `PointsWriter` that can be used for `to` and regular writes.
