### ISSUE TITLE
Spike: local development done in docker

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15337]

**Comment by desa** [comment]
@drdelambre please add any context to the spike here 😃

**Comment by drdelambre** [comment]
so.... i went on a journey. and i'm going to try and spit out a really high level overview of it here. there was a lot explored, so feed back is appreciated in case i missed the mark.

;TLDR; not hard to do, needs a more solid value prop for the team.

first some context on why this is even being explored. i'm used to developing locally from docker. I find it super awesome and useful for constructing complicated development environments that can be shared as workflows for fellow developers. Being able to spin up arbitrary infrastructure that has been developed by others in a team has a lot of cool side effects; from mocked subsystems to advanced performance evaluation to stretching deployment sequencing paradigms. There is also an awesome property of virtualization in a large organization where, if you can guarantee that a production image being deployed is going to be the same as a development image, production complexity is pushed to the edge nodes and the devops team doesn't have to scale linearly with the application teams. Mixed content / CORS / JWT validation across domains / whatever weird issue that comes up when a web product is pushed into the infrastructure should be caught and dealt with at the developer who added the feature. Sometimes this is viewed as the death of the "it works on my machine" argument.
But nothing is perfect, and containerized development has some downfalls. Two of the most general complaints that have popped up in my experience of rolling the paradigm out to teams are 1) speed and 2) a general mistrust of magic. You can expect tests, linting, and compression to run at half the speed within virtualization. When you add an orchestration layer like minikube, file watching and hot reload features disappear, but the rest of the stack doesn't seem to be affected during development (as long as you give typescript enough RAM), and using adhoc docker-compose files and some creative mocks might delay the requirement for local orchestration entirely. The later complaint is far more dangerous for the technology's adoption. It ties into the promise of pushing the complexity back to the developer and captures a tendency of teams to reject the tool, citing it as the cause of this complexity. If a project survives the initial education and adoption phases, this problem falls off completely. But there's a rough period, and if the adoption isn't solving production issues in a local development environment (an initial contract assumed above), this project only adds friction.

DISCLAIMER OVER!

After gauging the team's current experience / familiarity with this paradigm, and assessing some of the current development infrastructure's pain points (predominately the speed/complexity of testing meaning that it makes more sense to not run locally), I'd recommend that we DO NOT try to implement it yet. The cost of the disruption while everyone is currently fighting the toolchain seems to outweigh the immediate benefits.

That being said, while exploring possibilities, I ended up making all of the initial infrastructure required for local development and changes to the existing project to allow for it. It would need some polishing before release though. Solving the "how" wasn't as hard as solving the "why". Recommended follow up actions revolve around developing a use case around the why:

1) have a prod image / devops pipeline that reflects the local development environment. this helps strengthen the contract between developers and operations and move the former to more of a 'service owner' role while rationalizing the pain of adoption.

2) make the tools available to the team, with a lot of education about docker's role in engineering these days and have a unified set of talking points behind the push. For some people it may never make sense to make this jump outside of keeping all node versions at LTS. There should be a more compelling reason being communicated that affects them directly.

3) set up some jenkins pipelines that directly affect local development. These can be viewed as layered vm caching systems from an ops perspective (low initial value add / later optimization), but the artifacts can also be used to reduce setup time for developers and target caching layers to their development cycle [read: dont yarn install or set up a gopath ever again] (high value because developer time is expensive). example stack: chrono_node [base node version + ubuntu packages] -> chrono_deps [yarn install run on a package.lock] -> chrono_env [all the transpilation tools that make js possible] -> chrono_test [testing resources added]. NOTE: this would trigger another spike on how to update local docker instances without invoking jenkins, but Mark Rushakoff tells me that this is easy / done elsewhere.

4) Demo some use cases of a value add

**Comment by desa** [comment]
@drdelambre really great write up. I'm going to close and label this so that we can revisit it in the future.
