### ISSUE TITLE
Sort by "Modified" in Dashboards does not sort by modified date

### ISSUE THREAD

**Issue by sjwang90** [influxdata/influxdb#15610]
__Steps to reproduce:__
1. Go to Dashboards page
2. Default page is sorted by Name, Click "Modified"
3. Sorting by Modified does not sort by last modified date, continues to sort by name

__Expected behavior:__
When select "Modified", expect dashboards to sort by modified in asc/desc order

__Actual behavior:__
Sorts by Name

![dashboards_sortbymodified](https://user-images.githubusercontent.com/32681364/67704901-38bd5c00-f973-11e9-8738-583f272c53e9.gif)

**Comment by karel-rehor** [comment]
I can confirm this issue is showing up in the nightly builds 

```
ts=2019-11-25T08:43:10.485363Z lvl=info msg="Welcome to InfluxDB" log_id=0JKRVw5G000 version=nightly commit=ce9ce176d build_date=2019-11-25T07:23:15Z
```

![SortDashboardsByModified](https://user-images.githubusercontent.com/25881301/69530692-c0968600-0f72-11ea-9a61-a51703dc6033.gif)

Adding label 'selenium/nightly' because we want to cover this in the nightly tests.

Related Issues
#15379  
#15247 
#14923 
#13950 

Note the attached json shows the creation/modified order of the dashboards 


[dashboards-order.json.txt](https://github.com/influxdata/influxdb/files/3886004/dashboards-order.json.txt)
