### ISSUE TITLE
_measurement and _field should be single select in Data Explorer

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15626]
![field-selection-remains](https://user-images.githubusercontent.com/1477539/67778640-daa77c00-fa39-11e9-8b1b-ded6b1b8cd87.gif)

If the user wants to visualize more than one field/measurement they can create another query

**Comment by sanderson** [comment]
I think there are benefits to allowing users to select more than one measurement and field in a query (fields especially):

1. To use CPU metrics as an example, say a user wants to included both `usage_system` and `usage_user` in the same graph. The could create two queries in the same cell, but this doubles their reads when they could easily do it in one query.
2. Maybe less of a case with measurement, but I think the same applies. Being able to query and compare metrics from multiple measurements without unnecessarily increasing the query load seems like a win to me.

**Comment by desa** [comment]
@sanderson I definitely understand where you're coming from.  I feel less strongly about fields than I do about measurements.

Measurement should be single select because without it the possible tags that are displayed are nonsense. For example suppose I select `disk` and `mem` for measurements and then I look at the possible set of tags and I select the `device` tag and filter by a particular device there. If I do that, I will be filtering out all of the `mem` values in the first place.  I could limit the possible fields to tags that they have in common, but that seems like not necessarily the right thing to do either, since their is no guarantee that the common tag key has common tag values.

**Comment by sanderson** [comment]
☝️That's a good point and one that has often bugged me. I feel less strongly about allowing multiple measurements than I do about allowing multiple fields.

If we were do allow multiple measurements/fields, I think the UI should be updated to somehow group the fields and tags lists to show which measurement each is coming from, but this may not be feasible.

Here's a quick mockup of an idea:

![image](https://user-images.githubusercontent.com/181484/67785085-556c9900-fa32-11e9-9637-1c95910a24bc.png)

**Comment by desa** [comment]
Yeah, that could potentially work.

My general feeling is that a simple query builder will be sufficient for 80% of queries and that the other 20% should be pushed into writing a custom flux query. I'd like to keep the types of queries that one can build in the UI using the query builder very simplistic. The types of queries I'd like to have be query builder based are

1. Raw select of a single measurement & field with grouping
2. AggregateWindow of a single select of measurement & field with grouping
3. Overall aggregate of single select of measurement & field with grouping

I think that this will work for 80% of queries that users want to write, but I may be mistaken.

**Comment by russorat** [comment]
i also disagree that _measurements and _fields should be single select. I believe it's too hasty to disable this functionality so soon.

there is a valid flow where a user selects the bucket, then the field, then multiple measurements that have that field. this isn't the case for system metrics which don't make sense, but it's common for things like prometheus metrics and is an advantage over the current builder from the builder in v1.

I would much rather be smarter about displaying options to the user, as in only show fields that are valid for all measurement selections. Also, letting them know that the fields are limited because of their selection.

**Comment by desa** [comment]
@russorat The more I think about this issue, the more I think that there's an even larger issue here. Took me a second to realize what you were saying about prometheus metrics. The core issue is that with prometheus metrics, `_measurement` is similar to the concatenation of `_measurement` and `_field`.

**Comment by russorat** [comment]
i think i'd be more ok with changing the default behavior of multi select lists in the app as a whole so that it works more like other multi-selects i've used. so by default, select a single value, but hold down a key to select multiple, and hold shift to highlight all values between.  this would also address: https://github.com/influxdata/influxdb/issues/15290

**Comment by russorat** [comment]
bump
