### ISSUE TITLE
Scrollbar jumps to the top after a selection or input

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15633]
When i select a value, the list of options should not scroll back to the top.

![Kapture 2019-10-29 at 11 12 14](https://user-images.githubusercontent.com/4805997/67796319-15f77a00-fa3d-11e9-9b18-8402802633a7.gif)

**Comment by hoorayimhelping** [comment]
this one irritates me, i have a couple of ideas about how to fix it, cause it's not straightforward.

**Comment by russorat** [comment]
It also happens when configuring graph options. Any change scrolls the panel back to the top. Very annoying.

**Comment by russorat** [comment]
this is also happening on dashboards where you have to scroll.

**Comment by TCL735** [comment]
This is a clockface issue. DapperScrollbars does not have state to persist the position of the scrollbars, and therefore will always re-render with position 0 (or whatever prop is passed in). Ideally, DapperScrollbars should keep track of its own position (after the initial render) rather than rely on a prop.
