### ISSUE TITLE
Check status defaults to `ok` instead of `unknown`

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#15645]
A threshold check with a single threshold defined in the UI as:
```
{level: "CRIT", value: 80, type: "greater"}
```
creates a check which produces a task:
```
package main
import "influxdata/influxdb/monitor"
import "influxdata/influxdb/v1"

data = from(bucket: "data")
  |> range(start: -15s)
  |> filter(fn: (r) =>(r._measurement == "cpu"))
  |> filter(fn: (r) =>(r._field == "usage_user"))
  |> filter(fn: (r) =>(r.cpu == "cpu0"))
  |> aggregateWindow(every: 15s, fn: mean, createEmpty: false)

option task = {name: "Name this Check", every: 15s, offset: 0s}

check = {
  _check_id: "04b24ecaa80fd000",
  _check_name: "Name this Check",
  _type: "threshold",
  tags: {},
  }

crit = (r) =>(r.usage_user > 80.0)

messageFn = (r) => ("Check: ${ r._check_name } is: ${ r._level }")

data
|> v1.fieldsAsCols()
|> monitor.check(data: check, messageFn: messageFn, crit: crit)
```

should produce a status with level `crit` if value is greater than 80, 
and `unknown` if value is less than 80. 
Currently produces status with level `ok` if value is less than 80

![Screen Shot 2019-10-29 at 3 11 48 PM](https://user-images.githubusercontent.com/10937678/67813316-7cd95b00-fa5e-11e9-9f3a-a060a0f22e1e.png)

**Comment by nathanielc** [comment]
> Currently produces status with level ok if value is less than 80

I thought this was expected. Its an easy change to make but would require users to also specify the `ok` condition in order to get recovery messages.

**Comment by ebb-tide** [comment]
I would expect status to default to `unknown` and both `unknown` and `ok` to generate a recovery message.

**Comment by russorat** [comment]
if i set `CRIT > 80` and `OK < 40`, what level do i get for a value of 50?

**Comment by ebb-tide** [comment]
currently `ok`

**Comment by nathanielc** [comment]
> if i set CRIT > 80 and OK < 40, what level do i get for a value of 50?

You would get `unknown`, @ebb-tide if you get `ok` in that case then its definitely a bug (but a different bug).

If you set `CRIT > 80` but do not set an `OK` condition what level should you get for a 50?

If we say it should be an `unknown` then you would not get recoveries when the value drops below 80 and users would have to define both `CRIT > 80` and `OK <=80` in order to get recoveries.

If we say it should be `ok` then you would get recoveries when the value drops below 80 without requiring the user to explicitly state an `ok` condition.

If we say that `unknowns` trigger recoveries then `ok` and `unknown` are the exact same thing and there is no purpose in having both.

**Comment by nathanielc** [comment]
Adding a bit more to clarify:

There is a difference between setting and not setting the `ok` condition. If you do not set the `ok` condition then the default `ok` condition is `true`, meaning that any value that does not match a `crit`,`warn` or `info` condition is `ok`.

A user cannot set the `unknown` condition, the `unknown` level is used  if no other level's condition evaluates to `true`. 

So in the case of 

>if i set CRIT > 80 and OK < 40, what level do i get for a value of 50?

the `unknown` level is used since the `ok` condition evaluates to `false` as well as the `crit` condition.

**Comment by ebb-tide** [comment]
I'm so sorry! I tested this with the ok condition set wrong @nathanielc you are totally right
> if i set CRIT > 80 and OK < 40, what level do i get for a value of 50?
is `unknown`.

**Comment by ebb-tide** [comment]
This behavior is totally ok with me now that I understand it, sorry for the false alarm!
