### ISSUE TITLE
export existing resources via influx packages

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#15764]
As a user, I would like to clone desired resources, so I can enable reuse and source control around my newly created package.

initial POST /api/v2/packages should be extended to support the resource kind and the id of existing resource to clone:

request body: 

```
{
    "pkgName": PKG_NAME,
    "pkgDescription": PKG_DESCRIPTION,
    "pkgVersion": PKG_VERSION,
    "resources": [
        {
            "kind": RESOURCE_KIND,
            "id": RESOURCE_ID
        }
        ....
    ]
}
```

**Comment by ebb-tide** [comment]
Can you provide an idea of the shape of the response so that the monitoring team has an idea of what to expect before you start working on this? 
what would the response be for a POST request to `/api/v2/packages` with a dashboard and its id? 

```
{
    "pkgName": PKG_NAME,
    "pkgDescription": PKG_DESCRIPTION,
    "pkgVersion": PKG_VERSION,
    "resources": [
        {
            "kind": "dashboard",
            "id": dashboardID,
        }
        ....
    ]
}
```

**Comment by jsteenb2** [comment]
@ebb-tide it'd just be a package with stuff baked out based on resources provided.

**Comment by ebb-tide** [comment]
I'm really looking for a more precise answer than `stuff baked out`, and there is a reason that I am asking this question. I am wondering precisely what response I get when I request a dashboard with its id. Will the API (1) return a dashboard and cells/views only or will it (2) also return all associated resources such as variables in the queries? As the primary consumer of this API I need to know what you are planning re: whether the API or the consumer is responsible for discovering implicit associations between resources. Perhaps it would help to produce a swagger definition of the contract for request and response before you implement this work so that we can ensure we are all on the same page.

**Comment by jsteenb2** [comment]
@ebb-tide when you call the create pkg endpoint, you're going to get a pkg returned. Not sure what you are looking for. Its the same package you'd submit to the apply endpoints to create the resources.
