### ISSUE TITLE
Create build using Flux with Rust parser support

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#15768]
The Flux project has a new Rust parser that can be enabled using a Go build tag. We need to create a build of InfluxDB that uses the Flux with the Rust parser. This build should be enabled using a build tag. 

DOD

* Can run a single static binary of InfluxDB that uses the Rust Flux parser
* Go CI tests run against the Rust version of Flux parser
* We only need to support x86 platforms as part of this issue. A follow on issue will tackle the cross-compilation to other platforms/architectures.

**Comment by affo** [comment]
I am currently investigating on this and tried to understand what's happening there.

I know my conclusions are super straightforward for others, but I summarize what I understood down below.

As long as I understood, in Flux we have a function called `parseFile` that can be built conditionally using the `libflux` tag (go parser: https://github.com/influxdata/flux/blob/75a508b7c909f87cc1b85db5dc82d5eed60e553c/parser/go_parser.go#L11, rust parser: https://github.com/influxdata/flux/blob/75a508b7c909f87cc1b85db5dc82d5eed60e553c/parser/libflux_parser.go#L13)

This is perfect, because everything else that parses something in Flux depends on that. For example, compilers in `lang`: https://github.com/influxdata/flux/blob/780ffd77ed641d0005fbc704f56c4e329b33cbf3/lang/compiler.go#L100.

Ok, so if you `go build -tags libflux`, you get a working version of Flux that uses the Rust parser.

InfluxDB relies on `Compile` method of a compiler to compile, that uses `parseFile`,  so, the objective here is to make InfluxDB build its Flux dependency with tag tag enabled.

I tried to compile with that, but I got:

```
go build -tags "libflux" ./cmd/influxd/
# github.com/influxdata/flux/libflux/go/libflux
ld: library not found for -lflux
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

An error referring to this line (https://github.com/influxdata/flux/blob/75a508b7c909f87cc1b85db5dc82d5eed60e553c/libflux/go/libflux/parser.go#L6) I think.

So, now what? Am I taking the wrong direction? Should we compile `libflux` separately and link the binary dynamically on `go build`? I think I need further guidance on this.
