### ISSUE TITLE
Date weirdness in dashboard view

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15808]
Notice how the date strings overlap in the lower left cell
![Screenshot 2019-11-08 10 27 27](https://user-images.githubusercontent.com/1477539/68488392-edc50380-0212-11ea-8d02-d679152169a4.png)

When toggling between UTC and Local for their timezone, `undefined` shows up in dashboard view
<img width="399" alt="Screenshot 2019-11-08 at 13 09 59" src="https://user-images.githubusercontent.com/1477539/68488568-52805e00-0213-11ea-9d9f-140fc2a447f2.png">

**Comment by desa** [comment]
Grouped these issues together because they felt related. If they aren't, we can break them apart.

**Comment by desa** [comment]
cc @deanasheehan

**Comment by Asalem1** [comment]
@desa I can't seem to recreate the `undefined` issue pictured above. Do you happen to have any details on how to reproduce the bug / when the issue was reported? A similar issue appears to have taken place in one of `giraffe`'s dependencies:

https://github.com/zapier/intl-dateformat/issues/4

But that seems to have been resolved a couple of months ago when the dependency was upgraded to 0.1.1

**Comment by desa** [comment]
@Asalem1 it's very likely that we have an older version clockface in the cluster where this was discovered. I'll try updating the cluster to use the latest version the UI.

**Comment by desa** [comment]
@deanasheehan can you confirm whether you still see `undefined` in the frankfurt cluster when you toggle the timezone.

**Comment by Asalem1** [comment]
Apparently, the undefined error is reproducible by switching to a new language where the time is then formatted to 24h rather than AM/PM

**Comment by Asalem1** [comment]
Fixed the `undefined` error in this PR:

https://github.com/influxdata/giraffe/pull/116

Need to publish a new version
