### ISSUE TITLE
add last run status to checks/rules

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15838]
Similar to tasks, we should return
```
	LatestCompleted string                 `json:"latestCompleted,omitempty"`
	LatestScheduled time.Time              `json:"latestScheduled,omitempty"`
	LastRunStatus   string                 `json:"lastRunStatus,omitempty"`
	LastRunError    string                 `json:"lastRunError,omitempty"`
```

for checks and notification rules.

We should display something similar to the tasks UI.

![Screenshot 2019-11-11 11 38 44](https://user-images.githubusercontent.com/1477539/68604137-d470c100-0477-11ea-988a-71933b21508d.png)

This will involved modifying the checks and notifications UI and API. In the API, we'll need to grab those values from the task that backs the check/rule.

**Comment by desa** [comment]
Should also display error for tasks in the UI

**Comment by desa** [comment]
Link https://github.com/influxdata/influxdb/issues/15844

**Comment by Asalem1** [comment]
Currently blocked by changes made in the following PR:

https://github.com/influxdata/influxdb/pull/16333

It seems like the changes made to updateCheck weren’t updated here:

https://github.com/influxdata/influxdb/blob/master/ui/src/alerting/components/CheckCard.tsx#L17

Need some clarity from @ebb-tide on how to best go about update the component to accurately reflect the new functionality since the previous implementation seems to be a bit different on might require an overhaul of the way the check data is currently being updated
