### ISSUE TITLE
threshold value dragging is weird

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15832]
![weird-dragging](https://user-images.githubusercontent.com/1477539/68601871-3aa71500-0473-11ea-8dca-676a3c21413c.gif)

**Comment by TCL735** [comment]
I am 100% convinced this is an issue. Notice on the left hand side, the value of the threshold marker is changing as you drag. There is a sluggishness to the dragging, but that comes from having a huge range from the top of the marker to bottom. The range is traversed as you drag.

Perhaps there could be a visual improvement on the marker to make it more obvious that the dragging is having an effect on the threshold value. Something on the right hand side to let the user know the threshold value is changing.

**Comment by TCL735** [comment]
Dragging quickly with more force seems to speed up the range traversal.

**Comment by desa** [comment]
@TCL735 I think the thing that is jarring to me is that my cursor is so far away from the threshold marker as I drag. Ideally what would happen would be that we maintain the max value of the graph until after the threshold drag finishes. Does that help at all? Is there more definition I can add?

**Comment by TCL735** [comment]
After a deeper analysis, multiple issues exist with dragging in thresholds checks.

1. Dragging for range above ("greater") and range below ("lesser") do not set max and min values. The current value becomes the max or min, which leads to the marker being sluggish--it tries to stay at the edge of the rendered area, until the range is within the domain of possible values.

2. Dragging for min/max does not sync the values in the form. This is a bug, because dragging for range above/below syncs with the selected value from dragging.

**Comment by TCL735** [comment]
Proposed fix with single marker dragging:

![image](https://user-images.githubusercontent.com/10736577/69176027-c2b39d00-0ab9-11ea-85f3-53adae879c66.png)

**Comment by TCL735** [comment]
Single marker dragging with proposed fix:
![single_marker_dragging](https://user-images.githubusercontent.com/10736577/69176532-ba0f9680-0aba-11ea-9894-96f7d8153f08.gif)

**Comment by TCL735** [comment]
Double marker dragging with proposed solution:

![double_marker_dragging](https://user-images.githubusercontent.com/10736577/69178142-dc56e380-0abd-11ea-99ed-a25d119c27cf.gif)
