### ISSUE TITLE
Support additional time formats for table view

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15905]
![Screenshot 2019-11-14 09 27 15](https://user-images.githubusercontent.com/1477539/68865583-10e32d80-06c1-11ea-983b-36c22c30ba8a.png)

Ideally, we'd have some presets, but allow users to specify their own custom format if they'd like. Specifically it would be great to have `HH:mm`.

**Comment by desa** [comment]
cc @r1ckbrown

**Comment by desa** [comment]
Link https://github.com/influxdata/influxdb/issues/15906#issuecomment-560522183

**Comment by desa** [comment]
* `DD/MM/YYYY HH:mm:ss.sss`
* `HH:mm`
* `HH:mma`

**Comment by Asalem1** [comment]
In order to fully support the `a` (am/pm) configuration, we need to update Giraffe to handle these cases

**Comment by dewenni** [comment]
It seems that since this request was opened, the date and time formats were extended.
But it is still not possible to use custom formats.

At the moment every format includes the time information.
But I want to habe formats without time information.

for example:
31.01
31.01 - Monday
January
February
....

Is it planned to have the possibility to use custom formats using key words?
