### ISSUE TITLE
Gauge doesn't always fit container

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#15911]
![guage-scales-poorly](https://user-images.githubusercontent.com/1477539/68868135-f7dc7b80-06c4-11ea-85d6-455cd7300689.gif)

All numeric values on a gauge should always be visible.

**Comment by desa** [comment]
cc @r1ckbrown

**Comment by russorat** [comment]
@zoesteinkamp what's happening with this issue? has it stalled?

**Comment by desa** [comment]
@zoesteinkamp As a part of this work can we confirm behavior on mobile.

**Comment by r1ckbrown** [comment]
I was showing the visualisation to a colleague today, and my gauge still doesn't fit
<img width="219" alt="image" src="https://user-images.githubusercontent.com/27981402/84403646-d8c3af00-abfd-11ea-859b-0af8e0dee4c8.png">

**Comment by desa** [comment]
@TCL735 has a new gauge implementation in giraffe. Would be worthwhile to get that in as a part of this.

**Comment by TCL735** [comment]
PR for the new Gauge: https://github.com/influxdata/giraffe/pull/192

After that is published, influxdb will need to consume it and update its own code to use the additional view options. With the additional view options, a Gauge's value can be moved, so that it will not overlap with the rest of the rendering.
