### ISSUE TITLE
v.windowPeriod is not dynamically updated

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#16098]
If I issue a query for the last 5m worth of data the window period is `1500ms`
![Screenshot 2019-12-03 13 45 17](https://user-images.githubusercontent.com/1477539/70079656-27e7b200-15d3-11ea-9aa0-f7d173657dee.png)

When the time range is updated to be for the last 12h, the window period is not updated appropriately
![Screenshot 2019-12-03 13 46 50](https://user-images.githubusercontent.com/1477539/70079777-64b3a900-15d3-11ea-9914-7c0d6577d0c4.png)

**Comment by desa** [comment]
cc @stuartcarnie

**Comment by Asalem1** [comment]
@desa what should the windowPeriod be set / updated to? It looks like in both cases it's being set to `15000ms`. This seems to be the preset regardless of what the timerange selected will output

**Comment by Asalem1** [comment]
@drdelambre the issue here stems from the fact that the webpack compiler is no longer handling `wasm` files in the same way it used to based on these changes:

https://github.com/influxdata/influxdb/pull/16003/files#diff-543f361bc90ba449ebf911e739ec94cfL36

The solution we will try to implement is to separate the compiler logic so that `monaco` routes are handled by the new additions, and everything else should be handled by the original rule.
