### ISSUE TITLE
test: intermittent failure of `Dashboards can create a dashboard from a Template - can create a dashboard from a Template` cypress test

### ISSUE THREAD

**Issue by goller** [influxdata/influxdb#16129]
```
Dashboards can create a dashboard from a Template - can create a dashboard from a Template
CypressError: cy.click() can only be called on a single element. Your subject contained 2 elements. Pass { multiple: true } if you want to serially click each element.
```

![Dashboards -- can create a dashboard from a Template (failed)](https://user-images.githubusercontent.com/1922921/70187315-7e2c2200-16b3-11ea-89f0-86d0a987eef0.png)

CircleCI Link: https://circleci.com/gh/influxdata/influxdb/74064#tests/containers/0

**Comment by hoorayimhelping** [comment]
Found the issue. It's a race condition that you can see in this gif:

![race](https://user-images.githubusercontent.com/146112/70196990-432feb80-16bf-11ea-9279-20e905f3cab8.gif)

When things are going fast (ideally, as written in the test) the header is rendered a few miliseconds before the body, and the only `Create Dashboard` that exists is in the header. You can see in the gif above that the second `Create Dashboard` button gets rendered in the body right after the `Create Dashboard` button in the header gets clicked.

When things aren't going ideally, like when they fail, the body renders at around the same time as the header, or the test runner isn't fast enough to click the header before both are rendered, and it explodes.

The fix is to contextualize the [`getByTestID` call](https://github.com/influxdata/influxdb/blob/master/ui/cypress/e2e/dashboardsIndex.test.ts#L77) to be scoped to either the header or the body.

```ts
cy.getByTestID('overlay--header').getByTestID('add-resource-dropdown--button').click()

cy.getByTestID('overlay--body').getByTestID('add-resource-dropdown--button').click()
```
