### ISSUE TITLE
InfluxDB eats up all available memory in TSI mode

### ISSUE THREAD

**Issue by Kamforka** [influxdata/influxdb#16197]
I have high cardinality data stored in InfluxDB, which means that I have a lot of unique series, therefore I enabled time series indexing to store cold data on disk rather than in memory during queries.

However still if I try to do queries like:
```
SELECT COUNT(*) FROM my_rp.my_meas
```

or

```
SELECT * FROM my_rp.my_meas ORDER BY time ASC LIMIT 1
```

Influx just consumes all available system memory and crashes.
Is there anything else I can configure to make influx use as little memory as possible for its queries?

It's a crucial problem in my case, since even if I just want to run a continuous query to aggregate data for a single hour, influx consumes almost all available memory and then doesn't release it, so the next query is more than likely to crash.

* System info: Linux 4.4.0-169-generic x86_64
* InfluxDB version: InfluxDB v1.7.9 (git: 1.7 23bc63d43a8dc05f53afa46e3526ebb5578f3d88)
* Other relevant environment details:

__Config:__
  - INFLUXDB_DATA_MAX_VALUES_PER_TAG=0
  - INFLUXDB_DATA_MAX_SERIES_PER_DATABASE=0
  - INFLUXDB_DATA_INDEX_VERSION=tsi1

**Comment by russorat** [comment]
@Kamforka thanks for the issue. If your database is under that much load, i would recommend leveraging Kapacitor instead of continuous queries to perform that action. 

Also, those are expensive queries because they are not limited by time. add time bounds to your WHERE clause to see if that helps. 

Also, take a look at: https://docs.influxdata.com/influxdb/v1.7/concepts/time-series-index/ to understand how TSI works and also: https://docs.influxdata.com/influxdb/v1.7/concepts/storage_engine/ 

The other option is to increase the resources available to Influx (more CPU and RAM).

I'm going to close this since it doesn't sound like a bug. Check out our community Slack (https://influxdata.com/slack) and forums (https://community.influxdata.com) if you have more questions about query optimization.
