### ISSUE TITLE
[UI - Telegrafs] - Question - No sort by bucket control

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#16199]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Onboard to Influxdbv2
2. Open Load Data > Telegrafs

__Expected behavior:__
Describe what you expected to happen.

Expected to find a control "Buckets" sort. 

__Actual behavior:__
Describe What actually happened.

There is no "Buckets" sort control.

__Question__ 

Is this by design?  

__Screenshot__

![TelegrafsNoBucketSort01](https://user-images.githubusercontent.com/25881301/70609462-1e2d0280-1c02-11ea-8f26-b2e6d1203ee6.png)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.4.0-170-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Noticed in nightly builds docker image
```
ts=2019-12-11T08:47:23.514375Z lvl=info msg="Welcome to InfluxDB" log_id=0Je26NUW000 version=nightly commit=55ce0a0bf build_date=2019-12-11T07:27:45Z
```
* Other relevant environment details: Container runtime, disk info, etc

Browser: __Chrome 78__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.
Started with e2e testing enabled. 
```
--e2e-testing=true
```

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by drdelambre** [comment]
some context: this feature was removed as it was originally built with the incorrect assumption that every telegraf configuration reported to one and only one bucket. In reality, there are a lot of use cases involving reporting to multiple buckets, and there are some where a configuration doesn't report to a bucket at all.
instead of introducing new design language to the user in an attempt to navigate this discovery, it was removed.
I cannot speak the the further development, scope, or prioritization of adding back similar functionality, but the removal was intentional.

**Comment by corriganjohn** [comment]
Thank you Alex, that helps a lot --- I was trying to pull all the UI related tickets to see what could be cleared vs what needed some design work. While I'm sure we could address it if really needed, unless there is a high need to be able to sort configs by the (potentially) related Buckets I will just close this for now.
