### ISSUE TITLE
Wire up delete series

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#1647]
This is different than drop series. Drop series can take a set of tags, or an ID.

Delete series can additionally take a time range.

**Comment by otoolep** [comment]
@corylanou -- I think this is done, right?

**Comment by corylanou** [comment]
@otoolep No, `DROP SERIES` is complete, but not `DELETE SERIES`.  They difference, from what I understand, is that delete will remove data from a series, but not actually drop the meta data, even if the delete empties the entire series.  Delete can also remove a partial set of points from a series, where as drop always completely drops the series.

**Comment by pauldix** [comment]
That's right, with `DELETE` you can specify `WHERE` clause filters on either field values or the time range. So you can remove just part of a series.

**Comment by bobfeldbauer** [comment]
Any update on this? I'm on 0.9.2.1 and don't see delete functionality.

**Comment by beckettsean** [comment]
This is not currently scheduled for any particular release. I would estimate late this year for this particular functionality unless the community votes it up.

**Comment by cschneid** [comment]
To be clear, the docs about the query language (https://influxdb.com/docs/v0.9/query_language/spec.html) that list the `delete_stmt` and have an example: `DELETE FROM cpu WHERE region = 'uswest'` just isn't wired up, and doesn't work?

**Comment by beckettsean** [comment]
Thanks for the note, @cschneid. I made https://github.com/influxdb/influxdb.com/issues/191 to address the docs issue.

**Comment by diiidiii** [comment]
+1

**Comment by AlexeyDmitriev** [comment]
+1

**Comment by yujinqiu** [comment]
+1

**Comment by cnelissen** [comment]
+1

Need to be able to do stuff like:

DELETE FROM measurement WHERE tagKey = 'tagValue'
DELETE FROM measurement WHERE time < now() - 30d

**Comment by alexanderdavidsen** [comment]
+1

**Comment by Samuel1989** [comment]
+1

**Comment by comcomservices** [comment]
Deleting data points is essential for any database

Should be able to do 
DELETE FROM measurement WHERE time < now() - 30d
like we could in influxdb 0.7

**Comment by beckettsean** [comment]
@comcomservices for that use case perhaps [retention policies](https://influxdb.com/docs/v0.9/query_language/database_management.html#retention-policy-management) cover what you need.

**Comment by comcomservices** [comment]
@beckettsean We certainly use them but allot of times we need to remove bad data points from a data set as our clients or often OCD about these types of abnormalities, right now we add annotations to our graphs to explain these events but still deleting points like we had in 0.7 would be much better, right now we are working on a script to export everything, delete the series and then re-import only the data we want but feel that this is very far from ideal

Jon

<img width="957" alt="need_to_delete_bad_points" src="https://cloud.githubusercontent.com/assets/13089993/10704533/4a77de90-798c-11e5-844e-ee3a67bbb9b8.png">

**Comment by beckettsean** [comment]
Thanks for the details, @comcomservices. Another workaround is to overwrite bad points with an orthogonal field set. Since you're using Grafana I'll assume most of your points have a single field named `value`. If you find a bad point or series of bad points, you can overwrite them with a different field set that doesn't include `value`. 

Let's say this is the bad point: `my_measurement,tag=foo,anothertag=bar value=12 1234567890`. You could write this point to the database: `my_measurement,tag=foo,anothertag=bar ignore=True 1234567890` and it will silently overwrite the prior point. (The measurement, tag set, and timestamp are identical, and InfluxDB overwrites points, it does not store duplicates.)

Queries for `SELECT value...` or `SELECT MEAN(value)...` or `SELECT COUNT(value)...` will all ignore that point now, because it has no field named `value`. `SELECT *...` queries would still return the point, but since `*` cannot be used inside of functions, that shouldn't affect most graph-able queries.

**Comment by alexiri** [comment]
+1

**Comment by samhatchett** [comment]
+1 on this and also #4404 for reporting an error until this is implemented.

**Comment by discoduck2x** [comment]
+1

**Comment by cykl** [comment]
+1

**Comment by max3163** [comment]
+1

**Comment by codinl** [comment]
+1

**Comment by jordanbtucker** [comment]
> You could write this point to the database: `my_measurement,tag=foo,anothertag=bar ignore=True 1234567890` and it will silently overwrite the prior point.

@beckettsean Is this still true? I just tried this, but now my row has both the original field and its value and the new field and its value. (i.e. `value = 12` and `ignore = True`.)

**Comment by beckettsean** [comment]
@jordanbtucker with 0.10 it is no longer possible to overwrite the field set of a point. The database stores the union of the two field sets, with any duplicates taking the value from the most recently written point.

**Comment by skazi0** [comment]
I've just noticed that the "delete by overwrite" workaround doesn't work anymore after upgrade to 0.10.
Is there any other workaround available for removing bad datapoints until we have proper DELETE SERIES implementation?

**Comment by beckettsean** [comment]
@jordanbtucker @skazi0 

Overwriting a point was never a specific design goal with b1/bz1, just a handy side effect of the on-disk representation. Since it was a side effect it wasn't part of the test suite. The new TSM engine doesn't exhibit that same behavior, so the regression slipped right on by.

We are working to implement functionality that encompasses this and more, which is the [DELETE SERIES](https://github.com/influxdata/influxdb/issues/1647) functionality. DELETE SERIES with a narrow enough time range becomes effectively DELETE POINT.

**Comment by skazi0** [comment]
The fact that this behavior was not by design is clear to me.
Too bad there is no similar workaround for the TSM engine.
I guess we'll have to wait for the real feature then.

**Comment by max3163** [comment]
Any informations about the estimate time for the implementation of this must have functionality ?

**Comment by DavidEitzinger** [comment]
+1

**Comment by rvrignaud** [comment]
+1

**Comment by pmvilaca** [comment]
+1

**Comment by comcomservices** [comment]
What we finally have come to is keeping a copy of all the raw data before putting it into the database, when we get bad data we can delete the entire series and re-import the cleaned original data.

Sad but until a better workaround is available it's all we can do.

**Comment by pmvilaca** [comment]
@comcomservices you mean.. really write the points to a text file that you keep somewhere? you're not doing an export, changing the file and then reimport again?

**Comment by comcomservices** [comment]
@pmvilaca we used to do that but now we have a simple binary database that stores the raw binary floats and does memory caching to reduce hdd ops...   It's a backup to us as well as we have been plagued by corruption of our influx databases and this allows us a second degree of protection where exporting and reimporting would not

**Comment by sonneym** [comment]
+1
You can try doing it like cassandra, with tombstones to keep performance

**Comment by max3163** [comment]
Pls could you consider to work on it with high priority for 0.12 ??? 
Work on a database with no way to delete distinct series by time is rly difficult.

**Comment by pauldix** [comment]
@max3163 you can delete a series using the `DROP SERIES` command. This is to delete just some of the data within a series, but it is very high priority.

**Comment by max3163** [comment]
You provide a time series database, for me, the time clause is important in all queries.  I just hope you could consider to add this feature rly soon.

**Comment by sonneym** [comment]
is there an idea when this will be available? 
Sometimes you just have to delete.  I have a duplicate points in 0.10.1 and I can't get to the second one since the timestamps are the same, I really need the delete series functionaility and not: backup series, delete measurement and then copy back the valid series only

**Comment by mantzas** [comment]
+1

**Comment by nemesisdesign** [comment]
Great!
