### ISSUE TITLE
Transpiler: Implement function "top"

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#16487]

**Comment by jsternberg** [comment]
This is a good example of something we should be able to do since it doesn't involve joining anything.

https://github.com/influxdata/influxdb/blob/master/query/influxql/testdata/SelectorMath_3.influxql

This one involves selecting top based on multiple tags. The syntax here says to find the top 3 where `t0` and `t1` are the same, but will group them all into the same table afterwards.

https://github.com/influxdata/influxdb/blob/master/query/influxql/testdata/SelectorMath_5.influxql

There is another syntax that involves selecting fields outside of top (like `top(f0, 3), f1`). We can skip those for now. Focus on the `top()` usages where it has tags as arguments to the functions.
