### ISSUE TITLE
Spike on CGO Cross Compilation

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#16516]
See https://github.com/influxdata/flux/issues/2245#issuecomment-572788499 for details on how we think this can work.

We need to answer the question of how we can cross compile using CGO. Once we understand that, this issue is complete.

DOD

* Can cross compile a Go program with a CGO dependency

**Comment by jsternberg** [comment]
I created a simple project using cgo. It is composed of the following files:

```go
// file: say.go
package main

// #include "say.h"
// void free(void *);
import "C"

import (
	"os"
	"unsafe"
)

func say(s string) {
	cstr := C.CString(s)
	defer C.free(unsafe.Pointer(cstr))
	C.say(cstr)
}

func main() {
	for _, arg := range os.Args[1:] {
		say(arg)
	}
}
```

```c
// file: say.c
#include "say.h"
#include <stdio.h>

void say(const char *s) {
	puts(s);
}

```

```c
// file: say.h
#ifndef _SAY_H
#define _SAY_H

void say(const char *);

#endif
```

I then also added this file:

```
#!/bin/bash
# file: env

export GOOS=linux
export GOARCH=amd64
export CGO_ENABLED=1
export CC=$PWD/cc-linux-amd64.bash
export CC_FOR_linux_amd64=$PWD/cc-linux-amd64.bash
exec "$@"
```

```
#!/bin/bash
# file: cc-linux-amd64.bash

exec clang --target=x86_64-linux "$@"
```

Those two would be used as the bootstrap.

The good news is I am able to run `./env go tool cgo say.go` and it generates an elf file which means it is cross-compiling. The bad news is that the minute I start to use a header file I get a problem. For the cgo header, I had to remove `stdlib.h` to get cgo to generate anything.

I tried removing all header files, but cgo itself generates code that uses `stdlib.h`. This is a problem because clang doesn't seem to have those headers by default.

**Comment by jsternberg** [comment]
To be clear, this is cgo that has a dependency on `stdlib.h`. It's unlikely we can do anything about that.

```
jsternberg:[~/g/s/g/j/say] $ ./env go build
# runtime/cgo
_cgo_export.c:3:10: fatal error: 'stdlib.h' file not found
```

**Comment by jsternberg** [comment]
@rockstar has figured out how to perform cross compilation manually and is able to do it. He will be working on integrating that work into our `pkg-config` utility in the future so that we can use it as part of the cgo cross compilation and goreleaser. I'm going to close this issue.

That work is being discussed and done here: https://github.com/influxdata/flux/issues/2245#issuecomment-586344936
