### ISSUE TITLE
CORS issue since 2.0 OSS Alpha 21

### ISSUE THREAD

**Issue by ravz** [influxdata/influxdb#16546]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ...
2. ...
3. ...

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by Asalem1** [comment]
Hi @ravz, sorry that you're receiving CORS issues in 2.0 OSS Alpha 21. Do you happen to have any additional information on the error you're receiving (network logs returning an error), or steps on how to reproduce this error? I'd love to try and get this cleared up ASAP

**Comment by ravz** [comment]
here is the errors we receive now, Alpha 20 worked

> Access to XMLHttpRequest at 'https://influx.takatechnology.com/api/v2/query?org=Taka%20Technology' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> client.js:655 Uncaught (in promise) Error: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

**Comment by Asalem1** [comment]
@ravz thanks for providing that information. I'll take a look now and see if we can get this all cleared up soon.

**Comment by Asalem1** [comment]
@ravz thanks again for posting about this issue. I've tried to reproduce this on the most current branch by doing the following:

- Opening the Data Explorer and:
  - Creating a new query using the query builder
  - Creating a new query using the script editor
  - Updating a query using the query builder
  - Updating a query using the script editor
- Creating a Dashboard
  - Opening the newly created Dashboard
  - Updating the cells created in the dashboard
  - Deleting cells in the dashboard
  - Creating new cells in the dashboard
- Create a new Check
  - Created a new check using the query builder
  - Updated an existing check using the query builder

Since I have been unable to reproduce this issue, I'm going to go ahead and mark it as resolved/unreproducible. If you are still seeing this issue and have any further instructions on how to reproduce it in a way that I have not mentioned above, please let me know and I'll be happy to reopen the issue and take a look at it again.

Thanks
