### ISSUE TITLE
Add support for 2.0 write API to 1.x

### ISSUE THREAD

**Issue by dgnorton** [influxdata/influxdb#16898]
__Proposal:__

Make 1.x support the 2.0 write API.

This will allow users currently running 1.x to incrementally transition existing clients to the 2.0 write API. It will also allow new projects to be developed against the new API. This will smooth the upgrade path to 2.0.

__1.x Write API:__

https://docs.influxdata.com/influxdb/v1.7/tools/api/#write-http-endpoint

__2.0 Write API:__

https://v2.docs.influxdata.com/v2.0/write-data/#influxdb-api

__Proposed Changes:__

Add a  `/v2/write` endpoint to handle the v2.0 write protocol.  This involves mapping the `org` and `bucket`  parameters to `db` (database) and `rp` (retention policy). The implementation is [here](https://github.com/influxdata/influxdb/blob/1.8/services/httpd/handler.go#L775). Auth should "just work" since `Authorization: Token` support has already been added for Flux.

Both APIs support the same [line protocol](https://v2.docs.influxdata.com/v2.0/reference/syntax/line-protocol/) format for the raw time series data. The APIs differ only in the `/write` endpoints' request headers and URL parameters. Proposed mappings:

<table>
    <tr><th colspan="3">URL Parameters</th></tr>
    <tr>
        <th>2.0</th>
        <th>1.x</th>
        <th>Notes</th>
    </tr>
    <tr>
        <td>org</td>
        <td>n/a</td>
        <td>currently the org is ignored.  at some point we might try to encode which orgs are valid</td>
    <tr/>
    <tr>
        <td>bucket</td>
        <td>db/rp</td>
        <td>buckets will be encoded to include the database name and retention policy separated by a forward slash</td>
    </tr>
    <tr>
        <td>precision</td>
        <td>precision</td>
        <td>same in both APIs</td>
    </tr>
</table>

<table>
    <tr><th colspan="3">HTTP Headers</th></tr>
    <tr>
        <th>2.0</th>
        <th>1.x</th>
        <th>Notes</th>
    </tr>
    <tr>
        <td>Authorization: Token</td>
        <td>Authorization: Token</td>
        <td>Appears support for this was added as part of Flux support in 1.x. Clients send `username:password` as the Token.</td>
    <tr/>
</table>

Since the database and retention policies are encoded in the bucket, an empty retention policy should map to the default retention policy.

The following encodings should work:

`database/weekly` - maps to a database named "database" and retention policy named "weekly"
`database/` - maps to a database named "database and the default retention policy
`database` - likewise maps to a database named "database" and the default retention policy.

__Testing:__

Test that both the [2.0 Go client](https://github.com/influxdata/influxdb-client-go) and 1.x InfluxDB CLI can write data.

**Comment by dgnorton** [comment]
@timhallinflux can you review the proposed changes above? Ayan has PR ready but want to make sure this is correct before merging. Thanks

**Comment by pauldix** [comment]
So this work needs to dovetail with the work we're doing to add InfluxQL support to Cloud2. Given that it will always query a bucket with the translation `db` and `rp` in the query to a bucket named `<db>/<rp>` we should mirror that here.

So basically the `org` in the request should be ignored. And the bucket name should be parsed so that it resolves to a `db` and an `rp`. And if those don't exist it should return a 404. That way when the user sets up the v2 client libraries, they'll be writing into a bucket with that name. So when they upgrade later, it will be a smooth transition.

That make sense? @stuartcarnie, can you confirm my thinking on this?

**Comment by stuartcarnie** [comment]
@pauldix yes, they are related, but from different contexts and therefore different requirements.

## InfluxDB 1.x

What you are proposing is how we map a 2.x write request to a 1.x data store. This is the same as how we map the `from(bucket: "<db>/<rp>")` for a Flux query, which is to split the `bucket` string by `/` to extract `db` and `rp`. This behavior can be seen here for Flux in 1.x:

https://github.com/influxdata/influxdb/blob/40a7a577fc12870e7d520ec6ebd5177cf6edced3/flux/stdlib/influxdata/influxdb/operators.go#L89-L120

If `rp` is missing from the `from` expression, we use the existing logic to look up the default retention policy.

So if we have the following

| db   | rp      | default |
| ---- | ------- | ------- |
| foo  | autogen | ✓       |
| foo  | monthly |         |


**Writes via 2.0 API**

The behavior is obvious for writes with a bucket specified with the `<db>/<rp>` format. Verify there is a matching database and retention policy and proceed.

**WRITE with no retention policy**

Select the default retention policy using the existing rules, which in the above case is `autogen`.


## InfluxDB 2.x

Adding InfluxQL to Cloud 2.0 has to do the _reverse_, which requires additional metadata to provide the mappings as above. These mappings a required in order to find the `default` retention policy and map that back to a bucket, when it is excluded from an InfluxQL query. This is provided by the [`DBRPMappingService`](https://github.com/influxdata/idpe/blob/8ae98867b3669cc6ddf127a9fcc73e584b548d16/vendor/github.com/influxdata/influxdb/dbrp_mapping.go#L10-L36) I mentioned previously, which is already used by the transpiler.

**Comment by pauldix** [comment]
The overall goal here is that people adopting InfluxDB 1.x who want to use the 2.x client libraries will be able to do so, while giving them the smoothest possible onramp to upgrade to 2.x InfluxDB in the future. For those upgrading, they'll likely have significant numbers of Grafana dashboards that are using InfluxQL, so they'll need to be able to point those to the 2.0 InfluxQL endpoint and ideally have it just work. Ideally they wouldn't have to update their clients writing data in so they'd just have it now pointing at a 2.0 instance.

That is a good point to think about though with respect to them using Flux in InfluxDB 1.8 to query their data.

**Comment by stuartcarnie** [comment]
@pauldix that is my understanding too 👍 

A primary driver for that smooth transition to pointing Grafana to a 2.x InfluxDB is this additional metadata via the `DBRPMappingService`. We can expect user's are going to have many InfluxQL queries that don't specify a retention policy, so we will need to know which bucket to use.

**Comment by dgnorton** [comment]
Closed by https://github.com/influxdata/influxdb/pull/16908
