### ISSUE TITLE
Apply default aggregateWindow in data explorer

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#17076]
Currently, we do not set a default aggregateWindow for queries built using the query builder. This frequently results in query responses that are > 10MB. This causes a poor user experience.

WHEN I build a query with the query builder
THEN the `mean` aggregate is automatically selected

**Comment by desa** [comment]
cc @ssoroka

**Comment by mnorriswalker** [comment]
@desa - This came up in some user research and I spoke with @pauldix about it and tried to represent the desired point-of-view here.

GIVEN the user is in the Data Explorer working with data-filled Bucket
WHEN the user queries too much data that it will return a size related error
THEN the query is automatically downsampled
AND there's a persistent [NotificationDialog](https://influxdata.github.io/clockface/?path=/story/atomic-notification--notificationdialog) message that says "You're original query was too big. It was downsampled for better viewing."
AND there's an [Undo] button

WHEN I hit [Undo]
THEN the query is re-run without downsampling

**Comment by pauldix** [comment]
I would say that ideally it never submits the query that pulls back too much data. Ideally it would modify the query to apply downsampling automatically. That way the query engine/storage engine can provide an answer quickly and everything in the UI feels snappy.

**Comment by barbaranelson** [comment]
How would we know that a query is likely to return a large result set (without executing the query) or are you suggesting that we always downsample by default, even for small queries?

**Comment by pauldix** [comment]
I think downsampling by default, but it could be based on time range. If we assume a sampling interval of 10s then we can extrapolate when to downsample based on the number of horizontal pixels they have available. 1h = 360 raw samples, 2h = 720. So if you have anywhere from 500 - 700 pixels, you could probably query without downsampling for anything showing less than 2h of data. But if you go larger, add downsampling. So for 8h you'd aggregate by 1m buckets of time or for 72h you'd aggregate by 10m buckets of time.

Now the question is what happens if their sampling interval is something greater like 1m? I think if you pick a selector instead like `first` or `last` in those time intervals without filling missing intervals, you'll just get the raw samples, until it gets to the point where if filters them out.

It would be interesting to give them an option in the prompt that tells them it was downsampled. You can have the time window and the function used be dropdowns. So the user could then easily specify a different period or different summary function.

If I'm looking only at a single series, I find it useful to show min, max, mean when downsampling over larger periods of time.

**Comment by ssoroka** [comment]
Automatic downsampling based on pixels available sounds perfect, and what I would expect as a user.

**Comment by mnorriswalker** [comment]
@desa @russorat @alexpaxton here's the latest iteration of this Issue

User Problem:
The user can create queries that return too much data that can’t be displayed and crashes the UI

Solution: 
Auto downsample queries to return results that can be contained by the number of display pixels.

# Design Notes

**Prototype**
https://www.figma.com/proto/naxHHmkcY0Tc6pfbgzdq9T/Auto-Downsampling?node-id=77%3A3&viewport=-49%2C352%2C0.5&scaling=min-zoom

**Working file (has CSS)**
https://www.figma.com/file/naxHHmkcY0Tc6pfbgzdq9T/Auto-Downsampling?node-id=77%3A3

**Comment by russorat** [comment]
other tools limit the points per series to ~350. The number of series is sometimes limited as well, at least while exploring.

IMO, an aggregate can always be applied though. if there are fewer points or a single point in the aggregate, it would be the same as full fidelity.

The UI is blind though, so we might have to rethink the experience if there's no way for the UI to know if the data is full fidelity or not.

**Comment by TCL735** [comment]
This will break Single Stat, as currently Single Stat cannot render with Aggregate Functions applied.

**Comment by desa** [comment]
> This will break Single Stat, as currently Single Stat cannot render with Aggregate Functions applied.

How?

**Comment by mnorriswalker** [comment]
Refactor Aggregate Function Panel to have two modes Auto and Custom

_Given: I'm in the Data Explorer_

**Mode 1: Auto**
When: the `Auto` mode is enabled (via the AutoInput - https://influxdata.github.io/clockface/?path=/story/components-inputs-composed--autoinput)
Then: `MEAN` is selected by default
Or a user could select `MEDIAN`

**Mode 2: Custom**
When: the `Custom` mode is enabled
Then: I can select any of the aggregate functions
But: One must be selected at all times (like a radio button)

Design:
https://www.figma.com/file/naxHHmkcY0Tc6pfbgzdq9T/Auto-Aggregation?node-id=250%3A110

**Comment by barbaranelson** [comment]
In custom mode, I think we should default to one of the aggregate functions, but I think there should be an option to not aggregate.  Otherwise, once a user has looked at their data and realizes that it would fit without being aggregated they have no way to turn off the aggregation, without going into the script editor.

**Comment by elysianmichael** [comment]
Could this be changed to a setting that could be turned off? I've lost countless hours when testing because I don't realize that default aggregation is on and I think my data/times are writing incorrectly.

**Comment by barbaranelson** [comment]
It can be.  You can go into 'custom' and uncheck the aggregate method selected.

**Comment by elysianmichael** [comment]
That doesn't save though. Every time I go back into the data explorer it defaults back to auto mean aggregation.
