### ISSUE TITLE
Provide API for extactings option used Flux scripts, including type of the `v` in dashboard scripts

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#17430]
The platform allows for users to define _variables_ which are then accessible in any Flux script via the `v` option. 

For example I can define a variable `bucket` that is backed by a query to get buckets and when writing a dashboard query I can reference that variable like so:

```
from(bucket:v.bucket) 
   |> range(...)
   |> filter(...)
```

The `v` option is defined externally by the UI when the query is submitted. 

In order to export a dashboard with all of its dependency we need to know which _variables_ a given Flux script references otherwise we do not know which _variables_ to include in the export.

This can be done using Flux's type system, we can infer the type of `v` and then determine which _variables_ (i.e. fields) of `v` were accessed. This gives us an exact and robust method for determine which _variables_ are referenced from within a Flux script.

The API for such a function would be something like:

```

// Find all the referenced variables on the `v` option in the Flux script.
func FindVariableReferences(script string) []Variable
```

The implementation details are open but the general way I expect we would approach this is define the option `v` as a type variable with a constraint that it is a record and then let type inference determine what fields are required on `v`. Then we can map those fields back to _variables_ defined in the platform.

**Comment by nathanielc** [comment]
After some further investigation we have learned that the UI (i.e. browser) will also need access to a similar API endpoint. The UI wants to know which variables are being referenced in a given query so it can prompt the user to provide the value for those variables. 

As such we need to determine a design that allows us to expose this API to both Go code and the node module. Naturally the implementation will live in Rust, which is fine since all of the logic we need already lives on the Rust side. 

The questions then revolve around where and how to expose this to both systems:

* Does it make sense as part of the libflux API or is it too specific? 
* Should we create an `influxdb` specific wrapper around the `flux` node module that contains this InfluxData specific logic? Or should it all live in the `flux` node module for simplicity?
* Should we make the API a bit more generic so that its more generally applicable? Instead of specific to the needs of the `v` option.
* How do we encode type information? Currently the serialization of type information has remained a private detail of the API, this would expose it to some degree depending on how we decide to design the API.

**Comment by wolffcm** [comment]
> Should we make the API a bit more generic so that its more generally applicable? Instead of specific to the needs of the v option.

I wonder if we should center this new API around the use of options?  Since they are a special part of Flux where we can allow clients to learn about them before execution, and we provide a way for clients to set them.  The action of the new API could be _build a map of all the options used in the Flux script file, and their types_.

> How do we encode type information? Currently the serialization of type information has remained a private detail of the API, this would expose it to some degree depending on how we decide to design the API.

Would it be crazy to return something like a FlatBuffers representation of `map[[2]string]MonoType`, where the map is keyed on `[package,option_name]`?  Note that there is FlatBuffers target for JavaScript, which could allow use in the browser.

Otherwise we would need some other serialization of the option types, which can be arbitrarily complex.

**Comment by nathanielc** [comment]
NOTE: The scope for this issues does NOT include exposing the new API to the UI via WASM or the network. We will have a separate issue to determine a design for how to expose these types of API to the UI.

**Comment by rickspencer3** [comment]
AIUI:

1. We need to be able to extract options from any Flux script so that Template authors can sensibly parameterize Tasks
2. We need to be able to extract options for a Task so that we can store the options without running the script
3. The ui needs to be able to extract Platform Variables used in Dashboard scripts (Platform Variables just being a special case of options)

Further, I believe that the UI team would like to extract the Platform Variables/Options via the wasm, though I am not certain why they need to extract Platform Variables from scripts at all.

**Comment by yzhang1991** [comment]
We decide to build the following libflux API
```
// given a flux AST, and the name of the variable to look for, we return a flatbuffer containing the type of
// the designated variable.
struct flux_error_t *flux_find_var_type(struct flux_ast_pkg_t *, const char* vname, struct flux_buffer_t *)
```

**Comment by nathanielc** [comment]
I want to add some more depth to the above updates.

>    We need to be able to extract options from any Flux script so that Template authors can sensibly parameterize Tasks

Correct, this issue will cover that use case https://github.com/influxdata/influxdb/issues/17386

>    We need to be able to extract options for a Task so that we can store the options without running the script

Correct, this issue will also cover that use case https://github.com/influxdata/influxdb/issues/17386

>    The ui needs to be able to extract Platform Variables used in Dashboard scripts (Platform Variables just being a special case of options)

Correct, this current issue solves that problem, hence why it is being proposed as part of the libflux API (i.e. something we can expose via WASM)


Finally there is one more piece missing but the UI will also like to be able to interact with options, for that see https://github.com/influxdata/influxdb/issues/18834


@yzhang1991 This means that part of the DOD for this issue is to expose the flux_find_var_type function via the NodeJS WASM module we publish.
