### ISSUE TITLE
Checks, error="cannot add type constraint @ monitor.flux

### ISSUE THREAD

**Issue by StefanSa** [influxdata/influxdb#17461]
Hi there,
i get the following error message with this check message template `${r._field}`:

`lvl=info msg="Error exhausting result iterator" log_id=0Lo3wvEG000 service=t
ask-executor error="cannot add type constraint @ monitor.flux|121:20-123:11: type error 0:0-0:0: missing object properties (_field)" name=experim
ental-to15`

The same with `${string(v: r._value)}`

Version: `2.0.0 (ad38ed1)`

**Comment by russorat** [comment]
@StefanSa thanks! the data in the monitor is actually pivoted, so it's very likely that you would want to use the `_field` value instead of `r._value`.

for example, if my data looks like this:

| _value | _field | 
|-------|-------------|
| 1 | used_percent|

Then i would use `${string(v:r.used_percent)}` in my status.

**Comment by StefanSa** [comment]
@russorat 
you are right, this is how it works.
thx for your fast help here.
