### ISSUE TITLE
Sorting data by date in Script Editor with Flux

### ISSUE THREAD

**Issue by lxms** [influxdata/influxdb#17487]
__Steps to reproduce:__

1. Open "Data Explorer"
2. Activate "Script Editor"
3. Sort data with Flux by date field ( `|> sort(columns: ["_time"], desc: false)` )

__Expected behavior:__
Data rows sorted by date

__Actual behavior:__
No real sorting (see picture)
Parameter "desc" (true/false) has no effect.

__Environment info:__
Version 2.0.0 (a3ff52d) beta 7
<img width="1419" alt="screen" src="https://user-images.githubusercontent.com/1151552/77901105-56268700-727f-11ea-90a5-9906e53658a1.png">

**Comment by lxms** [comment]
Update: it works when  i add group function. Aswell "desc" param.
`|> group(columns: ["xyz"], mode:"by") `

**Comment by sanderson** [comment]
@lxms In your screenshot, each point is in a separate table (see the table ID in the `table` column). The `sort()` function only sorts rows in individual tables, which is why it sorts correctly after you use `group` to group everything into one table. Flux doesn’t guarantee the order of tables in a stream, only the order of rows in tables.

There has been some discussion about enforcing table order in Flux, but it hasn’t been implemented yet.

**Comment by lxms** [comment]
@sanderson Thank you for your answer. That makes  it obvious.

One final question, since i oversaw that information possibly. 
We write all points the same way over the `influxdata/influxdb-client-java`. Why are they organized in different tables? Do you have an explanation or link to a documentation.  Thanks in advance.

**Comment by sanderson** [comment]
By default, Flux groups data into series. A series is defined by a measurement, a tag set, and a field key, so tables will always share the same measurement, tag keys and values, and field key. I'd have to see your actual schema to know, but I'd guess that your tag values vary point to point so they're being treated as separate series.

**Comment by lxms** [comment]
@sanderson I was already thinking about that. That's the reason. Thanks for clarifying.

**Comment by sanderson** [comment]
@lxms No problem. Happy to help!
