### ISSUE TITLE
HTTP endpoint is publicly accessible without authentication with the default configuration

### ISSUE THREAD

**Issue by Gowee** [influxdata/influxdb#17639]
__Steps to reproduce:__
1. Install InfluxDB 1.7.10 with a package manager (e.g. pacman) or [the release tarball](https://github.com/influxdata/influxdb/archive/v1.7.10.tar.gz).
2. Run/Enable InfluxDB service without changing the default config located at `etc/config.sample.toml`.

__Expected behavior:__
All services (TCP/UDP sockets) are listened locally as `127.0.0.1:PORT` or `[::1]:PORT` or all of them are protected by some authentication mechanics.

__Actual behavior:__
The HTTP endpoint listened at `[::]:8086` are publicly accessible, without any authentication enforced. 

__Environment info:__

* System info: `Linux 5.5.4-arch1-1 x86_64`
* InfluxDB version: `InfluxDB v1.7.10 (git: master unknown)`
* Other relevant environment details: N/A

__Config:__
Not modified.

__Logs:__
Irrelevant

__Performance:__
Irrelevant

__Additional notes__:
This is not actually a bug. But it seems to me that the default config encourages insecure deployment. 

Sh*d** shows that there are more than 20k InfluxDB instances publicly reachable on the Internet.
I test against the first 100, to find that 63 of them do not require authentication to `show databases` (HTTP 200 OK).

**Comment by glinton** [comment]
Similar to how a popular video conferencing application is currently under fire and deemed "insecure", it is up to each user to implement the best security practices. We have provided [documentation](https://docs.influxdata.com/influxdb/v1.7/administration/security/) for the 1.X line to configure InfluxDB securely. However, the original goal of "fastest time to awesome" (aka ease-of-use)<sup>1</sup> was recognized as being too easy to misuse from a security standpoint. Because trusting users to properly configure software doesn't always fare well, InfluxDB 2.0 was designed to be [more] secure by [default](https://v2.docs.influxdata.com/v2.0/get-started/#set-up-influxdb)<sup>2</sup>.

It seems to me, your best course of action would be to properly file security issues with the owners of each of those 100 instances; of which I'm sure you got permission from to initiate your vulnerability scan.

1: At the time of initial launch it was a relatively common practice to trust user's would run software properly for their environment (I recall a popular key/value store's similar defaults).
2: It is always best practice to verify security and configuration prior to deploying software that is internet facing.
