### ISSUE TITLE
Build Linux Static binaries for InfluxDB 2.0

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17675]
similar to the ones we have for 1.x, we will need a `influxdb-2.0.0-static_linux_amd64.tar.gz` binary

**Comment by rawkode** [comment]
I just mounted the binaries we do [provide](https://v2.docs.influxdata.com/v2.0/get-started/#start-with-influxdb-oss) for Linux into an empty container and they run just fine.

While they don't have `static` in their name, I believe these are static binaries.

Closing this for now. Please reopen if I've made a mistake, @russorat

**Comment by russorat** [comment]
reopening based on https://github.com/influxdata/influxdb/issues/18627

**Comment by jsternberg** [comment]
The build system already has support for this so it should just be updating the build command and installing musl. The release happens in a docker container so that needs to be updated.

1. Add the rust musl target when installing the cross compilation tools https://github.com/influxdata/influxdb/blob/3eac7ec1545cb39b83fd621913065f84d0258c87/.circleci/config.yml#L43 (`rustup target add x86_64-unknown-linux-musl`)
2. Switch the go build command to use the special one for static linking inside of goreleaser: https://github.com/influxdata/influxdb/blob/3eac7ec1545cb39b83fd621913065f84d0258c87/.goreleaser.yml#L17

The proper build command needs the following additions to these sections:

```
ldflags: -extldflags "-fno-PIC -static -Wl,-z,stack-size=8388608"
flags:
    - -tags 'osusergo netgo static_build'
```

We might also need `-buildmode=pie` but I'm not sure. We seem to use that for static building internally but I don't know if it's required.

**Comment by jsternberg** [comment]
Also the stack size may need to be not set for arm but I'm not sure. We use that to tell musl to restore the default stack size to 8MB instead of the default that musl has of 128k.
