### ISSUE TITLE
Grafana plugin for InfluxDB 2.0

### ISSUE THREAD

**Issue by lafrech** [influxdata/influxdb#17703]
Same request as https://github.com/grafana/grafana/issues/17561.

__Proposal:__

It would be nice to have a Grafana plugin with the same features as the plugin for InfluxDB 1, with the query assistant GUI.

__Alternatives considered:__

There is a Grafana [Influx DB Flux datasource](https://grafana.com/grafana/plugins/grafana-influxdb-flux-datasource) plugin that provides a Flux interface. It is compatible with Influx 1 (recent releases with Flux enabled) and Influx 2. But it requires the user to write Flux queries.

__Use case:__

Our engineers work on systems that output csv files. As a computer guy, I can write (Python) code to store that data into Influx and then all they need to do is connect to Grafana and query using the GUI. They don't need to learn any language.

This has been a great improvement in our workflow (thanks for this already !). Thanks to this, the engineers have gained autonomy. They don't need to either struggle with tons of .csv files using excel or call the computer guy every other day for a new aggregation script.

I've been trying Influx 2 and it looks promising. I like the huge rework that has been done there to unify everything into Flux. I'd like to work with Influx 2 beta and I'd be happy to help improve it as a beta user but I'm stuck on Influx 1 for the Grafana query editor.

Is there anything planned?

Is there a change in Influx 2 that makes it impossible to realize?

**Comment by rbetts** [comment]
Grafana support on the SaaS version of InfluxDBv2 (InfluxDB Cloud) works internally and will be supported shortly for external users. In that case, we are using an internal `influxqld` service behind-the-scenes for backwards compatibility.

We don't yet have this level of backwards-compatibility support for the OSS 2.0 beta, however. As you mention, there is a grafana flux data source and we continue to coordinate with Grafana Labs on these integrations.

We'll be talking and blogging about these integrations in the near future and providing some demos in our community slack forum of the influxdb cloud integration once it's ready to be announced.

**Comment by lafrech** [comment]
InfluxDB 2.0 is now out. Congratulations.

We're still stuck on InfluxDB 1.x because the Grafana plugin with the request GUI is the killer feature on which our workflow relies, as described above.

Are there any plans to implement an equivalent feature in the Flux Grafana plugin? We use Influx 1.8 with Flux enabled and I'd be happy to provide feedback if there's anything to test.

**Comment by andyl** [comment]
Releasing Flux datasource in Grafana without a query builder is a giant step backwards.  I really regret upgrading to InfluxDB 2.0.

**Comment by timhallinflux** [comment]
@lafrech  -- 
InfluxDB OSS 2.0 and InfluxDB Cloud now both support InfluxQL.  This was added to support compatibility with InfluxDB 1.x.  For folks who are using Grafana, everything should work so long as you are on Grafana 7.0.2 or greater.  Meaning, the Grafana Labs team worked to overhaul the InfluxDB Data Source connector to allow it to work with InfluxDB v1.x and v2.x and allow you to choose the language you want to work with.  Either InfluxQL and/or Flux.  Meaning, you can also create 2 data source connections to the same instance -- one for InfluxQL and one for Flux. 

There is an upgrade process for OSS users that is documented here: https://docs.influxdata.com/influxdb/v2.0/upgrade/v1-to-v2/
While there are a number of steps, the two most important steps for ensuring compatibility are:
1) Buckets and Database and Retention Policy Mappings (DBRP)
Because 2.x uses the concept of Buckets (where retention policies are now an attribute of the Bucket), a mapping is created to allow for 1.x InfluxQL queries to "map" to the 2.x bucket names.  If you run the upgrade script....these mappings will be created automatically (along with the buckets themselves).  If you want to set this up manually -- you can, of course, but it's obviously manual and the instructions to do this.  The overview of this topic is here: https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/dbrp/ 
and instructions for creating these mappings manually are here (either using the new CLI or API):
https://docs.influxdata.com/influxdb/v2.0/query-data/influxql/#map-unmapped-buckets

2) v1 Authentication
InfluxDB v2.x requires authentication by default.  Tokens can be created which are used when contacting the various APIs or when setting up integration with third-party components like Grafana.  However, to maintain compatibility, there is a way to create InfluxDB 1.x username/password authentication credentials.  The upgrade script does this automatically for `ALL non-admin users` and preserves the existing passwords.  However, if you were running InfluxDB v1.x without authentication turned on OR you were leveraging a username/password combination that had `admin` permissions, we recommend the following prior to upgrading:
a) turn on authentication in InfluxDB 1.x
b) create a user with read-only permissions 
c) modify the Grafana datasource connection with InfluxDB v1.x to leverage is username/password combination and validate that everything is working correctly. 

Then by running the upgrade script, those Grafana dashboards and the datasource connection should all continue to work post-upgrade.

Again, you can also do all of this manually, if you wish.  The CLI tooling is the easiest way to do this -- assuming you remember the password(s)! https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/v1/auth/

In terms of enhancing the Grafana Flux-building query experience, you can continue to follow the progress of that issue with the Grafana team shown above.  We have also let them know of these requests.  But, their UX is up to them to enrich and enhance.

**Comment by timhallinflux** [comment]
@andyl   That is disappointing to hear.  InfluxDB 2.x does come with a native UI and that does include a Flux query builder.  The intention of that experience was to help with two things -- 1) initial selection of the basis data elements that make-up a Flux query (to reduce the amount of boilerplate Flux one writes and 2) to ease the transition from InfluxQL to Flux.

Yes, you can create fully functioning Flux queries using the builder and for some folks that may be enough to build dashboards.  But, for more sophisticated use cases, Flux has a substantial amount of power and capability that isn't exposed (and unlikely to be exposed) through the query builder.  So, the script editor is where we expect most folks will land over time.

Having said that, and your use case may be different, we have a number of folks who are building dashboards on behalf of others.  Meaning, they leverage Grafana and supply dashboards which are connected to InfluxDB along with dashboards connected to other datasources.  In these cases, we hear that our users are building the dashboards using the query builder (and then script editor) within the native InfluxDB v2.x UI and after validating that they have the queries correct, they render properly, etc. simply cut and paste them over to a Grafana dashboard.

However, if you are looking to provide a fully ad hoc dashboard building experience for all your users, I can understand that having a query builder (which at least mimics what we have natively in InfluxDB v2.x) is desirable.  Again, we will pass along your feedback to the team at Grafana Labs.   

If there is something more we can do... we are happy to take that feedback and see what we can do to address it.

**Comment by andyl** [comment]
Tim thanks for your reply.  Over the next couple weeks I'll give it another try with the V1 auth approach you described to @lafrech.  If that works then I'm good.   

> If there is something more we can do ...

As an outsider, the Influx Data organization looks overstretched.  The V2 docs are large and difficult to absorb, the V2 software has bugs, the upgrade experience is not good.  Maybe it would be better for Influx to narrow it's scope - meat-and-potatoes focus on usability, developer onboarding, training and documentation.

I'm a big influx fan - respect your work very much & hope to be a user for many years to come.  Thanks again for the notes you posted here.  :-)

**Comment by lafrech** [comment]
Thanks @timhallinflux for this reply. And thanks to the team for the work done.

I expected Grafana plugin to adapt to Flux rather than InfluxQL being reintroduced in Influx DB v2. I hope this won't be a burden for InfluxDB v2. I totally understand the need for a major release with breaking changes and from what I've seen, the merge of both languages into Flux seemed like a good choice. If InfluxQL is finally here to stay, then it makes sense to continue to rely on it in Grafana plugin and other clients.

Is there an EOL planned for InfluxDB 1.x? A quick search yielded [a one-year old message](https://community.influxdata.com/t/tick-1-x-and-influxdb2-life-cycle/8293) saying "indefinite support".

I also asked on Grafana side (https://github.com/grafana/grafana/issues/17561) for Flux support, but for some reason I thought the developers of the Grafana plugin were from the Influx team, which is why I also asked here.

**Comment by lafrech** [comment]
With InfluxQL being reintroduced in InfluxDB 2, graphical query-building can be achieved with legacy InfluxQL support in Grafana so there is no real incentive to work on a GUI supporting Flux query building.

Therefore, this could be closed.

Unless there are plans to deprecate/remove InfluxQL from InfluxDB at some point?

**Comment by hoegge** [comment]
> 

No, this should not be closed. 

1. If you want people to learn Flux it should be build
2. There is a big overhead in creating v.1 databases for every buckets you want to use with Grafana - so at the moment there is no good solution for running v2 with Grafana
3. ... and finally you won't have the new features in flux, if you continue to use influxQL and the team does not implement the same things in influxQL

**Comment by n3k232** [comment]
Hi Guys, how long do you plan on supporting InfluxQL were relying on this to use the 1.x Querybuilder in Grafana, the Problem is, that it's not only my team which is Using the Querybuilder and i can't expect other teams to learn flux to manage their dashboards in Grafana. so were still stuck on influxdb 1.X

**Comment by hoegge** [comment]
influxQL should really be kept and actively be developed and improved as a first class citizen if you want to keep the entry barrier to using influxDB low. For programmers, this might be hard to understand and if you have the time to invest in learning flux - it is probably nice. But most database users are not programmers and the familiarity with SQL a major reason for keeping influxDB. Other companies like Couchbase move from the "programmers way" of interacting with database to a SQL like experience called N1QL, that I am sure will be a good foundation for future success.

**Comment by timhallinflux** [comment]
InfluxQL is and will continue to be supported.  It is supported via the v1 READ API across all editions of InfluxDB, including InfluxDB v1.x OSS, v2.x OSS, InfluxDB Enterprise and Cloud. The v2 READ API supports Flux.  This is available as part of InfluxDB OSS v2.x, Enterprise and Cloud.

@n3k232 -- you shouldn't be "stuck" as InfluxQL is supported.  From a Grafana perspective, you simply configure which language you wish to use and both InfluxQL and Flux are present.  So, assuming you are using InfluxDB v1.x OSS, you can upgrade to v2.x and try it out.  There are lots of instructions and details here to review: https://docs.influxdata.com/influxdb/v2.1/upgrade/v1-to-v2/

This issue is actually a request for Grafana to build something more than a text editor for Flux https://github.com/grafana/grafana/issues/17561 .  

So, @hoegge this is going to be closed, because having such a graphical builder is really up to the Grafana team to build. I would recommend continuing to follow-up on that Grafana issue to request a better builder experience.  We can do so as well.  However, Grafana are responsible for their own roadmap and development.  We are certainly eager to see the experience improve.  

In terms of overhead, there is no overhead...if you continue to use the v1 WRITE API, it will automatically create the bucket for you.  Further, we cannot implement everything in InfluxQL that we've implemented in Flux.  InfluxQL exists as that easy on ramp to InfluxDB.  If you have simple query demands, InfluxQL has that SQL-like syntax.  If it meets your needs, please continue to use it. 

Flux was built to address more challenging use cases and demands.  It will allow you to start simply and achieve significantly more sophisticated use cases as well.

**Comment by ypramos1986** [comment]
Any update on having available the Grafana plugin with the GUI similar to the one for InfluxQL?
Thanks
