### ISSUE TITLE
Rewrite rule to push down window through group (group/window/agg optimization)

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#17895]
From #17893 
> Alternatively we could make a ReadAggregateWindow call for all the windows and regroup and reapply the aggregate on the Flux side. This would require understand how to safely re-aggregate if possible. This seems more complex and not as likely to faster. Therefore this issue is solely focused on the planner rule to push down multiple ReadGroup calls.

This issues is about exploring the possibility of also adding a planner rule that would chose this method of pushdown + grouping. Its not clear if this method would ever be faster than the multiple ReadGroup calls method.

We should explore the space and see if we can find the conditions where it makes sense to push down ReadAggregateWindow and re-group on Flux side. 

DOD:

* We understand when it makes sense to use this alternative approach
* We understand what data we need to make that decision

Once we know the conditions and the data we need to make the planner decision  we can create a cost based plan rule.

**Comment by adrian-thurston** [comment]
I think this is only possible if the new group key is a subset of the original group key. If you're grouping _value then you can't regroup on the flux side?

**Comment by adrian-thurston** [comment]
Ah my above point is not relevant ... just noticed this in `PushDownGroupRule`.
```
// Storage can only group by tag keys.
```

**Comment by wolffcm** [comment]
Seems like this could be a straightforward rewrite of the plan:
```
from |> range |> filter
|> group(columns: ["cpu"]) |> window(every: 1m) |> count()
```
which could become
```
from |> range |> filter 
|> window(every: 1m) |> count() |> group(columns: ["cpu"]) |> sum()
```
And then existing rules for optimizing `from |> range |> filter 
|> window(every: 1m) |> count()` would all be allowed to work.

**Comment by wolffcm** [comment]
The work of this issue: create a rewrite rule
```
count
window
ReadGroup
--->
sum
group
ReadAggregateWindow
```

This works with the pattern that we'll commonly see with calls to `aggregateWindow`
```
from |> range |> filter
  |> group(columns: [...])
  |> aggregateWindow(fn: count, every: 1m)
```
Where the `group` appears before the windowing occurs.

DOD:
- Unit tests of 100% of rule logic

**Comment by jsternberg** [comment]
Very informal test on the OSS version.

```
from(bucket: "windowAggregateTest")
    |> range(start: 2020-06-01T00:00:00Z, stop: 2020-06-08T00:00:00Z)
    |> window(every: 1h)
    |> count()
    |> group(columns: ["_start", "_stop"])
    |> sum()
    |> duplicate(column: "_stop", as: "_time")
    |> window(every: inf)
```

With the aggregate count push down, you get about 921 milliseconds on my machine. Without the feature flag for this enabled, you get 8 seconds. If I modify the above to change `window` to include create empty, I get 15 seconds without the push down and 1.61 seconds with the push down.

This is better than I thought I would get. I thought that the group would potentially be too expensive with create empty and duplicate and `window(every: inf)` are pretty expensive right now. Those two are likely easy enough to fix but I am happy that it seems these already perform decently well even without optimizations.

Based on this preliminary test, I think that the specific optimization @wolffcm outlines is the lowest cost way to get some good performance out of this so I'm going to start working on the planner rule.

**Comment by jsternberg** [comment]
I tried this with a higher cardinality because the default generated dataset was pretty low. The default dataset was cardinality of `[10, 10, 10]` and I changed it to `[100, 20, 10, 5]`. The final query performed pretty slowly. I didn't let it finish but it was going to take probably over 2 minutes. I am trying to experiment to see where the hiccup might be. When I tried to do it with `window() |> count()` alone it performed quickly but then became lost in csv serialization for a long time so I am attempting to remove that portion for my tests.

**Comment by jsternberg** [comment]
For whatever reason, the query is now running in about 8-9 seconds. I must have forgotten to enable the feature flag on my test above.

I got an interesting result on a profile when I was running this with just the base aggregate window.

[cpu.svg.zip](https://github.com/influxdata/influxdb/files/4782462/cpu.svg.zip)

It seems from the flamegraph a majority of the time is spent in goroutine and channel maintenance and I'm curious how much of that might be the consecutive transports because of the large number of tables that are getting processed. It's interesting to see and indicates a potential future problem, but the current results are promising compared to the existing speed. I ran the query with the original:

```
from(bucket: "windowAggregateTest")
    |> range(start: 2020-06-01T00:00:00Z, stop: 2020-06-08T00:00:00Z)
    |> group()
    |> aggregateWindow(every: 1d, createEmpty: false, fn: count)
```

This completed in 30 seconds compared to the 8-9 seconds above.
