### ISSUE TITLE
Dashboard list takes a long time to load with a large number of dashboard

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#17931]
![dashboard-take-long-time.gif](https://images.zenhubusercontent.com/5d07f2d52ee3440ccd748a4e/cd0efd55-a0e6-416d-8d94-38845236a840)

**Comment by drdelambre** [comment]
seems like pagination got removed with normalization: https://github.com/influxdata/influxdb/pull/16535

**Comment by drdelambre** [comment]
scratch that. this never worked on an API level, just on a rendering level, and it seems like that's because the API level wasn't the bottleneck. There are some issues with over rendering and some lifecycle methods being messed up, but fixing those had negligible impact on rendering performance. Biggest improvement to performance has come by removing the `InlineLabels` component from the `DashboardCard` component. Still don't know what that means...

**Comment by drdelambre** [comment]
this change effectively disables the pagination: https://github.com/influxdata/influxdb/pull/17399

**Comment by drdelambre** [comment]
@alexpaxton why do dashboards get 3x faster when i remove this component?
https://github.com/influxdata/influxdb/blob/master/ui/src/dashboards/components/dashboard_index/DashboardCard.tsx#L84

**Comment by drdelambre** [comment]
fixed with #18142
