### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#18234]
# Background
As a user, I want to be able to browse and create new resources from templates, as well as see what templates I've used in the past

# Acceptance Criteria
* [x] I can click a link to view the list of community templates in influxdb github repo
  * Open the link in a new tab/window
* [x] I can choose a template to upload a resource
  * [x] Can use URL field

**Comment by rickspencer3** [comment]
Is there not a significant amount of effort and design implied by:

> I can see my list of my currently installed templates

Does this not imply that there is a source of truth for what templates are implied? This opens a host of questions about how to maintain consistency between that source of truth and changes that the user may make. For example, what happens if a user deletes all of the resources associated with the template?

I think templates are not objects that can managed in this manner, but are rather one way injectors which some ability to not overwrite previously injected objects.

**Comment by jsteenb2** [comment]
@rickspencer3 we have a source of truth for installed templates already. This endpint exists as well. Teh templates are associated with stacks by default. Teh stack can be multiple templates/packages, but it is a record of those applications.
