### ISSUE TITLE
Wire up MODE aggregate

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#1823]

**Comment by jacekgrzybowski** [comment]
Can we expect that in 0.9.2?

**Comment by pauldix** [comment]
This won't make it into 0.9.2. Maybe 0.9.3, but it's not particularly high priority right now.

**Comment by mareklipka** [comment]
What are the current plans about it?

**Comment by corylanou** [comment]
The query engine is undergoing heavy refactoring.  Removing help wanted label for now.

**Comment by jacek213** [comment]
any news on MODE aggregate? It would really make my life easier, now how to to perform 3 queries instead of it and process a lot of data in my use scenario.

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by agaurav** [comment]
@beckettsean Can we expect this anytime soon? It's a must have aggregator when sampling out metrics like response code, alert codes, ips, uuids etc. I am willing to submit a PR in case no one is working on it.

**Comment by beckettsean** [comment]
@agaurav no one is working on this for the 1.0 release, which will go into feature freeze soon. If you could submit a PR I believe it would make it into the 1.1 release.

**Comment by pauldix** [comment]
@agaurav if you submit a PR along with test code before August 8th then I think we'll be able to merge it for 1.0. A new aggregate function isn't a very high risk thing so we should be able to pull it in.

**Comment by agaurav** [comment]
@pauldix Great, I will submit a PR by Saturday then.

**Comment by agaurav** [comment]
@pauldix Please have a look at the above PR and let me know anything else is needed.
It is currently implemented as an aggregator rather than as a selectors. I will correct this once I am able to understand how to send the mode frequency as auxiliary value which I guess will be enough to implement the histogram function requested in https://github.com/influxdata/influxdb/issues/3674.

**Comment by opavader** [comment]
@pauldix @beckettsean please merge https://github.com/influxdata/influxdb/pull/7111 for version 1. I really need the mode aggregator.

**Comment by agaurav** [comment]
This is extremely disappointing. PR for the above is pending for more than 20 days and now rc1 is out. People have been waiting for this function from the version 0.9 & some are stuck on 0.8 because of this. What's the point of using a tsdb if it cant even have the very core sampling methods.

**Comment by pauldix** [comment]
Sorry guys, we'll take a look at this today. Just talked to the team and it seems pretty low risk and is well tested so we'll try to get it cherry picked over to the 1.0 branch. Guess an RC2 will be getting cut at some point.
