### ISSUE TITLE
Regression: Startup times for influx && influxd have increased by ~3 secs each

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#18292]
The startup times for both influx and influxd have dramatically increased since the merge of [algo-w](https://github.com/influxdata/influxdb/pull/18216)

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. checkout and build from algo-w merge branch: `git checkout d22380dc8b && make build`
2. time it: `time influx -h` or `time influxd -h`
3. checkout preceeding commit: `git checkout 97dc4d18db && make build`
4. time it: `time influx -h` or `time influxd -h`

__Expected behavior:__
Expected startup time for influx and influxd to not increase.

__Actual behavior:__
Roughly a 3s bump on both

**Comment by rickspencer3** [comment]
I assume that this is a total 6 second delay in start up? 

Even 3 seconds is annoying, and we should fix this. However, for now, I think we need to keep the Flux team 100% focused on releasing the performance improvements that are already in the pipeline.

**Comment by jsteenb2** [comment]
this issue is to catch the regression, it has become very slow. I trust you all to do the prioritization 👍. 

I would like to see some tests added to verify these startup times don't regress and are not caught until someone notices it in their CLI. The flux deps have been the driver behind the slow startup times, would be nice to keep this in our field of vision moving forward.

**Comment by mark-rushakoff** [comment]
Last time this happened, it was unnecessary Flux compilation at startup. See https://github.com/influxdata/influxdb/issues/15441 and https://github.com/influxdata/influxdb/pull/15777. Maybe there's something similar at play this time.

**Comment by jsteenb2** [comment]
@mark-rushakoff I believe that's right. The regression happens at the merger of algo-w

**Comment by jsternberg** [comment]
This seems to be due to a refactor that is loosely connected with the algorithm w refactor. Previously, the bulk of the work for initialization came from finalizing the builtins. When we refactored it, a lot of the work for initialization is now in `RegisterPackage` instead since we perform semantic analysis there instead of delaying it to finalizing the builtins.

There's probably two different ways to handle this. One would be to stop doing initialization of the runtime using `func init()` so that we aren't dependent on imports for the initialization order. Another might be to refactor the runtime registration so it goes back to saving the ast and delaying the semantic analysis to finalizing the builtins.

**Comment by adrian-thurston** [comment]
Possibly init() is the wrong place to do this work. The init() function could be used to log that the flux package exists, but later on the initialization work can happen before any flux code is evaluated.

**Comment by wolffcm** [comment]
Possible solution to this issue:

- Modify the `builtins` tool so that it finds stdlib packages that have a function named `StdlibInit()`, and generates a function `InitFlux()` in `packages.go` that will 1) call all those functions and 2) perform the finalizing steps for having a workable Flux runtime
- Refactor `flux repl`, `influx` and `influxd` to call `InitFlux()`


Source code for builtins tool, relevant code:
https://github.com/influxdata/flux/blob/master/internal/cmd/builtin/cmd/generate.go#L156

**Comment by wolffcm** [comment]
We think there's a simple fix, timeboxing to one day, if it takes longer, we'll need to put it into next sprint.

**Comment by jsternberg** [comment]
The fix for this is in flux v0.70.0 which was included in https://github.com/influxdata/influxdb/pull/18783.
