### ISSUE TITLE
rpm post install script can't be run during kickstart/pxe install

### ISSUE THREAD

**Issue by lfarkas** [influxdata/influxdb#18436]
all of the influxdb, telegraf, kapacitor has the same post install scripts and all of them fail during pxe/kickstart install.

unfortunately the spec file for building rpm are not public even though the whole source and open source. it'd be very useful if you can add the rpm's spec files to the source since in this case anyone can test it, debug it and fix it.

currently on a running RHEL/Fedora system if you install influxdb...rpm it's working properly, but unfortunately if it's installed during a kickstart/pxe install part of the operation system it's not working. unfortunately i'm not able to identify the bug itself (until someone share the spec file with me).

imho the bug somewhere the sjell incompatibility. since the postinstall script run by /bin/sh while it's first line show :
```#!/bin/bash```

and when it's try to determine which distro it's running:
```
if [[ -f /etc/redhat-release ]]; then
    # RHEL-variant logic
    if command -v systemctl &>/dev/null; then
        install_systemd
    else
        # Assuming sysv
        install_init
        install_chkconfig
    fi
```

it seems that even on a rhel/centos-7 system it's call install_init instead of install_systemd.

if someone share the spec file with me i can test/debug it and send the fix for it.

**Comment by russorat** [comment]
thanks @lfarkas!

I checked internally and we are using FPM to build them, which doesn’t involve spec files. Maybe @mark-rushakoff can explain in a little more detail.

**Comment by mark-rushakoff** [comment]
It's been a very long time since I've touched FPM for this kind of thing, but you can take a look at https://github.com/influxdata/influxdb/tree/master-1.x/releng/packages, and in particular https://github.com/influxdata/influxdb/blob/master-1.x/releng/packages/fs/usr/local/bin/influxdb_packages.bash, for how we compose the packages with FPM.

Fixes would be especially welcome if you could update the test for the packages too: https://github.com/influxdata/influxdb/blob/master-1.x/releng/packages/spec/clean_install/run.bash

**Comment by jordansissel** [comment]
Hi! I maintain fpm. Is this still an issue for y'all? Maybe we can work together to figure out how to make it work.
