### ISSUE TITLE
Flux queries should survive a browser refresh

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#18536]
when editing a flux query in the UI, when i refresh the page, i expect the flux query to still be there. right now, it is lost.

**Comment by 121watts** [comment]
Saving Data Explorer (DE) state to localStorage is straight forward enough.  However, what is not clear is what we should do when someone links to the Data Explorer from a bucket on the bucket's index page.  Currently, we link to the Data Explorer and choose their bucket for them with a reset query builder. 

Since DE state is wiped out every page refresh this was not a big deal.  However, now that we are attempting to persist this state it brings up the question: "How do we want to handle linking to the DE when a query already exists?".  We could

1) Do what we do now, blow away DE state and select the bucket (with a warning when they click the bucket from the index)
2) Keep query state and open a new query tab with that bucket selected
3) Stop linking from the bucket index
4) A better idea than any of the above...

**Comment by russorat** [comment]
On further review of this issue, we've decided to not do this change. there are a few reasons for this:

1. Queries in the Data Explorer are meant to be ephemeral and are for ad hoc exploration of data. Adding this capability seems trivial, but it introduces an expectation that the queries in DE will stick around, making any experience where they don't stick around that much more frustrating.
2. There are experiences where we link to the data explorer and overwrite the information that is there. Solving those cases and keeping the user's query would add significant work to this issue.

When you are working on a query and would like to save progress while you visit other parts of the app, we recommend you save them to dashboard cells. If you start a query in the DE and need to save it, you can use the Save As capability to save it to a dashboard.
