### ISSUE TITLE
forward slash `/` in board name causes influxdb to crash.

### ISSUE THREAD

**Issue by teranos** [influxdata/influxdb#18859]
__Steps to reproduce:__

1. Create a board
2. Change the name of board into something which contains: `/`
3. Inlfuxdb is no longer accessible.

__Expected behavior:__
Change of name should throw an error in the UI.

__Actual behavior:__
Influxdb crashed

**Comment by drdelambre** [comment]
this one might be less severe, needs to be triaged as a routing or resource bug first

**Comment by Asalem1** [comment]
@teranos do you happen to have any additional information about this? I can't seem to reproduce this locally or on production. Are you encountering this issue on OSS? Is there any additional console data that's output? What's the error you're seeing? Is there specific data in your dashboard?

**Comment by teranos** [comment]
Experiencing this issue on OSS.

**Comment by Asalem1** [comment]
@teranos is it still relevant? I'm unable to reproduce this. What's the error that's being produced? Do you happen to have a screenshot of the error? Any console or network errors that might indicate specifically what the issue is? What was the name of the dashboard you were trying to name but could not?

**Comment by teranos** [comment]
I do not seem to have this issue anymore since updating to the newest version. tested the forward slash just now.
