### ISSUE TITLE
Restoring backup causes: restore: unexpected EOF

### ISSUE THREAD

**Issue by 12pita3naru** [influxdata/influxdb#19034]
I'm using influxdb 1.8 on Docker 18.09 and I'm testing backup and restore a certain database called "import", it looks like the files that generated it's 1KB or 2B and I think it's to small for a database more that 2000 entries.

__Steps to reproduce:__
This the steps I used to create a container, backup and to restore the database

1. __Create a docker container:__
1.1. docker run --detach --restart always --name influxdb --publish 8886:8086 --volume C:\Docker\Volumes\var\lib\influxdb:/var/lib/influxdb -volume C:\Docker\backups:/backups influxdb:latest

2. __Import the database from a txt file:__
2.1. influx -import -path=import.txt -precision=ns

3. __Create backup from "import" database:__
3.1. docker exec -it influxdb influxd backup -database import  backups

4. __Delete the database__

5. __Stop the container__
5.1. docker stop influxdb

6. __Create a container that restore the database__
6.1.  docker run --rm --entrypoint /bin/bash -v C:\Docker\Volumes\var\lib\influxdb:/var/lib/influxdb -v C:\Docker\backups:/backups influxdb:latest -c "influxd restore -metadir /var/lib/influxdb/meta -datadir /var/lib/influxdb/data -database import /backups"

__Expected behavior:__
Should be expected that the database was restore

__Actual behavior:__

Using metastore snapshot: /backups/import.backup/meta.00
2020/07/23 11:51:18 Restoring offline from backup /backups/import.*
restore: unexpected EOF

**Comment by lesam** [comment]
@12pita3naru - we're doing an in-depth look at backup and restore. Are you able to provide:

* the `import.txt` file
* any/all server-side logs

So we can try to duplicate?

Also:
* I see a C: drive, was this on windows? Are you using Docker Desktop or a different docker VM/runner?
* What is the filesystem type of `C:\Docker\Volumes\var\lib\influxdb` ? It is probably NTFS, you can check with e.g. https://www.howtogeek.com/681125/how-to-see-a-drives-file-system-on-windows-10/

**Comment by davidby-influx** [comment]
<pre>sudo docker run --detach --restart always --name influxdb --publish 8886:8086 --volume /home/davidby/var/lib/influxdb:/var/lib/influxdb --volume /home/davidby/tmp/backups:/backups influxdb:1.8
</pre>
<pre>&gt; sudo docker exec -it ca49a9819bba sh
# influx
Connected to http://localhost:8086 version 1.8.10
InfluxDB shell version: 1.8.10
&gt; show databases
name: databases
name
----
_internal
&gt; CREATE DATABASE testy
&gt; use testy
Using database testy
&gt; INSERT m,t1=&quot;foo&quot; v=2
&gt; select * from m
name: m
time                t1    v
----                --    -
1638404443009299832 &quot;foo&quot; 2
&gt; INSERT m,t1=&quot;bar&quot; v=3
&gt; INSERT m,t1=&quot;baz&quot; v=4
&gt; exit
# influxd backup -database testy backups
2021/12/02 00:22:06 backing up metastore to backups/meta.00
2021/12/02 00:22:06 backing up db=testy
2021/12/02 00:22:06 backing up db=testy rp=autogen shard=2 to backups/testy.autogen.00002.00 since 0001-01-01T00:00:00Z
2021/12/02 00:22:06 backup complete:
2021/12/02 00:22:06 	backups/backups/meta.00
2021/12/02 00:22:06 	backups/backups/testy.autogen.00002.00
# influx
Connected to http://localhost:8086 version 1.8.10
InfluxDB shell version: 1.8.10
&gt; drop database testy
&gt; exit
# exit
</pre>


<pre>&gt; sudo docker run --rm --entrypoint /bin/sh --volume /home/davidby/var/lib/influxdb:/var/lib/influxdb --volume /home/davidby/tmp/backups:/backups influxdb:1.8 -c &quot;influxd restore -metadir /var/lib/influxdb/meta -datadir /var/lib/influxdb/data -database testy /backups&quot;
[sudo] password for davidby: 
Using metastore snapshot: /backups/meta.00
2021/12/02 22:58:57 Restoring offline from backup /backups/testy.*
</pre>

**Comment by davidby-influx** [comment]
Closing. Unable to replicate, no response from the user.
