### ISSUE TITLE
Concurrent sorting

### ISSUE THREAD

**Issue by jfcg** [influxdata/influxdb#19069]
__Proposal:__
Replacing standard library's sort with a concurrent sorting library like [sorty](https://github.com/jfcg/sorty).
Note: I am the author of sorty.

__Current behavior:__
standard sort is not concurrent and runs in a single goroutine. This is very slow.
Also `sort.Interface` is slower than sorty's `lesswap()` as a way to access generic collections.

__Desired behavior:__
As a time series database, InfluxDB can benefit a lot from concurrent sorting (with sorty or one of alternative libraries.)

__Alternatives considered:__
See the benchmarks in sorty readme.

__Use case:__
I have inspected InfluxDB code: standard sort is heavily used. sorty can cover all of it except calls to Stable().

**Comment by russorat** [comment]
@jfcg thanks for the issue and the library! We discussed this internally and we already do concurrent sorting in the places where it is most critical. Thanks!

**Comment by jfcg** [comment]
Hi Ross,
Just out of curiosity, I would like to examine how InfluxDB does concurrent sorting so that I can grab an idea or two. [This query](https://github.com/influxdata/influxdb/search?l=Go&type=Code&q=sort) did not yield any result that looks like it (I checked them all). Am I looking at the wrong files, or using a wrong keyword?
Thanks a lot..

**Comment by e-dard** [comment]
Hey @jfcg thanks so much for the suggestion for your library (which looks very interesting by the way!).

InfluxDB is ran by ourselves on thousands of nodes as part of our Cloud and Enterprise products, and we continuously profile all nodes, archiving profiles for later review. Typically Go's `sort` does not appear in CPU profiles for ours and our users' usecases. 

Historically sorting did become a problem in one place, which is the in-memory cache (which is very similar to a `memtable` if you're familiar with LSM-like databases). What used to happen was for very high cardinality use-cases the number of keys in the cache would be a problem when we needed to snapshot the cache to a TSM file (which is very similar to an `SSTable`). Each TSM file has an index that contains all the keys in that file, and they must be sorted. For very high cardinality cases we sort Go's `sort` dominating there (for millions of keys).

To address this we shard the cache using heuristics based on cardinality at runtime. So instead of creating one TSM file we create, e.g., four concurrently using shards of the cache keyspace (which basically means we're doing a concurrent sort there). This solved the problem and we don't see sort much at all in many profiles.

Here is a link to the code: https://github.com/influxdata/influxdb/blob/master/tsdb/tsm1/compact.go#L840-L860

I appreciate that there may be some further performance gains to be had using your library but in general we do not find sorting to be a performance bottleneck for us.

Hope that helps!

**Comment by jfcg** [comment]
Thanks for the detailed explanation Edd.
