### ISSUE TITLE
V2.0: Listing all organizations only returns first 20 results

### ISSUE THREAD

**Issue by antongocode** [influxdata/influxdb#19319]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create more than 20 organizations
2. Use either `/api/v2/orgs` or `influx org list` to retrieve list of organisations

__Expected behavior:__
I'd expect more than 20 entries or some pagination mechanism.

__Actual behavior:__
List is limited to 20 entries. Missing organizations can be access if id/name is known.

__Environment info:__

* InfluxDB version: InfluxDB 2.0.0-beta.15 (git: f54848f443) build_date: 2020-07-23T18:27:19Z

**Comment by KevinSmile** [comment]
https://github.com/influxdata/influxdb/blob/8b51618a21b756e2b4bcc03e6b0aa97d8fc4e1ef/tenant/storage_org.go#L111-L117

https://github.com/influxdata/influxdb/blob/8b51618a21b756e2b4bcc03e6b0aa97d8fc4e1ef/paging.go#L10-L13

The reason is `DefaultPageSize = 20`.

I think it's confusing, maybe we could show some more messages here?

**Comment by antongocode** [comment]
I assumed it was something along those lines, but as far as I can see this API doesn't expose a way to set that and neither does the CLI tool (could be wrong). In contrast, the buckets API lets you set offset and limit for "List All Buckets" and this is extended to the client libraries.

**Comment by antongocode** [comment]
By the way this also affects the UI, which only displays 20 organizations when switching organizations.

**Comment by KevinSmile** [comment]
Yes! It's an API design issue.
 I'm trying to fix it.

@antongocode
