### ISSUE TITLE
Provide -lponly option for influx_inspect export & generate only line protocol

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/influxdb#19367]
This would allow for for line protocol exports to more easily move between 1.x and 2.x.  

Currently, the user needs to crack the export and remove the DML lines.

**Comment by dgnorton** [comment]
@timhallinflux should this be `-noddl`? DDL creates the database. DML is the data/line-proto.

**Comment by timhallinflux** [comment]
yes... remove all lines that are not LP.  2.0 doesn't accept the various non-LP stuff at the top.

**Comment by ayang64** [comment]
oh -- so it is the other way around?  `-noddl`?

**Comment by dgnorton** [comment]
@ayang64 it means getting rid of any line that isn't line protocol. In other words, remove all the lines starting with `#` and also the `CREATE DATABASE` lines.

@timhallinflux since this command line option is removing all of the DDL and part of the DML, leaving only line protocol, should the flag be `-dataonly` or `-rawdata` maybe?

**Comment by timhallinflux** [comment]
`-lponly` ?

**Comment by dgnorton** [comment]
Implemented in:
master-1.x - PR #19609
1.8.3 - PR #19611
