### ISSUE TITLE
Design an option that users can set to rerun a task if it fails

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/influxdb#19406]
Tasks can fail for reasons beyond the control of the user. For example:

1. The task could try to access an external service that is unavailable.
2. InfluxDB itself returns an internal error.

In general, it is not safe to retry all tasks, because a task could have a side effect. However, users should be able to decide on a case by case basis if they want a task to retry automatically.

When tasks retry, they should use the original time window from when they first ran to ensure that downsampling tasks run effectively.

**Comment by aanthony1243** [comment]
clarify:  this is a case where we only want to retry if we get a report that `queryd` itself fails with a 500

**Comment by rickspencer3** [comment]
Goal is to have a design for this to be implemented in a future sprint

**Comment by brettbuddin** [comment]
I've been thinking about these retries and talking with @aanthony1243. Here are some thoughts:

Task Query execution is currently a push-based model. The Task Query Executor sends requests to Gateway, which forwards requests to a load-balanced fleet of Query Pods. The Query Pods themselves execute up to 100 concurrent queries from many different users.

Reduced Query Pod availability is a failure scenario of Tasks that has been quite common lately. In this situation, all Tasks being scheduled will likely run into problems issuing query requests to Gateway which will cause pressure within the Task Scheduler/Execution system.

Retrying good Task queries—while still not free of gotchas in how Scheduling/Execution works—isn't the main concern. I'm worried about Tasks containing Flux that can crash a Query Pod. When a Task sends request to Gateway, and the Query Pod it's routed to crashes, the Task Run will receive an upstream disconnect error (`503`). If we were to retry these, we would multiply the rate of Pod crashes and push us into CrashLoopBackoff state more quickly.

Coupled with the way the Scheduler produces Task runs, things get worse the shorter the interval between this Task's Runs and how long the back-off period in retrying is. Due to the concurrent nature of the executor worker pool [1], we could potentially have many Task Runs for a single Task schedule consuming a significant number of outstanding workers—all of which are retrying the bad query. I haven't done a lot of research into it, but I suspect this could increase load on `etcd` as well.

Due to this failure state, and how often we've run into it over the last few months, I don't think it's safe to pursue general Task retry behavior **yet**. Recent discussions of one query per-pod behavior and restricting the number of query-induced Pod failures that a single Task can cause will open the door to retries.

With that said, it's more reasonable to retry `500` (exact) codes. They don't imply infrastructural problems like unreachable Pods. These error codes happen less often, but they mean there is something on the other side giving you that code—not Kubernetes/Istio reporting it. This is much less useful though and isn't really the reason we want these retries.

Another option, which seems expensive, is the isolate customers that have some sort of retrying enabled to their own Query Pod groups and Task scheduling. Task scheduling isolation would be necessary to protect the schedules of other customers from becoming starved for resources by a feedback loop caused by retrying.

[1] The Task Query Executor currently runs a pool of up to 100 concurrent workers that feed from a queue that has a maximum capacity of 1000 in-flight Task triggers (instances of a scheduled Task).
