### ISSUE TITLE
update goreleaser.yml to use the tag template variable

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#19667]
we probably should change the process to use the tag template variable and include multiple image patterns like tag, major, minor.

https://github.com/influxdata/influxdb/blob/c40162bcb78b1e87b429452a74dd51143776788b/.goreleaser.yml#L122

> We probably want to change the .goreleaser.yml to use “{{ .Tag }}” over that static env variable

then we wouldn't need this change: https://github.com/influxdata/influxdb/pull/19666

fyi @BondAnthony

**Comment by zendern** [comment]
I'd be happy to open a PR on this. We have this on another go project I work on. Would basically looks like so. And doing multiple tags like this allows the users to opt into auto updates or not if they are good with any patch update, minor updates or if they just want to pin to that specific tag they can.  

```
image_templates:
    - "quay.io/influxdb/influxdb::{{ .Tag }}"
    - "quay.io/influxdb/influxdb::v{{ .Major }}"
    - "quay.io/influxdb/influxdb::v{{ .Major }}.{{ .Minor }}"
```

**Comment by BondAnthony** [comment]
@zendern a PR would be great, thank you!

**Comment by zendern** [comment]
> @zendern a PR would be great, thank you!

Cool I'll work one up today. I saw it was assigned and didn't want to step on toes.

**Comment by gshif** [comment]
I think these two lines won't be necessary:
```
 - "quay.io/influxdb/influxdb:v{{ .Major }}"
 - "quay.io/influxdb/influxdb:v{{ .Major }}.{{ .Minor }}"
```

**Comment by BondAnthony** [comment]
@gshif I wouldn’t mind the couple extra tags. When projects use this pattern it reduces some overhead for the operators. Just my opinion though.

**Comment by gshif** [comment]
@BondAnthony, All i meant is that we never had images with either Major and/or Major/Minor tags. If you think there is a value in this, then let's get it there.
@russorat your thoughts?

**Comment by zendern** [comment]
So the changes are simple :) clearly its 3 lines...trying to validate locally and running into not having things installed/env issue . I think there might be something missing from local setup but it also could be just `goreleaser` is only run on ci so no one really needs/has validated locally. 

Attempting to run this. Which is what I've run in the past to generate all the things and validate it works but will just not push anything.
`./bin/goreleaser release -p 1 --skip-publish --snapshot --rm-dist`

I can go one of two ways....

1. Keep trying to get everything installed on my macbook to get it to work....current error on macbook

```
zender [projects/oss/influxdb]  19667/goreleaser-tag! → ./bin/goreleaser release -p 1 --skip-publish --snapshot --rm-dist                                                                                       [a171c4e2cb]

   • releasing...
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • releasing v2.0.0-rc.0, commit a171c4e2cbab3bcb1bdfd6ee56f0c59c9e2b83e0
      • pipe skipped              error=disabled during snapshot mode
   • parsing tag
   • running before hooks
   • setting defaults
      • snapshotting
      • github/gitlab/gitea releases
      • project name
      • building binaries
      • creating source archive
      • archives
      • linux packages
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • docker images
      • artifactory
      • blobs
      • homebrew tap formula
      • scoop manifests
      • milestones
   • snapshotting
   • checking ./dist
      • --rm-dist is set, cleaning it up
   • writing effective config file
      • writing                   config=dist/config.yaml
   • generating changelog
      • pipe skipped              error=not available for snapshots
   • building binaries
      • building                  binary=/Users/zender/dev/projects/oss/influxdb/dist/influx_linux_amd64/influx
   ⨯ release failed after 0.89s error=failed to build for linux_amd64: # runtime/cgo
/Users/zender/go/bin/xcc: line 19: exec: musl-gcc: not found
```

or 

2. if you can confirm the `dshell` docker image in the project intended to mock/be more similar to the CI setup?? Wondering if I should tweak it to deal with those oddities im running into instead of dealing with any type of local machine setup. In the 
dshell container i did have to use the `./env` otherwise i get other oddities around `pkg-config`

Current error in the container
```
influx@08af2d1f8b46:~$ ./env ./bin/goreleaser release -p 1 --skip-publish --snapshot --rm-dist

   • releasing...
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • releasing v2.0.0-rc.0, commit a171c4e2cbab3bcb1bdfd6ee56f0c59c9e2b83e0
      • pipe skipped              error=disabled during snapshot mode
   • parsing tag
   • running before hooks
   • setting defaults
      • snapshotting
      • github/gitlab/gitea releases
      • project name
      • building binaries
      • creating source archive
      • archives
      • linux packages
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • docker images
      • artifactory
      • blobs
      • homebrew tap formula
      • scoop manifests
      • milestones
   • snapshotting
   • checking ./dist
      • --rm-dist is set, cleaning it up
   • writing effective config file
      • writing                   config=dist/config.yaml
   • generating changelog
      • pipe skipped              error=not available for snapshots
   • building binaries
      • building                  binary=/code/dist/influx_linux_amd64/influx
   ⨯ release failed after 10.34s error=failed to build for linux_amd64: # runtime/cgo
exec: "xcc": executable file not found in $PATH
```

**Comment by BondAnthony** [comment]
@zendern it's been a little while since I've needed to test the release process but when I did it was done through the dshell container. I have a mac also but I normally compile within a container.

@russorat, we probably need to focus on documentation of installing a working dev environment without a hassle.

**Comment by russorat** [comment]
@gshif if i understand this correctly, for dockerhub, we go down to the PATCH version for influxdb, so i don't know of a reason we wouldn't want to do that in quay: https://hub.docker.com/_/influxdb?tab=description

@BondAnthony i agree! i will run through from an empty VM to see if i can repro

**Comment by danxmoran** [comment]
Looks like this was done in #19902
