### ISSUE TITLE
InfluxDB 2.0.0 setup fails to print correct retention period.

### ISSUE THREAD

**Issue by ssoroka** [influxdata/influxdb#19671]
__Steps to reproduce:__

1. docker run -p 8086:8086 quay.io/influxdb/influxdb:2.0.0-rc
2. docker exec -it container-id influx setup
3. put any non-zero value for retention period

__Expected behavior:__
see a retention period

__Actual behavior:__
```
Please type your retention period in hours.
Or press ENTER for infinite.: 1y

Please type your retention period in hours.
Or press ENTER for infinite.: 8760


You have entered:
  Username:          steve
  Organization:      steve
  Bucket:            telegraf
  Retention Period:  0 hrs
```

__Environment info:__

* System info: Darwin 19.6.0 x86_64
* InfluxDB version: 2.0.0-rc

**Comment by gshif** [comment]
Setup does not fail to setup retention period for the bucket. What happens is that `setup` does not print the value set for the retention period on the screen, but this values is being set in the local datastore. The bug is that set retention period values is not being printed out.
- Enter retention period value to be 100 hours
```
Please type your retention period in hours.
Or press ENTER for infinite.: 100
```
- The value entered is not being printed to the screen for confirmation
```
You have entered:
  Username:          test
  Organization:      test
  Bucket:            test
  Retention Period:  0 hrs
```
- Return the list of all buckets. As can be seen from the results the retention period is set correctly for the `test` bucket. 
```
ID			Name		Retention	Organization ID
9564391e21139c36	_monitoring	168h0m0s	4c1b6138db084d68
8aabf355b6557e0f	_tasks		72h0m0s		4c1b6138db084d68
4191143cafa03e9d	test		100h0m0s	4c1b6138db084d68
```

**Comment by russorat** [comment]
🤔  i see it being used here: https://github.com/influxdata/influxdb/blob/master/cmd/influx/setup.go#L310

**Comment by danxmoran** [comment]
Running `influx setup` on the latest RC correctly prints the retention period for me:
```
Welcome to InfluxDB 2.0!
Please type your primary username: test

Please type your password:

Please type your password again:

Please type your primary organization name: test

Please type your primary bucket name: test

Please type your retention period in hours.
Or press ENTER for infinite.: 72


You have entered:
  Username:          test
  Organization:      test
  Bucket:            test
  Retention Period:  72 hrs
Confirm? (y/n): y
```

999660a refactored the code the day after this issue was opened, I'm guessing it inadvertently fixed the problem.

**Comment by russorat** [comment]
Closing as fixed.
