### ISSUE TITLE
scrapers not working in RC0

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#19679]
creating the scraper through the UI works fine, but it fails to actually scrape any data.

This is the entry from the debug logs:

```
2020-10-02T15:40:58.000564Z	debug	Request	{"log_id": "0PbVP8_l000", "service": "http", "method": "GET", "host": "localhost:8086", "path": "/metrics", "query": "", "proto": "HTTP/1.1", "status_code": 200, "response_size": 5919, "content_length": 0, "referrer": "", "remote": "[::1]:58149", "user_agent": "Go-http-client", "took": "4.088ms", "body": ""}
2020-10-02T15:40:58.012081Z	error	Recorder handler error	{"log_id": "0PbVP8_l000", "error": "database not found: "}
```

viewing http://localhost:8086/metrics works just fine.

**Comment by russorat** [comment]
Workaround for now is to create a task to scrape data using the https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/experimental/prometheus/scrape/ function.

**Comment by stuartcarnie** [comment]
@russorat is this a GA issue or post GA?

**Comment by russorat** [comment]
it should be fixed before GA

**Comment by stuartcarnie** [comment]
Ok, moved to TODO of GA board

**Comment by stuartcarnie** [comment]
@russorat what bucket were you attempting to store the metrics within?

**Comment by stuartcarnie** [comment]
I notice that the default selection is `_monitoring`:

![image](https://user-images.githubusercontent.com/52852/95489995-6fa23d00-094c-11eb-8332-55171d256cd2.png)

However, if I expand the drop-down, `_monitoring` is not an option:

![image](https://user-images.githubusercontent.com/52852/95490035-8052b300-094c-11eb-9325-9d0f9e12a51b.png)

I will continue to dig and determine where the problem lies.

**Comment by russorat** [comment]
@stuartcarnie that looks like a separate UI bug. let's open a separate issue for it.

**Comment by matthewoates** [comment]
I'm not seeing any activity when setting up scrapers. Also no visibility into why from the UI.
