### ISSUE TITLE
Add /metric gauge for templates

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#19688]
similar to telegraf, we should have a metric for the number of templates installed in http://localhost:8086/metrics:

```
# HELP influxdb_telegraf_plugins_count Number of individual telegraf plugins configured
# TYPE influxdb_telegraf_plugins_count gauge
influxdb_telegraf_plugins_count{plugin="aggregators.basicstats"} 1
influxdb_telegraf_plugins_count{plugin="aggregators.final"} 1
influxdb_telegraf_plugins_count{plugin="aggregators.histogram"} 1
influxdb_telegraf_plugins_count{plugin="aggregators.histogram.config"} 2
influxdb_telegraf_plugins_count{plugin="aggregators.merge"} 1
```

I would expect it to look like this:

```
# HELP influxdb_templates_install_count Number of InfluxDB Templates installed
# TYPE influxdb_templates_install_count gauge
influxdb_templates_install_count{template="csgo"} 1
influxdb_templates_install_count{template="custom"} 1
```

**Comment by russorat** [comment]
similar to https://github.com/influxdata/influxdb/issues/19737

**Comment by glinton** [comment]
@russ I see `"custom"`, as a template name, is that intended to be a catch-all/generic "custom" template name, or is that referring to a template being named "custom" prior to install? would the template url be a better metric than a template's name so we'd have `/wherever/it/lives/csgo/template.yml=3` instead of `csgo1=1; csgo2=1; csgo3=1`? (assuming it's acceptable to store (perhaps without the host?))

**Comment by russorat** [comment]
so i think that's a catch all for someone loading up their own template that isn't in the community templates repo.

A template can be a file path, a url, or a byte stream, so it's tough to know what the "right" way to identify it is. I think template url would be good, and then file name for a file, and maybe just "byte_stream" for a byte stream?

I think the idea was to get a sense of the most popular templates being installed from our community templates repo.
