### ISSUE TITLE
Telegram Drop Down does not exist 

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/influxdb#19719]
The option to select Telegram when configuring alerts doesn't exist in the drop down for Cloud or OSS 2.0-rc 0. 
<img width="834" alt="Screen Shot 2020-10-09 at 3 03 05 PM 1" src="https://user-images.githubusercontent.com/30506042/95626799-95107300-0a40-11eb-8b0c-27e0935c6bba.png">

https://community.influxdata.com/t/telegram-endpoint/16244

**Comment by lberruti** [comment]
As reported here https://github.com/influxdata/influxdb/issues/17899#issuecomment-791890086, telegram alert notifications are disabled in OSS.
Please, can telegram alert notifications be enabled in OSS?

**Comment by ep1cman** [comment]
So, I got this figured out eventually. The short answer: is yes you can get it enabled.

Long answer:
If you clone the repo and open the file `ui/src/shared/selectors/flags.ts` you will find a bunch of UI features that have been disabled. you can simply edit the file to set them to true to enable them. Or if you prefer, just run the following command:

```
sed -i "s/'notification-endpoint-telegram': false,/'notification-endpoint-telegram': true,/g" ui/src/shared/selectors/flags.ts
```
However if you try to run make as is you'll find that these changes don't stick, and this is because of a rather sly line in the UI makefile. Rather building the UI locally, it instead runs a script that fetches the latest build of the UI from github, which obviously has these features disabled. You can modify the ui makefile to restore the proper build witht he following command:
```
sed -i "s/.\/fetch_ui_assets.sh/yarn build/g" ui/Makefile
```
You can either rebuild the whole of influxdb, or you can use your existing binary and use `--asset-path` option as per the instructions here: https://github.com/influxdata/influxdb/blob/master/ui/README.md

Finally if you are using the dockerfile provided in this repo to run influx, you will find that an error occurs when attempting to connect to telegram because it does not recognise the certificate authorty used by telegram. This can easily be remedied by installing the `ca-certificates` package and running the `update-ca-certificates --fresh` command to get the latest trusted CA certificates.

I have published a dockerfile with all the modifications listed above. You just need to replace the one in this repo with the one here: https://gist.github.com/ep1cman/5a51af73cba19a104523286167f29869
