### ISSUE TITLE
Add shard duration settings to the CLI

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#19764]
based on the outcome of this https://github.com/influxdata/influxdb/issues/19738

Let's add the ability to adjust bucket shards from the CLI.

**Comment by jphavoc** [comment]
This feature seems promising, but will InfluxDB re-optimize bucket shards that already contain data or does this only apply to data that will be written? I could not find any information how InfluxDB handles my use case.

**Comment by wagerfield** [comment]
I would very much like to see this configuration carried over from 1.x. I too am trying to backfill years worth of data at a "coarse-ish" time resolution of 1 data point per minute with ~200 series, but simply can't due to the default shard group duration of 7d that results in Influx throwing the error "too many files open" after about 100 shards have been created. Without being able to backfill this historical data V2 is unusable for my use case unfortunately. My current options are to either use 1.7 or look at an alternative DB—neither of which I'm that keen on given the time spent learning V2 and writing the code to interface with it.

**Comment by russorat** [comment]
we still need to have this, but @wagerfield, for too many files open, you can try increasing your ulimit settings: https://docs.influxdata.com/influxdb/v2.0/write-data/developer-tools/csv/#too-many-open-files-errors

**Comment by wagerfield** [comment]
Thank you @russorat—appreciate you taking the time to help me out 🙌 

I had come across this solution while Googling the issue, but got the impression that it's not an optimal solution since it still results in 100's of shards being created for data elapsing over many years. Since my data set spans back ~10 years, this results in ~500 shards with the default shard group duration of 7d for an infinite RP.

I tried increasing the `ulimit` from the system default of 256 to 65,536 (2^16) and was able to write all my data to InfluxDB. However, when I kill the daemon, open a new terminal session and start the daemon again, I run into the same "too many open files" error since the `ulimit` resets to 256 for each new Terminal session. I therefore need to increase the `ulimit` each time I start the Influx daemon which doesn't "feel" right to me—but I'm not very experienced in this domain.

From reading the [Influx 1.8 docs](https://docs.influxdata.com/influxdb/v1.8/concepts/schema_and_data_layout/#shard-group-duration-recommendations), shard group durations should be "twice as long as the longest time range of the most frequent queries". I expect this is so that numerous shard files don't have to be loaded into memory and queried "across" in place of 1 or 2?

In my case, I will be querying for years at a time eg. "give me all the data points for series A and B between 2012 and 2015 filtering on tags X and Y" —so Influx will have to get that data from ~156 shards (3 years * 52 weeks) if they're fragmented into 7d groups by default....at least that's how I think it works—but if there's a way of getting this information from the CLI, please let me know since I couldn't figure it out. All I know is that when I start the daemon _a lot_ of shards and TSM files are opened.

Whereas if all my historical data was broken up into 52w shard group durations or even one large 520w shard, I would imagine this would improve the query performance and also circumvent to the need to increase the `ulimit` each time I start the Influx daemon?

Do you have any idea on a time frame for getting this configuration into V2? [The PR that @hinst submitted[(https://github.com/influxdata/influxdb/pull/20620) looks like it's got the functionality in there 🤞
