### ISSUE TITLE
[feature request] limit the number of results returned via the configuration

### ISSUE THREAD

**Issue by joelgriffiths** [influxdata/influxdb#1994]
Grafana users (ie. My boss) tend to do strange things like graphing a weeks worth of data at 0.1s intervals. This crashes influxdb. Is there any way to configure, through the influxdb configuration file, the maximum number of values returned for any query?

**Comment by steverweber** [comment]
+1 strange boss issue

**Comment by jsternberg** [comment]
I think this is now fixed in 0.12. There are a lot more switches for limiting how queries are executed and returned. The one for this issue is in the http section.

```
[http]
    max-row-limit = 10000
```

This sets a maximum on the number of points returned in non-chunked responses. In a chunked response, there is no limit as they are sent in multiple chunks. For other query management limits, you can look at the documentation here: https://docs.influxdata.com/influxdb/latest/troubleshooting/query_management/

Thanks! I hope this resolves your issue. Please reopen if it does not so I can resolve it properly.
