### ISSUE TITLE
InfluxDB 2.0.1: Backup Issue "Error: Unable to open boltdb;"

### ISSUE THREAD

**Issue by sukhan85** [influxdata/influxdb#20051]
Raising a backup issue for InfluxDB 2.0.1.

When performing full backup or against a single database backup, there seems to be an issue.

Please see below list of all databases in my InfluxDB 2.0.1.

```
root@influxDB2:/vagrant# influx -o influxdata bucket list
ID			Name		Retention	Organization ID
b0140031a37dc15f	_monitoring	168h0m0s	d30d2d1531ac906b
1129e0b70879d049	_tasks		72h0m0s		d30d2d1531ac906b
43a5851855817497	telegraf	8h0m0s		d30d2d1531ac906b
01059a2f11e9473d	weather_monitor	12h0m0s		d30d2d1531ac906b
```

**Performing Full Backup**

Upon me running a backup command, I get the following error;

```
root@influxDB2:/vagrant# influx backup /vagrant -t $INFLUX_TOKEN
2020-11-16T14:40:02.490479Z	info	Backing up KV store	{"log_id": "0QWNo~jW000", "path": "20201116T144002Z.bolt"}
Error: Unable to open boltdb; is there a chronograf already running?  invalid argument.
See 'influx backup -h' for help
```

I could not see any activities within the logs to help me detect this issue. I did close the Chronograf and re-ran the backup command, but still no luck.

I only see a `.bolt` file generated with above command.

```
root@influxDB2:/vagrant# ls -lah *.bolt
-rw-r--r-- 1 vagrant vagrant 104K Nov 16 14:40 20201116T144002Z.bolt
```

I cannot see any `.manifest` file generated from this backup.

__Environment info:__

* System info: Linux 4.15.0-112-generic x86_64
* InfluxDB version: InfluxDB 2.0.1 (git: 37cc047133) build_date: 2020-11-11T03:53:31Z
* Other relevant environment details: VM running on VirtualBOX with local SSD storage.

**Comment by psteinbachs** [comment]
@benbjohnson Would you mind taking a look and confirming this is a bug?

**Comment by benbjohnson** [comment]
I'm unable to reproduce this locally on Linux (via vagrant) or on my Mac using either `v2.0.1` or `master`. I'm having @sukhan85 try it again to see if he can still reproduce.

> `Error: Unable to open boltdb; is there a chronograf already running?  invalid argument.`

The `invalid argument` is likely coming from `influx backup` when it tries to read the `bolt` file it just downloaded from the server. I'm really not sure why it would fail that. It does a file open & a mmap but I'm not sure what argument would be passed in that's invalid. It seems like the data for the file exists on disk.

> I cannot see any `.manifest` file generated from this backup.

re: manifest, it doesn't get written until the whole backup succeeds so that is expected.

**Comment by benbjohnson** [comment]
@psteinbachs It looks like the issue is backing up into the `/vagrant` directory. Per SO, it looks like mmap isn't supported on the mapped folder: https://stackoverflow.com/a/18421071

I'm not sure there's much we can do to fix this as we need to load Bolt data to process the rest of the backup and Bolt uses `mmap()`.

**Comment by danxmoran** [comment]
Looks like we can't really fix the failure in this case, but we could improve the logging to make it easier to see why the failure is happening.

**Comment by danxmoran** [comment]
@benbjohnson looking into this a bit more... it looks like setting MAP_PRIVATE on the mmap call might fix the issue? Adding that flag would prevent writes from persisting to disk, but for the backup/restore use-cases (I think) we could get away with read-only uses. Bolt exposes the settings we'd need to tweak this behavior in its `Options`. WDYT?

**Comment by danxmoran** [comment]
@sukhan85 what box were you using in Vagrant when you saw this issue? I'm trying to intercept & replace the error message to be something more helpful than "invalid argument", but I'm not able to reproduce using hashicorp/bionic64

**Comment by sukhan85** [comment]
Hi Daniel,

I used "ubuntu/bionic64".

Thanks

Suleman
