### ISSUE TITLE
Error: Restore failed while processing manifest files: read manifest: parsing time "0" as ""2006-01-02T15:04:05Z07:00"": cannot parse "0" as """.

### ISSUE THREAD

**Issue by ced2git** [influxdata/influxdb#20135]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ...Backup Influxdb 1.8 
2. ...Restore in influxdb 2.0.2
3. ...

__Expected behavior:__

Able to migrate data between two instances of influxdb. One in version 1.8 (raspbian 32bit, rpi 4) and One in version 2.0.2 (ubuniu 20.0.4)

__Actual behavior:__

Error: Restore failed while processing manifest files: read manifest: parsing time "0" as ""2006-01-02T15:04:05Z07:00"": cannot parse "0" as """.

Cannot restore the data. 

__Environment info:__

* System info: Run `uname -srm` and copy the output here

Backup instance: Linux 5.4.51-v7l+ armv7l
Restore instance: Linux 5.4.0-28-generic x86_64

* InfluxDB version: 

Backup instance: InfluxDB v1.8.3 (git: 1.8 563e6c3d1a7a2790763c6289501095dbec19244e)
Restore Instance: Influx CLI 2.0.2 (git: 84496e507a) build_date: 2020-11-19T03:59:35Z

**Comment by danxmoran** [comment]
Hi @ced2git, the error you hit is expected because 1.x and 2.x use incompatible formats for their backup/restore manifests & metadata.

It looks like you're trying to move your deployment between machines (if not, `influxd upgrade` is the easiest way to get your data into a 2.x layout). I'd recommend:
1. In your 1.x environment, use [`influx_inspect export` ](https://docs.influxdata.com/influxdb/v1.8/tools/influx_inspect/#export) to dump all your data to disk in line-protocol format
2. Use the 2.x [`influx write`](https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/write/) command to write the exported LP into your 2.x instance
