### ISSUE TITLE
Improve validation error messages for DBRP API

### ISSUE THREAD

**Issue by Hualin-AUG** [influxdata/influxdb#20134]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Having an InfluxDB Cloud account (free tier)
2. Setup a bucket and write data into it
3. Try to do DBRP mapping with following command:

curl  --request POST 'https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/dbrps' \
--header 'Authorization:  Token {my token}' \
--header 'Content-type: application/json' \
--data '{
    "bucketID": "{my bucketID}",
    "database": "{some database name}",
    "default": true,
    "orgID": "{my orgID}",
    "retention_policy": "30days"
}'
__Expected behavior:__
A DBRP should be setup for the bucket I give

__Actual behavior:__
400 Bad request error happens with following message
{
    "code": "invalid",
    "message": "invalid ID"
}

__Environment info:__

* InfluxDB version: InfluxDB Cloud

__Config:__
Token I use an all permission token

**Comment by rbetts** [comment]
Let's also make the "Invalid ID" error messages disambiguate which ID(s) are invalid.  (See re-used errors here: https://github.com/influxdata/influxdb/blob/master/dbrp/http_server_dbrp_test.go#L185).

**Comment by timhallinflux** [comment]
@Hualin-AUG -- you might also consider trying the updated CLI which now has DBRP commands which should make this a bit easier to manage the mappings themselves.  https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/v1/dbrp/

We'll improve the error messages here in parallel.

**Comment by danxmoran** [comment]
+1 to more specific error messages. In that same direction, I suspect the actual error here is/was that the Cloud implementation expects`bucket_id` and `organization_id` instead of the Swagger-specified `bucketID` and `orgID` (it's fixed in OSS but I'm not sure if it's gone through to Cloud yet).

I don't think either impl is validating that requests contain all the expected keys. When there's a mismatch, the system ends up with an empty string for one (or both) IDs, and the empty string fails validation. The most specific validation error would be something like `Missing required key: "xxx"`

**Comment by danxmoran** [comment]
@Hualin-AUG if the new CLI tools don't work for you, could you also try using `bucket_id` instead of `bucketID` and `organization_id` instead of `orgID` in your request payload?

**Comment by Hualin-AUG** [comment]
> @Hualin-AUG if the new CLI tools don't work for you, could you also try using `bucket_id` instead of `bucketID` and `organization_id` instead of `orgID` in your request payload?

That absolutely solves the problem.

**Comment by rbetts** [comment]
@Hualin-AUG thanks for the bug-report. Really helpful as we iron out some usability gotchas here!
