### ISSUE TITLE
influx v1 dbrp list gives Error: Attempted to unmarshal error as JSON but failed: "unexpected end of JSON input":.

### ISSUE THREAD

**Issue by eaglejohn81** [influxdata/influxdb#20173]
Current version: InfluxDB 2.0.2 (git: 84496e507a) build_date: 2020-11-19T03:59:35Z
(Updated binaries yesterday from InfluxDB 2.0.0-rc.3 (git: f46a3bd91e) build_date: 2020-10-29T22:17:55Z - not sure if that is related)

Running "influx v1 dbrp list" gives: Error: Attempted to unmarshal error as JSON but failed: "unexpected end of JSON input":.

Also, when trying to use the API to get the database retention policy mappings returns error 500 (internal server error)

curl --location --request GET 'http://influxhost/api/v2/dbrps?org=myorg' \
--header 'Content-Type: application/json' \
--header 'Authorization: Token {token}

**Comment by eaglejohn81** [comment]
When starting fresh using the GA version 2.0.2 it is working fine... Did I miss something in the upgrade procedure from rc3 to 2.0.2?

**Comment by danxmoran** [comment]
@eaglejohn81 I think you're hitting #20121, which was caused by an accidental breaking change to our internal DBRP schema. The problem only occurs if you upgrade (2.x < 2.0.2) -> 2.0.2 and have DBRP mappings in your metadata.

We just merged a patch that will auto-migrate existing DBRPs from the old schema to the new on `influxd` startup, to be released in 2.0.3.

**Comment by eaglejohn81** [comment]
@danxmoran, that could be very well related indeed. Thank you for pointing this out!
