### ISSUE TITLE
Annotations MVP Epic

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/influxdb#20180]
Annotations Epic MVP
sources for this epic are: https://github.com/influxdata/influxdb/issues/15575 and https://github.com/influxdata/influxdb/issues/16954

Business Goals
Deliver minimum viable product for annotations - a single event overlaid onto time series data in a dashboard.

Acceptance Criteria
 As a user, I can view a singular event as a line overlaid with my time series data in dashboard views, with a tooltip on hover displaying the title and summary.
 As a user, I can create events with a start & stop time (but the stop time will always equal the start time), a title, and a summary overlaid with my time series data anywhere in the application.  This will only be available through a click event on the UI from the Annotate button.
 As a user, I can edit an annotation.
 As a user, I can delete an annotation.
 As a user, the retention period of annotation is unlimited.  (note: follow up with API provider)
 As a user, an annotation will apply for all dashboard cells simultaneously.

Technical
Annotations are stored in a separate db instance, not in a bucket.

Manual Use Case
User wants to drop a pin on a graph and have it persist
Users want their annotations to retain longer than their regular time series

Team
Design Lead - @mnorriswalker 
Product Lead - @russorat (interim @mnorriswalker )
Engineering Lead - @hoorayimhelping @StacieClark @glinton

Design Prototype
[Link to Figma Prototype](https://www.figma.com/file/AQk0tUthLFepRhFUibvzMI/Annotations?node-id=134%3A890)

**Comment by afausti** [comment]
Thanks @russorat for the user review session on the MVP Annotations feature today! we are excited to see it coming along in InfluxDB 2.0. 

Let me write down some notes from the meeting:
- Frossie mention the ability to add links to the annotation text. If markdown content like in the "Notes" cell  is allowed that would be great.
- I understand now my initial reaction with the "Enable 1-click Annotations" check box, I think it would be more natural if that was a button "Annotate" or "Add annotation" to represent the action of adding an annotation. I'm probably biased by the Chronograf implementation...
- When adding annotations it currently snaps to the closest data point, perhaps a "Snap" check box would make it more flexible for "manual" annotations.
- We talked about the scope of annotations: "cell", "dashboard" and "global". It would be really nice to control that. In Chronograf, they are always global and we essentially use tag filtering to show the "right annotations" for a given dashboard or cell. Global annotations are important for us as a mechanism to correlate features/events among different cells or even dashboards.
- Window (range) annotations are certainly useful.
- I think that adding labels with different colors for annotations like we do for Dashboards in 2.0 would be awesome.
- It seems like you guys made the technical decision to not store annotations in a bucket... and I was curious to ask why is that? I personally think that there are very compelling reasons for using a bucket:  1) the user could use Flux to query and display annotations in different ways inside the platform; 2) we don't need to implement an API for annotations, we could just use the InfluxDB HTTP API instead 3) InfuxDB tags could be used for the Annotations tags. And there are probably other advantages... like automatic annotations could be added by Flux tasks... I bring this up because annotations are essentially time series data right? and treating them like that seems very attractive to me.

Thank you again for organizing the user review session today. Sorry if I don't remember the name of all the participants to mention here @daviddkkim and... thanks guys!

**Comment by hoorayimhelping** [comment]
Annotations was toggled on in production a 7:30 PDT today, Monday May 3rd, 2021. This MVP epic is

### DONE

**Comment by nicob87** [comment]
sorry to bother, I am not finding how to write annotations with the api, is this implemented?
