### ISSUE TITLE
Nightly tag on quay.io contains a 1.7.x release

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#20247]
Reported by a surprised user in the Community forums:
```
$ docker run --rm -it -p 8086:8086 quay.io/influxdb/influxdb:nightly influx -version
InfluxDB shell version: 1.7.0~n201901110800
Enter an InfluxQL query
```
If we still want to provide nightly images, we need to udpate our CI to start pushing 2.x versions. Otherwise I'd say we should delete the nightly tag, to avoid future confusion.

**Comment by timhallinflux** [comment]
agreed.  We should remove this for 1.x and start for 2.x.

**Comment by gshif** [comment]
@psteinbachs , @timhallinflux 
We currently have a nightly job running in Jenkins to build quay.io/influxdb/influxdb:nightly images.This job pulls the `https://dl.influxdata.com/influxdb/nightlies/influxdb_nightly_amd64.deb`  package and creates an image based on the downloaded package. 
What happens is that influxdb 2.0 nightly creates an image based on 2.0 and puts it in the sameplace with the same name as image created by the above cron job. 
Should we create 2.0 nightly images using `quay.io/influxdb/influxdb2:nightly`instead of `quay.io/influxdb/influxdb:nightly`?

**Comment by timhallinflux** [comment]
yes.

**Comment by gshif** [comment]
Should be addressed by https://github.com/influxdata/influxdb/pull/20300
