### ISSUE TITLE
investigate test flakiness

### ISSUE THREAD

**Issue by drdelambre** [influxdata/influxdb#20482]
we got reports of weird tests cases failing. this holds everyone up by injecting uncertainty at the best, production bugs at worst

**Comment by genehynson** [comment]
https://github.com/influxdata/ui/pull/497 should resolve most of the flakiness. There is at least one outstanding flaky failure that we've yet to resolve. Sometimes tests will fail because of a 401 Unauthorized status code returned from the `/me` API. We added logging to hopefully help us nail down this issue

**Comment by genehynson** [comment]
https://github.com/influxdata/ui/pull/515 should help resolve the "detached from dom" issue with the checks test
