### ISSUE TITLE
Notebooks: I can see an autogenerated notebook name

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/influxdb#20692]
When a user creates a notebook, leaves and comes back, they cannot tell the difference in the notebooks due to having multiple notebooks with the same name. We would like to autogenerate a notebook name so that they we don't have the same default name repeated several times in the notebook list.

![image.png](https://images.zenhubusercontent.com/5fdbca6b688d8a81424e922b/0ea36054-7d79-4518-9085-8e7c96f37416)

The notebook naming format should be:

[author] + notebook + [timestamp]

For example:

jbridges-notebook-2021-07-11T13332

### Acceptance Criteria

- After creating a notebook, a user should be able to return and see the autogenerated notebook name.
- The autogenerated notebook name format should match the criteria above.

**Comment by drdelambre** [comment]
what should this autogenerated notebook name look like?

**Comment by jzahnd** [comment]
@mnorriswalker bump, any idea of what the name should look like?

**Comment by mnorriswalker** [comment]
This has to be a global change - we can't just change this for notebooks (CC @russorat )

Templates does a random name generation which we don't want to do. Example: `jolly-blackburn-e60001`

We would want to do something like:

[author]+ [resource type] + [timestamp]

So...

mnorriswalker-notebook-2021-04-19T17424

Thoughts?

**Comment by russorat** [comment]
i think templates is a little unique due to the fact that multiple resources are generated at the same time when you do an export. Also, template names need to be unique in the entire org, whereas nearly all of the UI resources can have duplicate names (except buckets, variables, and labels). We might still need the random hash at the end of the template resource name to avoid that issue, but the pattern still makes sense.

**Comment by russorat** [comment]
Let's do this for notebooks, and address the naming of other UI resources later.

**Comment by russorat** [comment]
bringing this issue back because it is using org name instead of user name in the title.

Username comes from the response from this api: https://docs.influxdata.com/influxdb/cloud/api/#operation/GetUsersID

it looks like this in cloud
![image](https://user-images.githubusercontent.com/4805997/126794157-485bc12c-eed8-45af-8118-9ef66a00ad2d.png)

and like this in OSS
![image](https://user-images.githubusercontent.com/4805997/126794407-7a02411a-e7de-4079-81d8-455e2b76330d.png)
