### ISSUE TITLE
 influxdb V2 : write_api.write(bucket, org, record) return : {"code":"unauthorized","message":"unauthorized access"} 

### ISSUE THREAD

**Issue by Julie97434** [influxdata/influxdb#20859]
Hello,
I'm new to influxdb V2 , I work on MacOS (Big Sur) and i have a problem.
I'm trying to run basic programs to write data using python. 

My python code:

```
from datetime import datetime

from influxdb_client import InfluxDBClient, Point, WritePrecision
from influxdb_client.client.write_api import SYNCHRONOUS

token = "token"
org = "org"
bucket = "bucket"

client = InfluxDBClient(url="http://localhost:8086", token=token)

write_api = client.write_api(write_options=SYNCHRONOUS)

point = Point("mem")\
  .tag("host", "host1")\
  .field("used_percent", 23.43234543)\
  .time(datetime.utcnow(), WritePrecision.NS)

write_api.write(bucket=bucket, org=org, record=point)
```

and I keep getting the same error:

```
influxdb_client.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Thu, 04 Mar 2021 09:10:59 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
```

I've almost entirely read the documentation : 
[https://docs.influxdata.com/influxdb/v2.0/get-started/](url)

**Comment by danxmoran** [comment]
@Julie97434 are you actually using `"token"` as the auth token in your code, or is that just a placeholder you put in for the issue?

Similarly, are your initial org and bucket really named `org` and `bucket`?

**Comment by Julie97434** [comment]
They are just a placeholder. In my real code, I created new ones as explained in the doc.

**Comment by danxmoran** [comment]
401 is returned by the server when it can't parse your token (vs 403, which means it can parse your token enough to see that you don't have permissions). A few more questions in that vein:
* Can you confirm that the token you're using is the same token that was written to `~/.influxdbv2/configs`? Or the equivalent if you configured a different path when setting up your instance
* Are you able to run `influx write 'mem,host=host1 used_percent=23.43234543'` from the terminal? That can help narrow down if it's a problem with the Python code vs. a bigger configuration issue

And some general questions:
* What version of InfluxDB are you running? There were some auth-related bugs in the early releases
* Can you resend the link to the docs you're looking at? Your original post gives me a 404 because of the `(url)` at the end

**Comment by Julie97434** [comment]
- I confirm i'm using the same token and org..

- When I run this command from the terminal :

```
% influx write 'mem,host=host1 used_percent=23.43234543'

Error: Failed to write data: unauthorized access.
See 'influx write -h' for help
```
it return a error ..

- I use : influxdb2-2.0.4-darwin-amd64 

- and sorry for the link 😄 

- I noticed other errors : (similar error when I run this command for `bucket `et `token` )

```
influx org ls 
Error: Failed find orgs: unauthorized access.
```

I probably installed something wrong...

**Comment by Julie97434** [comment]
Into error return by the python code, there is the date and time but the time return by the error does not correspond to the current time. Can the issue come from there?

PS: I live in the Reunion Island

**Comment by danxmoran** [comment]
@Julie97434 I wouldn't expect the timestamp to cause an auth error (though it might cause confusion later on when querying data, so I'd recommend removing it for now).

Did you perform initial setup via the UI, or via the CLI?

**Comment by Julie97434** [comment]
@danxmoran I perform initial setup via the UI. 

Excuse me but I didn't understand what I should remove ..

**Comment by danxmoran** [comment]
I would remove `.time(datetime.utcnow(), WritePrecision.NS)` from your code, because the server will automatically assign the "now" timestamp to points that aren't marked with a time.

Since you performed initial setup through the UI, I assume you also found the `token` value you're using in the UI. Can you list out the steps you used to find the token?

**Comment by Julie97434** [comment]
I found the solution, 

I used the name of the token and not the key ... Now than I using the token key everything is working !  

In any case, thank you for your help 😅
