### ISSUE TITLE
Epic: UI Metrics Foundation

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/influxdb#20865]
Create a flexible foundation to capture UI metrics from production to Tools (or other environment).

Change existing functionality from writing metrics to the AppData bucket in Tools to a new UI specific bucket (ui_metrics) with the ability to configure which environment the bucket resides in (may be different than Tools).

Use Case:
We want to capture a number of new metrics, and have Bonitoo update the code to capture those metrics. 

Requirements:
* Bonitoo cannot log into Tools, so a configuration must be designed to allow Bonitoo to write local dev metrics to an environment other than Tools.  
* Encapsulate logic to write metrics to a single function, allowing Bonitoo to write metrics code easily.
* Ability to write metrics to a new bucket, ui_metrics, since existing appdata bucket is overutilized.

**Comment by hoorayimhelping** [comment]
>Ability to write metrics to a new bucket, ui_metrics, since existing appdata bucket is overutilized.

currently, metrics are written to the [`frontendmetrics`](https://github.com/influxdata/k8s-idpe/blob/master/apps/idpe/frontend-services/common.libsonnet#L21). I think they're the only thing being written there. But either way, the configuration is located in k8s-idpe, linked above and can be changed there. I'm not sure if we can write to multiple buckets.

>Bonitoo cannot log into Tools, so a configuration must be designed to allow Bonitoo to write local dev metrics to an environment other than Tools. 

We currently have the ability to write locally to the default bucket with monitor-ci. Previously, I hacked something up locally through IDPE that [has a readme.](https://github.com/influxdata/idpe/blob/master/cmd/frontendservices/README.md) Do they have access to idpe or monitor-ci?

More generally, do we need to have a solution for testing this locally with the remocal/KinD setup?

**Comment by hoorayimhelping** [comment]
Thinking about this over the weekend and remembering a conversation I had with Barbara about this, it sounds like we need two things from this:

1. Tooling and process for local development to allow Bonitoo to confirm that the metrics they're writing are correct (with the assumption that things work the same way in prod as they do locally)
2. A process to handoff and test that those metrics are being written to tools correctly

Part 1) can (probably) be as simple as telegraf config that listens for metrics and writes them back to the local influxdb instance. I say 'probably' because right now monitor-ci handles using idpe for this, and we might need a simple proxy server to handle this.

Part 2) I'm imagining something as simple as a semi-formal list of metric names and instructions on how to get them to fire.
