### ISSUE TITLE
Delete the `transpile` command from the `influx` CLI

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#20905]
`influx transpile` hasn't been maintained, and it's not really needed now that our servers can handle InfluxQL. Delete it.

**Comment by sqlpac** [comment]
Bonjour,

Now I'm trained to Flux language, I am fan of this language. 2 weeks ago, I used frequently the transpile option to get ideas about the translation from InfluxQL to Flux, especially because I am used to SQL.
We just migrated 2 InfluxDB servers out of 10 from 1.7 to 2.0.4 version.
Isn't it too early to remove the transpile option, it helped me a lot while migrating.
Indeed I noticed subqueries could not be translated, but surely the transpile option could help other users like me for the migration in the next coming months.

It's just a opinion, maybe I have been the only one in the world using the transpile option for migration help and learning Flux language

Best regards and congrats, InfluxDB v2 is a great new version.

**Comment by sqlpac** [comment]
Thank you for the answer. I fully agree, it was just a thought waiting for the new exciting features which are more important : custom private packages with Flux ([Flux Custom Functions and Packages](https://community.influxdata.com/t/flux-custom-functions-and-packages/14980/6)) and ... InfluxDB IOx [Announcing InfluxDB IOx – The Future Core of InfluxDB Built with Rust and Arrow](https://www.influxdata.com/blog/announcing-influxdb-iox/)
