### ISSUE TITLE
how to connect influxdb by influx client

### ISSUE THREAD

**Issue by wha-lgtm** [influxdata/influxdb#21755]
this is influx config:
![image](https://user-images.githubusercontent.com/38023162/123651945-75cfa500-d85e-11eb-8b77-883f2375f217.png)

and i use influx connect,but nothing:
![image](https://user-images.githubusercontent.com/38023162/123652067-913ab000-d85e-11eb-999c-9eac22011049.png)

how to become : 1、like mysql connect service  2、can use show databases ,so on

**Comment by danxmoran** [comment]
@wuxiaobing1993 the v2 CLI doesn't support running an interactive shell, you'll need to run the commands listed by the help text to inspect different resources in the system.

**Comment by wuxiaobing1993** [comment]
@danxmoran 
Does the official document say that version 2.0 no longer supports client connection to the server?How do you know that?Can you give me a link?

**Comment by wuxiaobing1993** [comment]
Will the 2.0 version no longer connect directly to the server with the client configuration as the 1.0 version did？
As with the MySQL database, you connect to the server with the client password username and then use the sql language.

**Comment by russorat** [comment]
@wha-lgtm you can find full documentation for using the command line tool here: https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/

you can run queries against your influxdb using `influx query 'buckets()'` command.

i'm closing this for now since it doesn't seem to be a bug or feature request. please join us in the slack channel if you have more questions about getting started. https://influxdata.com/slack
