### ISSUE TITLE
[bug]: Saving an inactive task activates it without toggling it to active state

### ISSUE THREAD

**Issue by Srki032** [influxdata/influxdb#21874]
**OS info**: macOS Catalina 10.15.7, Darwin Kernel Version 19.6.0/RELEASE_X86_64
**InfluxDB version**: 2.0.7, installed with homebrew

**Steps to reproduce**:
1. Click on inactive task to edit it
2. Save the task
3. Return to task menu where task is toggled inactive
4. Check task runs for logs of new task execution

**Expected behaviour**:

- By saving the inactive task, no changes will take effect until the task is toggled active

**Actual behaviour**:

- By saving the inactive task, changes take effect while it is toggled as inactive & Task runs show it being treated as active
- In order to deactivate it, the task needs to be toggled active, then inactive

**Screen recording of the bug replication**:

https://user-images.githubusercontent.com/56439717/126171988-22ab0470-a0cc-4d88-a038-73f6843a149d.mov

**Comment by wbaker85** [comment]
Doesn't look like this is a UI-specific problem. I was able to reproduce it and the API responses show that the task status is still inactive after updating the task, but the task does start to run again. It seems that that act of submitting a `PATCH` request for the update puts the task into a running state even though it has the inactive status in the backend.

**Comment by raffs** [comment]
First time contributing in here :). I've taken an interest on InfluxDB recently - including interesting in the code. Thus, I've decided to investigate on this issue as a learning exercise; also to see if I could propose a fix. Here's it goes!

Apparently, the issue is coming from https://github.com/influxdata/influxdb/blob/d677fa1eebf0e536be22595bb951ac2a1c7843f9/task/backend/coordinator/coordinator.go#L133-L142. 

That particular code will `Release()` a tasks when it's being inactivated (active -> inactive). Otherwise, it will schedule it. The problem is, in this particular case, the tasks doesn't change the status: It was already inactivated. Consequently, the first expression (`from.Status != to.Status`) will be `false` and the else condition will be executed; which schedule the task. 

It seems we can fix this by adding a condition to ensure the tasks is only scheduled when the status is `active`. Then, if the tasks is being deactivated (first condition) we ensure that task is released, If the tasks doesn't change its status we only run it when is set to `active`. 

I'm submitting a PR with this proposed changes. 

Given my inexperience with this project, I'm not 100% clear whether this will the best approach or not. I'm looking forward for advices!
