### ISSUE TITLE
Shall i build the application if docker is already available?

### ISSUE THREAD

**Issue by enthusiastics** [influxdata/influxdb#22356]
I'm trying to deploy influxdb for my system. As i saw, i could either directly use their docker image or I could compile and build my own. 

But I also found articles saying deploying docker has almost 0 overhead vs starting my own virtual machine. So I would like to ask if would the performance of directly using docker images almost the same as building my own. In that case, I would probably not spend too much time trying to debug for the db deployment.

**Comment by wbaker85** [comment]
You can also download pre-built binaries for a variety of operating systems, instead of compiling it yourself: https://portal.influxdata.com/downloads/ - this would save you the trouble of building it locally.

Docker is definitely lighter weight than a virtual machine, but does come with some complexities over running a binary on bare metal. If you are comfortable running docker, there shouldn't be any major performance differences though.
