### ISSUE TITLE
INFLUX_SKIP_VERIFY Environment Variable Ineffectual

### ISSUE THREAD

**Issue by skursh104** [influxdata/influxdb#22495]
Influx CLI environment variable `INFLUX_SKIP_VERIFY` does not seem to have any effect on CLI commands.

For example, using the `--skip-verify` flag functions properly and as expected, but setting the `INFLUX_SKIP_VERIFY` seems to have no effect on CLI commands. Also, there is no data type listed in the documentation.

##### Relevant URLs
- This flag is mentioned on most CLI command pages, but here is an [example on the write page](https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/write/#flags)

**To reproduce:**
Configure InfluxDB with TLS enabled. Note: Relevant org, bucket, and token environment variables have been set for this example.
`username:/$ influx write "test measurable=1"`
`Error: Failed to write data: Post <redacted>: x509: certificate is valid for <redacted>, not localhost.`
`Error: Get "https://localhost:8086/api/v2/setup": x509: certificate is valid for <redacted>, not localhost.`
` #See 'influx write -h' for help`
`username:/$ influx write "test measurable=1" --skip-verify`
`username:/$ export INFLUX_SKIP_VERIFY=true`
`username:/$ influx write "test measurable=1"`
`Error: Failed to write data: Post <redacted>: x509: certificate is valid for <redacted>, not localhost.`
`Error: Get "https://localhost:8086/api/v2/setup": x509: certificate is valid for <redacted>, not localhost.`
`See 'influx write -h' for help`

Version:
InfluxDB 2.0.7 with same version CLI

**Comment by wbaker85** [comment]
This looks like it was fixed by https://github.com/influxdata/influx-cli/pull/208

I was able to successfully use the v2.1 CLI (installed via homebrew for me, but other platforms are available at https://portal.influxdata.com/downloads/ under "InfluxDB Cloud CLI", which works for OSS v2.0.8 as well) and successfully use the `INFLUX_SKIP_VERIFY` environment variable with a self-signed cert.

So you should be able to get this working by using the most recent version of the CLI! Closing this issue, but feel free to open a new issue in https://github.com/influxdata/influx-cli if you notice any other CLI bugs.

**Comment by Forbzy** [comment]
Hi @wbaker85 Im experiencing the same issue. Do you assign the variable INFLUX_SKIP_VERIFY equal to anything?
I'm using Influx CLI 2.0.9 (git: d1233b7951) build_date: 2021-09-30T18:53:33Z
