### ISSUE TITLE
Accidentally deleted the admin token

### ISSUE THREAD

**Issue by iserranoe** [influxdata/influxdb#22706]
I'm not sure if this is a bug, but any help would be appreciated.

After creating an admin user with `influx setup` I accidentally deleted the admin token and now I can't create new users or organizations as even with "All Access Token" the permissions "write:users" and "read:users" are missing. Is there a way to restore "admin's token"? Anyway, I think this token shouldn't be able to be erased.

**Comment by flopp999** [comment]
Still no way to recover the user that I created during Setup?
I tried Influxd recovery but it just give me errors.
No way to reset the Setup so I can do it again?

**Comment by jeffreyssmith2nd** [comment]
What errors is `influxd recovery` giving you? As of the 2.5.1 release, you should be able to login to the UI or the CLI with the username and password of the original user and then use them to create further authorizations/tokens.

**Comment by franck102** [comment]
I am in the same situation, trying to re-create an operator token yields

```
influxd recovery auth create-operator --org xxx --username yyy
2022-11-08T13:02:36.269955Z	info	Resources opened	{"log_id": "0e1qD2wG000", "system": "bolt-kvstore", "path": "/home/pi/.influxdbv2/influxd.bolt"}
Error: bucket "authorizationsv1": bucket not found
See 'influxd -h' for help

influxd version
InfluxDB v2.5.1 (git: 5b6fdbf05d) build_date: 2022-11-02T18:06:20Z
```

How do you "login to the CLI with the username & password"? I don't see any influxd cmd line switch to provide credentials?

**Comment by franck102** [comment]
I reinstalled from scratch and went through the initial setup again, using the Web UI: the "initial user setup" prompts you for username/password/org/bucket, it does create the operator token but it doesn't display it anywhere.
After that step I can click "Advanced" and go to Load Data -> API Tokens where the initial token shows as "created 24s ago".

Is there a way to use that token at all???

**Comment by jeffreyssmith2nd** [comment]
> How do you "login to the CLI with the username & password"?
When you create a config with the influx cli (`influx config create ...`) you can provide a `--username-password` flag to setup a configuration that uses username/password instead.

>  it does create the operator token but it doesn't display it anywhere.

I just verified that must have come through when the UI was updated, the correct procedure would be to use the above suggestion for logging in with username/password and then you can create new operator token. Alternatively, if you setup using the CLI it will add your operator token to the influx CLI config.

**Comment by franck102** [comment]
> > How do you "login to the CLI with the username & password"?
> > When you create a config with the influx cli (`influx config create ...`) you can provide a `--username-password` flag to setup a configuration that uses username/password instead.
> 
> > it does create the operator token but it doesn't display it anywhere.
> 
> I just verified that must have come through when the UI was updated, the correct procedure would be to use the above suggestion for logging in with username/password and then you can create new operator token. Alternatively, if you setup using the CLI it will add your operator token to the influx CLI config.

I can log in with username password, but that won't let me create an operator token? Only an "all access" token, which seems different, since I can't use it to run "influx server-config".

I worked around the problem by using "clone token" on the originally created token: that creates a clone operator token and gives me a chance to grab it.

**Comment by JoKr4** [comment]
I also ran into the problem how to get the all access token
(not after deletion but "in general")

The workaround described by @franck102 with the clone is working

But what is the official way of getting the all access token after a fresh installation?

`InfluxDB v2.6.0 Server: 24a2b62 Frontend: cbab7db`

**Comment by katchy3132** [comment]
> ```
> influxd recovery auth create-operator --org xxx --username yyy
> 2022-11-08T13:02:36.269955Z	info	Resources opened	{"log_id": "0e1qD2wG000", "system": "bolt-kvstore", "path": "/home/pi/.influxdbv2/influxd.bolt"}
> Error: bucket "authorizationsv1": bucket not found
> See 'influxd -h' for help
> 
> influxd version
> InfluxDB v2.5.1 (git: 5b6fdbf05d) build_date: 2022-11-02T18:06:20Z
> ```

@franck102 

I was able to get rid of this error  by specifying `--bolt-path ` , so using your command above : 

`influxd recovery auth create-operator --org xxx --username yyy --bolt-path /var/lib/influxdb2/influxd.bolt`

**Comment by andrew-r-weaver** [comment]
Not sure how to proceed. I setup influx 2.6.1 through docker, second time really setting up influx, first was bare metal. 
I can't get the original token, pretty sure my experience was similar to @franck102. Since, I have a document with all the keys I've been displayed.

> "initial setup again, using the Web UI: the "initial user setup" prompts you for username/password/org/bucket, it does create the operator token but it doesn't display it anywhere."

I've been able to build out all my dashboards and snmp telegrafs with the all access token I've made.
However, when I went to create a guest account to view those dashboards, discovered 

`Error: failed to create user "dashboard": 401 Unauthorized: write:users is unauthorized`

I tried to clone the original token, then use that displayed token, but same auth failure. 
I tried creating another new all access token, same auth failure.

`root@efa9244daf87:/# influxd recovery auth create-operator --org  --username  --bolt-path /root/.influxdbv2/influxd.bolt 
2023-01-06T20:09:28.040581Z     info    Resources opened        {"log_id": "0fEB54v0000", "system": "bolt-kvstore", "path": "/root/.influxdbv2/influxd.bolt"}
Error: bucket "authorizationsv1": bucket not found`

`root@efa9244daf87:/# influxd recovery auth create-operator --org  --username  --bolt-path /var/lib/influxdb2/influxd.bolt
Error: unable to open boltdb file unable to open boltdb file timeout`

**Comment by jeffreyssmith2nd** [comment]
@andrew-r-weaver:
The all-access token is a bit misnamed, it will not be able to create users (I know the UI currently implies that it can, that is incorrect).

The cloned token should work though, I tested that and is identical to the original operator token.

I believe the reason your `influxd recovery auth create-operator` command is failing is because influxdb is still running. `Error: unable to open boltdb file unable to open boltdb file timeout` is what bolt usually reports when the boltdb file is accessed while something else already as it open. If you stop influxd and then run the recovery command, that should work.

**Comment by jeffreyssmith2nd** [comment]
You can also login to the CLI using the username/password of the user that created the instance and then you will effectively have operator token capabilities.

**Comment by andrew-r-weaver** [comment]
@jeffreyssmith2nd 
Thank you for the response. 

I think you're right about the boltdb file, it was in use. 
I didn't want to stop the influxdb container to try. I was able to resolve my auth error without stopping the container/service. 

The problems that I figured out to get it to work. 

1. connect to the docker container running influxdb as the user running it. 
`docker exec --user "$(id -u):$(id -g)" -it influxdb bash`
This allowed me to run the `influxd auth list` to retrieve the key with write user. 

2. I read the command format incorrect. I thought it was asking for the token I wanted for the user. Not the token with privileges to create the user.
