### ISSUE TITLE
Updates to a remote or replication should immediately cause a remote-write retry if there is a failed write waiting to retry

### ISSUE THREAD

**Issue by wbaker85** [influxdata/influxdb#22943]
If a remote or associated replication is misconfigured, the remote writer will continue to retry the write in a loop. With exponential backoff being used between attempts, the time between remote write attempts may end up being minutes+. This will lead to a sub-optimal user experience if the user updates the configuration with a correction, but then has to wait several minutes until the write is re-attempted. Ideally, the update would trigger the write to immediately retry and reset the "backoff" timer.

This will most likely require changes to the remote services, as well as the replications service, to interact with the queue manager and send signals to the relevant replication queues.

**Comment by DStrand1** [comment]
Currently, to implement this well, we would need to connect the `remotes` and `replications` endpoints a bit too much, which is undesirable since `remotes` is designed to be usable by other features in the future. As a result, I'll close this issue out for now and we can reassess later if we want to do this for just `replications` endpoint changes
