### ISSUE TITLE
max-index-log-file-size parsed differently between config and environment

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/influxdb#22974]
In docs + the config file, you can set
`max-index-log-file-size = "128k"`
But... when they set
`INFLUXDB_DATA_MAX_INDEX_LOG_FILE_SIZE="128k"`
in their charts, Influx threw a paddy and refused to come up. We had to get them to change it to
`INFLUXDB_DATA_MAX_INDEX_LOG_FILE_SIZE=131072`
Are we doing some kind of type enforcement on the env var that we're not doing to the config file? They're running 1.8.10

**Comment by lesam** [comment]
Background: When we use the toml library to do the config parsing, these config parameters are type `toml.Size` and so the SI unit sizing works.

When we do the environment variable overrides, we don't do anything special for the SI unit sizing and it barfs.

**Comment by Hitesh-Agrawal** [comment]
Facing same issue, had to use numbers instead of the SI unit in ENV variable. When is this scheduled to fix or atleast get the docs fixed for the same so it reflects correct usage when using ENV -- https://docs.influxdata.com/enterprise_influxdb/v1.9/administration/configure/config-data-nodes/#tsi-tsi1-index-settings

**Comment by davidby-influx** [comment]
@kelseiv - maybe we could put the doc fix in for the next Enterprise release....

**Comment by davidby-influx** [comment]
Doc note made

**Comment by gwossum** [comment]
This will be fixed with #27312. Expected release in InfluxDB 1.13.0.
