### ISSUE TITLE
Hitting max map count can cause data to become unqueryable

### ISSUE THREAD

**Issue by lesam** [influxdata/influxdb#23172]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Set vm.max_mmap_count 'too low'
2. Create many (likely 1000's) of shards with TSI enabled

__Expected behavior:__
 * The database should gracefully fail with a complaint about vm.max_mmap_count being too low
 * The database should be more aware of different errors that occur during opening of TSM files, and only move the file aside for an error that actually indicates corruption.

__Actual behavior:__
1) Because we are out of mmap space, random memory allocations fail, crashing the application
2) Because we are out of mmap space, opening TSM files fails in a way that causes the TSM files to be marked as corrupt and moved aside.

__Environment info:__

* System info: Any linux version
* InfluxDB version: 1.9.6
* Other relevant environment details: n/a

__Logs:__

The most concerning errors are: `Cannot read corrupt tsm file, renaming`, which moves the TSM files aside even though they are not actually corrupt.

**Comment by davidby-influx** [comment]
This particular fix suggested above, which will help diagnose errors opening files that occur in `mmap` calls in [NewTSMReader](https://github.com/influxdata/influxdb/blob/7d182158f436e454c27af01cc90cbd2e9c759923/tsdb/engine/tsm1/reader.go#L222), is certainly not the only place where `vm.max_mmap_count` is exceeded. We will better diagnose failures on file opening, but memory allocations elsewhere will still cause panics in the runtime code from `SysAlloc` returning `ENOMEM`, and we need to remain aware of the cryptic nature of these failures, as well.

**Comment by lesam** [comment]
It might be worth just spawning a goroutine on linux that checks for this sort of thing (mmap too low, file ulimit too low, etc) and warns / exits if the limit is too low.

**Comment by davidby-influx** [comment]
Fixing `NewTSMReader` will probably be the low-hanging fruit that allow diagnosis in 80% of cases.  I would recommend that before looking at other monitoring solutions.

**Comment by lesam** [comment]
@WesleyDavid 262144 is 4x the original value, seems like a good place to go to. @andrew-influx really we'll need monitoring / alerting on this as well.

**Comment by WesleyDavid** [comment]
For posterity, it appears that we've been accidentally interchanging `vm.max_map_count` for `vm.max_mmap_count`. Notice the extra `m` in the second one. The correct tunable is `vm.max_map_count` with only one `m`. I've been double checking and correcting GH issues and my own scripts to make sure the wrong one hasn't leaked in to anywhere important. 😁

**Comment by WesleyDavid** [comment]
All existing hosts in Cloud 1's production ap-southeast-1 region have had `vm.max_map_count` changed to `262144` and `vm.min_free_kbytes` changed to always be 4.5% of physical host RAM. I'll keep an eyeball or two on it overnight and then we can discuss rolling this out to every other region in stages.

**Comment by davidby-influx** [comment]
Re-opening, as their may be more fixes and other mechanisms to mitigate this situation

**Comment by davidby-influx** [comment]
Issue for backport to 1.10: https://github.com/influxdata/influxdb/issues/23413

**Comment by lesam** [comment]
Re-closing - we fixed:

The database should be more aware of different errors that occur during opening of TSM files, and only move the file aside for an error that actually indicates corruption.

Opening a separate issue for linux-specific log warnings.

**Comment by lesam** [comment]
Opened https://github.com/influxdata/influxdb/issues/23439

**Comment by jdstrand** [comment]
> [jdstrand](https://github.com/jdstrand) closed this as [completed](https://github.com/influxdata/influxdb/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/influxdata/dependabot-for-influxdb-1.x/commit/ec412f793b0fbb0d4c1ee35ebbb1fbbc69baabf0 [5 days ago](https://github.com/influxdata/influxdb/issues/23172#event-6771401442)

This was surprising to me as all I did was merge master-1.x into the https://github.com/influxdata/dependabot-for-influxdb-1.x main branch. Reading https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue, what I understand to have happened is that I merged a commit (via `git fetch ; git pull --ff-only origin master-1.x`) in the default branch of dependabot-for-influxdb-1.x (dependabot only scans default branches which is why it is set up this way). One of the commits in that pull used `closes https://github.com/influxdata/influxdb/issues/23172` which appears to have triggered the `Issue in a different repository` [functionality](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) (which was presumably allowed since both repos are in the same org/have similar ACLs/what have you).

It looks like GitHub has a feature request for this to disable automatic issue closing: https://github.com/github-community/community/discussions/17308. I'm going to participate in that thread and in the meantime, update our [process docs](https://github.com/influxdata/influx-security-tools-cve-data#dependabot-alerts-for-alternate-branches) to mention this and to watch out for this. Most of the time, this shouldn't be a problem as we are only pulling from the default branch of the main repo which would have already auto-closed the issue by the time it is merged into the alternate dependabot repo, but if the issue is reopened after the fact but before the merge into the alternate repo (like this one was), then it seems it will auto-close it.
