### ISSUE TITLE
invalid import path contrib/jsternberg/rows

### ISSUE THREAD

**Issue by Voprsalek** [influxdata/influxdb#23481]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Install InfluxDB v2.3.0+SNAPSHOT.090f681737
2. Use "import "contrib/jsternberg/rows""
3. error @1:1-1:33: invalid import path contrib/jsternberg/rows

__Expected behavior:__
No errors

__Actual behavior:__
Error: error @1:1-1:33: invalid import path contrib/jsternberg/rows

__Environment info:__

* System info: Docker image influxdb:latest (5 days ago)
* InfluxDB version: InfluxDB v2.3.0+SNAPSHOT.090f681737

Thank you

**Comment by tscott11** [comment]
What is the replacement for import "contrib/jsternberg/rows"?

**Comment by Xebi4i** [comment]
Is there a way how to fix it? Can we replace the row function with something similar?

**Comment by sanderson** [comment]
@Xebi4i, @tscott11  `rows.map()` was an alternate implementation of the default `map()` function that was more performant, but also more restrictive. The default `map()` has since been updated with optimizations that put its performance on par with `rows.map()` without the functionality restrictions. Further optimizations are also being made to `map()`. To get the latest version of Flux that includes these `map()` optimizations, be sure to install or upgrade to the [latest InfluxDB OSS release](https://docs.influxdata.com/influxdb/latest/install/) or use [InfluxDB Cloud](https://www.influxdata.com/products/influxdb-cloud/).

**Comment by rudupa68** [comment]
I installed the latest 2.4 version and still seeing the error for the OverallThroughput field.

**Comment by sanderson** [comment]
@rudupa68 This package was removed. If using InfluxDB 2.4, just use `map()`.
