### ISSUE TITLE
regexp support look-around, including look-ahead and look-behind

### ISSUE THREAD

**Issue by ZeroSean** [influxdata/influxdb#23621]
__Proposal:__
use string regexp to filter metrics record, for example:
from(bucket: "tsdb_mysql")
  |> range(start: 2022-08-10T06:50:00Z, stop: 2022-08-10T07:15:00Z)
  |> filter(fn: (r) => (r._measurement == "mysql_global_status_queries" and r._field == "value") and r.hostname !~ /mgb-test(?!da01-dba|dp01-dba).*/)

__Current behavior:__
occured errror:  compilation failed: error @12:117-12:266: regex parse error: mgb-test(?!da01-dba|dp01-dba).* error: look-around, including look-ahead and look-behind, is not supported

__Desired behavior:__
flux string regexp support look-around, including look-ahead and look-behind.

**Comment by sanderson** [comment]
@ZeroSean The Flux regexp implementation is built on top of the Go regexp implementation, which does not support look-around, look-ahead, or look-behind expressions. This is done for performance reasons. Because this is more of a Flux issue rather than an InfluxDB issue, I'm going to go ahead and close this issue.

You may consider opening a feature request on the [Flux repo](https://github.com/influxdata/flux/) to add support for these expressions in the regexp implementation, but just know that this implementation was a conscious decision due to the performance impact of these types of expressions.
