### ISSUE TITLE
Some cascading docker problems

### ISSUE THREAD

**Issue by meyergru** [influxdata/influxdb#24049]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

* Create a docker instance of influxdb 2
* Start initial setup via GUI
* Try to backup the database with 'influx backup'

__Expected behavior:__

I should be able to create a backup.

__Actual behavior:__

This is impossible, because you need an operator token, a normal "all access" token does not suffice.
Alas, since you cannot create operator token via the GUI, you are stuck.
The follow-up problem then occurs, because with the initial setup via GUI, there is no operator token at all.
Then you decide to re-create a recovery operator token via "influxd recovery auth create-operator" only to find that this does not work when influxdb daemon is running.
And that is the last step to find that you can "docker exec" only when the container is running, but there are no tools inside the influxdb2 container that even allow you to show a process list. And when you stop the container altogether, you cannot "docker exec" into it.

This is a cascading problem caused by some bad decisions:

1. One cannot view the API tokens via GUI - not that this creates any security, because you can show the tokens via CLI, only more cumbersome.
2. The operator token is not created via all setup paths, much less presented one with a clear disclaimer,
3. The container is minimal, such that essential management commands cannot be started in a docker instance because they do not work with the daemon still running.

The only way to fix this was to stop the container, copy the database volume over to a full Ubuntu installation, install influxdb 2.6.1, start it, re-create an operator token, stop the daemon, copy back the database and restart the docker container.
Maybe there is a more elegant fix, however this was the straightforward way that I got from the documentation.

This should not be so hard!

__Environment info:__

* System info: docker image influxdb:2.6.1
* InfluxDB version: InfluxDB v2.6.1 (git: 9dcf880fe0) build_date: 2022-12-29T15:53:07Z
* Other relevant environment details: docker / portainer under Ubuntu 22.04

__Config:__
Nothing special

**Comment by rubinda** [comment]
How are you setting up influx cli? 
I've completed the setup via GUI and created a new config (`influx config create`) using the **username & password option** (`-p`) with the newly created user. After this I can view the created token (`influx auth list`), create backups using `influx backup` and view the server config (`influx server-config`) which I believe also requires an operator's token.
I've also tried finishing the setup using `influx setup` instead of the GUI and the aforementioned commands also work.

- Host OS: Ubuntu 20.04.5 LTS
- Influx CLI 2.6.1 (git: 61c5b4d) build_date: 2022-12-29T15:41:09Z
- InfluxDB v2.6.1 (git: 9dcf880fe0) build_date: 2022-12-29T15:53:07Z

**Comment by meyergru** [comment]
As I wrote: I followed a guide telling to just creating an influxdb docker image and setting up the database via the GUI.
This _seems_ to work fine, but never shows you the operator token - in my case, I erroneously installed influxdb 2.0 first and then upgraded the container to 2.6.1, which resulted in no operator token at all.

Then, you have to first create an operator token (which is impossible from inside docker, because either the daemon is  running and you cannot use recovery you stop the container, but then you cannot call influxd any more), So, the first bad decision is having to stop influxd to do such tasks and if that is actually needed, provide the docker container with the capability to do it by giving the user some utilities like ps or direct means of stopping only influxd, but not the whole contained.

Even after successful operator token creation, you still have to use the CLI in order to actually see it. 
There is no point in hiding the tokens in the GUI, because you can access them on the CLI, it is only way less convenient, but not one bit more secure. I call that a bad design decision.

I know that if you follow another path and setup influx via cli, you can do all that directly. However, the whole point of having influxdb under docker is to not having to do that.

**Comment by rubinda** [comment]
As I wrote:
I've used the version of the influxdb image you mentioned to create a **fresh and not upgraded** instance of influxdb running in docker.
I've completed the setup via GUI which I agree confusingly never gives you an opportunity to see a token.
However, setting up influx CLI (which is the only way to create backups if I'm not mistaken) on that new instance immediately recognized an operator token and **all the commands work as intended**. You do not need to complete the setup using the CLI, but you do need to provide the username and password (from GUI) when setting up the influx cli tool.

I wish to investigate, but **I am unable to reproduce your issue of the operator token not being created via any setup option** (which addresses the issue 2. in your original post). Perhaps your attempt to upgrade or using an outdated guide caused unwanted behaviour.

I am not affiliated with the influx team, but I'd like to give my 2 cents regarding 1. and 3. since I'm already here:

Regarding 1. (in the original post): There are plenty of systems (e.g. Github) which do not allow viewing token values after creation. I consider it a (risky) bonus to be able to view them via CLI.

As for 3. The whole idea is that the container should be minimal. A operator token is created during setup and can be used throughout the lifetime of the container. If you see a use case where you would need to create a new operator token without access to an existing one, perhaps the _minimal_ docker image is not suited for you. Might I suggest a custom docker image where you manually include influxdb? Or perhaps omitting docker and running it barebone?

**Comment by meyergru** [comment]
Maybe my specific problem started because the creation with influxdb 2.0 instead of 2.6.1 did not leave an accessible operator token. But that could easily happen otherwise as it is in no way obvious that an operator token is even needed for some operations. Since there was neither a token presented nor a "lark's vomit" disclaimer not to lose it, I was under the impression that there were only "all access" API tokens and "limited" tokens, not a third kind which is needed to make a backup. As such, even if an operator token was created and not shown to me, I might have deleted it from the GUI.

> Regarding 1. (in the original post): There are plenty of systems (e.g. Github) which do not allow viewing token values after creation. I consider it a (risky) bonus to be able to view them via CLI.
> 

Correct. But after all, this is the only way of getting to it as it is never displayed during the creation process, as you found. And by that, it it is accessible at all, it is not any more secure by hiding it from the GUI. If is was to be more secure, the tokens should not be retrievable at all, say, by using an asymmetric approach. But given the current creation process, I am glad that tokens ARE recoverable.

> As for 3. The whole idea is that the container should be minimal. A operator token is created during setup and can be used throughout the lifetime of the container. If you see a use case where you would need to create a new operator token without access to an existing one, perhaps the _minimal_ docker image is not suited for you. Might I suggest a custom docker image where you manually include influxdb? Or perhaps omitting docker and running it barebone?

There are plenty of ways I can imagine by which the operator token can get lost or not readily be available. Having no way to recover it is unacceptable in even a "minimal" docker image - much more so if that is the only one that is provided per default.

**Comment by jeffreyssmith2nd** [comment]
Hey @meyergru, a few thoughts:

1. This was not an intentional choice, this was an unfortunate regression that occurred when bringing the UI up to date. It is something I would like to address, and I agree it is cumbersome/unintuitive.
2. The operator token should definitely be created by all paths and if it is not, that is a bug. Note that due to item 1, it may be created but just not visible. You also can clone the operator token in the UI and use that cloned token.
3. If you want to execute commands using the docker image, you should be able to `docker run -v <volume_info_here> -p <port_forwarding> -it influxdb:<version> /bin/bash`. Once in that shell, you can execute any `influxd` or `influx` commands.

**Comment by meyergru** [comment]
Thank you! I did not intend to gripe (even if it may have sounded like it) and I have been able to resolve my specific issues. I now believe that the token not having been created and/or visible was caused by the 2.0 / 2.6.1 upgrade.

Good to hear that the problem will be addressed as normal users would probably fail to make it work.
