### ISSUE TITLE
Problem with Hyphen in string interpolation

### ISSUE THREAD

**Issue by john159753** [influxdata/influxdb#24096]
__Steps to reproduce:__
I created a simple alert, and wanted the measurement value to be included in the messaging. It seems like the string interpolation mechanism does not process my measurement name correctly, since it has a hyphen in it.

1. Create an alert, with a measurement that contains a hyphen
2. Change the messageFn to have "${r.Temperature-Current}"
3. It underlines red and the check does not fire as expected.

__Expected behavior:__
I would expect the string interpolation to write the value 

__Actual behavior:__
There is an error in the editor, "undefined identifier Current", where i would expect the full "Current-Temperature"

__Environment info:__
Windows Server 2019
InfluxDB 2.6.1

Maybe this is an escaping thing, but the documentation doesn't specify that anything but a double quote needs escaping. Adding a backslash does not help.
![image](https://user-images.githubusercontent.com/12056448/219500175-493d9244-edfb-4ce8-850e-6208930d9eb1.png)
![image](https://user-images.githubusercontent.com/12056448/219500218-2001f8db-b7c8-4a5a-bcc1-64e830acf7a5.png)

**Comment by sanderson** [comment]
@john159753 Because hyphens (`-`) are special characters, you can't use [dot notation](https://docs.influxdata.com/flux/v0.x/data-types/composite/record/#dot-notation) to reference keys with hyphens in them; you need to use [bracket notation](https://docs.influxdata.com/flux/v0.x/data-types/composite/record/#bracket-notation). But because bracket notation requires double quotes, you can't use bracket notation to interpolate a string, so you need to concatenate the string:

```js
messageFn: (r) => "The temperature for ${ r.unitname } is ${ r._level }. The current temperature is " + r["Temperature-Current"] + "."
```

**Comment by john159753** [comment]
Thank you so much for explaining that!
