### ISSUE TITLE
#FlightUnavailableError occur when executing simple query, I don't know how to solve this problem, help me to execute query. 

### ISSUE THREAD

**Issue by Shafvan4136** [influxdata/influxdb#24401]
For executing simple query for retrieving info from database, it won't connect to respected channel, their is problem making proper channel for this client connection, 
I need support to execute query for sql & influxdb.

**Comment by hiltontj** [comment]
Hey @Shafvan4136 - there hasn't been any activity on this issue for over a year, and we have drastically changed the flight interface since you opened this issue. You should be able to connect using FlightSQL to the same port that serves HTTP requests when you start the server with `influxdb3 serve`. Feel free to re-open or comment if you are still having issues.
