### ISSUE TITLE
Enable configuration and object store initialization for all `object_store` supported backends

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#24653]

**Comment by mgattozzi** [comment]
Turns out we already had this all wired up. [clap_blocks here has a function to set up the config and make an object store](https://github.com/influxdata/influxdb3_core/blob/86d72868fd39f7865e97d0b3a66bac29a5f662b2/clap_blocks/src/object_store.rs#L392). However, we do [not have the features enabled](https://github.com/influxdata/influxdb/blob/a5082ec4328d1c0e88b23415194882bcdede352a/influxdb3/Cargo.toml#L54-L56) by default so we just need to turn it on with a quick pr
