### ISSUE TITLE
Top N of an Avg Value

### ISSUE THREAD

**Issue by bnortman** [influxdata/influxdb#2467]
Something like this

select top(mean(value),10) from /ResourceName [0-9].Metric 120/ where time < 1428734700s and time > 1428733380s 

Which would first get the mean of value and then return the 10 highest. Can this be done?

**Comment by beckettsean** [comment]
related to #1821

**Comment by dswarbrick** [comment]
+1

**Comment by jamebr** [comment]
+1

**Comment by sl4dy** [comment]
+1

**Comment by jeffutter** [comment]
This would be very useful in queries such as:

``SELECT sum(value) FROM requests WHERE time > now() - 15m GROUP BY time(30s),host,path```

when there are many different 'path' labels for displaying in something like Grafana. Currently, with no way to use top I get back ~100 results, when I really only want to see the top 10 or so.

**Comment by steverweber** [comment]
using Limit and orderby should resolve this?
https://influxdb.com/docs/v0.9/query_language/data_exploration.html

**Comment by steverweber** [comment]
ah disregard, i miss read.

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
