### ISSUE TITLE
Change token generation for InfluxDB Edge

### ISSUE THREAD

**Issue by mgattozzi** [influxdata/influxdb#24704]
Currently this is how we generate the token:
https://github.com/influxdata/influxdb/blob/3dcf2778d693a1dd83809a18541240df4f12f9a8/influxdb3/src/commands/create.rs#L18-L31

We take the data in, get a Sha256 hash of it, and then hex encode it for the user. Instead what we want to do is change the command to do the following:

1. Do not take user input. The command should just be `influxdb3 create token`. This can be done by changing this line to just say `Token`
https://github.com/influxdata/influxdb/blob/3dcf2778d693a1dd83809a18541240df4f12f9a8/influxdb3/src/commands/create.rs#L13
2. The token itself will be created by:
- Getting 512 bits (64 bytes) of randomness and base64 encoding them
- Prepend a prefix of `apiv3_` to the base64 string like so `apiv3_<base64 string>`
- Sha512 the string
3. Print out the generated string of `apiv3_<base64 string>` for use in request headers
4. Print out the Sha512 version of the string

The actual server implementation will also need to be updated to use Sha512 here:
https://github.com/influxdata/influxdb/blob/3dcf2778d693a1dd83809a18541240df4f12f9a8/influxdb3_server/src/http.rs#L493

**Comment by jdstrand** [comment]
> 4. Print out the Sha512 version of the string

This is exposes an implementation detail of the server to the user. I'm guessing this is needed because the user is expected to somehow declare the sha512 to the server at least in the early days of the code?

Longer term I suspect at some point I think we'd want `influxdb3 create token` to "do the declaring" and we wouldn't need to give the sha512 to the user (eg, `influxdb3 create token` creates the token in the way you describe, creates the sha512 and then stores that sha512 in a (properly permissioned) file/S3 bucket/etc along with the permissions set associated with this token. Is this the general idea?

**Comment by mgattozzi** [comment]
Yeah. I think we'd want a better way long term on how to do it and making that a very easy experience for the user such that they will be able to do the secure thing without much hassle. I'm not sure the best way to make that experience happen though and I'm hoping we could sketch that out at some point.

**Comment by Dharmikas** [comment]
Influxdb2 allowed user to supply token whereas Influxdb3 did not allow to supply custom token. This makes it difficult in coding in a containerized way. If influxdb3 container goes down then we need to always create the token, copy it then do code changes and re-deploy them. Can we allow custom tokens in influxdb3?

**Comment by hiltontj** [comment]
@Dharmikas this is being worked on in https://github.com/influxdata/influxdb/issues/26437
