### ISSUE TITLE
Logarithmic mean

### ISSUE THREAD

**Issue by marijnz0r** [influxdata/influxdb#2482]
I'm working with sound data at the moment and I'm using the dB values in my database right now. I would like to switch to InfluxDB, but I don't see a way to get the mean of (logarithmic) dB values in a way with InfluxDB. Would it be possible for InfluxDB to add an average log function, like avglog(column)?
Or would I have to create it myself with user defined functions?

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
