### ISSUE TITLE
Develop an in memory Parquet cache for querying

### ISSUE THREAD

**Issue by mgattozzi** [influxdata/influxdb#24897]
Currently we do not have a cache for Parquet files. They're stored in an ObjectStore and only if designated as in memory are they really cacheable. We want the WriteBuffer to cache data in the current segment as Parquet as needed and shuffle data so that all _series_id are in the same file as much as possible. It could also be used by the WriteBuffer to cache ParquetFiles as needed.

This new cache should:

- [x] Have be an InMemory ObjectStore for as part of the WriteBuffer
- [x] Be hooked into how Parquet Query Chunks are produced for querying

**Comment by pauldix** [comment]
I'll also need a Parquet cache for the buffer. That is I'll want to convert data into Parquet, but hold onto it rather than writing it out to object storage because it's more memory efficient and I'll want to shuffle the buffer data before sending it off to object store.

Also, I'd like to have the in-memory store separate from the object store. Meaning, I don't want it going out to object store to fetch things if they're not available in cache. At the very least, have it not pull into cache something that is a miss that it then sends to object store.

**Comment by mgattozzi** [comment]
After talking with @pauldix offline I've updated the ticket to be purely about having an InMemory cache specifically for use by the write buffer. A separate issue can be opened up for the actual shuffling of data. This will merely add and hook up the machinery to have a cache to the WriteBuffer
