### ISSUE TITLE
Difficulty Saving All InfluxDB Stuff Under Single Named Volume with Docker

### ISSUE THREAD

**Issue by jmwoc** [influxdata/influxdb#24900]
I find it difficult to save all my influxdb data to a single named volume for data persistence and ease of backing up/duplication. After running the following command line prompt, I still get 2 anonymous volumes in addition to the named volume I created.

docker run -d --name=influxdb-container-test1 -p 8086:8086 -v influxdb-storage-test1:/var/lib/docker/volumes influxdb:2.0 --net=network-test1 --bolt-path /var/lib/docker/volumes/influxdb-storage-test1/bolt/influxd.bolt --engine-path /var/lib/docker/volumes/influxdb-storage-test1/engine

I referenced these 2 links when constructing this command:
1) https://community.influxdata.com/t/where-is-the-docker-data-stored/10108/3
   - See Alessandro_Manfredin's response from 05/2020
   - I am not exactly sure what the --bolt-path and --engine-path flags do, but I believe the bolt and engine items drive needing the additional volumes, I just want them to save under my named volume.
2) https://community.influxdata.com/t/using-influxdb-version-2-i-dont-know-how-to-save-it/31271/2
   - See Anaisdg's response from 08/2023
   - Not sure if I'm specifying the correct file path for my named volume (or the --bolt-path and --engine-path).

Any suggestions?

**Comment by philjb** [comment]
If you run `docker image inspect <image_id_for_influxdb2.0>` you'll see the image defines two volumes.

```
            "Volumes": {
                "/etc/influxdb2": {},
                "/var/lib/influxdb2": {}
            },
```

these are the anonymous volumes. You need to specifically mount those expected paths otherwise it will create two anonymous volumes. See the docs here: https://hub.docker.com/_/influxdb which show in the first example how to specify those volumes (reproduced here):

```
docker run \
    -p 8086:8086 \
    -v "$PWD/data:/var/lib/influxdb2" \
    -v "$PWD/config:/etc/influxdb2" \
    influxdb:2
```



Also, I recommend you use tags `2` or `2.7` or `latest` instead of `2.0` which is quite an old version now.
