### ISSUE TITLE
Where can I find the code of gossip module

### ISSUE THREAD

**Issue by guoxiangCN** [influxdata/influxdb#24917]
Hi~ , A while ago, while reading the code for this project, I discovered a good gossip implementation. Currently, I have found that it can be used out of the box for one of our projects, but it has been removed from the code repository of this project.

May I ask if the implementation part of Gossip belongs to the open source part? If so, where can I find it? If it doesn't belong to the open source part, then let it go~ 
Regards!

**Comment by pauldix** [comment]
That bit is no longer part of our ongoing open source efforts. However, you can find the code (under open source license) under this commit here: https://github.com/influxdata/influxdb/commit/aa458ed1661a9e0ea58e5f999d383c08f8309c36

It's not relevant to what we're doing in this repo so we've since removed it.

**Comment by guoxiangCN** [comment]
Thanks for your reply !
