### ISSUE TITLE
Should not allow retention policy with Replication > number of data nodes

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#2567]
Multiple copies of the same point on the same node accomplishes little other than using up extra disk space. Therefore the replication factor should never exceed the number of data nodes. 

Running a single-node cluster so by definition only one data node. From the CLI ran `> CREATE RETENTION POLICY test_dupe ON mydb DURATION INF REPLICATION 3` and the RP was created without error and happily accepted writes.

**Comment by cboggs** [comment]
Were you able to confirm that Influx was actually writing each point 3 times to that single node? Or maybe I'm misunderstanding your observation.

At first blush I actually think it makes sense for a cluster to accept a RF > data_node_count, as long as the system is able to recognize that when data_node_count is finally >= the RF, the data that was not replicated fully (due to a lack of data nodes) is subsequently replicated appropriately to the new nodes.

It seems like a silly scenario, but I can imagine a situation where a 3-node cluster loses a data node, and while it's being brought back online / replaced, new databases are created with RF=3. If the cluster appropriately removes the failed data node, then the new RF should still be accepted and should accept writes, but should log warnings about replication being incomplete (or something).

Then when that 3rd data node is back online / replaced, whatever data should have been replicated on that node is automatically replicated to it and primacy for the appropriate shards is reassigned.

Then again, I could be unaware of major problems with that line of thinking. :-) That's just how I envision a resilient cluster.

**Comment by beckettsean** [comment]
@cboggs I didn't try to confirm anything about the replication, it just seemed a bit nonsensical. You bring up an interesting edge case, though, where the RF can be temporarily greater than the node count due to a node outage. 

I think, though, that it would be acceptable for the retention policy create statement to error out while there were still only two nodes. Retention policies that have to be created during that downtime can be altered post-node restore. 

The real question is whether the data re-replicates when the RP is updated. I think right now historical data is not re-replicated due to changes but that could be something triggered with a specific command.

**Comment by cboggs** [comment]
Yea that seems pretty reasonable. Creating lots of databases frequently seems like an anti-pattern (or at least a non-pattern), so it's probably not a common enough case to worry about explicitly.

As for the historical replication, that does indeed sound difficult to manage automatically. Having to trigger a 'recovery' operation or something after node replacement would be a good interim fix. Automating it would be ideal though - I'm kind of in love with Elasticsearch's ability to do so. :-)

Thanks for the feedback!

**Comment by toddboom** [comment]
Closing this out since it's no longer applicable.
