### ISSUE TITLE
Make FreeBSD builds part of incremental releases

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#2637]
From https://groups.google.com/d/msgid/influxdb/944ff840-ec33-4399-a17c-6f1e2b20ea18%40googlegroups.com. Thanks to Sebastian Yepes.

FreeBSD port source: https://github.com/syepes/FreeBSD-Ports/tree/master/databases/influxdb
```
# cd /usr/ports/databases/influxdb
# make package
# ls -l work/pkg/influxdb-0.9.0.r30.txz (This is the final binary pkg)                                                                        
-rw-r--r--  1 root  wheel  4364844 May 21 16:27 work/pkg/influxdb-0.9.0.r30.txz
```

**Comment by yvesf** [comment]
I use influxdb on FreeBSD and based my port also on the one from 'cheffo'. In general, I personally don't feel the need for binary packages of influxdb for FreeBSD.
Compared with the port configuration linked from sebastian, I did some changes differently and also went to use it with the ports-mgmt/portshaker tool. One benefit of that is that an file named GID/UID is merged with the main /usr/ports/UID or GID file.

I also updated the git commit id's of the dependences, by just taking the latest commit-id's from master but I think this is the most important point around packaging influxdb. 
While grafana (just as example of another go project), describes it's dependencies using `godep`, in influxdb it's more or less random which version of a dependency is used in the end. I would highly appreciate if the influxdb-repo either use godep or just provides a list of used dependency and their recommended versions.
You find my port here: https://www.xapek.org/git/yvesf/freebsd-ports-influxdb if you want to compare it.

**Comment by kev009** [comment]
One of the benefits of 'upstream' doing builds is the FreeBSD port would be a binary port due to the way go packaging works, with 'upstream' selecting the precise tags of the deps they want for the static go binary.  I haven't looked around to see if that is how other Golang ports are done on FreeBSD, or whether we repeat the build in ports ourselves like the current port does.

Anyway @xmj updated this to 0.9.3 for an evaluation we're doing at @llnw.. https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=202981 and will keep it up to date if things pan out.

**Comment by beckettsean** [comment]
We are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/6454) for all packaging requests, so that we can close this issue until we are ready to work on it.

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
