### ISSUE TITLE
[feature request] Add CAST function

### ISSUE THREAD

**Issue by sudabon** [influxdata/influxdb#2911]
CAST is the function that converts field type in the select query.

For example, if convert from string field 'fieldA' to integer, query is like this:

```
select cast(fieldA AS integer), ...
```

At least, It is preferable to support integer/float/string as conversion type.

**Comment by sudabon** [comment]
I think CAST function is the ideal solution.
But we needed to use sum function for string field of decimal number in 0.9 ASAP.
So I implemented conversion feature in sum function, that converts from string to integer/float implicitly.

https://github.com/sudabon/influxdb/commit/9e8290a8bfbe5354b17428f5c4e329beedcccf95

If you decide not to implement CAST function, I hope you merge this.
When you contact with me, I will send pull request.

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by pjkCochin** [comment]
I am also in dire need of a cast function to run aggregate queries on columns that are strings. Any suggestions?

**Comment by pjkCochin** [comment]
I am also in dire need of a cast function to run aggregate queries on columns that are strings. Any suggestions?

**Comment by zsserg** [comment]
I strongly support either this function or the ability to change field type ( #2651 ). Ideally both of them - would add so much flexibility!
My use case:
I had ifluxdb populated with logstash plugin via use_event_fields_for_data_points option. However, I forgot to set up coerce_values properly, thus logstash sent everything as strings. Now I have no option to fix this except deleting all the stuff and running it from scratch which is not very pleasant option.
