### ISSUE TITLE
Add functionality for ".d" config folder

### ISSUE THREAD

**Issue by ryanwalder** [influxdata/influxdb#3103]
I was wondering if there were plans to support ".d" config files at any point? This would make managing things in config management a little easier in my view (bootstrapping a secure cluster for instance).

**Comment by beckettsean** [comment]
We are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/6454) for all packaging requests, so that we can close this issue until we are ready to work on it.

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
