### ISSUE TITLE
Make previous versions available via homebrew

### ISSUE THREAD

**Issue by vptheron** [influxdata/influxdb#3241]
I would like to downgrade to 0.8.8 while the team is working on fixing 0.9.X, however the current script in Homebrew doesn't provide the option of specifying the version when installing.

Can you please make older versions available? It makes it really hard to automate a server provisioning if the homebrew version is constantly being replaced for the latest one.

**Comment by toddboom** [comment]
@vptheron Old versions of recipes used to be available with `brew versions`, but it looks like they've moved them to their own tap. We can definitely do this, but it probably won't be able to get to it very soon since v0.8.x is being deprecated.

If you want access to the older recipes, you should be able to follow the history here:
https://github.com/Homebrew/homebrew/commits/master/Library/Formula/influxdb.rb

**Comment by beckettsean** [comment]
We are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/6454) for all packaging requests, so that we can close this issue until we are ready to work on it.

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
