### ISSUE TITLE
[Feature Request] More useful timestamps for Aggregation Functions without GROUP BY

### ISSUE THREAD

**Issue by jjfazio** [influxdata/influxdb#3337]
Currently the docs state:  "When performing an aggregation without a GROUP BY clause, the timestamp returned with the aggregated value(s) will be epoch 0 (1970-01-01T00:00:00Z)."

I think it would be nice for the timestamp returned to be more useful. It could either be the lower or upper bound in the WHERE clause. 

For example
```
SELECT SUM(value) AS value FROM temperature WHERE time > now() - 1d;
```

Instead of returning epoch 0 as the timestamp, this could return either (a) the date that now() returns or (b) the date now() - 1d returns. b seems like it would be more useful since you are summing up values starting at that date.

**Comment by pdknsk** [comment]
I agree with this. As is right now, it's very unintuitive. When I first got this result, I considered it a bug.
```
> select min(value) from item
name: item
----------
time                    min
1970-01-01T00:00:00Z    1
```
I think I understand now that the date is basically a fill date, meant to be ignored. Perhaps best not to return any date then.

**Comment by gunnaraasen** [comment]
Seems like there are four options on what the return timestamp should be.

- return no timestamp
- return the timestamp for the beginning of the aggregation period
- return the timestamp for the end of the aggregation period
- return the timestamps for both the beginning and end of the aggregation period (e.g. providing a `time_start` and `time_end`)

Returning only the beginning timestamp for the aggregation seems like the most intuitive and expected result. Thoughts?

**Comment by pdknsk** [comment]
> Returning only the beginning timestamp for the aggregation seems like the most intuitive and expected result.

Not to me. I'd think this is the date (or rather *a* date, perhaps first or last) when this ```min``` value occurred.

**Comment by jjfazio** [comment]
I think it would be nice to have both the time_start and time_end returned.

**Comment by beckettsean** [comment]
Heh, and we have arguments for all behaviors except the one that InfluxDB currently has. At least it's equally disappointing/non-intuitive for everyone!

**return no timestamp**

This is likely not a simple change, since every other `SELECT` query returns a timestamp per data point. It's also unexpected to run a data query on a TSDB and get something back without any associated time.

**return the timestamp for the beginning of the aggregation period**

Probably the simplest change and does give meaningful information. It tells me when the start of my range is, and the end of my time range should be obvious or easily calculated. 

**return the timestamp for the end of the aggregation period**

Most likely equally simple as returning the beginning timestamp, but the end timestamp is less informative. For many queries it would simply be the time at which the query was run. That's not as interesting or informative as the beginning of the range. The beginning of a series timeline is often unknown, but `now()` is pretty well defined.

**return the timestamps for both the beginning and end of the aggregation period (e.g. providing a time_start and time_end)**

The most informative, but probably the most complex to implement, since now we're returning a single data point with two timestamps.

**Comment by gunnaraasen** [comment]
@pdknsk I missed that you used `MIN()` in your example. Definitely agree selector functions like `MIN()` and `MAX()` should return the timestamp of the point.

@jjfazio Seems like `time_end` could be easily calculated from the beginning time if the range of the query is known as @beckettsean mentions above. Is there a case where an app consuming the results would not know the time range of the query?

**Comment by beckettsean** [comment]
@pdknsk @gunnaraasen There's an open issue to have selectors or an extension of selectors return the actual point with timestamp: #1577

**Comment by jsternberg** [comment]
I believe this is implemented in the new query engine. Please try this with 0.13 and tell us if the returned values are different than what you would expect. Thank you.

**Comment by RaW79** [comment]
Hi
sorry for not beeing familiar with github and just beginning with influxdB. But I just found this topic and struggled a lot with the behaviour of the time stamp using aggrate functions within group by. I´m using current version 1.8.3 at a raspberry pi and the returned timestamp is still the time stamp from the beginning of the aggregation period. For Downsampling data from shorterm to longterm database this has a huge impact.
Aggregate functions like sum, integral, mean and also count and so on act from a view from today into the past. Similar like water or electricity meters. Using the time stamp from the past shifts these results into the past and for increasing time period the error also increases. Can you please check if an improvement by also returning the timestamp for the end of the aggregation period can be used?
Thank you very much and best regards,
Ralf
