### ISSUE TITLE
improve debian package deinstallation

### ISSUE THREAD

**Issue by pdknsk** [influxdata/influxdb#3347]
```Bash
$ sudo find / -iname \*influxdb\*
/etc/rc6.d/K20influxdb
/etc/init.d/influxdb
/etc/rc3.d/S20influxdb
/etc/rc2.d/S20influxdb
/etc/rc4.d/S20influxdb
/etc/rc1.d/K20influxdb
/etc/rc0.d/K20influxdb
/etc/rc5.d/S20influxdb
/var/log/influxdb
/var/opt/influxdb
/opt/influxdb

$ ls /opt/influxdb/
influx  influxd  init.sh # broken links
```

**Comment by otoolep** [comment]
You need to purge: `--purge`.

**Comment by pdknsk** [comment]
I did already.

**Comment by otoolep** [comment]
Sending this to the man that knows best.

**Comment by otoolep** [comment]
@rossmcdonald -- happy to discuss this and share what I've learned from trying to solve this issue.

**Comment by beckettsean** [comment]
We are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/6454) for all packaging requests, so that we can close this issue until we are ready to work on it.

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
