### ISSUE TITLE
Fan out continuous queries should support the where clause

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#354]
A continuous query like this:

```sql
select * from foo where col = 'bar' into foo.bar
```

Is a fanout because it doesn't have a group by time clause. Currently, fanouts ignore the where clause. They shouldn't. They should work.

**Comment by pauldix** [comment]
Yes, 0.9.0 will support the where clause and all the operators.

**Comment by jsternberg** [comment]
@jwilder this looks like something we should potentially do when enhancing continuous queries in the future.

**Comment by beckettsean** [comment]
@jsternberg @jwilder I think this can be closed. 

`SELECT * INTO "foo.bar" FROM foo where col = 'bar' GROUP BY *` is perfectly valid and respects the where clause.

It wouldn't be possible to do as a CQ because there's no aggregation function, but this is fairly trivial to script with the CLI. 

If we're already planning to upgrade CQ functionality that's great, but perhaps we can close this for now since there's a workaround.
