### ISSUE TITLE
[feature request] should be able to alter the name of a retention policy

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#3746]
Currently, `ALTER RETENTION POLICY` only affects duration, replication, and default status. The name of the retention policy cannot be changed.

This is a blocking issue for https://github.com/influxdb/influxdb/issues/3733

**Comment by pauldix** [comment]
The RP maps to the underlying file structure so this is probably going to be tricky. I'm moving it to some unknown release since it's a low value feature that could potentially cause big problems.

**Comment by jsternberg** [comment]
I don't think this is possible at the moment. We would need to change the structure to use ids for the disk filesystem rather than using names. Maybe we can talk about this in the future or create some kind of manual tool to modify the meta store, but I don't think there's much demand at the moment for this.
