### ISSUE TITLE
pubsub api

### ISSUE THREAD

**Issue by jvshahid** [influxdata/influxdb#395]
This is just a place holder to discuss api design and internal design of the pubsub layer. Some pointers:

1. [CouchDB's change api](https://wiki.apache.org/couchdb/HTTP_database_API#Changes). Thanks @tisba

**Comment by Cubixmeister** [comment]
HTTP chunked responses should handle this well. For web clients InfluxDB server can return JSONP.
HTTP overhead in this case is really not a concern, headers are sent once per connection.

@schmurfy I don't think that subscribing changes to db would really add overhead to engine. In case of no active subscribers there is no data to be sent/synchronize. In go it could be implemented as simple list of subscribers per series/database. Subscribers could listen on given series or regexp.

**Comment by schmurfy** [comment]
I was not entirely speaking about performance, part of why I think influxdb is really good is that they defined a limited (in a good way) scope and until now kept to it allowing to focus on the core and not utility features that may be useful... or not.

That's my opinion anyway :)

**Comment by davidwdan** [comment]
I think that  [WAMP](wamp.ws) (Web Application Messaging Protocol) is worth looking into.  There is a Go implementation called [Turnpike](https://github.com/jcelliott/turnpike).  
The biggest benefit is that there is a thriving ecosystem of [WAMP libs](http://wamp.ws/implementations/), which would immediately be able to communicate with influx, without any additional work.

**Comment by massimiliano-mantione** [comment]
I'd like this to happen, and I could even give it a try with some help.

First of all I'd like to see how this should be implemented.

I'd distinguish three areas of work:

# The "frontend", or transport

Here I would stick to HTTP, but with bidirectional streaming.
I would imagine a "/subscribe" route (similar to the "/query" one), where an HTTP request to the route would actually create the subscription channel, which could work in one of three ways (we should pick one):

* The old "comet style" of streaming contents on an open HTTP connection
* Web sockets
* The new HTTP 2.0 full duplex streaming mode

In any case, a request on this route should create a "subscription" connection, with a reader and a writer on the server that received the request:

* the reader should be used to accept subscription "commands" (more on that later)
* the writer whould be used to publish the requested data


# The "subscription object"

Each HTTP connection to the "/subscribe" route creates a "subscription" on the server, which is active as long as the HTTP connection is open.

Subscription "commands" (or "requests") received on a subscription channel should look like a query, but (IMHO) without the ability to group, or do other "stateful processing".
In practice they should be pure filters, with operators on the data point properties (the name, tags, and fields).

To be clearer: a subscription should be a predicate on an arbitrary data point.
Data points that pass the predicate should be published, and data points that don't pass it should be ignored.
The client should be able to modify this "predicate" (or filter) writing "commands" on the HTTP channel.


# How the server would process "events" that must be published to subscriptions

This is the thing that made me think the most, and I'd like to know if my understanding of this issue is correct.
Infuxdb, internally, implements a "raft log", and every broker node participates in the raft.
This means (again, please correct me) that every committed data point will also "flow" through the log, through every broker.
And the clients connect to an arbitrary broker to write data points, so we can assume that clients will also subscribe to an arbitrary broker to subscribe to "events" (as described above).

If this is true, it would be "enough" for every broker to process every data point committed to the log in the following "logical" way:

* for every open subscription channel, apply the filter to the data point
* if it passes the filter, write it on the channel

I said "logical" way because this is a nested loop (subscriptions, and then filters), and maybe there is a way to store the filters and the subscriptions that makes this processing faster.
Also, individual subscriptions could be complex logical expressions that *maybe* could be optimized to fail faster (and waste less time) in the most common cases.
Anyway, this "subscription processing" could be asynchronous with respect to the log processing: it could be a goroutine started from the log processing, maybe even on a different physical thread to avoid slowing down the broker log.
What matters is that data points that pass the filter are written (streamed) on the subscription HTTP connection.

An important property of this approach should be that *every* data point that goes into the DB could be published, including those produces by continuous queries.
If my understanding is correct, this would happen because continuous queries push data into the log, which then distributes it to the data nodes (I hope I did not misunderstand this).


# Help I would need to give it a try

First: I am, unfortunately, not committed to this.
It might be useful for me at work but before I am sure that this can "go somewhere" I cannot really spend much time on this.
And I have no go-lang experience at all :-/

That said, *maybe* with a bit of help I could give this a try.

I would mostly need the following:

* a validation that the above reasoning on how to exploit the log is correct, and a pointer to the exact place in the code where this "log tapping" should occur
* an explanation on how to recognize and decode "data point insertion entries" among all the entries that are applied to the log
* some hints on where to "store" the "subscription object" inside the broker, so that both the log code and the http handler can see it: should this stay in the server, the broker or the log...
* if there are multithreading issues and locks involved...
* state your preference between "comet", "web sockets", or "HTTP2" about the way in which the HTTP socket should become a pair of streams

With the above directions, *maybe* I could give this a try and prepare a pull request :-)

And BTW, I'll be away and with no internet for a few days, so I'll not see your (eventual) replies until April 1st (and this is not a joke!).

**Comment by srini-raju** [comment]
+1

**Comment by toddboom** [comment]
There's now a basic pubsub interface that [Kapacitor](https://github.com/influxdata/kapacitor) uses for streaming data. It's likely that any additional work will be built on top of that design, so I'm closing this out for now.

**Comment by acruise** [comment]
Is there any documentation of the interface that Kapacitor is using? :)

**Comment by schmurfy** [comment]
You can get a basic idea by either sniffing (tcpdump, ngrep) what kapactor sends to influxdb but some basic documentation would be nice.

If I remember what I saw correclty you ned to open an udp port and then sends something like this to influxdb:

```
SUBSCRIBE <topic> <udp_port>
```

And after this you will receive every matching line.

PS: I think the syntax is correct but I am not sure if "subscribe" is the correct command name

**Comment by acruise** [comment]
Looks like this is the code responsible? https://github.com/influxdata/influxdb/tree/master/services/subscriber
