### ISSUE TITLE
[feature request] RATE function

### ISSUE THREAD

**Issue by cnelissen** [influxdata/influxdb#3976]
Are there any plans to implement a RATE function or similar functionality? What I need is to be able to calculate the rate for a certain event. For example:

Insert some event data every 1 minute: 
clicks value=100 2015-09-02T22:40:00Z
clicks value=125 2015-09-02T22:41:00Z
clicks value=181 2015-09-02T22:42:00Z
clicks value=112 2015-09-02T22:43:00Z
clicks value=205 2015-09-02T22:44:00Z

Now I want to know clicks per second for every 5 minute interval for the last day:

SELECT RATE(SUM(value)) FROM clicks WHERE time > now() - 1d GROUP BY time(5m)

There were 723 clicks during this 5 minute period, which equates to a click per second rate of 2.41 (723 / 300 seconds)

I see there is a DERIVATIVE function, but that only tells us the difference between the two points, not the data rate.

**Comment by beckettsean** [comment]
@cnelissen the DERIVATIVE function will do this, but you must tell it to provide the rate of change per minute, instead of the default 1 second.

`SELECT DERIVATIVE(value, 1m) FROM clicks WHERE time > now() - 1d GROUP BY time(5m)`

**Comment by beckettsean** [comment]
Actually, nevermind, I just realized I answered a different question. My apologies.

**Comment by jwilder** [comment]
Derivative returns the rate of change between consecutive points.  Try:

```
SELECT DERIVATIVE(SUM(value), 1s) FROM clicks WHERE time > now() - 1d GROUP BY time(5m) fill(0)
```
That calculates the total clicks in 5m buckets and then the rate of change between each bucket normalized to a `1s` rate.  It produces `2.41 clicks/second` for your sample data.

**Comment by matejzero** [comment]
I'm saving network traffic as counter value (not rate, ie StoreRates disabled in collectd). I then want to graph rate in Grafana, but the problem is that grafana changes Group by interval depending on the timespan I select, so that InluxDB returns a sane number of results.
Copied from Grafana:
* Group by time is important, otherwise the query could return many thousands of datapoints that will slow down Grafana
* Leave the group by time field empty for each query and it will be calculated based on time range and pixel width of the graph

The problem is that as the 'group by' changes, so does the calculated rate and I don't always get bytes/s as a result. How can I always calculate bytes/s and only return a limited number of buckets, so that I don't overload the client.

Data in database:
2015-09-11T11:07:40Z	912421510973
2015-09-11T11:07:50Z	912424145320
2015-09-11T11:08:00Z	912426741245
2015-09-11T11:08:10Z	912429581709
2015-09-11T11:08:20Z	912432091575
2015-09-11T11:08:30Z	912434608231
2015-09-11T11:08:40Z	912437174763

What is the right query to get bytes/s out and different size of buckets, based on GROUP BY
SELECT derivative(value,1s) FROM "interface" WHERE "fqdn" = 'graphite' AND time > now() - 1h GROUP BY time(60s)

Why does the upper query returns 2155 arrays, but the same query with 'mean' instead of 'derivative' returns only 720 arrays?

**Comment by matejzero** [comment]
Moved my question to #4081

**Comment by cnelissen** [comment]
Any update on this?

There is a different use case here from DERIVATIVE... A RATE function would take the raw value in a given bucket and divide it by the time that the bucket contains to give you a rate, which has nothing to do with previous values, which is what DERIVATIVE is evaluating.

Hopefully this will demonstrate the difference:

Using DERIVATIVE:
```
2015-09-02T22:40:00Z   value=1000 (derivative: null,    rate: null)
2015-09-02T22:41:00Z   value=1250 (derivative: 250,    rate: 4.16/sec)
2015-09-02T22:42:00Z   value=1810 (derivative: 560,    rate: 9.30/sec)
2015-09-02T22:43:00Z   value=1120 (derivative: -690,   rate: -11.50/sec)
2015-09-02T22:44:00Z   value=2050 (derivative: 930,    rate: 15.50/sec)
```

Using RATE:
```
2015-09-02T22:40:00Z   value=1000 (rate: 16.66/sec)
2015-09-02T22:41:00Z   value=1250 (rate: 20.83/sec)
2015-09-02T22:42:00Z   value=1810 (rate: 30.16/sec)
2015-09-02T22:43:00Z   value=1120 (rate: 18.66/sec)
2015-09-02T22:44:00Z   value=2050 (rate: 34.16/sec)
```


Basically, we are trying to calculate the rate for the whole value, not the rate of change from previous...

**Comment by cnelissen** [comment]
For more background on the use case for the data, many systems have ephemeral counters that get cleared every time you query them, which is what this data would represent - the number of times a certain event has happened since the last time the counter was checked, which we then want to translate into a per second rate.

**Comment by beckettsean** [comment]
@cnelissen you could solve that problem for each specific query with the division operator:

`SELECT value / 60 AS rate_per_sec FROM foo GROUP BY time(1m)`
`SELECT value / 300 AS rate_per_sec FROM foo GROUP BY time(5m)`
`SELECT value / 5 AS rate_per_min FROM foo GROUP BY time(5m)`

**Comment by jsternberg** [comment]
I think @beckettsean is right that this would just be solved by using the division operator normally. I believe we support this with aggregates in the latest release so you can do `SUM(value) / 60` too. If this doesn't work, please comment and I'll reopen the issue.

**Comment by Carbenium** [comment]
@jsternberg The solution offered by @beckettsean would be feature complete if the division operator would support time literals or there would be some kind of cast to seconds at least.
This would make integration into Grafana easier since their time interval variable only supports substitution as literals.

**Comment by Laugenbrezel** [comment]
I agree with @Carbenium, this would make life w/ Grafana way easier.
Also the fact that there is a direct connection between the calculation and the "GROUP BY" makes a good point for this RATE function, I think.

**Comment by Carbenium** [comment]
Any comments from the developers?

**Comment by kruegge** [comment]
Can we make a new feature request by @Carbenium 

> The solution offered by @beckettsean would be feature complete if the division operator would support time literals.
> This would make integration into Grafana easier since their time interval variable only supports substitution as literals.

**Comment by jsternberg** [comment]
What's meant by this?

> would be feature complete if the division operator would support time literals or there would be some kind of cast to seconds at least

Do you mean being able to do something like `value / 5m` and have the `5m` converted to nanoseconds? Or maybe something like `value / (5m / 1s)` if you wanted that converted to seconds?

**Comment by kruegge** [comment]
@jsternberg 

I can speak only for myself. I have in example a ratecount for requestsPerSecond and in aggregation of time like 5m i want also the requestsPerSecond in this grouped interval.
I save my data only every 1 minute.

for 1 minute aggregation currently i can use this:
`SELECT sum(requestsPerSecond) / 1 FROM "measurement" WHERE time >= now() - 1h GROUP BY time(1m), host`
or this
`SELECT sum(requestsPerSecond) FROM "measurement" WHERE time >= now() - 1h GROUP BY time(1m), host`

but for higher intervals like 5m i must use
`SELECT sum(requestsPerSecond) / 5 FROM "measurement" WHERE time >= now() - 1h GROUP BY time(5m), host`

for me i want to add time literals like this
`SELECT sum(requestsPerSecond) / (5m / 1m) FROM "measurement" WHERE time >= now() - 1h GROUP BY time(5m), host`
or this
`SELECT sum(requestsPerSecond) / (5m : 1m) FROM "measurement" WHERE time >= now() - 1h GROUP BY time(5m), host`

i don't know how the query builder interpret this, but what i want is to calculate the rate per second. In my measurements i have this ony only in 1minute aggregation available, so i can define the min aggregation format.

another example to understand:
When i save my measurements every 10s, then i can write this
`SELECT sum(requestsPerSecond) / (5m / 10s) FROM "measurement" WHERE time >= now() - 1h GROUP BY time(1m), host`

So you know what i mean or is this a useless feature for you?

**Comment by jsternberg** [comment]
I don't think it's useless. I'm just trying to think if that math makes sense or if it's going to lead to trouble in the future. I think that math would be consistent with how we currently treat durations and I think that math works when it's done in some other places within the query.

**Comment by Carbenium** [comment]
@jsternberg 
> Or maybe something like value / (5m / 1s) if you wanted that converted to seconds?

This would fit our needs.

**Comment by mathieulongtin** [comment]
+1. I was trying to do what scaleToSeconds does in Graphite. 

http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.scaleToSeconds

**Comment by edio** [comment]
Just in case: grafana now provides `$__interval_ms` variable for this kind of arithmetic expressions.

**Comment by sciurus** [comment]
Although what currently exists works, it's pretty cumbersome to always have to write queries like `SELECT sum("count")  / $__interval_ms * 1000` in order to get rates that are displayed correctly no matter what timerange in Grafana you're looking at.

**Comment by cout** [comment]
Scaling by `1 / $__interval_ms * 1000` is not the same as scaling using the sample interval; `$__interval_ms` is the interval used for aggregating data points for display.  If you zoom out, `$__interval_ms` increases.

Ideally one would scale by `1 / sample_interval` (e.g. if you sample bytes transferred every 5 seconds, then dividing by 5 gives you bytes per second).  This assumes 1) that you know the sample rate and 2) that the sample rate is consistent enough that dividing by a constant is acceptable.  Ideally one would scale each sample by the time elapsed since the last sample; doing so yields a rate while by independent of the sample interval.

The closest influxql expression I have found (using grafana) that yields the correct result independent of scale / time range is:

```
SELECT derivative(cumulative_sum(sum("value")), 1s) FROM ... AND $timeFilter GROUP BY time($__interval), ... fill(none);
```

This mostly fits my needs (an influxql equivalent of graphite's `scaleToSeconds`, as mentioned in https://github.com/influxdata/influxdb/issues/3976#issuecomment-305886898).

If your metrics are stored as cumulative values, you can use `derivative()` which will yield a rate in the appropriate units.  If your metrics are stored as the difference since the previous sample, then it is necessary to apply a function which is effectively the inverse of the difference function.  This is what the query above does.

I think an alternative is to use [`aggregate.rate`](https://docs.influxdata.com/flux/v0/stdlib/experimental/aggregate/rate/) in flux, but  we have a lot of legacy queries that still use influxql.
