### ISSUE TITLE
[feature request] RENAME FIELD

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4156]
From https://github.com/influxdb/influxdb/issues/828#issuecomment-83224779

e.g. `RENAME FIELD foo TO bar ON measurement`

Would have to update all CQs, too.

**Comment by bbinet** [comment]
+1, this would actually be useful

**Comment by curio77** [comment]
+1

**Comment by gylu** [comment]
+1

**Comment by leesjensen** [comment]
Consider the case where I am downsampling data to another database using a back reference.

`SELECT MEAN(*) INTO "db_history"."autogen".:MEASUREMENT FROM /.*/ WHERE time <= now()-10d GROUP BY time(1h)`

The field that was previously named `value` will now be `mean_value`. This makes it even harder to create dashboards since the field name is always different.

Alternatively it would be even better to just not generate a name but allow a 'AS' operator on the select.

`SELECT MEAN(*) AS "value" INTO "db_history"."autogen".:MEASUREMENT FROM /.*/ WHERE time <= now()-10d GROUP BY time(1h)`

**Comment by clemensvonschwerin** [comment]
What about fields with multiple types?

In my opinion allowing something like
``RENAME FIELD foo::float TO bar ON measurement``
would be a cool addition, which could also help a lot if actually only one type was intended but the ambiguity was introduced by default.

**Comment by bcutter** [comment]
Please reopen as it's not been implemented. Thanks.

https://github.com/influxdata/influxdb/issues/828#issuecomment-1013723202

**Comment by blueForestIcarus** [comment]
mind numbing lack of basic functionality
