### ISSUE TITLE
[0.9.3] dropping a db caused influxd to panic and die

### ISSUE THREAD

**Issue by zirpu** [influxdata/influxdb#4162]
The panic:

```
[http] 2015/09/18 15:13:55 10.13.1.226 - - [18/Sep/2015:15:13:55 +0000] POST /write?consistency=&db=telegraf&precision=s&rp= HTTP/1.1 204 0 - InfluxDBClient e0d6f7b1-5e17-11e5-8c1d-000000000000 10.34673ms
panic: assignment to entry in nil map

goroutine 6141 [running]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).partition(0xc20807e700, 0xc218f1c000, 0x40, 0x7e00, 0xc20d7d3b00)
	/root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:710 +0x28e
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).pointsToPartitions(0xc20807e700, 0xc212679000, 0xb6, 0x100, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:491 +0x110
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).WritePoints(0xc20807e700, 0xc212679000, 0xb6, 0x100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:243 +0x2b0
github.com/influxdb/influxdb/tsdb/engine/bz1.(*Engine).WritePoints(0xc2087710c0, 0xc212679000, 0xb6, 0x100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:210 +0xc3
github.com/influxdb/influxdb/tsdb.(*Shard).WritePoints(0xc20897c240, 0xc212679000, 0xb6, 0x100, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:212 +0x595
github.com/influxdb/influxdb/tsdb.(*Store).WriteToShard(0xc208034a90, 0x4, 0xc212679000, 0xb6, 0x100, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/store.go:303 +0xf7
github.com/influxdb/influxdb/cluster.func·002(0x4, 0x1, 0xc212679000, 0xb6, 0x100)
	/root/go/src/github.com/influxdb/influxdb/cluster/points_writer.go:241 +0xfc
created by github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard
	/root/go/src/github.com/influxdb/influxdb/cluster/points_writer.go:271 +0x30b

goroutine 1 [chan receive, 22 minutes]:
main.(*Main).Run(0xc2080620c0, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:91 +0x777
main.main()
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0xdc

goroutine 6 [syscall, 24 minutes]:
os/signal.loop()
	/root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, 24 minutes, locked to thread]:
runtime.goexit()
	/root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [IO wait, 24 minutes]:
net.(*pollDesc).Wait(0xc2080104c0, 0x72, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080104c0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010460, 0x0, 0x7f22bad50e30, 0xc2080e6000)
	/root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080371a0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2080371a0, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc2080d4960, 0x7f22bad52350, 0xc2080371a0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x57
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:313 +0x8f2

goroutine 9 [chan receive, 24 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc2080371a8, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc2080d4ab0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/meta/store.go:2058 +0x64
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc2080105b0)
	/root/go/src/github.com/hashicorp/raft/net_transport.go:346 +0x50
created by github.com/hashicorp/raft.NewNetworkTransport
	/root/go/src/github.com/hashicorp/raft/net_transport.go:138 +0x2c4
```

**Comment by beckettsean** [comment]
@zirpu is it possible there were points in the WAL waiting to flush to the database that was deleted?

**Comment by beckettsean** [comment]
Also, what version of InfluxDB are you running and how was it installed?

**Comment by zirpu** [comment]
Using 0.9.3 installed via the debian package on ubuntu 14.04 amd64.

**Comment by zirpu** [comment]
It was an active database for 'telegraf'.  I didn't see anything in the docs about a way to either rename or quiescent the db, so I just tried dropping it.

**Comment by tsailiming** [comment]
I had to killed mine before the drop succeeded. 

On InfluxDB starting, version 0.9.4.1, branch 0.9.4, commit c4f85f8

[query] 2015/09/19 03:01:42 DROP DATABASE data
[wal] 2015/09/19 03:01:43 write to index of partition 1 took 1.050638457s
[monitor] 2015/09/19 03:01:50 failed to store statistics: timeout
[monitor] 2015/09/19 03:02:02 failed to store statistics: timeout
[monitor] 2015/09/19 03:02:12 failed to store statistics: timeout
[monitor] 2015/09/19 03:02:20 failed to store statistics: timeout
[monitor] 2015/09/19 03:02:31 failed to store statistics: timeout
[monitor] 2015/09/19 03:02:40 failed to store statistics: timeout
[monitor] 2015/09/19 03:02:52 failed to store statistics: timeout
[monitor] 2015/09/19 03:03:02 failed to store statistics: timeout
[monitor] 2015/09/19 03:03:10 failed to store statistics: timeout
[monitor] 2015/09/19 03:03:21 failed to store statistics: timeout
[monitor] 2015/09/19 03:03:32 failed to store statistics: timeout
[monitor] 2015/09/19 03:03:40 failed to store statistics: timeout
[retention] 2015/09/19 03:03:45 retention policy enforcement check commencing
[retention] 2015/09/19 03:03:45 retention policy shard deletion check commencing
[monitor] 2015/09/19 03:03:51 failed to store statistics: timeout
[wal] 2015/09/19 03:03:55 Flushing 2 measurements and 3 series to index
[wal] 2015/09/19 03:03:55 Metadata flush took 12.464655ms
[monitor] 2015/09/19 03:04:03 failed to store statistics: timeout
[monitor] 2015/09/19 03:04:11 failed to store statistics: timeout
[monitor] 2015/09/19 03:04:21 failed to store statistics: timeout
[monitor] 2015/09/19 03:04:30 failed to store statistics: timeout
[run] 2015/09/19 03:04:37 Signal received, initializing clean shutdown...
[run] 2015/09/19 03:04:37 Waiting for clean shutdown...
[tcp] 2015/09/19 03:04:37 cluster service accept error: network connection closed
[shard-precreation] 2015/09/19 03:04:37 Precreation service terminating
[snapshot] 2015/09/19 03:04:37 snapshot listener closed
[copier] 2015/09/19 03:04:37 copier listener closed
[continuous_querier] 2015/09/19 03:04:37 continuous query service terminating
[retention] 2015/09/19 03:04:37 retention policy enforcement terminating
[monitor] 2015/09/19 03:04:37 shutting down monitor system
[run] 2015/09/19 03:04:38 second signal received, initializing hard shutdown
2015/09/19 03:04:42 InfluxDB starting, version 0.9.4.1, branch 0.9.4, commit c4f85f84765e27bfb5e58630d0dea38adeacf543
2015/09/19 03:04:42 Go version go1.5, GOMAXPROCS set to 2
2015/09/19 03:04:42 Using configuration at: /etc/opt/influxdb/influxdb.conf
[metastore] 2015/09/19 03:04:42 Using data dir: /var/opt/influxdb/meta
[metastore] 2015/09/19 03:04:42 Node at localhost:8088 [Follower]
[metastore] 2015/09/19 03:04:42 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
[metastore] 2015/09/19 03:04:44 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[monitor] 2015/09/19 03:04:44 Starting monitor system
[metastore] 2015/09/19 03:04:44 Updated node id=1 hostname=localhost:8088
[monitor] 2015/09/19 03:04:44 'build' registered for diagnostics monitoring
[monitor] 2015/09/19 03:04:44 'runtime' registered for diagnostics monitoring
[monitor] 2015/09/19 03:04:44 'network' registered for diagnostics monitoring
[monitor] 2015/09/19 03:04:44 'system' registered for diagnostics monitoring
[store] 2015/09/19 03:04:44 Using data dir: /var/opt/influxdb/data
[monitor] 2015/09/19 03:04:44 Storing statistics in database '_internal' retention policy '', at interval 10s
[wal] 2015/09/19 03:04:44 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/09/19 03:04:44 WAL writing to /var/opt/influxdb/wal/_internal/monitor/1
[wal] 2015/09/19 03:04:44 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/09/19 03:04:44 WAL writing to /var/opt/influxdb/wal/data/default/6
[wal] 2015/09/19 03:04:44 reading WAL files to flush to index
[wal] 2015/09/19 03:04:44 writing 109 series from WAL file /var/opt/influxdb/wal/data/default/6/01.000003.wal to index
[wal] 2015/09/19 03:04:44 writing 863 series from WAL file /var/opt/influxdb/wal/data/default/6/01.000005.wal to index
[handoff] 2015/09/19 03:04:45 Starting hinted handoff service
[handoff] 2015/09/19 03:04:45 Using data dir: /var/opt/influxdb/hh
[tcp] 2015/09/19 03:04:45 Starting cluster service
[shard-precreation] 2015/09/19 03:04:45 Starting precreation service with check interval of 10m0s, advance period of 30m0s
[snapshot] 2015/09/19 03:04:45 Starting snapshot service
[copier] 2015/09/19 03:04:45 Starting copier service
[admin] 2015/09/19 03:04:45 Starting admin service
[admin] 2015/09/19 03:04:45 Listening on HTTP: [::]:8083
[continuous_querier] 2015/09/19 03:04:45 Starting continuous query service
[httpd] 2015/09/19 03:04:45 Starting HTTP service
[httpd] 2015/09/19 03:04:45 Authentication enabled: false
[httpd] 2015/09/19 03:04:45 Listening on HTTP: [::]:8086
[retention] 2015/09/19 03:04:45 Starting retention policy enforcement service with check interval of 30m0s
[run] 2015/09/19 03:04:45 Listening for signals
2015/09/19 03:04:45 Sending anonymous usage statistics to m.influxdb.com
[query] 2015/09/19 03:04:47 DROP DATABASE data
[http] 2015/09/19 03:04:47 ::1 - - [19/Sep/2015:03:04:47 +0800] GET /query?pretty=true&db=data&q=drop%20database%20data HTTP/1.1 200 37 - curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.15.3 zlib/1.2.3 libidn/1.18 libssh2/1.4.2 214cd5de-5e38-11e5-8001-000000000000 19.348012ms
[wal] 2015/09/19 03:05:00 Flush due to idle. Flushing 5 series with 5 points and 265 bytes from partition 1
[wal] 2015/09/19 03:05:00 write to index of partition 1 took 30.138189ms
[wal] 2015/09/19 03:05:10 Flush due to idle. Flushing 8 series with 8 points and 469 bytes from partition 1
[wal] 2015/09/19 03:05:11 write to index of partition 1 took 8.990403ms
[wal] 2015/09/19 03:05:20 Flush due to idle. Flushing 8 series with 8 points and 469 bytes from partition 1
[wal] 2015/09/19 03:05:20 write to index of partition 1 took 29.102237ms
[wal] 2015/09/19 03:05:30 Flush due to idle. Flushing 8 series with 8 points and 469 bytes from partition 1
[wal] 2015/09/19 03:05:30 write to index of partition 1 took 20.684772ms
[wal] 2015/09/19 03:05:40 Flush due to idle. Flushing 8 series with 8 points and 469 bytes from partition 1
[wal] 2015/09/19 03:05:40 write to index of partition 1 took 15.37875ms

**Comment by jwilder** [comment]
Not reproducible in `0.10`.
