### ISSUE TITLE
[feature request] DROP MEASUREMENT should accept regex

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4275]
e.g. `DROP MEASUREMENT /^foo/` should drop all measurements starting with "foo".

**Comment by beckettsean** [comment]
related to https://github.com/influxdb/influxdb/issues/4351

@dgnorton not sure if it makes sense to tackle both at once, probably not. However, once we support SHOW with regex, it's natural to want DROP with regex.

**Comment by huhongbo** [comment]
#4501 has support show measurement ,how about drop support?

**Comment by beckettsean** [comment]
@huhongbo that PR only addressed the `SHOW MEASUREMENT` command.

**Comment by vchekan** [comment]
It would be nice to have a "dry-run" modifier for DROP command.

**Comment by bentatham** [comment]
+1

**Comment by bentatham** [comment]
As a workaround (for others that might need this now), I did this (to delete all measurements starting with ``spinach``:
```bash
influx --execute 'show measurements' --database=db | grep "^spinach" | xargs -I{} influx --database=db --execute 'drop measurement "{}"'
```
Not particularly efficient of course, but gets the job done.

**Comment by jwilder** [comment]
This is currently supported via `delete from /^foo/`.  A `delete from` without any filter criteria works the same as a `drop measurement`.

**Comment by Baiteman** [comment]
I do not recommend the previous suggestion when a lot of data is affected. Turns out it is a quick way to max out your machine's ram (~from 2 to 13 GB in half a minute xD)

**Comment by ninjarocketman** [comment]
Also `delete` does not drop the series from the index. So deleting data with `delete` can lead to a polluted index. Regex support for `drop measurement` would be great to fully clean data.

**Comment by AvinKumar** [comment]
Any updates on this feature.? I am in badly need a fix. In my case lot of junk measurements got created and I'm struggling to delete them. I also tried the suggestion given by bentatham but that didn't work too.

influx --database='mydb' -host 'localhost' -port '8086' -username 'test' -password 'test' --execute 'show measurements' | grep "^java" | xargs -I{} influx --database='mydb' -host 'localhost' -port '8086' -username 'test' -password 'test' --execute 'drop measurement "{}"'

**Comment by TattiQ** [comment]
@AvinKumar why didn't it work? what did you see exactly when running this command? 

I used to run  

 influx --execute 'show measurements' --database=db | grep "^measurement_name-*" | head -20 | xargs -I{} influx --database=db --execute 'drop measurement "{}"'  

I deleted the data in portions since full compaction kicked and this is a resource intensive process. 

```Full Compactions - Full compactions run when a shard has become cold for writes for long time, or when deletes have occurred on the shard. Full compactions produce an optimal set of TSM files and include all optimizations from Level and Index Optimization compactions. Once a shard is fully compacted, no other compactions will run on it unless new writes or deletes are stored. ```

**Comment by TattiQ** [comment]
of course I agree that it's time to optimize influx for deletions and make it possible to drop measurements using regex. It's pretty easy to get a situation where a lot of them are created by some code and this needs to be handled somehow

**Comment by dmoebius** [comment]
In [this SO post](https://stackoverflow.com/questions/38587898/in-influxdb-how-to-delete-all-measurements/38647418) someone mentions that `DROP SERIES` supports regexps. I cannot find this in the official v1.6 docs. Is it true? 
What's the difference between `DROP MEASUREMENT` and `DROP SERIES`?!?

**Comment by AvinKumar** [comment]
Hi Tatyana,
I am extremely sorry for late reply, somehow I missed your mail.

In my case multiple junk measurements were created like the ones shown
below.

Caused by: javax.servlet.jsp.JspTagException: Digest mismatch
java.lang.IndexOutOfBoundsException: Index: 1
... 91 more
TotalStackTree: java.lang.IllegalArgumentException: Illegal string value
\'job_listing\'A=0\'.  Legal values are \'none\'

I tried deleting them the way you have given but with no luck.
Influx Command:
$influx -host localhost -username admin -password pass -port 8086 --execute
'show measurements' --database=analytics | grep "^Caused*" | head -20 |
xargs -I{} influx -host localhost -username admin -password pass -port 8086
--database=analytics --execute 'drop measurement "{}"'

I get no error in the console.

Am I missing something here.?

-Avin

**Comment by reloxx13** [comment]
> In [this SO post](https://stackoverflow.com/questions/38587898/in-influxdb-how-to-delete-all-measurements/38647418) someone mentions that `DROP SERIES` supports regexps. I cannot find this in the official v1.6 docs. Is it true?
> What's the difference between `DROP MEASUREMENT` and `DROP SERIES`?!?

Can confirm drop series accept regex

used
`drop series from /^*\.POWER/`

**Comment by rsaim** [comment]
+1 for this feature.

**Comment by mnachmia31** [comment]
+1 for adding this feature

**Comment by fabide** [comment]
+1 for this feature

**Comment by louisoutin** [comment]
+1 for this feature

**Comment by boshng95** [comment]
+1 for this feature
