### ISSUE TITLE
PERCENTILE(value,0) does not work, returns null instead of MIN value

### ISSUE THREAD

**Issue by hughescr** [influxdata/influxdb#4418]
percentile(value,0) is just returning null while min(value) is returning a value

```
> select percentile(HUM,0),min(HUM) from station where time >= '2015-10-11' and time < '2015-10-12' group by time(6h)
name: station
-------------
time            percentile  min
1444521600000000000         49
1444543200000000000         90
1444564800000000000         78
1444586400000000000         54
```

**Comment by hughescr** [comment]
Running 87d99fb built from source using go get

**Comment by beckettsean** [comment]
Same behavior in 0.9.4.2

**Comment by beckettsean** [comment]
repro on 0.9.5 in https://github.com/influxdata/influxdb/issues/4724

**Comment by jsternberg** [comment]
It looks like we have an off-by-one problem with every percentile. Wolfram alpha tells me the 50th percentile of a 10 value slice should be the 5th value (4th index) ([here](http://www.wolframalpha.com/input/?i=50th+percentile+0,+1,+2,+3,+4,+5,+6,+7,+8,+9)) and it tells me the 51st percentile should be the 6th value (5th index) ([here](http://www.wolframalpha.com/input/?i=51st+percentile+0,+1,+2,+3,+4,+5,+6,+7,+8,+9)).

This ends up applying to the 0th percentile because it gets told it should access the 0th value (-1th index) and we exit if we get an invalid value like that. It looks like it's due to how the rounding and floor are being done. The rounding appears to be that it should round down on 0.5 rather than up and we currently always take the floor rather than attempting to round.

I'm going to double check this since I'm not the most familiar with percentiles.

**Comment by hughescr** [comment]
Not sure how the other percentiles should work (round up vs round down vs round to nearest), but 0th percentile should be the MIN, and 100th percentile should be the MAX, always.

**Comment by rbetts** [comment]
We provide MIN. We require a percentile value greater than 0 or return null.
