### ISSUE TITLE
[feature request] Be able to rename Measurements created with CQ wild card

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/influxdb#4775]
Given a query:

```
CREATE CONTINUOUS QUERY bar ON telegraf BEGIN 
  SELECT sum(value) AS "sum" INTO "telegraf"."derived".:MEASUREMENT FROM "telegraf"."default"./.*/ GROUP BY time(5m), *
 END
```

It would be nice to be able to add additional information to the `:MEASUREMENT` name such as changing measurement `cpu` to `1h_cpu`

**Comment by beckettsean** [comment]
I'd say this is a requirement for the feature, since measurements exist on all RPs in a database whether populated or not. There's little chance of keeping things sane if `raw.foo` is the raw points but `5m.foo` is the 5 minute rollups, since the field keys are not scoped to the retention policy. 

`SELECT * FROM raw.foo` would show the fields for the downsampled points, `SELECT * FROM 5m.foo` would show the fields from the raw points. 


I made this CQ on the telegraf database:

`CREATE CONTINUOUS QUERY tg1 ON telegraf BEGIN SELECT mean(value), max(value), min(value) INTO \"telegraf\".\"foobar\".:MEASUREMENT FROM \"telegraf\".\"default\"./cpu.*/ GROUP BY time(5m), * END`

selecting from the two RPs shows that `value` exists on the `foobar` RP query, and `mean`, `max` and `min` exist now on the `default` query.

```
#curl -iG 'http://localhost:8086/query?db=telegraf&pretty=true&rp=foobar' --data-urlencode 'q=select * from cpu_usage_guest where time > now() - 1m'
HTTP/1.1 200 OK
Content-Type: application/json
Request-Id: 31253967-899d-11e5-83c6-000000000000
X-Influxdb-Version: 0.9.5-nightly-ebb9172
Date: Fri, 13 Nov 2015 00:26:33 GMT
Transfer-Encoding: chunked

{
    "results": [
        {
            "series": [
                {
                    "name": "cpu_usage_guest",
                    "columns": [
                        "time",
                        "cpu",
                        "host",
                        "max",
                        "mean",
                        "min",
                        "value"
                    ],
                    "values": [
                        [
                            "2015-11-13T00:25:40Z",
                            "cpu0",
                            "sean-0.9.5",
                            null,
                            null,
                            null,
                            0
                        ],
```

**Comment by jackzampolin** [comment]
The only workaround for this is rollup the measurements into a different database:

```
CREATE CONTINUOUS QUERY bar ON telegraf BEGIN 
  SELECT sum(value) AS "sum" INTO "telegraf_derived"."default".:MEASUREMENT FROM "telegraf"."default"./.*/ GROUP BY time(5m), *
 END
```

**Comment by bwhaley** [comment]
Per @jackzampolin this should answer my question in #4793, that is I should be able to create a CQ that will rollup all the fields in all the series for all the measurements on a given DB. How does this feature do that? It seems like all the field keys across different measurements would have to match. I can't do something like `select mean(*)` because that doesn't make sense, but otherwise the field keys have to match across measurements.

**Comment by beckettsean** [comment]
https://github.com/influxdb/influxdb/issues/4823 might solve the problem of wildcard fields inside functions.

**Comment by epcim** [comment]
Still no solution.
As mentioned, workarounds:
- another database ( but then you need pre-created retention policies).
- additional retention policies

Assume from the input data you want to rollup hourly,daily,weekly,monthly,yearly aggregates and monthly/yearly you want to keep for a decade. That lead's to 5 another databases with aggregated data. Or creation of  5 retention policies.
