### ISSUE TITLE
Write stats on each query to _internal database

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#4898]
We should write the time each query takes into the internal database, and set the value of the point to the query.

**Comment by pauldix** [comment]
This shouldn't be on by default. Otherwise there's potential to blow up the amount of data being written. For instance if they're doing hundreds of queries per second.

It would be better to sample the queries and only write the worst performers in some interval of time. For instance, we could write at most one sample per second and track the queries and write out the worst performer in each second.

**Comment by otoolep** [comment]
Yeah, I was wondering about that. However, a load of hundreds of points/second is nothing compared to the ingest rate of an engine capable of 10000s points/sec. Each query would result in 1 point into the _internal database, but no more. I will say that the monitor system might need to batch though, to ensure decent indexing rates.

If we have to go to a sampling technique, and only write the worst performers for a given internal, then this is significantly more work than simply logging stats about each query.

**Comment by gunnaraasen** [comment]
Query stats would be very useful for debugging performance problems and having all query completion times would be more useful than just the worst performers.

For instance, if only the slowest queries are logged, there could be a relatively inexpensive query running every second that taxes the system but is overshadowed by a longer-running or distributed query. Both queries would be targets for optimization, but if only the slowest queries were reported you'd never know about the faster query running once a second.

Configuring the query string to be set as a tag and the completion time as the value could be useful for tracking query performance as a database grows (vs setting the query string as a field).

Being able to configure and disable query logging would be necessary.

**Comment by pauldix** [comment]
I think having it configurable and off by default makes it ok to log every query. I agree that having all of the data is preferable, but at some point it's not tractable.

Having the query string as a tag is problematic. Since there are so many variables and potentially different queries, the cardinality of that tag could be VERY high, which would take up a ton of memory.

It's safer to have it as a field. Over time as we expand the functionality of the query engine, that'll work well. It just means that when you query that data you'd be doing a range scan across the time range you're looking at, which is fine for this use case.

**Comment by otoolep** [comment]
Agreed, query strings need to be fields since they could vary way too much.

I was thinking about tags for stuff like "aggregate" vs. "raw" queries etc, but I'm not sure how helpful that would be. Of course tags will be used for, say, the hostname on which the query was first received, which is useful in cluster scenarios.

**Comment by beckettsean** [comment]
I love this idea. Tags that could be on the measurement:
 - User agent submitting the query
 - target database for the query
 - target retention policy for the query (if given)
 - precision of the query 
 - username provided for authentication
 - parent node of the query?
 
Basically all of the GET string parameters plus the UA, plus the originating node in clusters (not sure if this is meaningful, just speculating.) This will allow us to recreate the entire query history from the database, if the query logging is on. 

Since tags might get expensive for RAM and for writing, I think there could be two levels of query logging. The first (INFO) just logs two fields, the query string and the runtime, with no tags at all. The second (DEBUG) records the UA, GET string, and cluster/node details as tags.

**Comment by kfitzpatrick** [comment]
I would really like my customers to be able to get a list of the top N queries that are spending a long time running. Included I would like queries that have been running for more than a second (with the assumption that they are going to keep running). 

The use case I'm imagining is that you're working with influx and you're generally not getting the performance you'd expect. You'd be able to look and see "hey, is there anything here that has been running for a long time or any queries which have been historically slow?"

**Comment by lagergren** [comment]
This would be an excellent aid to us. It doesn't matter if it's on by default, but it would certainly make our world a lot simpler and I think seal the deal for InfluxDB migration for our production monitoring systems. Also the other stuff in the thread would be very helpful.

With query timings in stats we get pretty much all the visibility that we need for our proof of concept project.

**Comment by lagergren** [comment]
And the more detailed query stats we can get, the better.

**Comment by lagergren** [comment]
Hi guys, I take it this didn't get into 0.9.6.1?

**Comment by pauldix** [comment]
@lagergren it didn't, but we have it tagged for the next release so it should make it into a nightly at some point in the next 3-4 weeks.

**Comment by lagergren** [comment]
Excellent. When is the next release scheduled and is the code in yet? 
/Regards Marcus

**Comment by lagergren** [comment]
Oops, didn't mean to unassign you and can't figure out how to reassign.

**Comment by lagergren** [comment]
I really wanted this for 0.10.0. Awww

**Comment by e-dard** [comment]
I feel like we solved most of this with the slow query logging feature we introduced.
