### ISSUE TITLE
[0.9.5] Out of Memory errors when loading grafana dashboard

### ISSUE THREAD

**Issue by JonathanKnight** [influxdata/influxdb#4922]
When the grafana dashboard requests data from Influx the process crashes with OOM errors. This is using exactly the same data and dashboard as 0.9.3 which was OK. The server memory used spikes as the queries come in from the dashboard. I have experimented with larger machine memory but I have seen the same behaviour - all the memory is used before the process crashes.

**Comment by giovtorres** [comment]
+1

**Comment by dtouzeau** [comment]
I think this issue is the same for #4919 , this is not a graphana specific topic but related to the InfluxDB  engine itself... 
By testing in multiple environements you have to multiply by 1.2 the memory consumption according database size.
Database Size: 1GB = 1.2GB memory used.
Database Size: 5GB = 6GB memory used.
Database Size: 10GB = 12GB memory used.

Seems infux load the whole data in memory....

**Comment by tomeucapo** [comment]
Hi, have the same behavior on my Influx 0.9.5.1-1. 

Have a 3 databases with this sizes:

1,4G    ./internal_metrics
3,7G    ./ace_hotel
6,4G    ./rosetta

And only have 6GB of RAM. Now still swapping and consumes 100% CPU, but is correct this behavior? My databases increase daily, because have +40 hosts with +100 metrics per second. Have 2000 req/sec than generate +2000 writes/sec into Influxdb.

**Comment by dtouzeau** [comment]
This issue was seen from 0.9.0 to the newest version we expect that the 0.9.6 with tsm engine will reduce significantly the memory consumption.
We ask in the #4919 it there are some tips to decrease
It seems it depends of the number of TAGS used in database

**Comment by beckettsean** [comment]
@dtouzeau and everyone else, there are two entirely different RAM usage issues going on.

The first is that because InfluxDB `mmap`'s the shard files, it appears to take all available RAM on the box. However, when another process requests that RAM, InfluxDB will release it to the OS. That should never lead to OOM errors. However, for all versions of 0.9 to date, the system will happily take all available RAM, up to a bit over the total data size, if that much RAM is available.

The second issue, and the one that can and does lead to OOM issues, is that the inverted in-RAM index requires exponentially more RAM as the number of series grows. This is why [series cardinality](https://influxdb.com/docs/v0.9/concepts/glossary.html#series-cardinality) is a concern. A database with 10k series will need just a few hundred MB for the index, if that. A database with 100k series will need ~4GB of RAM, perhaps. One with 1 million series will need 16GB of RAM. A database with 10 million series will be happiest with 64GB or more. 

So, there's nothing odd about InfluxDB "consuming" all available RAM on start, that's what `mmap` does.

However, if you are seeing OOM issues, it's either a poorly crafted query or too many series for the index to live in RAM. For a poor query, just restrict the time range or find some other method to return fewer points. For too may series, the only current solution is to increase the RAM or to drop a number of series to make the index smaller.

**Comment by jsternberg** [comment]
There have been many improvements in terms of memory performance since 0.9.5. I'm going to close this. Please open a new issue if you still experience out of memory errors with the latest version. Thanks.
