### ISSUE TITLE
Poor error message on query with clauses out of order

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#4957]
```
> select count(value) from cpu_usage_guest group by time(1d)
ERR: error parsing query: aggregate functions with GROUP BY time require a WHERE time clause
```

Makes sense, we want to prevent people from having too many buckets in a `GROUP BY` query. 

So, hit the Up arrow and add a `WHERE time` clause:

```
> select count(value) from cpu_usage_guest group by time(1d) where time > 0
ERR: error parsing query: aggregate functions with GROUP BY time require a WHERE time clause
```

Same error, although clearly I now have a `WHERE time` clause.

The error should be something more like 

`ERR: error parsing query: WHERE time clause must occur before GROUP BY time clause`

Or, maybe we can remove the restriction that the clauses have to be in a particular order?

**Comment by rossmcdonald** [comment]
Still occurs on `0.10.0`:

```
> select count(usage_user) from telegraf."default".cpu group by time(10s) where time > now() - 30s
ERR: error parsing query: aggregate functions with GROUP BY time require a WHERE time clause
```

**Comment by jsternberg** [comment]
This still happens in 0.13. I'm going to leave this unassigned and we'll try to improve the error message either before 1.0 if we have time or post-1.0 since changing the error message wouldn't be a breaking change anyway.

**Comment by hkrizek** [comment]
Please add it at least to documentation.
There isn't any note about _ERR: error parsing query: aggregate functions with GROUP BY time require a WHERE time clause_ on "https://docs.influxdata.com/influxdb/v1.1/query_language/spec/"

**Comment by jsternberg** [comment]
The error message appears to be more correct for this. We should still work on improving error messages in general, but I think that's an IFQL project rather than InfluxQL.

The current error message is this: `ERR: error parsing query: found WHERE, expected ; at line 1, char 61`

This is a typical error message when an invalid identifier is found. I think this was likely fixed when we started properly checking for the semi-colon when separating multiple queries since the error message refers to a required semi-colon.
