### ISSUE TITLE
[repo] Add support for Alpine Linux

### ISSUE THREAD

**Issue by stevepacker** [influxdata/influxdb#4997]
Per your [blog entry](https://influxdb.com/blog/2015/12/04/introducing_repos_influxdata.html), I'd like to request [Alpine Linux](https://pkgs.alpinelinux.org/packages) as another repo.  Alpine Linux has become a popular linux distribution for minimal #docker images.

http://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package

**Comment by rossmcdonald** [comment]
Thanks, @stevepacker! I'll add that to the list of distributions to add support for.

**Comment by rmg** [comment]
The published binaries don't seem to work, but if you build the binaries yourself with `./build.py --arch=amd64 --platform=linux` the binaries appear to "just work".

**Comment by beckettsean** [comment]
We are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/6454) for all packaging requests, so that we can close this issue until we are ready to work on it.

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
