### ISSUE TITLE
[ 0.9.6-nightly-43a4201] Minor bug in time clause

### ISSUE THREAD

**Issue by ivanscattergood** [influxdata/influxdb#5009]
Hi, 
I am trying to find the timestamp of the first value in a series, so I have been using 

Select value from metric order by time asc limit 1

I have had serious performance problems, and a couple of times the database crashed. So I have started to put a time limit on the query. 

Select value from metric where time > now() - 30d order by time asc limit 1
This seems to work much better, but I did notice that 
time > now() -30d 

i.e. no space before the time operator returns no rows or an error message.

**Comment by otoolep** [comment]
This may be a parser issue, the code to examine is here: https://github.com/influxdb/influxdb/tree/master/influxql

**Comment by srhopkins** [comment]
I found what is [causing the behavior](https://github.com/influxdb/influxdb/blob/54ff1990bda4091b3b9227efefd3a641d6c4f4de/influxql/scanner.go#l207-l216) but I'm not sure of an elegant solution. I think there needs to be some additional logic in the parser to scan ahead for multiple non-tokens?

**Comment by ivanscattergood** [comment]
I was assuming that you would throw query parser error.  Something that tells the user its expecting a space.

**Comment by ivanscattergood** [comment]
I have just tried it against the 0.9.6 and it if I run the query without the space, I get no results and also it blocks writes (this is using the bz1 engine)

**Comment by nitishagar** [comment]
I would like to help on this. I see the file `scanner.go` - `scanNumber()` being pointed out for the place where number parsing is done.

Any other place where I should look at.

**Comment by otoolep** [comment]
@nitishagar -- all code that builds the abstract syntax tree is performed inside the `influxql` package. That is definitely the place to look, and I would be surprised if the fix wasn't in there.

If you want to understand more about how the package works, I suggest you read this article:

https://blog.gopheracademy.com/advent-2014/parsers-lexers/

**Comment by edwkar** [comment]
Hi!

I've taken a look into this, and I'd be glad to try at a fix, assuming @nitishagar isn't still on it. (If so, let me know.)

AFAICS, the issue boils down to the `parseFill` function (https://github.com/influxdata/influxdb/blob/master/influxql/parser.go#L2013), which apparently swallows expressions that do not match the expected `fill(...)` format. `parseFill` only does a single `unscan` when it encounters a non-`fill(...)`-expression, although such an expression may consist of an arbitrary number of tokens. In particular, it will `unscan` the subsequent whitespace token in cases such as @ivanscattergood's, and thus happily continue parsing.

One simple fix is to rewrite `parseFill` so that it *first* checks whether the next token is an IDENT with the literal value "fill", and then either backs out at once if not, or continues with parsing a `fill(...)` expression, returning a parse error if it fails. If a fix like that sounds OK, I would be happy to give it a try. (Another would be to add an option to save the state of the scanner before the `parseExpr` call.)

P.S.: I haven't looked for (possible) similar cases other places in the parser code. And, thank you for an awesome piece of software.

**Comment by nitishagar** [comment]
@edwkar You can go ahead with this. Somehow I didn't receive notification for the last 2 mentions and also was occupied with stuff at work. I look at picking up smoother item :)

**Comment by jsternberg** [comment]
This seems to now correctly report an error during parsing. I'm going to close this issue since it seems to be fixed in 0.13.
