### ISSUE TITLE
[feature/visibility] - Grafana template based on _internal

### ISSUE THREAD

**Issue by JulienChampseix** [influxdata/influxdb#5045]
Hi team,

For help us to follow our influxdb usage, diagnostics performance issue or trouble, that will be good if you could share with us a default grafana dashboard (json) based only on _internal for cluster mode and single node mode.

By this way we could provide you more details/screenshot in case of crash / trouble when raising an issue.

Thanks,
Julien.

**Comment by JulienChampseix** [comment]
(cc @otoolep @mjdesa )

**Comment by JulienChampseix** [comment]
sorry to be pushy on it but i think that could be usefull for all influxdb users :+1:

**Comment by mjdesa** [comment]
@JulienChampseix making a grafana dashboard might be a bit odd. However we may be able to put this information somewhere in the admin ui. Would that suffice?

**Comment by JulienChampseix** [comment]
@mjdesa that will be really usefull, by this way we'll keep the flexibility to interprete data stored into _internal directly with grafana and cross them with other datas from other datasources.
Maybe you share a gist exposing an grafana dashboard (json format) exposing usefull _internal datas

**Comment by supershal** [comment]
+1

**Comment by jpereira** [comment]
+1

**Comment by medvedik** [comment]
+1

**Comment by medvedik** [comment]
Here is the minimalistic version and don't forget to substitute or create "datasource": "internal" with yours.
[dashboard_internal.txt](https://github.com/influxdata/influxdb/files/248755/dashboard_internal.txt)

**Comment by ZhukovAlexey** [comment]
There's a dashboard available on grafana.net:
https://grafana.net/dashboards/317

It based on Internal InfluxDB metrics pulled from telegraf.

I haven't checked it, but I like the way it goes: Official Telegraf plugin which gets all internal information from _internal InfluxDB database (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/influxdb)

And it would be good to have an official Grafana dashboard which uses this data.

It's very important to make an official dashboard because there're a lot of internal metrics and its interpretation should be the same by all users and developers.

Bu think this feature won't be implemented by developers because of Influx Enterprise which has this in embryo but for money.

**Comment by qli-aa** [comment]
Any updates ?
