### ISSUE TITLE
[repo] Allow mirroring with RSYNC

### ISSUE THREAD

**Issue by ianare** [influxdata/influxdb#5066]
Our influxdb servers do not have Internet access, we rely on mirroring all needed packages ourselves.

It would be nice to use RSYNC for this, especially since this would minimize everyone's bandwidth usage. Right now we are forced to use wGET.

Thanks!

**Comment by beckettsean** [comment]
We are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/6454) for all packaging requests, so that we can close this issue until we are ready to work on it.

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
