### ISSUE TITLE
What about less accurate but more efficient percentile calculation?

### ISSUE THREAD

**Issue by tisba** [influxdata/influxdb#513]
I was wondering, what your opinion is about offering a less accurate, but way more efficient method for percentile calculation.

AFAIK influx currently calculates percentiles in a naive way. There are more efficient (and **way** faster approaches) to do this ([t-DIGESTS](https://github.com/tdunning/t-digest/blob/master/docs/t-digest-paper/histo.pdf) used in [Elasticsearch]( http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-aggregation.html#_percentiles_are_usually_approximate) e.g.). If you have many events, distributed over your cluster, then it might be nice to offer the user a way to trace accuracy for speed.

I have to deal with millions of events that I'd like to run percentile (actually I calculate entire percentile ranges) calculations over. The performance is okay-isch right now, but not very good for an interactive use case.

**Comment by seiflotfy** [comment]
I am looking through the right place in the code to implement it.
Also I am considering adding some new SQL statement like in Redshift: SELECT APPROXIMATE DISTINCT(COUNT(<field>)) ... Which implements a hyperloglog++. Should be faster

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
