### ISSUE TITLE
Ubuntu Trusty package should use upstart

### ISSUE THREAD

**Issue by johnl** [influxdata/influxdb#5209]
the Ubuntu Trusty package should use upstart to manage the process - that would allow upstart to handle restarting influxdb when it crashes. It currently just uses a basic initscript, which means there is no process supervision.

More recent Ubuntu (and Debian?) releases are going systemd of course, but Ubuntu Trusty is here for a few years yet, so I think it's worth the effort.

**Comment by francisdb** [comment]
+1 I guess this not-restarting issue is not there when using 15.10 (systemd)

**Comment by beckettsean** [comment]
We are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/6454) for all packaging requests, so that we can close this issue until we are ready to work on it.

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by hraftery** [comment]
+1 Wasted an hour figuring out the best way to respawn influxdb.
