### ISSUE TITLE
[0.9.6.1] cannot add single backslash at the end of a tag value

### ISSUE THREAD

**Issue by undera** [influxdata/influxdb#5231]
I'm using InfluxDB 0.9.6.1 on Ubuntu. Sending line with tag that has backslash at the end of its value is failing with 'unable to parse'.

Line that I write:

```
t440753,label=http://a.b.c/path/?separator\=\ value=1178 1448432542
```

The documentation says that backslashes should not be escaped: https://influxdb.com/docs/v0.9/write_protocols/write_syntax.html#escaping-characters

**Comment by beckettsean** [comment]
In this case the backslash is escaping the following space character. That ends up making `value=1178` part of the tag section, so the parsing fails.

It parses if there are two spaces there, but there's no way to get a single backslash at the end of the tag value:

```
> insert trailing_backslash,foo=ends-with-\  value=42
> insert trailing_backslash,foo=ends-with-\\  value=42
> insert trailing_backslash,foo=ends-with-\\\  value=42
> select * from trailing_backslash
name: trailing_backslash
------------------------
time			foo		value
1451331477814160860	ends-with- 	42
1451331480056996716	ends-with-\\	42
1451331482776764944	ends-with-\\ 	42
```

**Comment by undera** [comment]
I understand what happens and why, it's pretty obvious. Either docs should explicitly state this as a limitation, or parser should somehow allow ending tag value with backslash.

**Comment by beckettsean** [comment]
@undera I was documenting this for the eventual bug fixer. This is a parser bug that should be repaired.

**Comment by e-dard** [comment]
@beckettsean this seems like a very tricky thing to fix in the parser because it would involve determining if the parser is still looking at the measurement/tags or has moved onto the fields.

```
insert cpu\ value=1
```

It's not clear if the above is a measurement called `cpu\` with a single field `value=1`, or if it's the beginning of the following point:

```
insert cpu\ value=1 value=2
```

as in, a measurement name with a space in it `cpu value=1`, and a single field `value=2`.

Because the parser parses points in one pass I think it might be impossible to determine if one wants to insert an escaped space `\ `, or a literal backslash `\` and then some fields.

I'm assuming to fix this would require a change to the rules around escaping.

**Comment by beckettsean** [comment]
@e-dard that makes a lot of sense. I'd be quite happy to simply declare trailing backslashes illegal for identifiers.

**Comment by jpazsedano** [comment]
@bekettsean I think it would be even better forcing to escape backlashes. I mean, there's a reason why every parser that accept special characters makes mandatory to escape backslashes, and it's avoiding this kind of ambiguity.

If the rules about escaping have to be changed, that's the one to change. Forbiding a character that is widely used in potential data sources for influxdb is not a good idea because using them or not is not always decided by the admin or developer. For example I'm getting disk data usage through SNMP, and the way to differenciate between disks is by using a description tag that is not decided by me or anyone who cares about influxdb and its parsing rules.

By the way, looks like the parsing also fails even if the next character is not a whitespace. I have a telegraf datasource and this in the log:
`unable to parse 'Disk\\ usage,Disk=D:\\,agent_host=dservib01,host=dgrafana01.cyii.corp total=0i,used=0i 1487811930000000000': invalid tag format`

That's the telegraf log, that escapes backlsashes, so the actual input to influxdb is:
`Disk\ usage,Disk=D:\,agent_host=dservib01,host=dgrafana01.cyii.corp total=0i,used=0i 1487811930000000000`

And the parser is failing with it.
