### ISSUE TITLE
0.9.5.1 - Influxdb swaps and eventually killed on downsampling large amount of data

### ISSUE THREAD

**Issue by mhiller** [influxdata/influxdb#5321]
We're relatively new to influxdb and coming from a proprietary in house time series solution so forgive me if i use the wrong terms.

We have an application that can create upwards of 1 million events on a busy day . this is currently fed through telegraf to give a count and flushed every 10s to a single measure. the underlying  data schema has five tags which can change based on a given event. (so some uniqueness is here)

so we have 
app -> telegraf(10s) -> influxdb

when i do something like:
SELECT count(value) from measure WHERE time > now() - 7d GROUP BY time(10s) ORDER BY time desc (which logically should return ~65kpts from the series)

it ends up taking an exceedingly long time and eating through the swap and eventually getting killed off by the system.

the box is 4 core VM (2g cores) w/ 8gig of ram.

What is recommended as a possible solution ? 
If you need more info please let me know.

killed by system due to eating through swap
Jan  8 15:07:15  kernel: Out of memory: Kill process 59998 (influxd) score 949 or sacrifice child
Jan  8 15:07:15 kernel: Killed process 59998 (influxd) total-vm:12044148kB, anon-rss:7402388kB, file-rss:0kB

**Comment by mhiller** [comment]
even grouping by 1 minute  (which should yield 10,080) seem to get influxdb nuked after eating into swap abot 80% of the time. CPU doesn't reallyget impacted by this operation however

**Comment by mhiller** [comment]
upgrading to 0.9.6.1 and still having the same issue.

**Comment by beckettsean** [comment]
@mhiller it seems likely that the query is simply too resource intensive for the available RAM. 

> (which logically should return ~65kpts from the series)

Regardless of how many data points are returned, all the points matching the query have to be read from disk. If you are writing ~1 million points per day, then any query spanning seven days must pull all seven million points off disk in order to `COUNT` them. That's a fairly large number of points to query at once. 

Try narrowing your time range to a few days, or raising the RAM on the box to 16GB.

I don't see evidence of a bug so I'm going to close the issue.

**Comment by kostko** [comment]
> Regardless of how many data points are returned, all the points matching the query have to be read from disk. If you are writing ~1 million points per day, then any query spanning seven days must pull all seven million points off disk in order to COUNT them. That's a fairly large number of points to query at once.

But they shouldn't all be loaded into memory if they just need to be counted (for example)? Shouldn't they just be streamed from disk and discarded from memory if they are not needed? It can take a long time to read them, but the InfluxDB process should not just run out of memory due to needlessly loading all data into memory? It is a different story if you want do do aggregations like MEDIAN, where you need all the points that go into the same bucket. But for aggregation functions which can be computed incrementally, such queries should not cause OOM. Or am I missing something here?

**Comment by beckettsean** [comment]
@kostko the current query engine is extremely naive and does no optimization based on the functions to be applied. The engine is being refactored to make it easier to address these performance optimizations. It should work the way you describe, and it soon will, but right now that's not how it behaves.

**Comment by mhiller** [comment]
I disagree with this being closed. it clearly at a minimum an undesirable behavior. A single select query should not tank sql engine. Especially in a production app that is (potentially) client facing. I see about 15 other references to this issue between the google group matching this description so this is not single instnace.  Maybe a memory limit per query is required ? or 'fill or kill' logic is required ?

If this is addressed in some fashion in 0.10.0 ill test this there when the release candidate comes out.

**Comment by beckettsean** [comment]
@mhiller there are open issues for being able to kill a query and to limit the points returned. I don't see a reason to leave this one open in addition. No one is saying this is desirable behavior, it's just a rough edge that isn't yet fixed.
