### ISSUE TITLE
[Feature Request] Allow for Nested aggregate in TOP

### ISSUE THREAD

**Issue by mvadu** [influxdata/influxdb#5345]
Adding onto #1821 and #3930 
Currently TOP does not support nested functions. My use case is to have a `Top(Sum(<field>),1)` or `Top(Percentile(<field>,90),1)` to show a worst performing transaction. Can we have a new feature on TOP to accept and work on the output of another aggregate function? 

It should honor all the group conditions, so below query should give me worst performing transactions be each hour.

`SELECT top(percentile(ResponseTime,90),1) FROM "Application_Transaction_Metrics" WHERE "State" =~ /California$/ AND time > 1452623400s and time < now() GROUP BY time(1h), "State", BusinessTransaction`

**Comment by beckettsean** [comment]
This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
