### ISSUE TITLE
shard group does not exist error

### ISSUE THREAD

**Issue by Isaacpm** [influxdata/influxdb#5408]
Hi,
As requested in the influxdb group, here you have the listing of the directory from the affected server:
total 20
drwxr-x--- 5 influxdb influxdb 4096 Jan 20 11:06 .
drwxrwxrwx 8 influxdb influxdb 4096 Jan 11 15:15 ..
drwx------ 3 influxdb influxdb 4096 Jan 19 10:02 capacity_all
drwx------ 3 influxdb influxdb 4096 Jan  6 13:55 _internal
drwx------ 3 influxdb influxdb 4096 Jan 20 11:06 oracle_db_data

Any more info you need, just let me know and I'll get it to you asap.

Thanks,
Isaac

**Comment by Isaacpm** [comment]
It may look ok, I think it got recreated again after the restart as the script pushing data into the DB continued running and I could see new data. But not the old one.

**Comment by jwilder** [comment]
I'm not sure what this issue is referring to as there is not enough context provided in the description.  

Please take a look at [contributing bug reports](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#bug-reports) and provide more context to help us understand this issue better.
