### ISSUE TITLE
[0.10.0-beta1] CQ being scheduled and executed despite DROP CQ

### ISSUE THREAD

**Issue by zstyblik** [influxdata/influxdb#5417]
Hello,

this is most likely related to https://github.com/influxdata/influxdb/issues/5415. CQ is being scheduled over and over again despite the fact I've dropped it. Also, no other CQs are being scheduled even the new ones.

```
[continuous_querier] 2016/01/21 12:43:02 executing continuous query cq_net_1s (2016-01-21 08:31:20 +0000 UTC to 2016-01-21 08:31:30 +0000 UTC)
[continuous_querier] 2016/01/21 12:45:17 executing continuous query cq_net_1s (2016-01-21 08:31:10 +0000 UTC to 2016-01-21 08:31:20 +0000 UTC)
[continuous_querier] 2016/01/21 12:47:29 executing continuous query cq_net_1s (2016-01-21 08:31:00 +0000 UTC to 2016-01-21 08:31:10 +0000 UTC
```

**Comment by mjdesa** [comment]
@zstyblik what's the output of `show continuous queries`?

**Comment by zstyblik** [comment]
@mjdesa it was empty. no CQs.

**Comment by zstyblik** [comment]
@mjdesa couldn't there be some kind of race condition or interruption of CQ stop-n-drop when too many CQs are dropped at once or very fast consecutive order eg. via script?

**Comment by normanuber** [comment]
Has this been reproduced because it is happened to me. Looks like the CQ was scheduled before my drop command and ran. It attempted to run once after my drop command so it is not too big of a deal.

2016/02/02 00:30:18 InfluxDB starting, version 0.10.0.n1454054436, branch master, commit 834744a4c30e7f06a7c5fa8d0376de0d1930a318, built 2016-01-29T08:01:49.344780
2016/02/02 00:30:18 Go version go1.4.3, GOMAXPROCS set to 24

[query] 2016/02/02 00:47:15 DROP CONTINUOUS QUERY ten_sec_res ON network

[continuous_querier] 2016/02/02 00:49:11 error executing query: CREATE CONTINUOUS QUERY ten_sec_res ON network BEGIN SELECT mean(value) AS value INTO network.ten_sec.:MEASUREMENT FROM network."default"./.*/ GROUP BY time(10s), * fill(previous) END: err = retention policy not found: ten_sec

**Comment by beckettsean** [comment]
There appears to be a race condition where the CQ can run once after being dropped, if it was already scheduled before the drop executes. That doesn't strike me as terrible or even unexpected behavior, as long as it doesn't continue running.

**Comment by zstyblik** [comment]
@beckettsean, in the original description of this issue, CQ in question has been executed at least three times after dropped.

**Comment by beckettsean** [comment]
@zstyblik agreed, but that's on InfluxDB 0.10, which had a completely different query engine than InfluxDB 0.11+. We aren't patching InfluxDB 0.10, so unless there's a repro on 0.13 the issue is moot.

**Comment by zstyblik** [comment]
oki.
