### ISSUE TITLE
RPM package creates superfluous symlink

### ISSUE THREAD

**Issue by dennisjac** [influxdata/influxdb#5424]
I just installed the latest RPM package in my Fedora system and during the installation I got this output:
```
...
Created symlink from /etc/systemd/system/influxd.service to /usr/lib/systemd/system/influxdb.service.
...
```
This symlink should not be created at all since systemd will pick up the service file in /usr/lib/systemd/system/influxdb.service already. With the symlink I now have two services "influxd" and "influxdb" of which one is actually a reference to the other which is just wrong and only creates unnecessary confusion.

**Comment by rossmcdonald** [comment]
@dennisjac Those symlinks are created by systemd itself when installing the unit file, which declares an [alias](https://github.com/influxdata/influxdb/blob/master/scripts/influxdb.service#L21). We declare the alias `influxd` to avoid confusion since the daemon itself is `influxd`, however the database is commonly referred to as `influxdb`. There is still only one service, though, and we are only utilizing systemd's built-in functionality. I'd be happy to change it (or accept a PR) if this is considered a bad practice, though.
