### ISSUE TITLE
Relocating data (or creating continuous queries) using the INTO clause hangs when a mathematical expression is used in the SELECT clause

### ISSUE THREAD

**Issue by matthewmcneely** [influxdata/influxdb#5448]
```
$ uname -a
Linux ubuntu-hub-asus 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
```
InfluxDB starting, version 0.9.6.1, branch 0.9.6, commit 6d3a8603cfdaf1a141779ed88b093dcc5c528e5e, built 2015-12-10T23:40:23+0000
```
* Prebuilt package

### Test case
```
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE foo"
curl -i -XPOST "http://localhost:8086/write?db=foo" --data-binary @units.txt
```
Then in the influx shell (the select statement hangs):
```
use foo
select (1.0-(sum(defects)/sum(units))) into quality from production where time >= 1453753817000000000 and time <= 1453757342000000000 group by time(10m) fill(1)"
```

Explicitly adding an **AS** declaration is the workaround.

select (1.0-(sum(defects)/sum(units))) **as value** into quality from production where time >= 1453753817000000000 and time <= 1453757342000000000 group by time(10m) fill(1)"

Contents of units.txt
```
production units=1 1453753817000000000
production defects=1 1453753860000000000
```

**Comment by matthewmcneely** [comment]
Also note that I found this problem when constructing a continuous query with a similar structure. What's interesting here is that while the query to construct the CQ did in fact error (shown in the log file), it seemed to cause other issues, most notably a ton of "failed to store statistics: timeout" errors in the log. And a general slowdown in the responsiveness of the daemon in general.

**Comment by jsternberg** [comment]
I believe we fixed this at some point. It was caused by binary expressions not having a default time. If you are still using the older version, you can get around this by using aliasing (`AS colname`). If you upgrade to a newer version, we now have a default name for this kind of field and the `SELECT INTO` statement won't hang forever.

Thanks for reporting this issue. I'm sorry we weren't able to respond sooner and we are trying to improve our response time on issues.
