### ISSUE TITLE
[0.11.0] Limit Queries Slow With GROUP BY

### ISSUE THREAD

**Issue by ChromoX** [influxdata/influxdb#5553]
`SELECT cpu_usage FROM cluster GROUP BY name ORDER BY time DESC LIMIT 1`

I feel like the above query is something relatively common to want out of a time series database. When I run this query it seems like it has to load every series in it's entirety before then limiting at 1. I have 3000 series in my DB and this query takes longer the more history my series have.

Another note is that it seems that the above query is single threaded. My servers CPU sits around 116% occasionally bursting to 600%.

**Comment by samhatchett** [comment]
+1
this seems like a regression from 0.9.x; I remember this sort of query being blazing fast before 0.10

In my case I wish to fetch the point just prior to a particular timestamp - so my workaround for now is to add a `< time and > time` clause and query in 1-day chunks to iteratively find it. If the data is pretty dense, then the point is usually within a day so this ends up being pretty fast. But it is certainly a hack to make up for the engine's slowness in this case.

**Comment by samhatchett** [comment]
also, this type of query will sometimes kill the process if the system RAM is too low, so may be related to #5343

**Comment by larsonmpdx** [comment]
I've benchmarked this query on a clean database with a single float series, using influxdb 10.1. the time to complete seems to scale linearly with series length.  I'm getting about 100ms per 60k entries

**Comment by ChromoX** [comment]
@larsonmpdx When you were doing testing did each of your series have one field? I would assume that in the current configuration it would scale by O(n * f) where n is series length and f is number of fields. Regardless I would figure that with this being a common use case it should be optimized so that it doesn't have to read a whole series + fields just to be able to give you the last value.

**Comment by larsonmpdx** [comment]
one field, "value" (float) only

I agree that it's a common case for a time series database.  In my use case any query over 500ms or is failing (should feel immediate-ish), so that's only 300k elements.  Most series in my application will top out around a few million elements, so we need maybe a 10x speedup.  I imagine it will get better with the new query engine, if 0.9.x was faster

**Comment by jwilder** [comment]
The new query engine is in master now.  @larsonmpdx are you able to test one of the nightly builds?

**Comment by larsonmpdx** [comment]
sure, I'll let you know how it goes, thanks

**Comment by larsonmpdx** [comment]
ok.  nightly worked with the same dataset.  I'm now getting 25ms per 100k records.  I haven't tested scaling over a wide range but it still seems linear.  definitely a big step in the right direction

**Comment by larsonmpdx** [comment]
this isn't perfectly comparable, because it hasn't been running as long, but memory use is down by about 4x as well

**Comment by larsonmpdx** [comment]
I just checked the newest nightly - this is still running in linear time with respect to series length (I also checked a last()-based query, same story).  getting this in constant time would be killer, otherwise my application will probably have to store most recent values in a separate database

**Comment by jsternberg** [comment]
@larsonmpdx can you try again with 0.11.0? A bugfix to `ORDER BY desc` went into 0.11.0 a couple of hours before the release.

**Comment by larsonmpdx** [comment]
hi, just saw this

0.11.0 took a sample query from about 5s (the 10.beta thing I was on) to 3.5s (011.0).  Another good improvement.  I still think it won't be useful unless there's a shortcut of some kind added that takes this down to linear time - but I haven't studied your database enough to know how feasible that is.

I have stopped using this type of query, instead I give a time window like @samhatchett suggested.  That puts a cap on execution time.

**Comment by larsonmpdx** [comment]
sorry - meant constant time

**Comment by jsternberg** [comment]
Ah, I see what the issue is. Limit queries that have a `GROUP BY` or multiple sources, the limit iterator goes through all of the points and discards a lot of them.

The problem is that the limit query is a limit per group rather than the number of points in general, so it has to churn through all of the points to know all of the groups at the moment. I'll change the name of the issue and see if there's a way we can improve the timing on this kind of query.

For now, the best way is to limit the time period so it doesn't have to go through as many points (as you mentioned that you're doing).
