### ISSUE TITLE
Question: Limiting the size of memory use

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [influxdata/influxdb#5587]
Wanted to know how to limit size of the RAM influxdb can use, then it start using Memory Mapped IO (disk) for additional space? We have huge data set, but users shall be running influxdb in limited capacity laptops.

**Comment by rossmcdonald** [comment]
@gopalakrishnan-subramani There is currently no method for controlling InfluxDB's memory usage. Running out of memory is a pretty common issue when using expensive queries, so I'd recommend your users exercise caution when attempting to query results over a large dataset. 

That being said, the `tsm` storage engine (default with `0.10.0`) is extremely memory efficient, and we have been seeing much less issues with memory since the release. You may still see issues if attempting to run queries over a large number of series on underpowered machines, though. Also if performance is not critical for your use-case, then you can also utilize swap space to prevent InfluxDB from triggering the system's OOM-killer. You can also disable [Linux's memory overcommit settings](http://serverfault.com/questions/141988/avoid-linux-out-of-memory-application-teardown) if needed.

Regulating memory use will also be a target of development with the next few releases, so we should start to see improvements in this area relatively soon.
