### ISSUE TITLE
[0.11.0] Implicit upper bound on time in queries causes OOM

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/influxdb#5636]
Version information:

```
InfluxDB v0.11.0.n1455177634 (git: master 8d7a4a9accba0ace785218a1d8fcc36540f4bca4, built 2016-02-11T08:02:04.633643)
```

On a small instance of InfluxDB (single core, 1GB RAM), the following query causes the process to run out of memory:

```
SELECT max(req) - min(req) FROM _internal.monitor.httpd WHERE time > now() - 1m GROUP BY time(10s)
```

Where the total size of the InfluxDB data directory is roughly:

```
sudo du -hs /var/lib/influxdb/
644K	/var/lib/influxdb/
```

I'm well aware of issues with memory utilization in InfluxDB, but this seems to be a little strange considering: 
- the latest query engine refactor
- the system was sitting idle with 800MB of free memory prior to the crash
- The size of the entire data directory (including meta and wal) is less than 1MB

Full stack trace here: https://gist.github.com/rossmcdonald/bf5ec89da2b199813e7f

**Comment by jwilder** [comment]
@jsternberg @benbjohnson

**Comment by jsternberg** [comment]
This is an issue with fill and lacking a top bounds. I'll look into why as the default end time should be now, but adding `AND time <= now()` causes it to return correctly.

**Comment by jsternberg** [comment]
This seems to be because inside of `tsdb/query_executor.go` the now time is calculated and that time is not transferred to the select call in the case of an implicit upper bound.

I'm working on how to refactor the code in a way that makes sense. It's easy to add a new parameter to just pass in that time, but I don't feel that's the best way to tackle the problem at the moment.
