### ISSUE TITLE
[0.10.1] Few issues while stress testing (OOM kill/random crashes/memory unbound queries/cluster inconsistencies)

### ISSUE THREAD

**Issue by madushan1000** [influxdata/influxdb#5827]
Hi,
I'm stress testing influxdb for our production use. And I noticed the following issues. Plese, tell me if they are actually issues with influxdb or my configuration.
### My setup

Influxdb cluster with three meta nodes and two data nodes. two 4vCPU/15GB gcloud instances for data nodes and one 1vCPU/1.7GB gcolud instance for the additional meta node. With this (https://gist.github.com/madushan1000/d826f688387051a6ec1a) influxdb config.
### My test

A node script(using [node-influx](https://github.com/node-influx/node-influx)) writes 10000 data points (batched) to a one measurement with two-day default retention policy. Each write is 10 seconds apart (6 writes a minute). Each point has 16 fields, 2 tags and a timestamp with nanosecond precision. 
### Issues

1.) Out of memory crash 
After starting with an empty database the whole cluster crashed (except meta only node) after about 450 inserts (~1.5 hours). It seems to be an out of memory kill. (host influx-1 log: https://gist.github.com/madushan1000/934c90aee290f42299a7, host influx-2 log: https://gist.github.com/madushan1000/934c90aee290f42299a7 ). Db size if about ~5.5GB.

2.) Secondary/Standby data node randomly crashes without any apparent reason. CPU usage goes up a few minutes before the crash. There is no cause in the logs either (A log of such crash and a start: https://gist.github.com/madushan1000/4ccabb6f3230f5f1a370). This happened when writing 10000 points each 1 second. Nothing happens to the Primary/Master server.

3.) `select count(field) from mymeasurement` queries(or any other aggregation query) cause the server to crash when the measurement has a large number of data points(~ 73172 \* 10000 when I ran the query)

4.) When I drop a measurement or a series in one data node (With a retention policy with replication set to 2), It's not correctly propagated to the other nodes. 
Ex. 
- I have 30000 points in `mymeasurement`. Both nodes show that I have 30000 points. 
- I drop `mymeasurement` on data node 1 (`drop measurement mymeasurement`. Using the influx client). Data node 1 shows I have 0 points. Data node 2 shows I have 30000 points.
- I insert a point to `mymeasurement` on data node 1 (Using the node client). Data node 1 shows I have 1 point. Data node 2 shows I have 30001 points.
- Points are counted using `select count(...`

**Comment by rossmcdonald** [comment]
@madushan1000 Regarding your issues:

1. What is the [series cardinality](https://docs.influxdata.com/influxdb/v0.10/concepts/glossary/#series-cardinality) of the data you are writing into InfluxDB? The series cardinality is directly correlated to memory usage and performance. InfluxDB's memory management is not great in the current version, but, in my experience, in order to run out of memory that fast you must be running on very limited hardware or using tags with a very high cardinality.

2. I'm not sure what the issue could be here. Can you enable `cluster-tracing` to see if that provides more information?

3. InfluxDB does not have a robust method for handling memory in the current iteration, so unbounded queries will be very taxing on the system, potentially triggering OOMs. The next release (0.11) has a refactored query engine that should greatly improve performance and memory management in this regard.

4. This is fixed with https://github.com/influxdata/influxdb/issues/5573, and will be in the 0.11 release.

**Comment by madushan1000** [comment]
1) I have two tags `appId` and `host`. appId has about 10000 different values, host has 100 different values. series cardinality should be 10000 * 100 = 1e6. 
2) I'll try to do a test with cluster tracing on.

**Comment by jwilder** [comment]
Closing since 0.10 is no longer maintained and clustering was removed in 0.12.
