### ISSUE TITLE
[0.10.1] Influx CLI Now Shows Times as Integers

### ISSUE THREAD

**Issue by s1m0** [influxdata/influxdb#5888]
Since upgrading to 0.10.1, queries using the CLI (influx) return results with the time as an integer - 10, 13,16 or 19 digits, depending on the setting of 'precision'. Previous versions (I'm not sure when the behaviour changed) would output the full timestamp in human-readable format (e.g. "2016-02-29T23:59:59Z"). This might be linked to #4065 in which case, the change was in 0.9.5.

The full timestamp is much more user-friendly and allows for quick checking of queries, data integrity, etc. csv output to Excel is pretty-much useless without a proper timestamp.

Please revert to full timestamps or allow the format to be configurable.

**Comment by rossmcdonald** [comment]
@s1m0 Precision defaults to the `ns` epoch, but you can set it to the human-readable (RFC 3339) format by running:

```
> precision rfc3339
```

From within the Influx shell, or setting it when connecting, with:

```
influx -precision rfc3339
```

**Comment by jsternberg** [comment]
Closing this since the question has been answered. Please reopen if you think the issue has not been resolved. Thanks!

**Comment by maksa** [comment]
I think what s1m0 wanted to say is that display format should be separated from input format, i.e. that the display from select should use rfc3339 (or be user configurable), no matter what precision was used as input. I.e. that display and input should be two separate things. 

Frankly guys (user feedback ahead) - timestamp input is the most confusing part for an influxdb newcomer, which is strange since it's a timeseries database. It should be either fixed to work in a consistent and predictable manner for both input and display, or better documented. Is there a way to contribute to your documentation?
