### ISSUE TITLE
[0.11] FIRST(),LAST() no longer return the relevant timestamp and values seem off

### ISSUE THREAD

**Issue by rkuchan** [influxdata/influxdb#5890]
Using the [sample data](https://docs.influxdata.com/influxdb/v0.10/sample_data/data_download/) from the docs:
* `first()` and `last()` no longer return the relevant timestamp in 0.11
* `first()` and `last()` don't return the same point in 0.10 and 0.11

**0.10**
```
> SELECT FIRST(water_level) FROM h2o_feet WHERE location = 'santa_monica'
name: h2o_feet
--------------
time			        first
2015-08-18T00:00:00Z	2.064
> SELECT LAST(water_level) FROM h2o_feet WHERE location = 'santa_monica'
name: h2o_feet
--------------
time			         last
2015-09-18T21:42:00Z	 4.938
```

**0.11**
```
> SELECT FIRST(water_level) FROM h2o_feet WHERE location = 'santa_monica'
name: h2o_feet
--------------
time			        first
1970-01-01T00:00:00Z	5.597
> SELECT LAST(water_level) FROM h2o_feet WHERE location = 'santa_monica'
name: h2o_feet
--------------
time			        last
1970-01-01T00:00:00Z	5.745
```

I believe 0.10 has the right answer:
```
#First values of water_level

> SELECT water_level FROM h2o_feet WHERE location = 'santa_monica' LIMIT 3
name: h2o_feet
--------------
time			        water_level
2015-08-18T00:00:00Z	2.064
2015-08-18T00:06:00Z	2.116
2015-08-18T00:12:00Z	2.028

# Last values of water_level

> SELECT water_level FROM h2o_feet WHERE location = 'santa_monica' ORDER BY time DESC LIMIT 3
name: h2o_feet
--------------
time			        water_level
2015-09-18T21:42:00Z	4.938
2015-09-18T21:36:00Z	5.066
2015-09-18T21:30:00Z	5.01
```

I've tried to reproduce the 'getting the wrong point' issue in another data set and I can't!

**Comment by jsternberg** [comment]
We decided with the new query engine that all aggregates and selectors, regardless of whether a group by is used or not, would either return the interval time or the zero time. In the future, we're going to come up with a syntax that allows selecting the unit time as part of a separate column.

@pauldix can you confirm this is a desired change in behavior?

**Comment by jsternberg** [comment]
Although I'm going to look into why the value is incorrect. That seems to be wrong.

**Comment by pauldix** [comment]
@jsternberg I think that's right although I'm having trouble remembering why we'd want that. You'd almost always want the selector to return the time of the actual value and not the group by window.

The one thing I can think of is if you have multiple selectors and an aggregate mixed together. Then the output could have multiple points for the same group by windows, but with different values/point times for the selectors.

Did we create an issue for this anywhere?

**Comment by jsternberg** [comment]
I don't think we made an issue for it anywhere. I think the rationale for having the selectors return the interval time was because you felt it would be what people would expect when using `GROUP BY` and also to resolve the conflict when multiple selectors and aggregates are mixed together. The alternate syntax was the proposed method of giving the selected time as part of the query, but `time` would always be reserved for the interval.

**Comment by pauldix** [comment]
Yeah, I think people will want the actual time for the selected point. Maybe include automatically? `<selected_field>.time`?

**Comment by beckettsean** [comment]
This has come back in 0.12:

```
Connected to http://localhost:8086 version 0.12.1
InfluxDB shell 0.12.1
> use telegraf
Using database telegraf
> select last(usage_user) from cpu
name: cpu
---------
time	last
0	1.2096774193903288

> 
```

**Comment by beckettsean** [comment]
@jwilder @jsternberg @rkuchan

**Comment by jsternberg** [comment]
@beckettsean I think that was the desired behavior with a future feature request in #5926. @pauldix are we reversing that decision?

**Comment by beckettsean** [comment]
@jsternberg @pauldix what's the desirability of returning the selected point without a meaningful timestamp?

**Comment by pauldix** [comment]
There was something around consistency of the API. However, we need a way to select the timestamp of the returned point. Should prioritize that to get in ASAP

**Comment by jsternberg** [comment]
There were two reasons that, combined, produced a compelling reason to keep it as it was.

The first was API consistency. The time field was to act as the interval. To be fair, I'm not completely sure we should bother returning that field for aggregate queries that don't have a group by since it's mostly useless.

The second reason was because of ambiguity with multiple selectors. Multiple selectors would make it impossible to figure out which one the time field should refer to and would have to just be ignored and zero'd out. It also introduced a complexity in the actual code since the part of the code that creates the iterator for that column doesn't know whether only one selector was used or multiple selectors were used. It wouldn't be too difficult to modify that section of the code though, so that's not the biggest deal.

Do we want me to prioritize the time selector from the other issue or just make it so the time field here gets filled with the selector if and only if there is only one selector? The first is harder, but likely more correct. The second is easier, but might be more appropriate for a later point release or 2.0.

**Comment by beckettsean** [comment]
I vote for the second for now. Let's do the easy thing that makes `SELECT LAST(value) FROM foo` do the right thing. If that means `SELECT LAST(value), FIRST(value) FROM foo GROUP BY time(1m)` doesn't do what's expected, that's okay. An argument can be made that GROUP BY intervals should always be the returned timestamps, even for selectors (better graphs). 

Right now there is NO WAY to recover the timestamp for the point without selecting it by tags or using LIMIT or some other non-precise method. As long as a bare FIRST(), LAST(), MAX(), MIN() call returns the relevant timestamp, all problems can be solved with enough queries.

**Comment by beckettsean** [comment]
@gunnaraasen ^^ your thoughts?
