### ISSUE TITLE
[0.11-nightly] Continuous queries not being executed at all

### ISSUE THREAD

**Issue by KiNgMaR** [influxdata/influxdb#5896]
Hi everyone,

I have been observing this for a while (cf. https://github.com/influxdata/influxdb/issues/5415#issuecomment-183201454). In the latest nightlies, I am completely unable to get any continuous query to execute.

This is an example:

    CREATE CONTINUOUS QUERY cq_xxx_rows_per_minute_total ON xxx_prod BEGIN SELECT sum(num_responses) INTO cq_xxx_rows_per_minute_total FROM xxx_requests GROUP BY time(1m) END

The query is created, it's showing up in `SHOW CONTINUOUS QUERIES`, but that's it. The log does not hold any indication whatsoever of the "continuous_querier" performing any work.

My setup:
* Nightly build f18d7e759625b829a8ad82e1b7631e5e9412b7d0
* CentOS 6
* System time zone CET
* Sending points via UDP without timestamps

Everything else is working well, measurements are being written and can be queried. I already tried nuking the entire data and meta folders and starting with a fresh config, but this did not improve the situation.

Please let me he know what I can do to help in tracking this down. Some more info from when at least some continuous queries were working can be found in the comment I linked to above.

Thanks!

**Comment by whiten** [comment]
I ran into this as well on a one-node cluster. Debugging locally, I found that services.continuous_querier.Service.backgroundLoop() was failing to acquire a lease on "continuous_querier" with the error "Get http://localhost:8091/lease?name=continuous_querier&nodeid=0: stopped after 10 redirects". When I added logging to services.meta.serveLease() right before "if leader != h.s.httpAddr {", leader was "localhost:8091" while h.s.httpAddr was ":8091". I modified my config.toml so that meta/http-bind-address was "127.0.0.1:8091" rather than ":8091", these two values became equal, and continuous queries started working again for me. YMMV.

**Comment by KiNgMaR** [comment]
I can confirm that @whiten's workaround resolves the issue for me as well. :100: Thanks!!

Keeping the issue open so that the team knows that the default config may not work correctly for single-node setups.

**Comment by mvadu** [comment]
This is the same issue (8091 without a host) that was affecting windows version to start. I pushed a fix #6056 for windows part, but have not been able to test CQ's yet.

**Comment by benbjohnson** [comment]
Fixed via #6147
