### ISSUE TITLE
prblem with data insert

### ISSUE THREAD

**Issue by giammy2290** [influxdata/influxdb#5899]
if i run this insert with curl

    root@log:/log/track# curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'venue.performance.log,pagetype=frontend_v3_event,webid=2d6ae9cbbaeaecdd39fec2aecab80636  1457023252'
    HTTP/1.1 400 Bad Request
    Content-Type: application/json
    Request-Id: 4eb880f5-e15f-11e5-9a26-000000000000
    X-Influxdb-Version: 0.10.1
    Date: Thu, 03 Mar 2016 16:45:16 GMT
    Content-Length: 152
    Connection: close

    {"error":"unable to parse 'venue.performance.log,pagetype=frontend_v3_event,webid=2d6ae9cbbaeaecdd39fec2aecab80636  1457023252': invalid field format"}

doesn't works

**Comment by rossmcdonald** [comment]
@giammy2290 There is no field in the point you are trying to write, which is why you are getting the `invalid field format` error. If you change it to something like:

```
venue.performance.log,pagetype=frontend_v3_event,webid=2d6ae9cbbaeaecdd39fec2aecab80636  value=1 1457023252
```

It should work properly. There is more documentation on valid line protocol in the documentation [here](https://docs.influxdata.com/influxdb/v0.10/introduction/getting_started/#writing-and-exploring-data).
