### ISSUE TITLE
Floating point precision for math operations

### ISSUE THREAD

**Issue by dschniepp** [influxdata/influxdb#5921]
**Updated:**
I have a floating point issue when I use the **sum()** operator.
## Data

```
h2o_feet,location=coyote_creek water_level=7.12 1439856000000000000
h2o_feet,location=coyote_creek water_level=9.94 1439856200000000000
h2o_feet,location=coyote_creek water_level=7.12 1439856300000000000
h2o_feet,location=coyote_creek water_level=9.94 1439856400000000000
h2o_feet,location=coyote_creek water_level=7.12 1439856500000000000
h2o_feet,location=coyote_creek water_level=9.94 1439856600000000000
```
## Query

```
SELECT sum(water_level) FROM h2o_feet
```
## Result

```
time                                    sum
1970-01-01T00:00:00Z    61.11999999999999
```
## Expected

```
time                                    sum
1970-01-01T00:00:00Z    61.12
```

---

Is there a way to set the precision of floating point numbers for math operations?

InfluxDB: V 0.10.3

**Comment by jsternberg** [comment]
@dschniepp can you explain to me what the issue is? I need to know the following:

* What data are you using?
* What query are you using?
* What is the expected behavior?
* What is the actual behavior?

Thanks!

**Comment by dschniepp** [comment]
@jsternberg updated the initial question.

**Comment by jsternberg** [comment]
@joelegasse @kostasb we had a conversation about this recently. Should we be sending back floats with some kind of precision rather than sending back the raw float value? It seems to me that there should be a default precision, but that it should be customizable through the query engine.

Thoughts @pauldix?

**Comment by kostasb** [comment]
Related with https://github.com/influxdata/influxdb/issues/5938

**Comment by joelegasse** [comment]
I should first note that floating point numbers aren't fixed-precision decimals, and we shouldn't treat them that way. Luckily @dschniepp is using a similar dataset as #5938, which I found out that less than 1% of the values could be represented exactly as floating point values. You can see in this example that none of the values in this example could be represented exactly as floating point values: http://play.golang.org/p/Z-xoVtENO9 Also, your actual/expected output doesn't match the numbers you provided.

I do not think we should be rounding any values coming out of the system. Our everyday intuition says, "that number is wrong", but the result we get out is more accurate when considering the inputs the aggregate function was given. Consumers of the data (clients) might want to round to a few decimal places when printing values, but I don't think that should be built-in to floating point values returned from the system.

You can read my posts in #5938, but I'll summarize my feelings here: If you need precision from influxdb, use integer values for thousandths or millionths of a unit (or whatever the smallest unit is), rather than floating point values.

**Comment by pauldix** [comment]
@joelegasse I agree that if you need precision you should be using ints. However, for this case I think that it would be nice to give the user an option for rounding to some number of digits after the decimal place. Something that would happen at serialization time.

**Comment by jsternberg** [comment]
Looking back at this, I don't think we can perform this rounding at serialization time. I think rounding has to be done at the client. Floating point isn't particularly kind to certain numbers that would be rounded and we would likely run into the same issue where the client has to do its own rounding if we sent the digits over the wire as floats rather than strings.

Maybe we should convert this issue to adding rounding to the client?
