### ISSUE TITLE
Discrepancies in SUM and MEAN query results

### ISSUE THREAD

**Issue by kostasb** [influxdata/influxdb#5938]
After a random number of iterations executing the same SUM or MEAN query, different results are returned at the lower floating point digits with v0.11 master branch.

E.g.

Using sample dataset NOAA (https://s3-us-west-1.amazonaws.com/noaa.water.database.0.9/NOAA_data.txt)

SUM value calculated with Python is: 67777.66900000008
select sum(water_level) from h2o_feet
First 4 iterations match with the pre-calculated value. 5th iteration:
ValueError: Iteration 5: Sum(water_level) = 67777.66900000024 did not match 67777.66900000008

15 digit accuracy MEAN value calculated with Python is: 4.442107025822525
select mean(water_level) from h2o_feet
First 3 iterations match with the pre-calculated value. 4th iteration:
ValueError: Iteration 4: Mean(water_level) = 4.442107025822535 did not match 4.442107025822525

We have integration test cases that we can run to reproduce the issue easily.

@jsternberg @e-dard @joelegasse thoughts?

**Comment by joelegasse** [comment]
I'll start with the short version of my thoughts: don't use floating point numbers if you need precision. Store the value as thousandths or millionths in an integer value.

The slightly longer version of my thoughts can be found here (Go playground has a limit on snippet size, or I would have shared it from there): https://gist.github.com/joelegasse/76c04cb83a2e9558b69b

I created two slices of the `water_level` values as they appear in the data file you provided, once as `[]float64` to be interpreted by the Go compiler, and another as `[]string` to be parsed with exact, decimal precision.

```
unsorted   67777.66900000021
ascending  67777.66900000024
descending 67777.66900000008
exact      67777669/1000
converted: 67777.669 false

Only 130 of 15258 values were able to be exactly represented as floating point numbers
```

From the first three lines, where each value was interpreted as a float64, you can see that the order of operations on those values matters. The reason it matters can be seen at the bottom of the output: only 130 of the 15258 values could be represented exactly. That means that over 15000 values are potentially off by the least significant bit at several orders of magnitude below where the final sum ends up, which is important. As soon as the sum increases in order of magnitude, those least significant bits of the value with the lesser magnitude disappear, and aren't included in the sum, making those values potentially even less precise when added in to the total. This magnitude shift happens several times, compounding the error rate to the point where it becomes noticeable in the final result.

I used the word "noticeable", but the error as a percentage of the exact answer is on the order of 10^-13. Even the exact answer, which is being printed "correctly" isn't represented as a `float64` exactly.

"Fixing" this so that the order becomes predictable and repeatable would involve not performing any calculations until we are sure we have the values sorted (or will be accessing them in a sorted manner). This would most likely increase query response time, all in the name of providing a less-imprecise value, which, if used to calculate the sum of the mass of every living human, would be off by less than 2 grams.

Back to the short version: I don't think this is an issue worth solving, if it can even be considered an issue at all. If precision is needed, you should use precise values.

**Comment by jsternberg** [comment]
What @joelegasse says is fully possible. We don't sort the points before doing any of the call iterators except by the window which they're in. This is currently done for efficiency. I think we should just remind people in the documentation that a floating point value comes with the normal caveats of floating point. Maybe we want to add support for a high-precision floating point to InfluxDB at some point as an extra feature for those who need the precision?

**Comment by kostasb** [comment]
That is totally understandable and is actually a logical implication of summing the same set of floats with random order. Returning slightly different results for the same query against the same data set could be misleading though. 
We could consider providing an additional "precise" version of those queries which will have more computational cost. Otherwise if almost no real use case is ever affected by this, we can just mention it as a known issue in the docs.

**Comment by joelegasse** [comment]
I don't understand how it is misleading. I think @jsternberg has the right idea in that we should just educate people that the value `0.1` can never be stored exactly as a floating point value, and that InfluxDB makes no guarantees about the order of operations for aggregate functions. All of the aggregate values calculated (other than when using `math/big`) in the above example are technically incorrect.

I don't think adding a more precise floating point or decimal value type will have a significant benefit, but that's a larger discussion, and not really related to aggregate functions currently returning slightly different values.

**Comment by kostasb** [comment]
Thanks @joelegasse @jsternberg 
The next best thing we can do is document this behavior of variable results in the lower digits of floats when fields are aggregated. We want to make sure that this is justified to end users who might get slightly different results for the same query on a particular dataset.

**Comment by jsternberg** [comment]
@kostasb I think the knowledge that the points are floating point are enough. In the part of the documentation where we discuss floating point, a link to the inaccuracies of floating point could be enough. Telling people that their results are going to be slightly different each time they make a query is going to make people think that the calculation is wrong because we're doing something wrong rather than being a natural limitation.

An alternative is we can always try returning a slightly rounded value in the emitter rather than just printing all 15 digits every time.

**Comment by kostasb** [comment]
@jsternberg I will open an issue under our docs repo to add some clarifications about the inaccuracies of floating point, noting that points are not sorted before they are aggregated by mathematical functions - which may result in such minor discrepancies in the outputs.
