### ISSUE TITLE
attempting to use environment variable in config file

### ISSUE THREAD

**Issue by BrannonKing** [influxdata/influxdb#5964]
I attempted to use an environment variable in the config file like this:

dir = "$ProgramData/MyServer/InfluxDB/meta"
and this:
dir = "%ProgramData%/MyServer/InfluxDB/meta"

It appears that there is no handling for such things. Is there some way I can dynamically set that path? I'm running on Windows 10 with build 0.11.0~n1457510435, branch master, commit 425ef2c32a74c25929a178632efa8342e0d4d810

**Comment by gunnaraasen** [comment]
InfluxDB will check for environment variables from the environment (not the config file) when the process starts up. If any environment variables match the general pattern of `INFLUXDB_[section name]_[variable name]`, they'll override the equivalent variable in the config file. E.g. 

```
cmd /C "set INFLUXDB_META_DIR=%ProgramData%/MyServer/InfluxDB/meta && influxd"
```
(disclaimer, I don't regularly work with Windows so that syntax is probably wrong.)

@BrannonKing Does that work for you?

**Comment by BrannonKing** [comment]
This works great. The `wal-dir` was a little tricky: INFLUXDB_DATA_WAL_DIR. Change it to an underscore.

**Comment by gunnaraasen** [comment]
Yup, all dashes (`-`) in config variables are converted to underscores (`_`) for the environment variable.

I opened up https://github.com/influxdata/docs.influxdata.com/issues/304 to document the environment variables.
