### ISSUE TITLE
 Invoke-restmethod or invoke-webrequest to write multiple points to influxdb

### ISSUE THREAD

**Issue by timdicon** [influxdata/influxdb#5976]
Is it possible to write multiple points with  Invoke-restmethod or invoke-webrequest.  Using the syntax in https://github.com/influxdata/influxdb/issues/4194 I can write one row/point (thanks).  But I would like do the equiv of the below via powershell.

curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'cpu_load_short,host=server02 value=0.67
cpu_load_short,host=server02,region=us-west value=0.55 1422568543702900257
cpu_load_short,direction=in,host=server01,region=us-west value=2.0 1422568543702900257'

**Comment by BrannonKing** [comment]
It's possible that it's an EOL issue. You need to use `\n` not `\r\n`, the latter being the Powershell/Windows default. It would be nice if Influx would eat that `\r`.

**Comment by timdicon** [comment]
Thanks,  I had tried `n before but wasn't properly reading the error output stating 'bad timestamp' as my timestamps where to nearest s, not nano s.  

So using the below is successful:-

_$uri=”http://<hostname>:8086/write?db=test&precision=s”
$authheader = "Basic " + ([Convert]::ToBase64String([System.Text.encoding]::ASCII.GetBytes("<username>:<password>")))
$postparams = "testtime value=2.2 1457628961`ntesttime value=2.3 1457629321`ntesttime value=2.4 1457629440"
Invoke-WebRequest -Headers @{Authorization=$authheader} -Uri $uri -Method POST -Body $postparams_

**Comment by timdicon** [comment]
Thanks, I had tried `n before but wasn't properly reading the error output stating 'bad timestamp' as my timestamps where to nearest s, not nano s.

So using the below is successful (using `n instead of \n in the postparams ):-

`$uri=”http://:8086/write?db=test&precision=s”`
`$authheader = "Basic " + ([Convert]::ToBase64String([System.Text.encoding]::ASCII.GetBytes(":")))`
`$postparams = "testtime value=2.2 1457628961\ntesttime value=2.3 1457629321\ntesttime value=2.4 1457629440"`
`Invoke-WebRequest -Headers @{Authorization=$authheader} -Uri $uri -Method POST -Body $postparams`

**Comment by timdicon** [comment]
Thanks, I had tried `n before, but wasn't properly reading the error output stating 'bad timestamp' as my timestamps in $postparams were to nearest s, not nano s.

So using the below is successful (using `n instead of \n in the postparams ):-

`$uri=”http://<hostname>:8086/write?db=test&precision=s”`
`$authheader = "Basic " + ([Convert]::ToBase64String([System.Text.encoding]::ASCII.GetBytes("<username>:<password>")))`
`$postparams="testtime value=2.2 1457628961\ntesttime value=2.3 1457629321"`
`Invoke-WebRequest -Headers @{Authorization=$authheader} -Uri $uri -Method POST -Body $postparams`

**Comment by timdicon** [comment]
I have seen another way of writing multiple points/rows into influxdb from powerhsell using a hashtable then converting it to json, which is a neater way to add them from a powershell point of view...  

But I believe using the above syntax is using the line protocol, and therefore the most efficient way for influx?  

And that converting to a json is NOT recommended?

**Comment by jonseymour** [comment]
You can certainly write multiple points if you pipe them from stdin.

So (in a Unix shell)::

```
echo 'cpu_load_short,host=server02 value=0.67
cpu_load_short,host=server02,region=us-west value=0.55 1422568543702900257
cpu_load_short,direction=in,host=server01,region=us-west value=2.0 1422568543702900257' | curl --data-binary @- -XPOST 'http://localhost:8086/write?db=mydb' 
```

If your shell doesn't strip the \r, then add a tr filter:

```
echo 'cpu_load_short,host=server02 value=0.67
cpu_load_short,host=server02,region=us-west value=0.55 1422568543702900257
cpu_load_short,direction=in,host=server01,region=us-west value=2.0 1422568543702900257' | tr -d \\015 | curl --data-binary @- -XPOST 'http://localhost:8086/write?db=mydb' 
```

**Comment by joelegasse** [comment]
@timdicon To answer you questions about JSON: it is considered a deprecated format, it must be manually enabled currently, and will be removed in a future release.

**Comment by amoghmahesh** [comment]
Is it possible to to write multiple points to influx from a file which has data in format [ measurement-name,tag-name=tag-value value-name=value ] using Invoke-RestMethod ?

**Comment by iskrenpp** [comment]
After banging my head against the wall I finally figured it out and posting here to hopefully help someone else not lose their will to live LOL
The approach that I tested and worked beautifully is to save all lines of metrics with all tags, values, etc in influx line protocol in 'as is' format in a file. This will save it with \r\n e.g. CFLR at end of each line.
It turns out we don't care about this because we can use Get-Content to read this file which will take the lines individually and will not pay any attention to the line endings.
Then simply use new var line like this:
`$p=((get-content 'C:\file\path') -join "`n" )`

Important to keep in mind that using Invoke-WebRequet from windows Powershell into influx will not append for whatever reason the current time and you need to explicitly pass it in nanoseconds. 
I do it like this:
`$time= [long] (Get-Date -Date ((Get-Date).ToUniversalTime()) -UFormat %s)
$nanotime="${time}000000000"
`
then just append to each line as you write to the file at end of each line with leading space.

As explained earlier then I just do something like this
`$p=((get-content 'C:\file\path') -join "`n" )

Invoke-WebRequest -Uri http://influx.host/write?db=telegraf -Method Post -Body $p
`
