### ISSUE TITLE
InfluxDB should restrict names/keys

### ISSUE THREAD

**Issue by joelegasse** [influxdata/influxdb#6011]
InfluxDB has up to this point been very permissive in what it has allowed for names of various things: databases, retention policies, measurements, tag/field keys, and tag values. This can cause problems (#5870) when assumptions get made about how things are named. In the referenced issue, the new query engine was updated to assume that any measurement that began with an underscore (`_`) was actually an internal name that shouldn't be treated as a normal source for data. It was remedied, but the underlying cause was that no formal guidelines or restrictions existed on database and measurement names.

This can also cause problems for names that get used directly as path elements, currently just database names and retention policies. In short, don't name your database `../../.ssh`...

I understand there is some amount of "cool" factor in being able to name things any valid UTF-8 string, but it can also cause problems if not handled correctly. Handling arbitrary names correctly would also make the filesystem layout much less straight-forward that it is currently (`<data-dir>/<DB>/<RP>/<SHARD-ID>`). The database and retention policy path elements might need to be escaped, and names that look like escaped names would get ugly quickly.

I certainly don't want to sound like I'm saying, "ASCII is enough for anyone", but accepting any UTF-8 sequence is goes a little too far in the other direction, I think.

This issue is meant to track discussion around and hopefully agree on restrictions for various _things_ within InfluxDB.

Here's a starting list of things that should be considered for restrictions:
- Database names
- Retention policy names
- Measurement names
- Tag Keys
- Tag Values
- Field Keys
- User Names
- Continuous Query Names
- Subscription Names

Please comment with your thoughts about restricting the various items above, or if there is another category of _things_ that I forgot.

**Comment by jwilder** [comment]
@pauldix @beckettsean

**Comment by pauldix** [comment]
Database and retention policy names should definitely be restricted. I consider it a bug that they're not.

For measurement names, tag and field keys, and tag and field values, I don't think they should have restrictions. Making a change to any of those at this point would be a huge problem for anyone using InfluxDB. The line protocol and query language should support any character in those.

The only restriction that might be potentially interesting that I don't think would create too many problems would be that maybe measurement names and tag and field keys and tag values not be able to being or end with either `"` or `'`. We've seen users have problems when writing their client libraries and accidentally sending tag keys or tag values wrapped in double quotes.

**Comment by gerrickw** [comment]
Possibly if doing validation of input/output a fuzz test would be useful for finding possible issues.  When quickly checking online I see two with golang.

- https://github.com/dvyukov/go-fuzz
- https://github.com/google/gofuzz

Examples with go-fuzz: 
- https://blog.cloudflare.com/dns-parser-meet-go-fuzzer/
- https://speakerdeck.com/filosottile/automated-testing-with-go-fuzz

**Comment by beckettsean** [comment]
I agree with @pauldix that we should restrict database and RP names to a smaller set. That set should be chosen for minimal likelihood of filesystem weirdness. E.g. must start with `[A-z,_]`, no slashes allowed.

@joelegasse there are a few additional identifiers in the system:
- users
- continuous queries
- subscriptions

Beyond database and RP names, I see no obvious restrictions to the other identifiers provided we can get the escaping right for the line protocol and InfluxQL. That said, I think we can impose some parsing-friendly rules, like no unpaired double-quotes allowed. I'd like to support any combo of forward and backslashes, with the right escaping. Maybe we can allow for a batch-specific escape character? If I have a long file path or a bunch of regex, for instance, I could use `|` to escape the slashes rather than `\`.

**Comment by gunnaraasen** [comment]
We should move to using unique IDs internally for database and retention policy names. Moving to IDs would allow us to define safe path names and eliminate the need for restrictions on the user-provided DB/RP name. Plus ID's have already been proposed as a solution for a correct implementation of the `ALTER DATABASE` command, see https://github.com/influxdata/influxdb/pull/4291#issuecomment-150290432 and https://github.com/influxdata/influxdb/issues/4503.

Another consideration to keep in mind is that adding restrictions to database and retention policy names will be especially hard for users who already have invalid database names because there is currently no way to rename a DB/RP.

Restricting measurements, tag and field keys from beginning/ending with quotes sounds interesting. I think a warning in the logs and bug fixes to offending client libraries would be a better way to handle the issue since it's most often encountered in development. Also, I imagine tag values might include quote characters fairly often and the restriction would be annoying to work around.

I don't think a batch-specific escape character would be too useful either since people will mostly be writing/reading via a client library which should handle escaping correctly.

**Comment by pauldix** [comment]
@gunnaraasen having readable names is nice for administrators since those names are used in the file path names. Supporting unicode but enforcing everything to be a character, number, `-`, or `_` would be safe for the filesystem and still give people readable names in their paths.

Moving to another directory (which would also work for the ALTER DATABASE) is a cheap operation so that should still work too.

**Comment by gunnaraasen** [comment]
While it's nice to have human readable names, most administrators don't delve into the data directory (and really shouldn't have to). There are a bunch of ways to add human readable names where needed, such as each DB/RP directory containing a database info file, a central mapping of names to IDs, and/or sanitized symlinks to human friendly name.

One of the problems with ALTER DATABASE is that (in addition to moving directories) database names are also used in a bunch of other places, like continuous queries and user permissions. Moving to DB/RP IDs reduce the number of moving parts for a rename.

That said, I have no problem restricting database and retention policy names as long as the change is driven to help users and is not driven by the need to conform to OS path naming conventions.

**Comment by beckettsean** [comment]
Database and RP names are also very likely to be communicated in URL query parameter strings, whether at write time or at query time. URL support for full UTF-8 is pretty good, but I think restricting it to mostly bare ASCII ensures we don't have API compatibility issues on any network layer.

**Comment by joelegasse** [comment]
In browsing the issues, I came across one instance that should add a real-world example where supporting every single character (including the invisible ones) caused unexpected behavior: #5851. Escape sequences were saved in to the file, then fed to InfluxDB. Since `^[` (escape) isn't a comma or space, it was included as part of the measurement name. This was also then piped back out as a raw control character to the terminal via the CLI.

"Full Unicode support" includes control characters and non-printable characters as well. This leads me to think that we should restrict all names/keys/tag values to a restricted, but generous, character set. The wider character class of [Printable](https://golang.org/pkg/unicode/#IsPrint) includes "letters, marks, numbers, punctuation, symbols, and the ASCII space character", perhaps we should even consider disallowing marks as they could create multiple series for visually identical measurement names. String field values should be left alone, though, and only be modified in-flight to be properly escaped for the line protocol, but that would be unnoticed by the user's application.

**Comment by adampl** [comment]
Please, don't:
- enforce _any_ restrictions on the data (measurement name or tag/field name/value)
- issue any warnings about unusual characters
- reinvent special character escaping rules

As a last resort, you can encode the strings internally, even in base64, but please don't force clients to do this for you.

**Comment by erSitzt** [comment]
I'm not sure if the info is relevant here, but i'll just leave it :)

I had to spend some time looking for errors with my metrics visualization in grafana with influxdb as the backend because we are using slashes in our measurement names, which causes problems with grafana because they use slashes for their regex.

This happens with tags too
See here:
https://github.com/grafana/grafana/issues/6012

**Comment by beckettsean** [comment]
https://docs.influxdata.com/influxdb/v1.0/troubleshooting/frequently-asked-questions/#what-words-and-characters-should-i-avoid-when-writing-data-to-influxdb is likely relevant for folks who see this issue.

**Comment by foobar** [comment]
at least it should restrict retention policy name. e.g., if you create a RP with name "_series" and then drop it, all series files would be purged.
