### ISSUE TITLE
How to write heavy load to Influxdb?

### ISSUE THREAD

**Issue by pethani** [influxdata/influxdb#6071]
Hi,

i am new in influxdb and trying to store sensor data in Influxdb with 400-500 Field and 1 Tag and Timestamp given manually with nanosecond accuracy. i try to store 300,000 point for one specific tag with c# client (https://github.com/MikaelGRA/InfluxDB.Client) in 1000 batch set and it take quite lot time to send it from client node. In One database have approximately 20 to 25 series. 

configuration: Infludb Node:- 4gb RAM, corei5, HDD(Virtual node, 0.10 version of Influxdb)
                       Client Node:- 4gb RAM, corei5
i required it for my Master Project , if possible then please provide require hardware for improve performance.

**Comment by mark-rushakoff** [comment]
There's a few simple things you can do that will likely speed things up:

* Make sure your client is using the line protocol, not JSON, to write points. I couldn't tell which approach the library you mentioned is using, but [influxdb-lineprotocol](https://github.com/nblumhardt/influxdb-lineprotocol) is a .net library that may help.
* Prefer a solid state drive over an HDD.
* On the server, 4GB of RAM will do okay, but you'll probably see better performance with more RAM.
* Experiment with larger batch sizes.
* Make sure you're using the TSM engine, not the b1 or bz1 engines that are deprecated and not present in 0.11+.
* If possible, use InfluxDB 0.11 (it's in RC status now but the final cut is coming soon) rather than 0.10.

**Comment by pethani** [comment]
@mark-rushakoff  Thank you very much
i already using TSM engine and also tried with 1500, 2000, 3000 large batch size, but then it become even worse then 1000
i will try  influxdb-lineprotocol  and

**Comment by toddboom** [comment]
Closing this out since it's not an issue that needs to be resolved.
