### ISSUE TITLE
Allow Percentile to be used as a selector in InfluxQL.

### ISSUE THREAD

**Issue by nathanielc** [influxdata/influxdb#6292]
Allow this type of query:

```
> insert cpu,host=server01 value=2
> insert cpu,host=server02 value=3
> insert cpu,host=server03 value=4
> select percentile(value, 50), host from cpu
name: cpu
---------
time                                        value   host
1460489980728867428     2       server02
```

Currently you get this:

```
> select percentile(value, 50), host from cpu
ERR: error parsing query: mixing aggregate and non-aggregate queries is not supported
```

**Comment by pauldix** [comment]
Not sure if it makes sense to have percentile be a selector. It doesn't map to a specific host, does it? For example if you had:

```
host1 val=10
host2 val=20
host3 val=20
host4 val=30
```

Which host would the `50` percentile return?

**Comment by jsternberg** [comment]
I assume these are at the same time? I would guess it would choose `host2`, but I admit that it's not exactly the best answer. I think the same might apply to `first()` and `last()` though too since it's not clear which tag it should choose when a `GROUP BY` is not used and the timestamps are the same. It just chooses something at the moment.

I think `min()` and `max()` would also run into the same problem too.

**Comment by pauldix** [comment]
@jsternberg ah you're right. Ok, carry on, guess we should just have some clearly defined order of operations for if multiple points have the exact same time. first of the ascending sort order of whatever the thing is?

**Comment by jsternberg** [comment]
We probably should, but I think we've left it as non-deterministic for now because of speed. It might be just best to say in the documentation, "If the tag wasn't specified in the `GROUP BY` then it's non-deterministic which one you'll get."

We could make selectors deterministic though. Non-deterministic helps speed up aggregate calls though. We could also only make it deterministic if an auxiliary point has been selected.
