### ISSUE TITLE
Epoch time in ns can't be display in javascript

### ISSUE THREAD

**Issue by max3163** [influxdata/influxdb#6370]
It's impossible to display the timestamp in epoch format ( ns ) in javascript. 

When influxdb send a timestamp value in JSON like this : 

 [
     1460549358372198212,
     "bob",
     "W001478 start",
     "JMETER"
],

you can't affect the value in javascript : 
console.log(1460549358372198212)
=> 1460549358372198100

JSON mean JavaScript Object Notation, but this data is not representable, I think it will be better to send it as a string.

**Comment by e-dard** [comment]
@max3163 as I understand it Javascript has native support for double-precision floating-point numbers, which is why it cannot handle numbers large enough to represent nanoseconds since the epoch, e.g., `1460549358372198212`.

This is a limitation of Javascript; there may be libraries or frameworks that enable the handling of numbers this large.

**Comment by max3163** [comment]
I know it's a limitation of Javascript but why use a Javscript Standard (JSON) if you can't represent data  with it....

**Comment by gunnaraasen** [comment]
The epoch of query results can be changed by including `epoch=s` as a query parameter.

**Comment by max3163** [comment]
I know that too, but I need the exact timestamp to proceed after on update. 
And because of javascript limitation, I can't, and create duplicate record than update the selected one.

**Comment by gunnaraasen** [comment]
This seems to be a fairly special case specific to Javascript and not a bug. Please open a feature request if you would like to be able to return timestamps as strings.
