### ISSUE TITLE
[Question] Linux CPU %

### ISSUE THREAD

**Issue by Drewster727** [influxdata/influxdb#6387]
I'm fairly new to InfluxDB and I'm having an issue with storing CPU values from telegraf, the data is not quite showing up correctly when I display it in Grafana. I have created an issue with Grafana here:
https://github.com/grafana/grafana/issues/4716

They seem to think it's a telegraf and/or influxdb issue, so I made an issue with telegraf here:
https://github.com/influxdata/telegraf/issues/1029

Still no resolution yet. My graphs are show up with extremely high CPU % (> 100%) which is obviously incorrect. Can anyone shed some light on this? Or how I can properly do this?

Thanks!

**Comment by jwilder** [comment]
In grafana, how do you have your axes configured?  Are the axes assuming a value from 0.0-1.0 or 0-100?  I believe the cpu percentages reported by telegraf are in the range of 0-100 so the if grafana is set to use 0.0-1.0, it would scale them up incorrectly.

I'm going to close this because InfluxDB doesn't deal with CPU percentages and the queries you are running are not doing any math so the data is either written incorrectly or being displayed wrong.
