### ISSUE TITLE
generated config file should have canonical paths by default, not ~

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#6392]
### Bug report

**System info:** [Include InfluxDB version, operating system name, and other relevant details]
InfluxDB 0.12, any non-OS X system

According to @rkuchan in https://github.com/influxdata/docs.influxdata.com/pull/390#issuecomment-210561715, the generated config file has OS X specific paths for the meta, data, and wal directoies.

**Expected behavior:** [What you expected to happen]

I think we should default to Linux paths, not OS X.

**Comment by beckettsean** [comment]
@rossmcdonald am I missing something?

**Comment by gunnaraasen** [comment]
Looks like it's not OS X specific but rather sets the data directories to be in the user's directory by default. 

https://github.com/influxdata/influxdb/blob/master/cmd/influxd/run/config.go#L100

Should be pretty easy to set the directory name as a build flag and add support for the correct data directories names per distribution to the build script.

**Comment by rossmcdonald** [comment]
Yep, the generated paths default to putting everything under `~/.influxdb`, so if you run it as root you get `/root/.influxdb`. Having a build flag that sets which directories are used would be very useful, though.

**Comment by beckettsean** [comment]
Confirmed it's using `~`, not anything OS X specific. I do think we should use `/var/lib` if we can, since that's the canonical install location.

**Comment by beckettsean** [comment]
Alternately, can we put something in the config file or the upgrade instructions that gives a one-liner for the conversion? Something like `sed /$HOMEDUR/\/var\/lib/gi` or whatever is syntactically correct.

**Comment by jsternberg** [comment]
The primary reason for this is so that it's possible to run the binary easily when run as non-root. This is essential for us as developers as we don't want to have to generate a config when we're testing locally or run the application as root on our development machines.

It's possible for us to detect when the user is root and change the config locations, but it's inadvisable to run the server as root anyway and we would then have to hard code the username. It's much easier to just have the package include a config with the appropriate paths that gets run or have them set by environment variables as part of the init script.

If we're concerned about the binary writing to `/root/.influxdb`, we can also have a check when starting the server and have it so it won't start when the user is root by default. Then you just add a new command line option to turn off that feature. It prevents people from stupidly starting the binary as root, but still allows them to shoot themselves in the foot if they're really intent on doing that.

**Comment by beckettsean** [comment]
My concern is not really about `/root` but that the package is configured by default for the non-production use case. I don't think that makes sense. Why optimize for the developer use case when we want people to find it easy to use in production? Is there not a way to handle the developer use case with environment variables, perhaps? Asking every sysadmin to alter the config file every upgrade for the convenience of the developers seems selfish, to me.

**Comment by jwilder** [comment]
You can use env vars to generate a config with different defaults:

```
INFLUXDB_DATA_DIR=/var/lib/influxdb/data INFLUXDB_DATA_WAL_DIR=/var/lib/influxdb/wal INFLUXDB_META_DIR=/var/lib/influxdb/meta influxd config > config.toml
```

```
...

[meta]
  dir = "/var/lib/influxdb/meta"
  retention-autocreate = true
  logging-enabled = true
  pprof-enabled = false
  lease-duration = "1m0s"

[data]
  dir = "/var/lib/influxdb/data"
  engine = "tsm1"
  wal-dir = "/var/lib/influxdb/wal"
  wal-logging-enabled = true
  query-log-enabled = true
  cache-max-memory-size = 524288000
  cache-snapshot-memory-size = 26214400
  cache-snapshot-write-cold-duration = "1h0m0s"
  compact-full-write-cold-duration = "24h0m0s"
  max-points-per-block = 0
  data-logging-enabled = true

...
```

**Comment by jwilder** [comment]
Closing this since the config file installed via packages have the correct paths and you should not be generating a config when using the packages.
