### ISSUE TITLE
Correct way to query counter with derivative

### ISSUE THREAD

**Issue by etlweather** [influxdata/influxdb#6493]
I have read the docs but I still feel uncertain that I am querying correctly. The example of derivative in the doc isn't with a counter (it's a water tank fill level).

So if I have a counter, like a network switch port octets counter for in/out traffic, it only goes up until the counter is reset to 0. I want to create a query that derives from the increasing counter, the Bits per second.

Is this correct?

`SELECT derivative(mean("ifHCInOctets"), 1s) *8 FROM "ifHCInOctets" WHERE "host" = 'switch1' AND "instance" = 'Gi1/0/2' AND $timeFilter GROUP BY time(30s) fill(null)`

I guess the part I am really not sure is the mean(), seems to me I should use max instead. (This query was made through Grafana).

**Comment by gunnaraasen** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.

That said, `max()` should give more accurate results than `mean()`. You'll also want to use `non_negative_derivate()`, which won't produce large spikes when the counter resets. Finally, the `1s` duration in the `non_negative_derivate()` function should work fine with the default duration, which is the same as the `GROUP BY` duration. See the [derivative documentation](https://docs.influxdata.com/influxdb/v0.12/query_language/functions/#non-negative-derivative) for more info.

**Comment by etlweather** [comment]
Sorry for using the wrong channel and thank you for providing an answer regardless! Perhaps some additional examples in the docs will help, so I'll try to squeeze in some time to propose something.

**Comment by lambdaq** [comment]
in case anyone else having trouble with this,

use `SELECT non_negative_derivative(max("MY_VALUE"), 10s) ....... fill(previous)` 

The key part is `fill(previous)` to avoid huge spikes.

**Comment by sssabas** [comment]
I'm also trying to do what the original poster commented - getting the bits/sec from the counter values for ifHCInOctets. The query I'm using (in light of the comments above) is:

SELECT NON_NEGATIVE_DERIVATIVE(max(value), 1s)*8 FROM ABC WHERE hostname='myrouter' AND metric='Gi0/0_ifHCInOctets' AND time >= '2017-11-01T00:00:00Z' AND time <= '2017-11-30T23:59:59Z' GROUP BY time(1h) fill(previous)

The issue is the values returned by the query above don't seem to match at all with the values I'm getting for the same device & interface from Graphite. 

Is there something wrong with my query?
Would appreciate any help/pointers.
