### ISSUE TITLE
Derivatives are only doing a delta, not applying the time component

### ISSUE THREAD

**Issue by paulstuart** [influxdata/influxdb#6503]
### Bug report

__System info:__ [InfluxDB 0.13.0~n201604180800, CentOS 6.7]

__Steps to reproduce:__

1. Create a derivative of a value grouped by time

__Expected behavior:__ The results should be calculated as the difference of the value over the grouped time range divided by the time range itself

__Actual behavior:__ The results only show the difference for the time range

__Additional info:__ 

### Derivative results

	> select derivative(mean(value)) as value from vsvrTotalResponses where time > now() - 5m and Grouping='TESTSERVICE' group by time(1m),*
	name: vsvrTotalResponses
	tags: DC=, Grouping=TESTSERVICE, Host=10.200.1.2
	time                    value
	----                    -----
	2016-04-29T00:24:00Z    291.5
	2016-04-29T00:25:00Z    279.5
	2016-04-29T00:26:00Z    249.5
	2016-04-29T00:27:00Z    239.5
	2016-04-29T00:28:00Z    268.5
	2016-04-29T00:29:00Z    224.5

### Source data

	> select  value from vsvrTotalResponses where time > now() - 5m and Grouping='TESTSERVICE' 
	name: vsvrTotalResponses
	------------------------
	time                    value
	2016-04-29T00:24:32Z    1392598
	2016-04-29T00:25:02Z    1392724
	2016-04-29T00:25:32Z    1392806
	2016-04-29T00:26:02Z    1392943
	2016-04-29T00:26:32Z    1393086
	2016-04-29T00:27:02Z    1393216
	2016-04-29T00:27:32Z    1393292
	2016-04-29T00:28:02Z    1393457
	2016-04-29T00:28:32Z    1393588
	2016-04-29T00:29:02Z    1393747

### Manually calculating

     2016-04-29T00:26:02Z    1392943
     2016-04-29T00:25:02Z    1392724
						     -------
                                 219

**Comment by jsternberg** [comment]
Thank you for the bug report and for all of the information and the nice formatting. It really does make it easier to look at the issue.

I think there might be a misunderstanding in the docs that needs to be clarified. First, the manual numbers you have calculated aren't correct with the query you used, but I can understand where the confusion came from. You used `derivative(mean(value))` which means you want to group every minute interval by their mean. So you end up with these values for the ones you manually calculated:

```
2016-04-29T00:25:00Z    1392765.0
2016-04-29T00:26:00Z    1393014.5
```

The derivative is then calculated by subtracting these two and you get `249.5`. That's only a minor misunderstanding though and just changes your expected output to something like 4.15/s. The problem is that derivative does something special with a nested aggregate as documented [here](https://docs.influxdata.com/influxdb/0.12/query_language/functions/#derivative):

> `DERIVATIVE()` also works with a nested function coupled with a `GROUP BY time()` clause. For queries that include those options, InfluxDB first performs the aggregation, selection, or transformation across the time interval specified in the `GROUP BY time()` clause. It then calculates the difference between chronological field values and converts those results into the rate of change per unit. The unit argument is optional and, if not specified, defaults to the same interval as the `GROUP BY time()` interval.

Since you have an aggregate and a `GROUP BY time()`, it defaults to using that (`1m`) as the divisor. So you end up with a change of `249.5/m`. If you want to switch it back to using seconds, you can do this:

```
SELECT derivative(mean(value), 1s) FROM vsvrTotalResponses where time > now() - 5m and Grouping='TESTSERVICE' group by time(1m),*
```

I hope this helped. If there's anyway we can improve the documentation to prevent this kind of confusion, please tell us.

**Comment by paulstuart** [comment]
Jonathan,

Thanks for a gracious reply to an RTFM bug report. I think perhaps breaking the last sentence out as a separate note might help for those of use with reading comprehension issues :-)

> DERIVATIVE() also works with a nested function coupled with a GROUP BY time() clause. For queries that include those options, InfluxDB first performs the aggregation, selection, or transformation across the time interval specified in the GROUP BY time() clause. It then calculates the difference between chronological field values and converts those results into the rate of change per unit.

> Note: The unit argument is optional and, if not specified, defaults to the same interval as the GROUP BY time() interval.
