### ISSUE TITLE
Use go 1.6.2

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#6511]
There have been many changes since we last tried go 1.6 that have reduced pointers and allocations.  We previously could not upgrade due to significant performance degradations.  

Initial tests with go 1.6.2 indicate we might be able to switch now, but we still have more testing.  See #5217.

If we switch, we need to update CI, build scripts and documentation.

If anyone is able to test latest master using go 1.6.2 and report their findings, it would be very helpful.

cc @mark-rushakoff @toddboom

**Comment by mark-rushakoff** [comment]
I shared the following writeup internally this morning, but I'll post it here as well. The TLDR is that for this use case (just taking count of a single field), Go 1.6.2 seems to be about 10% faster than Go 1.4.3 on average, but there's more variation in 1.6.2 (that I hypothesize has to do with the concurrent GC).

Go 1.6.2 doesn't have quite the performance gains I would have hoped to see over 1.4.3. Go Tip seems to have significant performance improvements, but the Go 1.7 release isn't until August.

Because Go 1.4 is effectively EOLed and we've  made significant application-level performance improvements during 0.13, my recommendation would be to cut over to Go 1.6.2 immediately for the 0.13 RCs and official release. As the Go 1.7 RC comes out, we can run more tests, and I anticipate we'll see another significant performance boost.

----

# Setup

We wrote one million points across one thousand series and one thousand timestamps, where each point contained a floating point, integer, string, and boolean value. The points looked similar to this:

```
ctr,s=000001 bool=F,float=0.017000,int=1i,string="0x1" 1461944214189
ctr,s=000002 bool=F,float=0.034000,int=2i,string="0x2" 1461944214189
ctr,s=000001 bool=T,float=0.051000,int=3i,string="0x3" 1461944214190
ctr,s=000002 bool=T,float=0.068000,int=4i,string="0x4" 1461944214190
```

Then, after writing one batch of a thousand points (one point per each of one thousand series, all with the same millisecond-precision timestamp), we executed count queries against the individual field types both with and without `GROUP BY s`. The queries looked like this:

```
SELECT count(float) FROM ctr
SELECT count(float) FROM ctr GROUP BY s
SELECT count(int) FROM ctr
SELECT count(int) FROM ctr GROUP BY s
SELECT count(string) FROM ctr
SELECT count(string) FROM ctr GROUP BY s
SELECT count(bool) FROM ctr
SELECT count(bool) FROM ctr GROUP BY s
```

We repeated this experiment against InfluxDB 0.12.1 from Tutum's InfluxDB docker image, and against docker images of InfluxDB built from source as of April 28 with:

* Go 1.4.3 (the version of Go we currently use for official builds of InfluxDB)
* Go 1.6.2 (the latest official version of Go)
* Go tip (what will eventually become Go 1.7 on August 1 2016)

No special configuration was used for any experiment variation. All of the experiments were run on the in-house SF servers.

# Data

For each iteration of the experiment, we recorded the latency of each query and plotted it against the number of points in the measurement. The columns in this plot correspond the different build variations, and the rows correspond with the different data types written. The axes are the same across all the subplots.

![screen shot 2016-04-29 at 10 56 30 am](https://cloud.githubusercontent.com/assets/290647/14925790/ff4a3c36-0dfd-11e6-918b-3a675674dbf0.png)

The time to complete the experiments (alternating between writes and queries, not concurrently) was:

* Tutum 0.12: 1399 seconds (100%)
* Go 1.4.3: 1356 seconds (97%)
* Go 1.6.2: 1223 seconds (87%)
* Go tip: 1049 seconds (75%)

The raw data is [available in a gzipped CSV file](https://github.com/influxdata/influxdb/files/243005/count.csv.gz)

Take a moment to carefully look at the plots yourself to see if you can reach any of your own conclusions before you read our conclusions.

# Discoveries

Counting floats seems to have drastically improved since 0.12. Compare "Float v012" and "Float go143".

There seems to be a "break" in the curves at approximately 475k and 950k points. We have not investigated the cause, but we tentatively assume it has to do with data being evicted from the WAL into TSM files. After the first break, GROUP BY is always slower than without.

The builds using Go 1.4.3 (the left two columns of plots) seem to have more consistent performance at the expense of longer overall runtime. The right two rows use Go's concurrent garbage collector, which seems to have more variation in performance but faster overall runtime.

The speed of iterating through booleans, floats, and integers seem to be roughly the same, and iterating through strings seems to take only slightly longer.

There seems to be "tri-modality" in the curves across all build variations. We don't yet have an explanation for this, but the working assumption is that the modality is a result of whether the garbage collector is running and possibly whether a compaction is running.

**Comment by sebito91** [comment]
This is great work, very nice to see the depth of checking the team is performing before rolling out changes. The  push to go1.5 really bit us which is why we manually cut back to go1.4.3 until upstream matched.

Given the changes with go1.6.2, even if the overall performance is negligible it's at least not a regression. Our GC numbers have virtually disappeared, where previously we'd have pauses up to 2s (yes, seconds) under certain load.

Very big :+1: from us!
