### ISSUE TITLE
Support Ctrl+C to cancel a running query in the Influx CLI

### ISSUE THREAD

**Issue by jsternberg** [influxdata/influxdb#6563]
The Influx CLI does not allow you to use Ctrl+C to cancel a running query. We should catch the signal and close the connection on the client side.

This may require a change to the Go client API.

**Comment by emluque** [comment]
Hi, I've been working on this the last couple of days. I have arrived at a solution using the context package.  There was a small change on the client code to add a function "QueryWithContext". The solution is working 
(main changes can be seen on my fork: https://github.com/emluque/influxdb/commit/d353e41aa8232c6a6c20a2b8bb87eec40bac8b6f )but I'm still writing some tests, the whole thing should be done by end of week. I will then issue a merge request, I just wanted to claim the issue, since my solution is almost done.
