### ISSUE TITLE
Support more math (power, logarithm, trigonometric functions)

### ISSUE THREAD

**Issue by jordens** [influxdata/influxdb#659]
Basic math operations in queries, like a power operator, square roots, some logarithm, exponentials and trigonometric functions would be great.
I would especially like to see power and logarithms. They would come in handy especially with #438 . I would like to be able to do:

`select ain0**2 from /.*/ limit 1`

`select log10(pressure) from /.*/ limit 1`

**Comment by eliperelman** [comment]
Adding my +1 behind this.

**Comment by toddboom** [comment]
@eliperelman any functions in particular that you're needing?

**Comment by eliperelman** [comment]
I'm specifically needing square root so I can calculate upper bounds:

`select mean(value) + (1.96 * stddev(value) / sqrt(count(value)) as "upperBound" from measure ...`

**Comment by eliperelman** [comment]
Although having an upper bound function might be more succinct. :)

`select upperbound(value, 95) from myseries`

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
