### ISSUE TITLE
field type changed during usage.

### ISSUE THREAD

**Issue by majj** [influxdata/influxdb#6622]
### Bug report

__System info:__ 

influxdb-0.12.0
CentOS 5.11
 
![field_type_change](https://cloud.githubusercontent.com/assets/543810/15238823/467383ee-190f-11e6-8b08-f6a6672cb580.png)

**Comment by gunnaraasen** [comment]
Field types are set at the shard level so it is possible for different field types to exist on the same field in different shards. A new shard was likely used starting at 2016-05-09T00:00:00Z. This is likely due to a bug or ambiguity in the input protocol.

Are you using line protocol or a different input method, like the Graphite input, to insert points?

**Comment by majj** [comment]
@gunnaraasen:  line protocol,  thanks!

**Comment by gunnaraasen** [comment]
The line protocol explicitly sets field value types. Integers require an `i` to be appended to the end of the number.

Do you have a sample of the line protocol points being sent to InfluxDB during that time period? Were there any changes to the client(s)?

Can you also try the same query using the `influx` CLI? Sometimes the Javascript parsing in the admin panel does funky things with numbers.

**Comment by jsternberg** [comment]
I would actually bet this has nothing to do with the server and everything to do with JSON's inability to tell the difference between a float and an integer.

**Comment by jsternberg** [comment]
I'm going to close this since I don't think there's anything we can do about the result. If there's anything actionable we can do to help with this, please reopen the issue. Thanks.

**Comment by toddiuszho** [comment]
Is it possible for a type to set in a shard, rotated off, and then later the shard is re-used again? I'm asking because Influx has hummed along for months, but now I'm getting the int vs. float drama, despite appending 'i' at the end of all my numbers in the Line Protocol.

However, months ago, there was a bug in an HTTP POST module I was using where it would omit the last character of every line. So the final 'i' in all my POSTs were being omitted.

I believed I cleared the measurement out and started fresh. All was well for months, until now.

**Comment by jsternberg** [comment]
@toddiuszho I'm not entirely sure what you mean, but a measurement can only have one possible field type per shard. But each shard can have a different field type and with floats and integers specifically, they'll get casted to a float.

If you try the beta release, you can try to figure out if this is your problem by running:

```
> SHOW FIELD KEYS
```

This now includes an extra column that will have the field type for the column. If you see `float` there and you want integers, you can now do this:

```
SELECT value::integer FROM cpu
```

That will force integers and will convert any floats to integers by truncating them.
