### ISSUE TITLE
[0.13] batch write with HP-UX curl 400 Bad Request

### ISSUE THREAD

**Issue by ZhukovAlexey** [influxdata/influxdb#6636]
InfluxDB System info: RedHat 7, InfluxDB 0.13

I'm trying to execute the command below on HP-UX 11.31

```
curl -i -X POST 'http://vuis-test:8086/write?db=stress&precision=s' --data-binary "GC_LOG3,jvm=GBA old_after_mb=2402.12 1463404947\nGC_LOG3,jvm=GBA old_after_mb=2403.97 1463404969"
```

HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: e828f849-1b75-11e6-bf42-000000000000
X-Influxdb-Version: 0.13.0
Date: Mon, 16 May 2016 14:53:10 GMT
Content-Length: 143

{"error":"unable to parse 'GC_LOG3,jvm=GBA old_after_mb=2402.12 1463404947\\nGC_LOG3,jvm=GBA old_after_mb=2403.97 1463404969': bad timestamp"}

Something wrong with \n. I create batch insert dynamically.

```
curl  -X POST 'http://vuis-test:8086/write?db=stress' --data-binary "GC_LOG3,jvm=GBA old_after_mb=2402.12\nGC_LOG3,jvm=GBA old_after_mb=2403.97"
```

{"error":"unable to parse 'GC_LOG3,jvm=GBA old_after_mb=2402.12\\nGC_LOG3,jvm=GBA old_after_mb=2403.97': invalid number"}

But this works

```
curl -i -X POST 'http://vuis-test:8086/write?db=stress' --data-binary "GC_LOG3,jvm=GBA old_after_mb=2402.12
GC_LOG3,jvm=GBA old_after_mb=2403.97"
```

I've tried to use ansi C quoting string https://github.com/influxdata/influxdb/issues/3147#issuecomment-115486040, but it didn't work.
(But it helps me if curl is invoked on SuSe.)

**Comment by jsternberg** [comment]
I don't think that `--data-binary` for curl interprets `\n` as a newline. I think you have to use an actual newline. That would likely be the reason why the last command works because you use a real newline instead of trying to use the escape `\n`. In ANSI C terms, using `\n` in the `curl` command line is the equivalent of typing `\\n` in a C string.

I'm going to close this since it's not related to InfluxDB but related to the command line and the `curl` command. I hope that explanation helped. If you have further questions, please direct them to the [mailing list](https://groups.google.com/forum/#!forum/influxdb).

**Comment by ZhukovAlexey** [comment]
**jsternberg**, thank you.

Yes, your explanation definitely helped.

Just needed to do a concatenation with real newline symbol.

```
data_batch="${data_batch}${point}
"

```
