### ISSUE TITLE
influx cli sometimes frozes on FUTEX wait when -execute 'drop measurements...' is used

### ISSUE THREAD

**Issue by dalibort** [influxdata/influxdb#6715]
Hi,
I created (due to mistake in graphite template). about 10000 measurements like this one:
internet.asr2.snetwork.AS63859.inbytes

Since I found no way how to delete them using influx SQL commands (seems no wildcard in 'DROP measurement name' is allowed I used 'influx -execute' to list all measurements into a file and then to delete them via a simple bash script using this command line:

influx -database graphite -execute 'DROP MEASUREMENT "internet.asr2.snetwork.AS7679.inbytes"'

The problem is that the influx cli utility several times stopped responding.
When I was using 0.13.0 from your rpm another influx cli instance showed that there is running DROP MEASUREMENTS query (40minutes+ for example). Using KILL QUERY xy caused the query disappeared from SHOW QUERIES but influx with -exec remained blocked.

I upgraded to nightly build (version 0.14.0~n201605230800) in hope the problem is solved here. But later I observed the same problem several times. The only difference is that SHOW QUERIES does't  show the running DROP MEASUREMENT query.
I tried to run strace to see where the influx cli is hanging and it shows:

strace -p 5970
Process 5970 attached
futex(0x9d76a8, FUTEX_WAIT, 0, NULL

There are writes into other measurements simultaneous to the DROPs in the database

Note:
the DROP MEASUREMENT is terribly slow (deleting one measurement each several seconds). The task is running for 24hours and still not finished. Although I am testing influxdb on a virtual machine whith rather poor disk subsystem.

Regards
Dalibor Toman

**Comment by jsternberg** [comment]
Is #6563 related? It seems like the inability to use Ctrl+C is one of two things here. The other seems to be that we should offer a way to perform this kind of action asynchronously.

Kill query also only works for `SELECT` queries at the moment. @rkuchan can add a caveat to the documentation so that this limitation is at least documented while we're working on trying to allow `KILL QUERY` to be used for more than just `SELECT` queries.

Does this sound correct?
