### ISSUE TITLE
Timestamp inconsistency using FIRST / LAST aggregation functions.

### ISSUE THREAD

**Issue by OptrixAU** [influxdata/influxdb#6737]
### Bug report

__System info:__
InfluxDB 0.13.0 on Ubuntu 14.04 LTS x64

__Steps to reproduce:__

1. In a table with some content, issue asking for the FIRST value after a given date...

```
SELECT FIRST(Real_Current_Phase_A) as Real_Current_Phase_A,
    FIRST(Real_Current_Phase_B) as Real_Current_Phase_B,
    FIRST(Real_Current_Phase_C) as Real_Current_Phase_C
    FROM INCOMERPM1,DB1PMDB3
    WHERE time > '2016-05-26 09:50:00' ORDER BY time ASC LIMIT 1
```

The results are all timestamped soon after the given point.

2. Invert the query - ask for the LAST value before a given date.

```
SELECT LAST(Real_Current_Phase_A) as Real_Current_Phase_A,
    LAST(Real_Current_Phase_B) as Real_Current_Phase_B,
    LAST(Real_Current_Phase_C) as Real_Current_Phase_C
    FROM INCOMERPM1,DB1PMDB3
    WHERE time < '2016-05-26 09:50:00' ORDER BY time DESC LIMIT 1
```

The results are timestamped as Unix epoch - 1970-01-01T00:00:00Z

__Expected behavior:__ 

To be honest, I'd be satisfied if either behavior was consistent.

My absolutely ideal solution would be for the timestamp to match either the **earliest** or the **latest** timestamp on the data used in the aggregation. 

__Actual behavior:__ 

While the FIRST query gives a timestamp that appears to be something to do with the data aggregated, the LAST does not - it's always epoch. 

__Additional info:__ 

This has been validated both in the Web Admin page and via Python.

Note that if I use a UNIX TIMESTAMP (ie .seconds since epoch) instead of a string in the queries, BOTH queries return unix epoch as the timestamp.

**Comment by jsternberg** [comment]
The reason is because selectors will return the timestamp of the point if and only if it's the only function call in the query. Since there are multiple selectors and no group by interval, the time returned is the beginning start time of the query. In your first example, you use `>` as the time comparison operator so you are setting a lower bound. That's the time that gets returned. In the second example, you are using `<` which sets the upper bound instead. The default lower bound is then the epoch and you get zero for the time.

@rkuchan I took a cursory look at the documentation for functions and I don't see a note about the special time values selectors can return and the caveats. Is this somewhere I missed? If it isn't, can we get that added to prevent confusion? Thanks.

**Comment by jsternberg** [comment]
I'm closing this since the question seems to have been answered. If there's still some confusion or there's a bug, please respond and I can reopen the issue if needed.
