### ISSUE TITLE
Out of Memory (Fatal) Error when Dropping Measurement

### ISSUE THREAD

**Issue by goakley** [influxdata/influxdb#6796]
### Bug report

__System info:__
Debian GNU/Linux 8 (jessie)
3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux
InfluxDB 0.13.0

__Steps to reproduce:__
1. Collect around 50,000 data points in a single measurement
2. Attempt to drop the measurement with `DROP MEASUREMENT [name]`
3. Wait a few seconds

__Expected behavior:__
After some time, InfluxDB should signify that it has successfully dropped the measurement, or that it has encountered some error and cannot finish dropping the measurement.

__Actual behavior:__
InfluxDB crashed and took a few minutes to restart from WAL segments.  Running `DROP MEASUREMENT [name]` a second time succeeded.

__Additional info:__ [Include gist of relevant config, logs, etc.]
[Log contents](https://gist.github.com/goakley/38e78e2fbd28a9fa42e57d16a7676664) (includes stack trace)

**Comment by joelegasse** [comment]
@goakley Can you see if @jwilder's change fixes your issue?

**Comment by jwilder** [comment]
Going to close this as it should be fixed by #7015.  The logs show hundreds of writes blocked on the `tsdb.Store` mutex.  `DropMeasurement` incorrectly was holding the writing lock which locks up the whole `tsdb.Store` for writes and queries.  The lock caused writes to pile up and ultimately a compaction ran and allocation triggered an OOM.
