### ISSUE TITLE
"default" retention policy not created

### ISSUE THREAD

**Issue by phemmer** [influxdata/influxdb#6825]
### Bug report

__System info:__ 
InfluxDB 1.0beta1
CentOS/7

1. `create database test`
2. `show retention policies on test`

__Expected behavior:__ a retention policy called `default`

__Actual behavior:__ no retention policy called `default`

__Additional info:__
This is either a bug in in InfluxDB, or a bug in the documentation. [The documentation](https://docs.influxdata.com/influxdb/v0.13/guides/downsampling_and_retention/#working-with-rps) states that a `default` retention policy is automatically created when a new database is created.

This is also causing breakage when trying to use telegraf, as telegraf creates its database, but then fails with errors because the `default` retention policy doesn't exist:

```
Jun 11 19:04:10 linux telegraf[4469]: 2016/06/11 19:04:10 Output [influxdb] buffer fullness: 8816 / 10000 metrics. Total gathered metrics: 8816. Total dropped metrics: 0.
Jun 11 19:04:10 linux telegraf[4469]: 2016/06/11 19:04:10 ERROR: {"error":"retention policy not found: default"}
Jun 11 19:04:10 linux telegraf[4469]: 2016/06/11 19:04:10 Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
```

**Comment by jsternberg** [comment]
The "default" retention policy was renamed to "autogen" to avoid confusion when talking about the "default" retention policy versus the default retention policy. So now autogen is the default. This can be customized by setting this value:

```
[meta]
  default-retention-policy-name = "default"
```

I think the telegraf beta was not updated to reflect this change. I think @sparrc is working on fixing that.

With the 1.0 beta, please change your links to `v1.0` instead of `v0.13`. Thanks.
