### ISSUE TITLE
Group By tag not working with Difference Aggregate function

### ISSUE THREAD

**Issue by SekharBeri** [influxdata/influxdb#6845]
version: 0.13.0
operating system: Ubuntu 

Running Query: 

**select difference(first(consumption_count)) from DummyMeterData where time >='2015-05-01 00:00:00' and time < = '2016-06-01 00:00:00' group by month**

i am trying to execute above query, But, I am getting below error

**Server returned error: error parsing query: difference aggregate requires a GROUP BY interval**

In above query month is a tag value in mentioned measurement. I came to an understand that it should not possible to build a query with tag value while using aggregate function **diiference**. But it is working fine with Spread function. 

what is the reason that we can group by the time interval which was not happening with the tag. Can anyone help on this

Thanks in advance

**Comment by jsternberg** [comment]
The reason is because `GROUP BY interval` means to use a `GROUP BY time(...)` clause. You can group by a tag too, but it's unrelated to this error. If you remove the `first()` call, then you don't need the group by interval, but it also won't use the aggregate function (if you need it).

In the future, you can also get questions answered more efficiently using the [mailing list](https://groups.google.com/forum/#!forum/influxdb). If you have any more questions, please direct them to that mailing list. Thanks!
