### ISSUE TITLE
【v0.13】influxdb donot   collection data from  collectd 

### ISSUE THREAD

**Issue by themass** [influxdata/influxdb#6887]
collectd  conf

`   <Plugin network>
        <Server "127.0.0.1" "82586">
                Username "admin"
                Password "admin"
                Interface "eth0"
        </Server>
</Plugin>`

influxdb v0.13  conf
`
[[collectd]]
  enabled = true
  bind-address = ":25826"
  database = "collectd"
  typesdb = "/usr/share/collectd/types.db"

   batch-size = 1000 
   batch-pending = 5 
   batch-timeout = "1s" 
   read-buffer = 0 `

there is no log and data, service all is ok.

**Comment by jsternberg** [comment]
Hello @themass,

Can you send this message to the [mailing list](https://groups.google.com/forum/#!forum/influxdb) instead? We use the issue tracker for covering features or bugs related to InfluxDB rather than support questions. If there's a bug, someone on the mailing list will direct you back here to file it.

Thanks!
