### ISSUE TITLE
CQ clause to introduce relative time boundaries

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#6921]
### Feature Request

**Proposal:**

Imagine a CQ like:

```
CREATE CONTINUOUS QUERY foo ON mydb RESAMPLE EVERY 10m BEGIN
   SELECT...GROUP BY time(1d)
END
```

There are two different possible user intentions from that syntax. Currently we only support one.

**Current behavior:** 

A CQ like the above will execute every 10 minutes, but it will operate on the same interval every 10 minutes. The `WHERE` clause will be something like `WHERE time > '2016-06-27 00:00:00' AND time < '2016-06-27 23:59:59'` for every copy of the query run on that day. The query will update the total every 10 minutes, but there will be only one timestamp in the output for any given day.

**Desired behavior:** 

Many users are asking for syntax to make the CQ execute a relative offset query every 10 minutes, analogous to `SELECT...WHERE time > now() - 1d` that runs every 10 minutes, generating 144 unique points per day, not one.

**Use case:** 

Mostly useful for queries that use running average/max/min rather than one built on calendar boundaries. See https://groups.google.com/d/msgid/influxdb/e4b02849-ebb9-47a1-9a88-dbbf00822acc%40googlegroups.com

**Comment by shang-wang** [comment]
Thanks @beckettsean for adding this. Just in case anybody else wonders, as of today this could be solved temporarily using kapacitor with the suggestion given by @nathanielc in ticket #4820 . But it would be really helpful if influxdb could support it as well.

**Comment by jwilm** [comment]
We have a similar need to the desired behavior. We have a 1s granularity series for which we could like to derive another 1s dataset _based on the last 86,400 seconds of data_. This is not currently possible as this and several other issues discuss.

After reading through the CQ docs and associated discussion on this tracker, I'm left wondering why the GROUP BY is not an optional clause in a CQ. It's slightly orthogonal to this issue, but imagine if there was a `SAMPLE` (instead of `RESAMPLE`) clause which specified `EVERY <period>` -- that would allow running queries at a predefined sampling rate with on an arbitrary time span.
