### ISSUE TITLE
[feature]continuous query with time offset

### ISSUE THREAD

**Issue by jffifa** [influxdata/influxdb#6932]
Here comes a common situation that data is written to influxdb with some latency(i.e. written with timestamp specified), and when we need to do some aggregation or downsampling on such data stream, we would like to run CQ every `<interval>` time , but with some offset or latency, i.e. we want to aggregate on data between `now()-latency-interval` and `now()-latency`, instead of between `now()-interval` and `now()`.

The only way I know to do such a job is to use `RESAMPLE FOR <LONG_DURATION>` in CQ query, but that may lead to useless workload for influxdb.

For example, we may need to do aggregation on data between `now()-60seconds` and `now()-50seconds` every `10seconds`, in CQ:
```
CREATE CONTINUOUS QUERY RESAMPLE FOR 60s BEGIN ... GROUP BY time(10s) END
```
However, such CQ leads to 6 queries on data `[now()-60s, now()-50s)`, `[now()-50s, now()-40s)`, `[now()-40s, now()-30s)`, `[now()-30s, now()-20s)`, `[now()-20s, now()-10s)`, `[now()-10s, now()`, where the only useful query is the first one.

**Comment by beckettsean** [comment]
Continuous queries are designed to operate on new timestamps, and there is no way to have them exclude new timestamps. The additional queries should be idempotent, is there some harm in letting them run?

You can also use Kapacitor or ad hoc [backfill queries](https://docs.influxdata.com/influxdb/v0.13/query_language/data_exploration/#the-into-clause) to process the data.

**Comment by jsternberg** [comment]
If I understand this correctly, is this a request to have some kind of offset to delay the interval when a CQ runs? Maybe something like:

```
CREATE CONTINUOUS QUERY RESAMPLE DELAY 50s BEGIN ... GROUP BY time(10s) END
```

Maybe replace `DELAY` with `OFFSET` so we don't have to add a new keyword.

**Comment by jffifa** [comment]
> Continuous queries are designed to operate on new timestamps, and there is no way to have them exclude new timestamps. The additional queries should be idempotent, is there some harm in letting them run?

No, there is no harm but just performance concerning.

**Comment by jpriebe** [comment]
@jffifa - did you find another way to handle the delayed data situation?  I recently encountered this problem, where I'm inserting AWS CloudWatch metrics into an influxdb, and some of those metrics come in on a two- to three-minute delay (and not just sometimes; they are always delayed).

Without resampling, nothing gets written by the continuous queries.  But I worry that the extra resampling that I've defined is going to waste compute resources...

**Comment by pootzko** [comment]
Hi all,

I feel this should be re-opened. We have a situation where we have some sensor listeners which timestamp data points and then batch-send them every few seconds to Influx. This sometimes causes the latest points of the hour to be dropped from the CQ for that hour. 

I'm aware of the group by time() with the offset option [Example 4](https://docs.influxdata.com/influxdb/v1.3/query_language/continuous_queries/#examples-of-basic-syntax) but if I understand this correctly, this will shift the whole CQ interval to be calculated from say 8:00-9:00 to 8:15-9:15.. and that's not what we need. We need to roll-up the data from 8:00-9:00 but we want that event to occur at for example 9:05.

Is there an option to do this and I'm missing something or is it not possible? 

Thnx

**Comment by t0mk** [comment]
What about revwriting the CQ to kapacitor TICK script and use the shift node:
https://docs.influxdata.com/kapacitor/v1.3/nodes/shift_node/

**Comment by davidh-ssec** [comment]
I agree with @pootzko and am hoping this issue could be reopened (if there isn't another issue open somewhere). I have a situation where meteorological instrument's observations are batch sent in 1 minute intervals (5 second data) due to the commercial instrument software being used. While migrating the data ingest to a new server and adding an additional 1 minute delay (during migration) I noticed that my 1m average CQ wasn't catching any of the data in the interval because it was coming in ~50 seconds after the CQ was being run. I now get almost no 1 minute CQ data points. After I remove this 1 minute extra delay I'm still concerned that the last few data points won't be included in the CQ due to the batch sending even if the CQ does produce a value.

**Comment by davidh-ssec** [comment]
I'm running in to this situation again and was wondering if there has been any consideration to adding a feature like this. I've been reading the documentation for resampling and don't think there is any way to reliably achieve what I'm trying to do with a CQ. If I'm understanding things correctly using resampling the CQ could produce the right value after a couple executions, but it would still write a data point for the time that will get updated in the future the next time the CQ runs. My users may be requesting only the latest data point for a field and adding it to a local cache of the data (to reduce the amount of data sent). Using resampling would not work for their use case.

I could manually backfill I suppose, but I'm guessing that has quite the performance hit too. Any other suggestions?

**Comment by davidh-ssec** [comment]
@dugwood The situation you describe is exactly what I want to avoid when I mentioned users only retrieving the newest data point. In example 3, as you point out, it recalculates the data points twice. This means that if someone grabs the most recent data points from the first resample, caches them locally, and then never requests those data points again, they now have invalid data. In fact I used `EVERY`/`FOR` as a temporary workaround on my server and the next day I had an email from a user asking why the data points changed (they were actually coming up as null occasionally due to how late the data was for that interval).

As for how long is too long for late data, in this specific case it's probably 2 minutes for a 1 minute average CQ. Regardless, the data points are recalculated so users see data change over time.

**Comment by davidh-ssec** [comment]
> although you may never know exactly when the data points will be available from the source.

Right but I would like the option to choose what that threshold is without resampling multiple times. There is a point where data being late is ok. There is a point where data being later than that is *not* ok. Points that arrive within the acceptable window should be included in the average window, once. Points that arrive later than the acceptable window should not be included in the average and that is fine. If I, as the maintainer of the DB, could choose what that threshold is and not have to resample the results multiple times to do an average and don't have to set up a cronjob to run the CQs manually every couple minutes that would be awesome. I understand that InfluxDB offers options for achieving the same final result, but it seems to require extra computation or extra queries outside of the CQ system (cronjob) for this specific case.

If I had to insert all of my data over again then I would run the CQs manually which is a fairly acceptable request, especially considering I was the one who had to put all the data back in.

I'm not sure I understand your non-functional requirement statement. My hope would be that with a feature like DELAY I wouldn't need to resample at all and could do everything I want with just a GROUP BY (X minute averages every X minutes). Hopefully this all makes sense and I understand if this feature  isn't worth the development time/effort to add, but it is an issue that is not solved by the existing CQ functionality (from what I understand).

**Comment by dugwood** [comment]
As I said, the NFR is valid, should be implemented, and as you said I don't know the effort either.

The issue in your lack of resampling is to expect a result that's depends on the source (telegraf?), that can't be reproduced. Running a live log (such as a logparser) and running from an old log won't produce the same results. And you can't expect to reproduce the source as it occurred the first time (all points will be there, but the first time some were missing).

So the threshold is a good idea... but impossible to implement in order to always have the same values in the end.

But I agree that if you don't mind about the resampling or reimporting in the future, you'll be fine with your `DELAY`.

**Comment by gusutabopb** [comment]
+1 for this.

It is quite common practice and [recommended](https://docs.influxdata.com/influxdb/v1.7/guides/writing_data/#writing-multiple-points) to batch points while writing, which by definition causes a delay between the datapoint timestamp and the time it gets written into InfluxDB.

I stream live financial data which is either already timestamped or timestamped upon arrival on my streaming script. However, due to batch writing, data only gets written into InfluxDB after a few seconds, causing a `1m` based CQ I have to miss some points for a up to a few seconds.

After realizing this I am current using the `RESAMPLE FOR` work around (nicely explained by @pootzko [on this blog post](https://cmikavac.net/2018/04/03/delayed-continuous-query-data-resampling-with-influxdb/)), but as pointed out by others, 1) this wastes CPU cycles by redoing unnecessary queries and 2) creates the issue of data changing over time as pointed out by @djhoese.

**Comment by pohmelie** [comment]
Also, looks like cq (or any query) is not atomic. Since `last` aggregation can be bigger than `max` aggregation. https://github.com/influxdata/influxdb/issues/17169

**Comment by mananpatel1** [comment]
Hi , I want to set time 4:00 PM of my continuous query but current time is 5:15 PM. In built function is that , when I create new CQ it will take current time. But I want to override the time on particular CQ. 

Ex. 
current time is 5:15 and I want to execute this query.
But this CQ's time is 5:15 and I want to override the time of CQ 5:15 to 4:00.

Can I do this?

**Comment by dugwood** [comment]
> current time is 5:15 and I want to execute this query.
> But this CQ's time is 5:15 and I want to override the time of CQ 5:15 to 4:00.

@mananpatel1 if you know that CQ is exactly 5:15 and you want to run it with data up to 4:00, you just need to filter your data with `time() > now() - 75m` (5:15 - 4:00 is 60 + 15 = 75 minutes)

**Comment by mananpatel1** [comment]
> > current time is 5:15 and I want to execute this query.
> > But this CQ's time is 5:15 and I want to override the time of CQ 5:15 to 4:00.
> 
> @mananpatel1 if you know that CQ is run exactly at 5:15 and you want to run it with data up to 4:00, you just need to filter your data with `WHERE time() < now() - 75m` (5:15 - 4:00 is 60 + 15 = 75 minutes)

Whenever I create new CQ that time new measurement was not created. I think this will give the data from 4:00 to current time but I want to set my CQ's time 4:00.

**Comment by mananpatel1** [comment]
> > current time is 5:15 and I want to execute this query.
> > But this CQ's time is 5:15 and I want to override the time of CQ 5:15 to 4:00.
> 
> @mananpatel1 if you know that CQ is run exactly at 5:15 and you want to run it with data up to 4:00, you just need to filter your data with `WHERE time() < now() - 75m` (5:15 - 4:00 is 60 + 15 = 75 minutes)

I write < where time = '2021-01-18 16:00:00' > and it is working. Thank you @dugwood
