### ISSUE TITLE
[Feature Request] UI enhancements to admin web-page; alternatively new stand-alone UI tool

### ISSUE THREAD

**Issue by cgfischer** [influxdata/influxdb#6941]
### Feature Request

**Proposal:** 

We have been using the built in admin web pages with mixed results. Our developers and administrators would like to have a more refined and full featured developer / administrator UI toolset that supports:

  1) Schema navigation with something like a tree-control
  2) Dynamic statistics display that updates automatically as load conditions change;
       maybe built-in trend charts
  3) Ad-hoc query tool and data table display with paging, sorting and adjustable column widths
  4) Ability manage “saved queries” and associated data table formatting preferences including
       column widths
  5) Continuous query (tail –f …) query viewer with data table display with user adjustable
       column widths

Specifically we are looking for a tool something like TOAD, MongoChef or SQLDeveloper with feature sets that are specialized for InfluxDB and time-series data investigations.

**Current behavior:** [What currently happens]

**Desired behavior:** [What you would like to happen]

**Use case:** [Why is this important (helps with prioritizing requests)]

**Comment by jsternberg** [comment]
I don't think we have any plans at the moment to enhance the admin web page. The admin web page is mostly for quick user testing when initially testing InfluxDB and we don't want to build it out into something like Grafana or Chronograf.

/cc @nhaugo

**Comment by yonger1516** [comment]
it will be very useful if we can generate chart from admin web UI, which is really a different requirement from Grafana and so on which suit for monitoring but not for analyzing.
As a performance tuning engineer, i don't have to monitor all hosts in dashboard because we always change hosts, so if we want to have a look for a specified time range in a host for all resource usage, no tool can do this easily.
I know influxdb has similar feature in version 0.8 but you  deprecated it in later release. I don't think you will get this feature back, so i just request you a help: if i want to separate this feature from 0.8 of source code and integrate it into your later stream personally, is it possible or easy to do? how ?

**Comment by Tomcat-Engineering** [comment]
@yonger1516: 

Looks like they are deprecating the whole Admin interface and suggesting that we use Grafana or Chronograf instead: https://github.com/influxdata/influxdb/commit/b6863b04d1be975b01f8cf239604d87e8c55b91d

However, if you want basic graphs in the Admin interface, you can check out my branch here: https://github.com/Tomcat-Engineering/influxdb/tree/graphs-in-admin-interface.

Annoyingly, I just finished writing it when I noticed the deprecation notice!

Here's what it looks like:

![screen shot 2016-11-13 at 20 32 37](https://cloud.githubusercontent.com/assets/12047075/20248648/6407feaa-a9e0-11e6-8bdb-f17d8c5b6273.png)
