### ISSUE TITLE
Performance of SHOW MEASUREMENTS needs improvement

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#6950]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

InfluxDB 0.13+

__Steps to reproduce:__

query `SHOW MEASUREMENTS`, it often takes multiple seconds.

@mjdesa is working up a test of response times vs. measurement count.

**Comment by mjdesa** [comment]
Single data node cluster. Instances type `m4.xlarge`.
![unspecified](https://cloud.githubusercontent.com/assets/1477539/16534535/489d56c0-3f95-11e6-8fab-cbc1ca3a688e.png)

**Comment by beckettsean** [comment]
@mjdesa so in all cases `SHOW MEASUREMENTS` returns in less than 1 second for ~40000 measurements? Using 0.13 or 1.0 looks like sub-second response times until > 100k measurements?

**Comment by mjdesa** [comment]
@beckettsean that seems to be the case.

![unspecified](https://cloud.githubusercontent.com/assets/1477539/16536364/4bfb4b00-3fa5-11e6-96b9-c963f0c104b2.png)

**Comment by mjdesa** [comment]
The results could be a little bit artificial because I only have one series for each measurement. If anyone thinks it'd be worthwhile I can extend this test to check what happens when each measurement has many series.

**Comment by beckettsean** [comment]
@benbjohnson @jsternberg do you think the performance of `SHOW MEASUREMENTS` would be affected by the number of series in each measurement? My gut says not enough to make it worth testing.

**Comment by r3cgm** [comment]
Without overly complicating the testing methodology, I'd be curious to see side-by-side results for 200k series fetched as one big result vs. two fetches of 100k records apiece using pagination.  Seems like it should take the same amount of time but does it?  I don't have a sense for how much transactional overhead there is independent of the actual query being run.

Are there ideas on board for caching results or otherwise speeding up the response time?  Even if you just kept a stateful in-memory copy of all series so they could be returned instantly that would be really helpful.  I wouldn't think the overhead would be that much to maintain such a data structure but I'm just guessing.

If there are new patches to the code I can probably test them out from the daily builds.  Hope there is movement on this issue soon. :)

**Comment by jsternberg** [comment]
I don't think that the number of series will affect the timing of this. I do think it is possible that the number of shards can affect the timing of this in a negative way. @desa is it possible to extend the test to also include the time period of multiple shards? In the tests you have done so far, what's the number of shards?

I don't know if it's significant enough to matter, but it can potentially be a confounding variable that isn't accounted for. When testing, you may want to try setting the shard duration to something like a year just to make sure that it doesn't affect the results.

**Comment by desa** [comment]
@jsternberg I made a note of to this for future reference if we do decide that we want to test this with many shards.
