### ISSUE TITLE
[Feature Request] Time literal arithmetic

### ISSUE THREAD

**Issue by azhmur** [influxdata/influxdb#7001]
### Feature Request

**Proposal:** Implement basic arithmetic operations for time literals

**Current behavior:** We can't use any expressions with time literals

**Desired behavior:** `1m/1s = 60`

**Use case:** Grafana uses $interval macros to specify automatic interval on charts. We like to get something like "value per second" metric. 
`select sum(value)/(1m/1s) from measure group by time(1m)`

**Comment by urill** [comment]
I am using influxdb+grafana for rotations per minute monitoring. This feature will be very useful.

**Comment by leesjensen** [comment]
This would help my problem. I am currently grouping by time and another metric say 'service'.

`select sum(value) from x group by time(1m) service`

The problem is that if my sample time doesn't match my aggregation time then I can't adjust for the sample time properly and I end up with inflated summation values.

For example think of a sample time of 15 seconds and a aggregation time of 1 minute.

If I could do this it would fix it:

`select sum(value)/(1m/15s) from x group by time(1m) service`

Or more generally in a system like Grafana:

`select sum(value)/($interval/15s) from x group by time($interval) service`

**Comment by azhmur** [comment]
Grafana made workaround $__interval_ms.
