### ISSUE TITLE
discussion: Should multiple selectors in a query return more than one line of results?

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7045]
### Feature Request

**Proposal:** [Description of the feature]

`SELECT LAST(foo), MAX(bar), FIRST(baz)...` should return three lines in the result, not one. That way the actual timestamp for each point can be provided.

**Current behavior:** [What currently happens]

Given these points:

```
> select * from selector
name: selector
--------------
time            bar baz foo
1469126083643297249 1   15  12
1469126089187079301 12  12  1
1469126100199191932 42  42  42
1469126128754879528 2   0   22
```

The return from three selectors has no meaningful timestamps:

```
> SELECT LAST(foo), MAX(bar), FIRST(baz) FROM selector
name: selector
--------------
time    last    max first
0   22  42  15
```

**Desired behavior:** [What you would like to happen]
Instead, what if the return were as follows:

```
> SELECT LAST(foo), MAX(bar), FIRST(baz) FROM selector
name: selector
--------------
time    last    max first
1469126128754879528 22  
1469126100199191932     42  
1469126083643297249         15
```

**Use case:** [Why is this important (helps with prioritizing requests)]

Right now, multiple selectors in a single query returns only the field values, not a timestamp. Selectors are returning a single point, so the timestamp is often meaningful information. We can reduce overall queries for systems if multiple selectors can be used in a single query, rather than forcing users to do `SELECT LAST(foo)...; SELECT MAX(bar)...; SELECT FIRST(baz)...`

**Comment by beckettsean** [comment]
@pauldix @jwilder @nhaugo @gunnaraasen @jsternberg thoughts?

**Comment by gunnaraasen** [comment]
I'm not a huge fan of this proposal since it feels like it would be awkward to parse the results for these kinds of queries.

I would suggest creating separate functions for selectors that return the time of the point, e.g. `LAST_TIME(foo)`, `MAX_TIME(bar)`, etc. Then results would look something like this. 

```
> SELECT LAST(foo), MAX_TIME(bar), MAX(bar), FIRST_TIME(baz), FIRST(baz) FROM selector
name: selector
--------------
time                last max_time            max first_time          first
1469126128754879528 22   1469126100199191932 42  1469126083643297249 15
```

(This assumes the first selector's time is automatically returned as the `time` column, which is consistent with the single selector behavior but also not really intuitive.)

**Comment by gunnaraasen** [comment]
Some slight variations would be adding an optional property to selector functions to return the timestamp.

```
> SELECT LAST(foo), MAX(bar, time), MAX(bar), FIRST(baz, time), FIRST(baz) FROM selector
name: selector
--------------
time                last max_time            max first_time          first
1469126128754879528 22   1469126100199191932 42  1469126083643297249 15
```

Or a meta-selector function called `TIME()`.

```
> SELECT LAST(foo), TIME(MAX(bar)), MAX(bar), TIME(FIRST(baz)), FIRST(baz) FROM selector
name: selector
--------------
time                last time_max            max time_first          first
1469126128754879528 22   1469126100199191932 42  1469126083643297249 15
```

**Comment by jsternberg** [comment]
I would also vote no for this. I think it might be worth talking in the future about changing the HTTP response since I don't think it's in the correct format, but I don't like the idea of sending back a nil value and I agree with @gunnaraasen that it makes our (already difficult) response harder to parse.

I think one of the approaches @gunnaraasen used as an alternative may be an appropriate solution. I'm hesitant to do something like `MAX(bar, time)` as I think it makes it more difficult for the parser, but using `TIME()` as a function may be good. We would need a bit of a refactor to the query validator though as the query validator is too hard to work with right now to properly do nested functions.

**Comment by pauldix** [comment]
I'm sure we already wrote this up in an issue somewhere. The idea that we had landed on (I thought) was something like this:

```sql
SELECT max(foo), time(max, foo) as max_foo_time, 
       min(bar), time(min, bar) as min_bar_time
FROM asdf
```

This would give you the power to set the column names of the times explicitly.

**Comment by aleonnet** [comment]
Hi guys, this feature is really needed.
Actually I have to perform three queries instead of one to get min/max/last power measurements instead of one:

SELECT min("power") AS "min_power", time as "time_min" FROM "sensors"."autogen"."electric" WHERE time > now() - 24h AND "id"='40997'
SELECT max("power") AS "max_power", time as "time_max" FROM "sensors"."autogen"."electric" WHERE time > now() - 24h AND "id"='40997'
SELECT last("power") AS "last_power", time AS "time_last" FROM "sensors"."autogen"."electric" WHERE "id"='40997'
