### ISSUE TITLE
Incremental backup size

### ISSUE THREAD

**Issue by bovy89** [influxdata/influxdb#7073]
Hi,
I'm making backup of my influxdb database on a remote server via influxd command and my aim is to make incremental backup every day or more often.

Currently, my production data size is about 200GB and I'm doing daily incremental backup using the -since option, but the backup size, after a few days, is very different compared to production (e.g. 300GB+).

Am I doing something wrong or I'm missing something to achive this result?

As attachment, you can find my backup script.
[bkp_script.sh.txt](https://github.com/influxdata/influxdb/files/390133/bkp_script.sh.txt)

OS: Centos 6.7
Influxdb version: 0.13 (was 0.10) both pre-built package

**Comment by bovy89** [comment]
[bkp_script.sh.txt](https://github.com/influxdata/influxdb/files/390133/bkp_script.sh.txt)

**Comment by max3163** [comment]
I have the same problem on ur installation. 
The size of the backup database grow up more quickly than ur production database.

**Comment by max3163** [comment]
No news about a fix  ?

**Comment by WuBingzheng** [comment]
same problem. Any progress?

**Comment by acapogna-pf** [comment]
Hi guys, I know it's been a while, but i'm having this issue in v1.8.10, after restoring (portable) data from another instance running 1.8.9 i see the data size is insanely bigger than the source (500 GB before vs 1.7 TB after restoration).
I think the problem is more on the backup step, as i see backup is 500 GB size but all in .gz, so unzipping such file will most likely result in the bigger size (which lead me to exclude the import step).
Can you please advice on how to act?
