### ISSUE TITLE
[Feature request] Shards should track their last modified (wall) time

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#7079]
### Feature Request

**Proposal:** 

When I run `SHOW SHARDS`, I would like to see the wall time of the last time a shard was modified (either data inserted or deleted). Currently this information is not available through InfluxQL.

**Use case:** 

To assist with incremental backup and restore, seeing when a shard was last modified would inform the operator whether a single shard's backup needs to be updated or whether it is still up-to-date.

If a shard's end time is in the future, it will typically need to be re-backed up. But for old shards, there's no simple way to know if a backup is still in sync or whether old data has been modified.

**Comment by jsternberg** [comment]
I think this might be possible by just using the mtime of the latest mtime within the folder.

**Comment by jwilder** [comment]
#7651 exposes the underlying data.  Query language could be updated now.

**Comment by jsternberg** [comment]
A few notes about this. @jwilder thinks this should be used to improve incremental backup rather than forcing an operator to look up the times with `SHOW SHARDS` so we may want to add that functionality as part of this. I'm not aware of what we would have to do to make that happen, but it seems like a decent idea that should be written down.

For the original proposal, there's a little bit of an issue that may be the case when it comes to this. There's no way to send back a time in the JSON without using either a string or an integer. So I'm not sure which one of these to send back. Sending back an integer, while probably better, may be an issue in that the client won't know to convert that integer into a time value for pretty print displays.
