### ISSUE TITLE
UDP performance issues with dropped points and high memory usuage

### ISSUE THREAD

**Issue by bischofs** [influxdata/influxdb#7091]
We are currently having issues with the UDP functionality of influx. We are sending over 75 unique data points per batch at about ~8000 points per second with around 1000 distinct series. After a certain amount of time we begin to drop udp points.

We are running 0.13 and here is our udp configuration. Why does the system drop points if it cant keep up? Should we implement some sort of queue in front of influx so that points are not dropped? Our application requires all the data to be in the database, at the expense of real time viewing.
```

[[udp]]
  enabled = true
  bind-address = ":8089"
  database = "udp"
  # retention-policy = ""

  # These next lines control how batching works. You should have this enabled
  # otherwise you could get dropped metrics or poor performance. Batching
  # will buffer points in memory if you have many coming in.

  batch-size = 100000 # will flush if this many points get buffered
  batch-pending = 25 # number of batches that may be pending in memory
  batch-timeout = "10s" # will flush at least this often even if we haven't hit buffer limit
  read-buffer = 8388608 # UDP Read buffer size, 0 means OS default. UDP listener will fail if set above OS max.

  # set the expected UDP payload size; lower values tend to yield better performance, default is max UDP size 65536
   udp-payload-size = 65536
```

**Comment by MikeSchroll** [comment]
Can you confirm its only 1000 series by sharing your series cardinality by running:
SELECT sum(numSeries) AS "total_series" FROM "_internal".."database" WHERE time > now() - 10s

I'm just a concerned user with a similar setup, so hoping I don't run into this problem.

**Comment by jsternberg** [comment]
Can you confirm that all of the packets are even reaching the database? This sounds like normal behavior for UDP. UDP isn't guaranteed to reach the destination and it's possible the OS is just dropping packets when the interface is overwhelmed with points. If you need an absolute guarantee for the data to be there, you'll likely need to use the HTTP line protocol which operates over TCP.

I'm going to close this since it doesn't appear to be a bug, but a normal function of the network protocol. If I'm wrong, please respond and I can reopen the issue if there's a bug in the software somewhere. If you need help with using the HTTP line protocol or how to properly use the UDP service, you can ask on the [mailing list](https://groups.google.com/forum/#!forum/influxdb).
