### ISSUE TITLE
[Feature request] PERCENTAGE_BETWEEN() function

### ISSUE THREAD

**Issue by ConradIrwin** [influxdata/influxdb#7105]
### Feature Request

__Proposal:__ Add a new function PERCENTAGE_BETWEEN() that allows you to calculate the inverse of a percentile. (percentiles answer the question "what latency are 80% of users experiencing", percentage between answers the question "what % of users are experience latency > than 50ms").

__Use case:__ We want to classify latency into buckets of "great/good/ok/bad/awful" so we can get a quick visualization of "how many users are seeing slow performance?"
![a4ncvwt](https://cloud.githubusercontent.com/assets/94272/17310750/3c4bd364-57fb-11e6-9a61-15cb8fb95969.png)

We currently do this using grafana's support for stacked metrics, using queries of the form: 
```
SELECT count(value) FROM "ui.switch_thread" WHERE $timeFilter AND value <= 25 GROUP BY time($interval)
SELECT count(value) FROM "ui.switch_thread" WHERE $timeFilter AND value > 25 AND value <= 50  GROUP BY time($interval)
SELECT count(value) FROM "ui.switch_thread" WHERE $timeFilter AND value > 50 AND value <= 100  GROUP BY time($interval)
SELECT count(value) FROM "ui.switch_thread" WHERE $timeFilter AND value > 100 AND value <= 1000 GROUP BY time($interval)
SELECT count(value) FROM "ui.switch_thread" WHERE $timeFilter AND value > 1000 GROUP BY time($interval)
```
I would like to be able to construct these lines without requiring any additional filtering in the WHERE clause so that it's easy to define a single continuous query that down-samples these lines, the end result would look something like this:

```
SELECT PERCENTAGE_BETWEEN(value, 0, 25),
              PERCENTAGE_BETWEEN(value, 25, 50),
              PERCENTAGE_BETWEEN(value, 50, 100),
              PERCENTAGE_BETWEEN(value, 100, 1000),
              PERCENTAGE_BETWEEN(value, 1000, 10000000000000)
FROM "ui.switch_thread" WHERE $timeFilter;
```

There's an open question as to how to specify inclusive vs. exclusive ranges, I suggest that the lower-bound is tight, PERCENTAGE_BETWEEN(value, 0, 25) would match results where `0 <= value < 25`, but if adding new syntax is an option it might be more explicit to do:

`SELECT PERCENTAGE(0 <= value < 25)`

**Comment by jsternberg** [comment]
What's the intended output of this? Is the function supposed to operate more as a filter for existing data? The current implementation acts as a selector and will only output one value. For that, I'm not sure the query example you gave makes much sense since they wouldn't line up well.

```
SELECT PERCENTAGE_BETWEEN(value, 0, 25),
              PERCENTAGE_BETWEEN(value, 25, 50),
              PERCENTAGE_BETWEEN(value, 50, 100),
              PERCENTAGE_BETWEEN(value, 100, 1000),
              PERCENTAGE_BETWEEN(value, 1000, 10000000000000)
FROM "ui.switch_thread" WHERE $timeFilter;
```

This seems like each one would be a separate query, but I'm still not certain of the desired output. Could you give me a small example of some simple data and the expected output?

**Comment by ConradIrwin** [comment]
When I started implementing this, I realised that it's one level of abstraction too far.

Instead what I really want is a conditional count (syntax TBD).

```
SELECT 100 * count(0 <= latency < 100)/count(latency) FROM page_load
```

Let's say we have this data:

```
page_load
--------------------------
time                | latency
2015-08-01T01:01:01 |  50
2015-08-01T01:01:02 |  60
2015-08-01T01:01:03 |  150
2015-08-01T01:01:04 |  40
2015-08-01T01:02:00 |  30
2015-08-01T01:02:01 |  40
2015-08-01T01:02:02 |  60
2015-08-01T01:02:03 |  40
2015-08-01T01:03:00 |  110
2015-08-01T01:03:01 |  120
2015-08-01T01:03:02 |  130
```

The question I'm trying to answer is "what % of page loads were under our target of 100ms over time"

```
SELECT 100 * count(0 <= value < 100)/count(value) AS under_target FROM page_load GROUP BY time(1m)
```

```
page_load
=======
time                | under_target
2015-08-01T01:01:00 | 75%
2015-08-01T01:01:00 | 100%
2015-08-01T01:01:00 | 0%
```

Obviously it might be better to use a different name instead of `count()`.


# Aside: current implementation

Right now to do this we add an extra field to the table:
```
page_load
--------------------------
time                | latency  | under_target
2015-08-01T01:01:01 |  50      | 1
2015-08-01T01:01:02 |  60      | 1
2015-08-01T01:01:03 |  150     | 0
2015-08-01T01:01:04 |  40      | 1
2015-08-01T01:02:00 |  30      | 1
2015-08-01T01:02:01 |  40      | 1
2015-08-01T01:02:02 |  60      | 1
2015-08-01T01:02:03 |  40      | 1
2015-08-01T01:03:00 |  110     | 0
2015-08-01T01:03:01 |  120     | 0
2015-08-01T01:03:02 |  130     | 0
```

And then do:

```
SELECT 100*sum(under_target)/count(under_target) FROM page_load
```

Which gives the same result.

```
page_load
=======
time                | under_target
2015-08-01T01:01:00 | 75%
2015-08-01T01:01:00 | 100%
2015-08-01T01:01:00 | 0%
```

What I'm trying to avoid is the need to add extra columns to make this work.

**Comment by jsternberg** [comment]
Hm, if I understand you correctly, then you don't necessarily want a new function, but a way to have the `WHERE` clause act conditionally per aggregate query rather than forced within the `WHERE` clause. I think we would need to hash out a syntax that makes sense, but I don't think we currently have a way to do what you're asking.

With your original issue, I think it's easier to just continue treating them as separate queries. I don't think `PERCENTAGE_BETWEEN()` makes sense as a function since I think the work can be done through a `WHERE` clause and mixing multiple `PERCENTAGE_BETWEEN()` calls would result in a very strange output.

If it's OK, can I close this issue and open a new one for the conditional aggregation syntax? I have a feeling that it might be covered by subqueries whenever we work on those, but that hasn't been specced out so I don't know yet.

**Comment by ConradIrwin** [comment]
Yup, I think you're right. Can you link this issue to the conditional aggregates one when you make it please :).
