### ISSUE TITLE
Client: Support for async writes

### ISSUE THREAD

**Issue by wienczny** [influxdata/influxdb#7124]
Please add support for async writes to the influxdb client like the Java client already supports. It would be great if the client supported automatic flushes after X items add added or after a given timeout is reached.

I would like to send batches of at most 100 items at least every 60s to influxdb.

This could be implemented as wrapper around the Client interface.

**Comment by BrannonKing** [comment]
Which client are you referring to, exactly? Most languages support asynchronous HTTP calls.

**Comment by wienczny** [comment]
Sorry, I was referring to the golang v2 client. I looked at the code and saw '''Write''' sending the http request.

**Comment by jsternberg** [comment]
We are going to be making a new client with better support for the features within InfluxDB at influxdata/influxdb-client. This will allow us to keep the client separate from the main repository so that people who are using it don't have to download the entire server to use the client.

I'm going to close this issue since we are not going to modify the client library within this repository. Please recreate this issue in that new repository so we can be sure that we support this functionality. Thanks.
