### ISSUE TITLE
Clustering issue on v0.11

### ISSUE THREAD

**Issue by Abhishekpan** [influxdata/influxdb#7148]
Hi,

I am using clustering features of InfluxDB v.0.11 and kept both node as a hybrid node. If both nodes are up its working fine  but if I down any of the node I am getting write error. I can say influxDB service got down.
So my question is
If any of the node is down, will influx service be still available ?

**Comment by jsternberg** [comment]
Sorry @Abhishekpan, clustering is no longer supported in the open source version and we do not support v0.11 anymore. You can try the mailing list to see if someone is willing to help, but you may not get an answer.

The issue tracker is only for feature requests or bugs.

From an initial guess based on your question, I would bet you are trying to write with a consistency of `all` and have a replication factor of 2. That will cause it to fail because it can't write to one of the two nodes. Or you're trying to write to the server that is dead. It also might just be broken and not work. Clustering wasn't a complete feature in v0.11 and it had a lot of bugs.
