### ISSUE TITLE
Add hyperloglog functions

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#717]
For people that want to calculate distinct counts across large numbers of items, we should support HyperLogLog functions. I was thinking of something like this: http://antirez.com/news/75

Basically have an aggregate that will output a string like the redis implementation. And have a function for summing them and another function for outputting the count. Like this:

``` sql
select hllHash(user_id) from events group by time(1h) into 1h.hll.events

select hllSum(hllHash) from 1h.hll.events

select hllCount(hllSum(hllHash) from 1h.hll.events where time > now() 30d

select hllCount(hllHash(user_id)) from events group by time(1d) where time > now() - 7d
```

Notice the examples where we're chaining them together.

**Comment by howie** [comment]
+1

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by lesam** [comment]
Re-opening as this is now actively worked on for 1.x

**Comment by lesam** [comment]
Note the was only implemented in 1.x, the corresponding issue to implement HLL in flux is here: https://github.com/influxdata/flux/issues/354
