### ISSUE TITLE
LIMIT should be performant regardless of the number of points queried

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7182]
We continue to get reports from customers that `SELECT...LIMIT 1` is RAM-intensive when there is no time range boundary on the query. 

It seems to me that a LIMIT query need never sample more than one shard to find the answer. Why do unbounded LIMIT queries seem to sample all points?

@jsternberg

**Comment by jsternberg** [comment]
So there's a really simple answer for why LIMIT needs to sample all shards (it does not need to sample all points and it doesn't do that in 1.0-beta3). The reason is because LIMIT is the last point _for that series_.

__Example:__

```
cpu,host=server01 value=2 10
cpu,host=server02 value=2 10000
```

When you ask `SELECT * LIMIT 1 GROUP BY host ORDER BY desc`, the question you are asking is "What is the last point for every series with a unique host?" We may occasionally need to check every shard to know the answer to that question since we have to search through all of the shards backwards so that we could return both of the points above.

When you put a time range, you say, "I don't care about a series if its last point is older than this value." With the above query, we don't know that information and can't make that assumption.

We have a few optimizations though to make this faster. One is that shards will only return a limited number of points for each shard. This optimization was older and was put in because we would scan all shards for any unique series that we were trying to find and throw out values we didn't care about. Throwing out values took a lot of time so we stopped doing that.

There should be a second one @benbjohnson worked on that should be far better. @benbjohnson sorted the order of the shards we sampled by the times on the shards so we didn't have to merge the streams later, but just concatenate them. That also means that we can stop sampling shards when we read all series, but that's frankly unlikely since there will likely be at least one point needed from each shard in a normal system.

@benbjohnson can you confirm that with two shards, shard 1 and shard 2, we don't look in shard 1 anymore if we found the series in shard 2 for LIMIT?

**Comment by jsternberg** [comment]
Also @benbjohnson's optimization is only in the nightly at the moment. It didn't make it into beta3. The other optimization is in beta3, but it doesn't perform very well if the user has a very large number of shards.

**Comment by beckettsean** [comment]
Thanks for the updates, @jsternberg. Do you know if @benbjohnson's updates are in the RC1?

**Comment by benbjohnson** [comment]
@jsternberg I added limiting to restrict how many shards are processed at once (https://github.com/influxdata/influxdb/commit/6c7d56d). Is that what you're thinking of? That won't limit the number of shards processed in total though.

**Comment by jsternberg** [comment]
Ah, I figured that restricting the number of shards processed would cause the limit iterator to never process some of the lazy iterators because it had already reached the limit. If we haven't done that, we would try to do that.

**Comment by jsternberg** [comment]
Related to #7303.

**Comment by jsternberg** [comment]
I'm going to try working on this again. I think the internals for the query engine have improved since I last worked on this so it might be easier to get this working. Previously, we tried using lazy iterators for this and I think those ended up being faster. But, it slowed down other queries. So I'm going to try seeing if we can do something similar with lazy iterators but only for limit queries.

**Comment by balalinux** [comment]
I understand that we need to sample all the shards when we have "ORDER BY" in the query. But, even for "SELECT...LIMIT 1" why does this still crashes the influxdb server. Btw, Im running 1.2.2.

Thanks.

**Comment by jimaek** [comment]
Will this get fixed in the upcoming massive 1.3.0?

**Comment by mitar** [comment]
Still relevant, I think.

**Comment by foobar** [comment]
still relevant on 1.7.x
