### ISSUE TITLE
Re-add support for syslog logging

### ISSUE THREAD

**Issue by kbabioch** [influxdata/influxdb#7190]
### Feature Request

**Proposal:** Re-add support to log to syslog directly rather than being forced to use log files.

**Current behavior:** Currently it seems to be impossible to log the syslog directly. Such a feature was implemented back in #902, but it has been removed since then for no apparent reason 06bfd9c4 as pointed out by @swdream in #902.

**Desired behavior:** It should still be possible to log to the syslog directly with an appropriate option and/or log target.

**Use case:** Direct syslog integrates better with the whole logging stack available on Unix systems. You can send off your logs to a centralized server, etc. It also integrates much better with systemd (i.e. the journal) and you no longer have to clean up and rotate your logfiles for yourself.

**Comment by jwilder** [comment]
The process logs to stdout and stderr which you should be able to redirect to logger and add tags or send remotely. Does that not work?

**Comment by kbabioch** [comment]
Yes, redirecting output works, but this is not the same as directly logging to the syslog, since a lot of meta information is missing. Sure, one can make use of logger and pipe messages in that way, but this is not exactly a clean solution. Also I cannot assign any senseful priority to messages logged this way, since it applies to all of them and I'm not familiar with the internals of influxdb. This is really something that needs to be handled by the application itself, since only it know what to consider as warning, error, etc.

Logging to syslog (and/or journal) is something an application should support natively, not by some workaround the administrator has to implement. Given that this was already implemented and basically each other serious daemon is doing it correctly, I'm not sure where the reluctance to re-add this support is coming from? Personally I consider this to be a major regression.

**Comment by jsternberg** [comment]
If you use systemd (the default in Ubuntu 16.04 and Red Hat 7/CentOS 7), you can configure the journal to log to the syslog. That seems like it would work.

The reason why there's some reluctance is because it requires additional code and this seems like something that should be done by another application. Can you give me some examples of applications that support natively logging to syslog? I know some exist, but I believe most just log to files and upstart or systemd to log to syslog. Is there a reason why those solutions won't work? What meta information is missing?

**Comment by jsternberg** [comment]
Related to #7036 since we'll need that refactor if we're going to include meta information about log levels.

**Comment by kbabioch** [comment]
> you can configure the journal to log to the syslog. That seems like it would work.

For me it is the other way around, I want all of my logs to be in the journal, along with as much meta information as possible. Sure, I can pipe in your stdout and stderr, but this way all messages are messages, they don't have a priority assigned.

> and this seems like something that should be done by another application.

No, it is the responsibility of the application to produce useful log information by using standard interfaces (e.g. syslog and/or journal). Dumping everything onto stdout is not a particular nice way.

>  Can you give me some examples of applications that support natively logging to syslog?

Basically every well-behaved daemon does it. This is an ad-hoc list of daemon I am running

- [Dovecot][1]
- [Postfix] [2]
- [Grafana][3]
- [sshd][4] (options -e and -E to explicitly disable it)
- [ntpd][5] (option -l to explicitly disable it)
- [named][6]
- [openvpn][7] (option syslog)

>  I know some exist, but I believe most just log to files and upstart or systemd to log to syslog.

Are you serious? Usually it is the other way around. Daemons produce log information using the syslog interface, which in return is then delegated into logfiles by a syslog daemon, e.g. rsyslogd. 

>  Is there a reason why those solutions won't work? 

It makes administration a major PITA. When the syslog interface is used, it is easy for an administrator to change log targets (local files, central log server, etc.), but with simple files it is not as easy. Simply dumping information into a file is very inconvenient for system administration.

>  What meta information is missing?

For starters the log level. Depending on the setup, the administrator may decide that he only wants to log errors, etc. With braindead files this is not possible. The journal supports [several][8] other fields. In case you want to support this (and hence add support for systemd), also consider adding support for [sd_notify][9], so systemd can better look into the internal status of influxdb and make use of its watchdog functionality. This, however, should probably be tracked in a separate feature request.

[1]: http://wiki2.dovecot.org/Logging
[2]: http://www.postfix.org/BASIC_CONFIGURATION_README.html#syslog_howto
[3]: http://docs.grafana.org/installation/configuration/#log
[4]: http://man.openbsd.org/OpenBSD-current/man8/sshd.8
[5]: http://linux.die.net/man/8/ntpd
[6]: http://www.zytrax.com/books/dns/ch7/logging.html
[7]: https://openvpn.net/index.php/open-source/documentation/manuals/65-openvpn-20x-manpage.html
[8]: https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#
[9]: https://www.freedesktop.org/software/systemd/man/sd_notify.html

**Comment by jsternberg** [comment]
I've linked this to our refactor of the logging system since I don't think we'll do this before that anyway. We don't currently have a logging level so a syslog logger wouldn't add that information at all at the moment. Our current logging system also doesn't make this easy, but the refactored logging system would make this much easier.

**Comment by steve-mushero** [comment]
Note Apache, MySQL, and other larger daemons have been adding services for these over the years as you can set the facilities, etc. plus then easily send all machine/service logs to ELK, etc. without extra work.  Not perfect and there are other ways/feeds, plus watchers like Telegraf, Logstash, etc. also for various use cases, but logging to syslog should be done on any nice Linux daemon.

**Comment by Artanicus** [comment]
Any update on this? Would avoid a lot of pain to just go straight to syslog without having to parse the nonsense zap format for level etc.

**Comment by AndyMender** [comment]
I think InfluxDB should provide some log level granularity. As it is now, on Linux systems running systemd everything (stdout and stderr) gets sent as-is via rsyslogd to journalctl, which then turns the log into a homogeneous binary stream of debugging level information. Much of it (regular HTTP/HTTPS POST requests) is not needed for daily use and just floods the otherwise useful system journal. If you include Grafana and Telegraf, it's very difficult to read anything from it.

FreeBSD passes stdout and stderr to a logger with the INFO severity level and the DAEMON facility. stdout and stderr can be split, however that's still hardly any granularity.

**Comment by DG12** [comment]
Again.
Adding syslog for at least a few critical messages would not be difficult and would be a huge help.

For Example:  "fatal error: runtime: out of memory" should be sent with priority  crit (even alert or emerg)

The config file implies this is actually in place in the [logging] stanza!
