### ISSUE TITLE
write failed : indirectIndex: not enough data for max time

### ISSUE THREAD

**Issue by freeseacher** [influxdata/influxdb#7202]
### Directions
Db failed with error in topic

### Bug report

__System info:__ 
```
# influx -version
InfluxDB shell version: 1.0.0~rc1
```

RHEL 7.2

full debug info as requested 
[influx.zip](https://github.com/influxdata/influxdb/files/434335/influx.zip)

**Comment by freeseacher** [comment]
After stopping influxdb and moving file to a separate directory start hang on this trace
[bug.txt](https://github.com/influxdata/influxdb/files/434397/bug.txt)

**Comment by freeseacher** [comment]
[bug2.txt](https://github.com/influxdata/influxdb/files/435727/bug2.txt)

**Comment by freeseacher** [comment]
[bug3.txt](https://github.com/influxdata/influxdb/files/435728/bug3.txt)

**Comment by freeseacher** [comment]
The latest on makes system unusable with cyclic reboot. 
Please add an option to ignore or autorecover broken tsm files... 
Or add some debug info what exact file was broken so i can automate it with external tooling

**Comment by freeseacher** [comment]
[bug4.txt](https://github.com/influxdata/influxdb/files/436496/bug4.txt)

next one. same behavior. cyclic reboot.

**Comment by jwilder** [comment]
@freeseacher This a dup of several other issues you have logged.  See this [thread](https://github.com/influxdata/influxdb/issues/6958#issuecomment-233003037).  There is something about your setup that is causing memory and/or data corruption and unfortunately I don't know how to reproduce it to better handle it. 

In that thread, you had mentioned vmware migrations as well clocks getting reset.  In this issue you mentioned copying files from one dir to another.  The database does not modify TSM files once written, so if they are corrupt, it's likely something external has corrupted them.  Since the errors you have logged are from very different parts of the system, that also leads me to believe it's not an issue in the database itself and is more likely something in your environment.  That could be hardware issues, host migration, file system bugs, kernel issues, etc..
