### ISSUE TITLE
Feature request: fill(previous) for sparsely filled fields.

### ISSUE THREAD

**Issue by retorquere** [influxdata/influxdb#7216]
On recommendation of @beckettsean (https://github.com/influxdata/influxdb/issues/6878#issuecomment-242527032):

**Proposal:** support fill(previous) for sparsely filled fields on regular, non-grouped selects. I have a measure where I have many timestamps have GPS coordinates (GPS.latitude, GPS.longitude) but only a subset of those has weather info (Weather.temperature and some others). This sparsely populated weather data semantically means "if you find no value, the previous value can be assumed to be valid for the current timestamp". A `fill(previous)` sounds perfect for this, but fill(previous) only works when I group by timeslice. There are many cases however where I want each individual point, just with the "blanks filled in".

**Current behavior:**

```
curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=mydb" --data-urlencode "q=select GPS.latitude, Weather.temperature from car where time >= '2015-10-13T14:16:13Z' limit 10"
```

yields

```
{
    "results": [
        {
            "series": [
                {
                    "name": "car",
                    "columns": [
                        "time",
                        "GPS.latitude",
                        "Weather.temperature"
                    ],
                    "values": [
                        [
                            "2015-10-13T14:16:14Z",
                            51.9893696,
                            5
                        ],
                        [
                            "2015-10-13T14:16:15Z",
                            51.9893696,
                            null
                        ],
                        [
                            "2015-10-13T14:16:16Z",
                            51.9893696,
                            null
                        ],
                        [
                            "2015-10-13T14:16:17Z",
                            51.9893696,
                            null
                        ],
                        [
                            "2015-10-13T14:16:18Z",
                            51.9893696,
                            null
                        ],
                        [
                            "2015-10-13T14:16:19Z",
                            51.9893696,
                            null
                        ],
                        [
                            "2015-10-13T14:16:20Z",
                            51.9893696,
                            null
                        ],
                        [
                            "2015-10-13T14:16:21Z",
                            51.9893696,
                            null
                        ],
                        [
                            "2015-10-13T14:16:22Z",
                            51.9893696,
                            null
                        ],
                        [
                            "2015-10-13T14:16:23Z",
                            51.9893696,
                            5
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Desired behavior:** I'd love for there to be a way to have those nulls be replaced by 5, so just return exactly the same points as with a regular non-grouped selected, just with the nulls filled in by the value in the column in one of the rows already selected.

**Use case:** A group-by substantially affects performance, and if I select over a time range where there are no measurements I get groups with fully empty lines.

**Comment by jsternberg** [comment]
I think this issue will end up being solved as part of #3552. We've avoided previously using fill for missing fields and instead going with always using null, but I think allowing any value of fill to be used when a measurement is missing and we are trying to join together series will be the correct way going forwards.

I'm going to keep this open as tracking for this issue specifically, but watch #3552 for progress on it since I'm almost certain it will be addressed as a consequence of resolving that issue. Thanks!

**Comment by ccaapton** [comment]
I read this issue and #3552 carefully, and did some thinking about the internal design. It looks quite difficult  if you want to implement the fill() at the SELECT stage as other functions like min()/first() do. This is because time-stamps are not organized as link-list or ordered-array, thus finding the adjacent time-stamp is quite a bit of work.

Alternatively, influxdb could add a post-SELECT stage, in which backward/forward filling become trivial, as the result is already sorted. [Pandas](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.fillna.html) in python have this function.

If the post-SELECT stage approach is adopted, then #3552 is also easy to solve, just like any other join-able database solve it.

**Comment by ccaapton** [comment]
The syntax would then turn into:
` SELECT BFILL("field1")[, BFILL("field2") ] from (select * from mydb)`
` SELECT FFILL("field1")[, FFILL("field2") ] from (select * from mydb)`

**Comment by nathanielc** [comment]
Added difficulty/medium, there is a similar feature to use `fill(0)` on raw queries that will make enabling fill previous a simpler task. Flux on the other hand does not yet have any fill support, so Flux will need to have its `interpolate` function completed before we can update the transpiler to run these kinds of quieries on Flux.
