### ISSUE TITLE
Low WAL performance for many small write requests

### ISSUE THREAD

**Issue by mhamrle** [influxdata/influxdb#7222]
### Feature Request

**Proposal:** Reduce number of fsync calls

**Current behavior:** WAL writes write requests into a file and calls fsync after every written request.

**Desired behavior:** I would like to reduce number of fsync calls during writing into WAL file.

**Use case:** :
I am using Influxdb in in small deployment with 15 services. From each service I need to send metrics into one central influxdb server. Even it is not many metrics the services generates many http write requests and these requests significantly load influxdb server. After a while I figured out that the load is caused by queued write request into WAL. WAL writes one request into a file and then calls fsync. Tracing linux storage subsystem showed up that writing data into file is negligible compared to fsync. Fsync takes about 20ms on SSD disc, data writing about 2ms.

So it clear that I cannot expect more that 50 http requests per second because influxdb spends all time only by fsyncing  20ms \* 50 = 1000ms. Big improvement can be achieved by reducing number of fsyncs. Instead of calling fsync after every write the fsync will be called after given time interval - for example 100ms. So WAL will process incoming write requests and write them sequentially into file (without fsync), all written requests would wait for one collective fsync. After given interval fsync is called and all waiting finished requests would return with success.

It is trade off between low processing time of http requests and total throughput.

**Comment by bitwalker** [comment]
I just wanted to add in my own observations using InfluxCloud - the average write request hovers between 50ms and 150ms, often taking as long as 500ms-1s. We have data coming from a large number and variety of sources, in most cases a single point at a time, in others the opportunity to batch writes is possible (and something I'm implementing at the application layer), but it does seem like we're more or less capped at ~10 requests per second before we plateau. I can get ~70 reqs/sec testing against a local Influx instance, but when you factor in talking across the internet, and against a cluster instead of a standalone instance, the ~7x performance penalty seems high, but hard to know how much of that is spent where (latency just reaching InfluxCloud, time spent fsyncing the writes, replication/consensus, serialization, etc.)

I was really hoping Influx could handle a much higher level of concurrency than this with small writes, but it looks like that is not a thing which will change soon. Anyway, hopefully some extra data will help.

**Comment by jwilder** [comment]
Fixed via #8143
