### ISSUE TITLE
Influx_inspect export doesn't follow symlinks

### ISSUE THREAD

**Issue by freeseacher** [influxdata/influxdb#7223]
### Bug report

__System info:__
any os, 
```
# influx -version 
InfluxDB shell version: 1.0.0~rc1
```

__Steps to reproduce:__

1. make the following hierarchy 
```
tree /var/lib/influxdb
/var/lib/influxdb
├── data -> /data/influx
├── meta
│   └── meta.db
└── wal -> /wal/influx

3 directories, 1 file
```

the reason for it is just to have one /data dir with all db and other stuff. of cause i know that i can remap directories in infludb.conf. but i want to have configs as mush as i can from defauts. and use remap as universal solution for all db's
2. influxdb on that works as usual.
3. run `influx_inspect export -db noc -rp d90 -out export -dir /var/lib/influxdb/ -start-time 2016-07-25T00:00:00Z -end-time 2016-07-26T00:00:00`

__Expected behavior:__
export file contains all data
__Actual behavior:__
export file is empty only with headers
```
# cat export 
# INFLUXDB EXPORT: 2016-07-25T03:00:00+03:00 - 2016-07-26T03:00:00+03:00
# DDL
# DML
```
__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by jsternberg** [comment]
It seems like this is the reason: https://golang.org/pkg/path/filepath/#Walk

> Walk walks the file tree rooted at root, calling walkFn for each file or directory in the tree, including root. All errors that arise visiting files and directories are filtered by walkFn. The files are walked in lexical order, which makes the output deterministic but means that for very large directories Walk can be inefficient. __Walk does not follow symbolic links.__

A potential issue with changing this to follow symbolic links is that usually these things don't follow symbolic links so they can avoid entering an infinite loop.

If you want the data to be on a different volume than the other files (which is completely understandable), have you tried just mounting the second data volume to `/var/lib/influxdb/data` instead of trying to use a symlink? I think symlinks are typically not advised because of issues like the one I mentioned above.

**Comment by jsternberg** [comment]
I'm closing this because I believe changing this to follow symlinks will introduce more complications with the potential of infinite recursion. If you want your data to be on another filesystem (which is a really good thing), then you can have different filesystems and mount it directly to the appropriate location or you can just change the configuration file. Maybe we can allow you to specify multiple directories with the `influx_inspect` command. If you want us to add the ability to specify multiple directories to export, please open an issue for that. Thanks.
