### ISSUE TITLE
client for influxdb 0.10.3

### ISSUE THREAD

**Issue by aerokite** [influxdata/influxdb#7247]
**client v2** doesn't work with **influxdb 0.10.3**. 

If old client is deprecated, which client should we use for **influxdb 0.10.3**.

Will new client support old influxdb in future?

**Comment by jsternberg** [comment]
You can probably just pin yourself to an older commit on the older clients and it will work properly or you can take an older commit and copy the client library to your own repository that you can use.

We are not going to be supporting a client for 0.10.3 since that is a fairly old version and it was a release from before 1.0. Whatever clients we support will support everything from 1.0 to newer. My guess is the only difference between them is the internal use of chunking (which didn't work in 0.10.3) and changing `GET` to `POST` so if you undo those two changes, the client will work.

If you want to ask more questions about this, I advise you to take it to the [mailing list](https://groups.google.com/forum/#!forum/influxdb).
