### ISSUE TITLE
Can I host influxdb on my dedicated server rather than buying from InFluxdata?

### ISSUE THREAD

**Issue by ajayg27** [influxdata/influxdb#7255]
I am looking to migrate my application to influxdb but confused on some aspects. 

First, it says influxdb is open source but I also see some pricing associated with the servers and stuff. Please advise.

Second, can  use influxdb as alternative to OpenTSDB?

and finally my application uses Hadoop cluster and OpenTSDB with Hbase. Will Influxdb able to handle the load?

My questions may sound very basic but any lead would help. Thanks!

**Comment by jsternberg** [comment]
Hello @ajayg27,

Someone on our team would love to answer your questions, but the issue tracker on GitHub is primarily for development. If you're interested in using InfluxDB either for open source or one of our commercial offerings, you can fill out this form in the [Contact Us](https://influxdata.com/contact-us/general-inquiries/) section of our website. You can also try the [mailing list](https://groups.google.com/forum/#!forum/influxdb).

I'm going to close this issue though because the people who monitor the issue tracker aren't the people who will be able to properly answer your questions. Sorry for the confusion!

**Comment by ajayg27** [comment]
Thanks @jsternberg I have filled out the form on website.

**Comment by ericvrp** [comment]
After some days of browsing the Influxdata site I did not encounter a link to the InfluxDB mailinglist except here in Github issues. Where is it located? Just so I can see if there is any other source in information that I was missing.
