### ISSUE TITLE
What is the wal file retention interval?

### ISSUE THREAD

**Issue by mslee89** [influxdata/influxdb#7269]
Hi. i can't speak english very well.

i wonder What is the wal file retention interval.
-rw-r--r-- 1 influxdb influxdb 3360273 2016-09-09 17:23:20.670711421 +0900 _00001.wal

Wait for answers.

**Comment by jwilder** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. In the future, please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.

Wal segments are removed as snapshot compactions complete.  This happens when when the cache in memory reaches a certain threshold (~25mb) by default or the shard has not received any writes for a period of time (default 1h).

The [storage engine docs](https://docs.influxdata.com/influxdb/v1.0/concepts/storage_engine/) have more information about this process.
