### ISSUE TITLE
https-private-key only works for [http], not for [admin]

### ISSUE THREAD

**Issue by dandv** [influxdata/influxdb#7284]
The following section under `[http]` works; InfluxDB starts successfully:

```
  https-enabled = true
  https-certificate = ".../cert.pem"
  ### Use a separate private key location.
  https-private-key = ".../privkey.pem"
```

Copying the section under `[admin]` prevents InfluxDB from starting:

> run: open server: open service: crypto/tls: found a certificate rather than a key in the PEM for the private key

**Comment by hydro-b** [comment]
I ran into the same issue. The workaround for now is to combine both key/cert into the same file and only specify the following under [admin]:
https-enabled = true
https-certificate = "combined key/cert file"

Note that the file should start with the private key, otherwise influxdb will give an error.

I would like to suggest the following. 99% of the time users will want to use the same certificate/key for both the admin/http (API) interface. Instead of having to specify the same cert / keyfile twice in the config file, make one general "server" config for https/cert/key which will be used for admin and http interface, if "https-enabled=true" the general server config will be used. If a user wants to overrule the admin and/or http interface with a specific key/cert they are still able to do so. Ultimate flexibility.

**Comment by dandv** [comment]
> Note that the file should start with the private key, otherwise influxdb will give an error.

In my case, I appended `privkey.pem` to `cert.pem`, and InfluxDB works even though the cert is the first file.

+1 for using the same cert for both HTTP and Admin.

**Comment by edumlauer** [comment]
Can you show how you combined both files? I tried different combinations of the file path but none worked.

**Comment by jsternberg** [comment]
The admin interface is deprecated and being removed. Sorry that we never got to this, but I'm going to close this issue.
