### ISSUE TITLE
Use single quotes to display query results in the Admin UI

### ISSUE THREAD

**Issue by dandv** [influxdata/influxdb#7287]
I just got bitten by #1757 in the Admin UI, because the query displays results in double quotes, and I just copy/pasted a value between double quotes from one point into the query string, wondering why my `WHERE value="foo bar"` didn't work.

Since quote handling breaks use expectations, would it make sense for the Admin UI to display string values within single quotes, to further emphasize their use (and to save users a bunch of time when they try using `"` for quoting strings)?

**Comment by jsternberg** [comment]
It also might be worth seeing if we can send back any informational messages in the query request for people who use a field that doesn't exist. It should likely be possible to learn that information and then something like `"no field or tag named 'foo bar' exists"`. Those using the API would never see the message unless they looked for it since it would get encoded in the messages section, but that sections does get printed by the influx client. It probably wouldn't be too much work to have the Admin UI display those messages too.
