### ISSUE TITLE
Fresh install of 1.0 cli fails 'invalid character 'M' looking for beginning of value'

### ISSUE THREAD

**Issue by simonswain** [influxdata/influxdb#7291]
### Bug report

__System info:__ 

Ubuntu 14.04 Desktop

__Steps to reproduce:__

1. Download and install .deb of influxdb 1.0 via influx site download
```
wget https://dl.influxdata.com/influxdb/releases/influxdb_1.0.0_amd64.deb
sudo dpkg -i influxdb_1.0.0_amd64.deb
```
2. run influx command line client. Client fails, with this error:
```
Failed to check token: invalid character 'M' looking for beginning of value
```

__Expected behavior:__ 

Cli works

**Comment by jsternberg** [comment]
Can you check the version of `influx` using `influx -version`?

**Comment by simonswain** [comment]
```
$ influx --version
InfluxDB shell version: 1.0.0
```

**Comment by jsternberg** [comment]
Can you verify that you are querying the correct server? You can try this with curl.

```
$ curl -v http://localhost:8086/ping
```

You should see an `X-Influxdb-Version` header in the response. If that's an older version, then the client will fail because it's trying to use a `POST` query instead of a `GET`. We started supporting `POST` requests to the server in 0.13 and made it the default there.

**Comment by simonswain** [comment]
```
$ curl -v http://localhost:8086/ping
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8086 (#0)
> GET /ping HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8086
> Accept: */*
> 
< HTTP/1.1 204 No Content
< Request-Id: db293efe-7944-11e6-9c43-000000000000
< X-Influxdb-Version: 0.12.2
< Date: Mon, 12 Sep 2016 23:58:52 GMT
< 
* Connection #0 to host localhost left intact
```

Is this my previous install still there?

I did apt-get purge before installing the new one, and ensured no influx processes were running.

**Comment by jsternberg** [comment]
Try this:

```
$ influxd version
```

If that shows 1.0, then the server might not have restarted. Just restart it then. If that shows 0.12.2, that means you still have the old one installed.

Since this isn't a bug, I'm going to close this. Questions regarding user help should go to the [mailing list](https://groups.google.com/forum/#!forum/influxdb). If you still need help, just link them to this thread so they have some context and continue the conversation there. Thanks!

**Comment by simonswain** [comment]
Thanks for your help.
