### ISSUE TITLE
update defaults in config for latest best practices

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7320]
remove `compact-min-file-count` and `max-points-per-block`
reduce `compact-full-write-cold-duration` and `cache-snapshot-write-cold-duration` settings
increase `cache-max-memory-size`?

**Comment by kostasb** [comment]
These changes will affect many users since most use default values.

Some suggestions:

`cache-max-memory-size = 1048576000`
Users with hot shards growing fast have had to increase this value. It should cause no harm raising it as it is only the maximum and can help avoid errors when hitting the max.

`cache-snapshot-memory-size = 104857600`
This is the in memory representation of cache, which can be different from the size on disk. Flushing the cache in larger chunks may yield better performance. There are indications from a few real world cases that this can help reduce I/O, but no hard numbers.

`cache-snapshot-write-cold-duration = 10m`
time allowed before cold cache gets flushed

`compact-full-write-cold-duration = 4h`
time allowed before a cold shard is compacted

Would be great to have performance testing figures with the old defaults and the new ones before decisions are made.

**Comment by e-dard** [comment]
@jwilder could you add a note about how the demo config file works in terms of describing the current default values in comments? That will clear this issue up then https://github.com/influxdata/influxdb/issues/7504
