### ISSUE TITLE
[Feature Request] Complex / Imaginary data type

### ISSUE THREAD

**Issue by jason-turner2** [influxdata/influxdb#7322]
### Feature Request

**Proposal:** Add support for complex numbers, i.e. numbers with an imaginary component. For example: `3 + 4i`. Since `i` is already used in the line protocol to specify integers, `j` is appropriate (and is the symbol conventionally used by electrical engineers).

**Current behavior:** Real floating-point values are supported. A work-around is to use field keys such as: `x_re` and `x_im` to denote the real and imaginary components. The lack of built-in standardization leads easily to a situation of "one standard per site".

**Desired behavior:** Additional "complex" data type, equivalent to two floats. Notation for insert via line protocol could be, for example: `foo tag1=sometag field1=3+4j timestamp`. As a "minimum viable feature", this could be storage only: complex math does not need to be added at first.

**Use case:** This is of particular importance with electrical applications and frequency-domain analysis of time series. Note that frequency-domain analysis covers a lot of time series territory that at first glance has nothing to do with frequencies. It's a tool for quickly and efficiently working with any data that requires convolution to solve analyses.

**Comment by tkeffer** [comment]
+1.

Complex numbers are also useful in fluid dynamics, where they can represent, for example, the x-and y-components of velocity.

**Comment by jeremyforan** [comment]
1+

**Comment by gefaila** [comment]
I'd like to retrigger this issue.  I need a facility for the storage of complex numbers for the analysis of currents and voltages in power monitoring.  In electrical systems all voltages and currents and resistances have both a magnitude and direction.  They have to be complex numbers because to calculate resistance or power you have to divide or multiply complex numbers.  So for me the Flux functions for manipulating complex numbers are an equal priority to being able to store them

**Comment by 19914039** [comment]
Yes, for processing power system signals, some times it is required to perform DFT or FFT etc, which require the support of complex number -j. Adding this feature would be more helpful to the community of electrical.
