### ISSUE TITLE
need a way to force shards to roll over

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7355]
### Feature Request

**Proposal:** [Description of the feature]

Provide equivalent function in OSS to the `influxd-ctl truncate-shards` command.

**Current behavior:** [What currently happens]

Shards cannot be truncated early, so `ALTER RETENTION POLICY` changes cannot take effect until the shards roll over. 

**Desired behavior:** [What you would like to happen]

It should be possible to force the current shard group to terminate and create new shards with updated settings.

**Use case:** [Why is this important (helps with prioritizing requests)]

Imagine being on a system with `30d` shards and realizing they were too long. It could take up to a month for any changes to actually take effect.

https://github.com/influxdata/influxdb/issues/5878 is also exacerbated by the lack of any way to close current shards for writes.

**Comment by supershal** [comment]
+1

**Comment by dlanderson** [comment]
Any updates on this?

**Comment by shilicqupt** [comment]
Any updates on this?

**Comment by dgnorton** [comment]
I came across this issue while researching another issue. A couple notes in case this issue is ever reopened and implemented:
* OSS meta client already supports `TruncateShardGroups(t time.T)` so that would need to be called
* The write path in OSS does not currently use the `TruncatedAt` field in the shard group meta data and would need to be modified to do so. Probably `coordinator/points_writer.go` in `PointsWriter.MapShards(wp *WritePointsRequest)` method needs to check `TruncatedAt` before mapping a shard to take writes.

**Comment by foobar** [comment]
could this be planned in 1.8.x?
