### ISSUE TITLE
[feature request]: Ability to restore backup to a new DB name

### ISSUE THREAD

**Issue by danyli78** [influxdata/influxdb#7369]
I found that using the SELECT \* INTO ... to migrate data to another DB is taking forever for large database. Can we backup and restore DB to a new DB name which should speed up the DB migration. 

Thanks..

**Comment by TheOneValen** [comment]
I also have a use case in which this feature might be useful.

I have two InfluxDB instances with different (mutual exclusive) database which I like to merge into one with all databases.

With existing tools I was not able to "restore" the missing databases into the other instance.

e.g.

Instance 1 show databases:
db1
db2

instance 2 show databases:
dba
dbb

merged instance show databases:
db1
db2
dba
dbb

**Comment by lukaszgryglicki** [comment]
+1, I've created such script:
```
#!/bin/sh
if [ -z "$1" ]
then
  echo "You need to provide input database name"
  exit 1
fi
if [ -z "$2" ]
then
  echo "You need to provide output database name"
  exit 1
fi
echo "drop database $2" | influx
echo "create database $2" | influx
echo "select * into $2..:MEASUREMENT FROM /.*/ GROUP BY *" | influx -database "$1"
```
Currently, to generate my data into `prod` database takes about 12 minutes.
I wanted to create a solution that regenerates data into some `test` database, and then (if succeeded) just "renames" this `test` database to `prod`.

`influxd -backup` failed because it *CANNOT* restore into the different database that the original one.
And this script works, preserves tags, values, all... but takes about 1,5 hours to complete!!
Why?

All my golang/code and a ton of complex Postgres scripts fully generate prod database in 12 minutes. Why simplest select into (that doesn't need to calculate anything, just 1:1 copy data) takes 90 minutes?

What are my options?

**Comment by timhallinflux** [comment]
https://github.com/influxdata/influxdb/issues/7758

**Comment by lukaszgryglicki** [comment]
Commented on #7758: https://github.com/influxdata/influxdb/issues/7758#issuecomment-336479123
