### ISSUE TITLE
integrate hdrhistogram

### ISSUE THREAD

**Issue by ceeaspb** [influxdata/influxdb#739]
Long tail non normal data can be summarised efficiently with the following data structure

https://github.com/codahale/hdrhistogram

**Comment by ceeaspb** [comment]
related to #59 #11

Many use cases aggregate data at source. There are too many data points to individually send to influx.

This feature would build on #59 to allow influxdb to 
- recieve and store (hdr)histogram data,
- operations on the stored histograms like union to calculate percentiles for specified intervals

https://github.com/codahale/hdrhistogram

see also
https://github.com/bbc/notes-on-perf-testing/blob/master/ch/gatling/real_time_graphs.md

@beckettsean as longer term was added a year ago, is it now short-medium term? :)

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by calder** [comment]
There's a decent amount of support for this over in #5930. This is a pretty critical feature for timeseries databases, even if other open source ones don't have it yet.
