### ISSUE TITLE
Show statements assume shards exist in default retention policy

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#7404]
### Bug report

**System info:** 1.0.1

**Steps to reproduce:**

```
> create database test
> use test
Using database test
> show series
> show retention policies on test
name       duration           shardGroupDuration         replicaN           default
----       --------           ------------------         --------           -------
autogen    0s             168h0m0s               1              true

> create retention policy foo on test duration inf replication 1
> insert into "test"."foo" cpu value=1
Using database test
Using retention policy foo
> show series
>
> select *  from test.foo.cpu
name: cpu
time               value
----               -----
1475528903595605201        1
> alter retention policy foo on test default
> show series
key

---
cpu
```

**Expected behavior:** 

`SHOW SERIES`, etc.. should work regardless of what the `default` retention policy is.

**Actual behavior:** 
`SHOW SERIES` is rewritten to:

```
SELECT "key" FROM test.default._series
```

If there are no shards created within the `default` RP, no iterators are created and no data is returned.

**Comment by jsternberg** [comment]
I think this might just be an error in the meta service. When you run those commands, do you get a log similar to this one?

```
[httpd] ::1 - - [04/Oct/2016:13:04:55 -0500] "POST /write?consistency=all&db=db0&precision=ns&rp=rp0 HTTP/1.1" 204 0 "-" "InfluxDBShell/unknown" 0e36ed1d-8a5d-11e6-800a-000000000000 4144
[query] 2016/10/04 13:04:58 SELECT "key" FROM db0.autogen._series
[httpd] ::1 - - [04/Oct/2016:13:04:58 -0500] "POST /query?chunked=true&db=db0&epoch=ns&q=show+series HTTP/1.1" 200 110 "-" "InfluxDBShell/unknown" 100b6542-8a5d-11e6-800b-000000000000 860
```

In the second `httpd` line, I don't see `rp=rp0`. That would likely be the reason it doesn't substitute the correct value.

**Comment by jwilder** [comment]
Work around for this is to run `show series from "test"."foo"./.*/`

**Comment by e-dard** [comment]
@jwilder had a discussion with @joelegasse and @corylanou, and the general consensus is that fixing `SHOW SERIES` to show all series across all retention policies (which is how the docs describe it should work) doesn't seem that useful.

The reasoning being that the value from the output of `SHOW SERIES` is dubious because each series doesn't have any retention policy information associated with it. Therefore, it's not possible to select any further information from the database given the output of `SHOW SERIES` because you don't know what retention policies the series data belong to.

The existing behaviour of outputting the series data from the current default retention policy is probably preferable, so I think we should close this issue.

**Comment by jsternberg** [comment]
As just an aside for something that we may want to consider, should we include an `rp=<name>` parameter to the query? This could act as a way of overriding the default retention policy so commands like `SHOW SERIES` can be used to show another retention policy other than the default.

**Comment by e-dard** [comment]
@jsternberg yeah exactly. If we changed the behaviour of `SHOW SERIES` we would need to add that 👍 .

**Comment by e-dard** [comment]
Alright change of plan after further discussion with @jwilder @joelegasse; we're going to try and fix this issue so that `SHOW SERIES` outputs all series across the entire DB.

**Comment by rbetts** [comment]
This won't happen for 1.3.0; however, it might make sense to fold into the necessary SHOW SERIES work that TSI-by-default will require.

**Comment by jefferyk** [comment]
I still get this behavior on a influx 1.7.1 database. Do I have to be using tsi1 to fix this?
If I issue Show series, I get no output, since i have no measurements in the autogen retention policy. But if I do show series from "rpname"."measurement" it lists them fine. Is this a bug, or how it should be working?

**Comment by mpvader** [comment]
Please re-open; this is still a problem. Or, change the documentation and highlight this limitation. Though, having (unexpected) limitations is generally not helping to make something a beloved product.

Thanks.
