### ISSUE TITLE
slow tsm writing speed v.s. cache-snapshot-memory-size

### ISSUE THREAD

**Issue by whille** [influxdata/influxdb#7459]
### Bug report
System info:
InfluxDB version:
v1.0.1
CentOS release 6.5 (Final)
x86_64 GNU/Linux
32 cpu cores
256G RAM
300G+ SSD disks

### Steps to reproduce:
1. 100+ measurements, 8 tags and 50 filed per measurement, write every minute: about 40k/sec writing speed, i think. And there're several aggregation reads meanwhile.
2. even increase cache-snapshot-memory-size to 4G, there're still logs showing: cache maximum memory size exceeded; if set cache-snapshot-memory-size=0, OOM occurs.
3.   cache-snapshot-write-cold-duration = "10s" , snapshot to tsm sometimes  takes more than 2 min：
[tsm1] 2016/10/10 18:34:30 Snapshot for path /var/lib/influxdb/data/CDN/rp_access/1864 written in 2m50.441790907s

the design doc saids:
In cases where IO performance of the compaction process falls behind the incoming write rate, it is possible that writes might arrive at the cache while the cache is both too full and the compaction of the previous snapshot is still in progress. In this case, the cache will reject the write, causing the write to fail.

In our situation, disk IO < 20%, cpu > 80%. I wonder if the tsm writing block writing performance. Please someone give me clues.

**Comment by jwilder** [comment]
If you are getting `cache maximum memory size exceeded`, you should increase `cache-max-memory-size`.  You can disable the max size by setting that to 0.

Increasing `cache-snapshot-memory-size` is not what you want since that causes the snapshots to be even larger and more time consuming.  I would suggest lowering it 10mb or so.

Can you attach some sample writes in line protocol format?

**Comment by whille** [comment]
@jwilder thx. Here's the line sample, some strings are masked:
tbl,afeff_fefsa=A,affefef_name=fseffe01,ccffe_name=cfsefsf01,region=XffeFEFF_FFfef 206_all=0i,206_hit=0i,206_miss=0i,206_other=0i,2xx_all=10i,2xx_hit=10i,2xx_miss=0i,2xx_other=0i,302_all=0i,302_hit=0i,302_miss=0i,302_other=0i,3xx_all=0i,3xx_hit=0i,3xx_miss=0i,3xx_other=0i,403_all=0i,403_hit=0i,403_miss=0i,403_other=0i,404_all=0i,404_hit=0i,404_miss=0i,404_other=0i,416_all=0i,416_hit=0i,416_miss=0i,416_other=0i,499_all=0i,499_slow=0i,4xx_all=0i,4xx_hit=0i,4xx_miss=0i,4xx_other=0i,5xx_all=0i,5xx_hit=0i,5xx_miss=0i,5xx_other=0i,block_all_count=10i,block_long_count=0i,block_short_count=10i,byte_all=11104i,byte_big_hit=0i,byte_big_miss=0i,byte_hit=11104i,byte_miss=0i,byte_preload=0i,byte_small_hit=11104i,byte_small_miss=0i,byte_very_big_hit=0i,byte_very_big_miss=0i,qps_all=10i,qps_big_hit=0i,qps_big_miss=0i,qps_big_slow_hit=0i,qps_big_slow_miss=0i,qps_de=0i,qps_hit=10i,qps_miss=0i,qps_pd=0i,qps_preload=0i,qps_small_hit=10i,qps_small_miss=0i,qps_small_slow_hit=0i,qps_small_slow_miss=0i,qps_very_big_hit=0i,qps_very_big_miss=0i,qps_very_big_slow_hit=0i,qps_very_big_slow_miss=0i,qps_vs_hit=10i,qps_vs_miss=0i,qps_vs_slow_hit=0i,qps_vs_slow_miss=0i,rt_all=13i,rt_big_hit=0i,rt_big_miss=0i,rt_hit=13i,rt_miss=0i,rt_small_hit=13i,rt_small_miss=0i,rt_very_big_hit=0i,rt_very_big_miss=0i,rtt=606750i,up_connect=4i,up_first_all=13i,up_first_hit=13i,up_first_miss=0i,up_rt_hit=12i,up_rt_miss=0i 24598855

**Comment by jwilder** [comment]
@whille That's a lot of fields.  If you are writing 40k points/sec with 50 fields each, that's is about 2M values/sec.  Writing this many fields hits some code paths that are better optimized in 1.1 so it will be slower in 1.0.x.  As I suggested before, setting `cache-max-memory-size` to `0` of several GB should resolve the error you are seeing.

Going to close this since the config options were not set correctly and causing your process to OOM.
