### ISSUE TITLE
should disable InfluxDB on low IOPS systems, by configurable default

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7500]
### Feature Request

**Proposal:** 

InfluxDB should refuse to boot and issue a console and log error when the IOPS of the `/data` and other important directories are below a configurable threshold.

**Current behavior:**

InfluxDB (and InfluxEnterprise) starts and tries to run, even on HDD systems with 1/10th the required IOPS for reasonable performance.

**Desired behavior:**

By default, InfluxDB will not start if it detects below some setting, I propose 1000 IOPS. The limit can be configured, but then we can put warnings and performance disclaimers in the errors and the config comments. 

To clarify, I'm asking for something like `[data] min-iops-required = 1000` in the config file. Just edit that to `min-iops-required = 1` and relaunch the system to disable the setting. The idea is that it's a step users must intentionally take, and at that point of editing the config setting InfluxData can push them to documentation describing the issues with low IOPS systems.

**Use case:**

This will avoid some support issues with customers running on underprovisioned hardware, as well as re-inforcing that while InfluxDB will run on 120 IOPS drives, it won't run well.

**Comment by phemmer** [comment]
I would highly disagree with this decision.

First of all, how are you going to determine how many IOPS the drive can do? Is InfluxDB going to just hammer it as hard as possible when it first starts up and see what kind of performance it gets? Deliberately saturating a hardware component just so you can measure its performance seems like a bad idea. Especially if the component is shared with any other services.

Also what if the drive is shared with another service (such as the case of a SAN), and right when InfluxDB is measuring it, another service is saturating it, so that the InfluxDB gets a bad measurement. This would cause InfluxDB to not start. Randomly not starting a potentially critical service is also not a good idea.

Thirdly, you can't know everyone's use case. InfluxDB might be run on systems which don't need massive disk performance. Lets take a look at my InfluxDB:
![image](https://cloud.githubusercontent.com/assets/1826947/19632945/1e382006-997a-11e6-8b6d-a8a7e4d724c5.png)
These graphs show the number of writes and reads against the volume InfluxDB stores its data on. As you can see, it's pretty much all writes, and almost no reads. This is because the box has enough memory to where nearly all reads come from cache. All the dashboards that we have up only use time ranges of the last few hours.
As for writes, we have 51 hosts writing in their metrics, which as shown, averages around 300 disk writes per second, well under the proposed value of 1000.

Fourthly, such a feature is not standard practice. You don't see databases such as MySQL, or PostgreSQL refusing to run because the drive they are running on isn't highly performant.
https://en.wikipedia.org/wiki/Principle_of_least_astonishment

> This will avoid some support issues with customers running on underprovisioned hardware

This seems like a really weak argument. While I don't work for your support, I can't imagine these are that common, or that time consuming to troubleshoot. At least not enough to justify implementing a feature that would likely result in a large amount of collateral damage.

Instead of trying to guess when the user might have a problem due to insufficient hardware capacity, what about logging something when such is actually detected? For example, if the write queue, or read queue is backing up, or never/rarely reaches 0, then log a message.

**Comment by toni-moreno** [comment]
Hi @beckettsean , I also disagree

Some weeks ago I ask for IOPS related performance documentation  (https://github.com/influxdata/influxdb/issues/6930) . And as yourself said _"...InfluxDB has a steady-state need for IOPS and there is not a simple relationship between write or query volume and IOPS required.."_

How do you want put a IOPS limit if you can not say us how to prevent exceed this limit, based on known parameters as num input metrics or queries ? 

IMHO the correct way to avoid support issues is just to give us more accurate information about IOPS vs Input Metrics / Queries.

Thank you very much.

**Comment by beckettsean** [comment]
@toni-moreno @phemmer I appreciate your feedback. I would like to point out that I advocated this as a default behavior that can be disabled, not a total ban. The idea is that users with low IOPS devices should be aware they are running InfluxDB in a low performance environment.

If I update the proposal with more detail maybe it will make more sense:

__Desired behavior:__

By default, InfluxDB will not start if it detects below some setting, I propose 1000 IOPS. The limit can be configured, but then we can put warnings and performance disclaimers in the errors and the config comments. 

To clarify, I'm asking for something like `[data] min-iops-required = 1000` in the config file. Just edit that to `min-iops-required = 1` and relaunch the system to disable the setting. The idea is that it's a step users must intentionally take, and at that point of editing the config setting InfluxData can push them to documentation describing the issues with low IOPS systems.

@phemmer 
> First of all, how are you going to determine how many IOPS the drive can do? Is InfluxDB going to just hammer the drive as hard as possible when it first starts up and see what kind of performance it gets? Deliberately saturating a hardware component just so you can measure its performance seems like a bad idea. Especially if the component is shared with any other services.

Then again, running a high performance database on shared hardware is also not a good idea. I admit, I don't know how to sample IOPS, but abusing the disk for ~2 seconds on first boot doesn't seem that awful. The results can be cached thereafter so it wouldn't happen on restart.

> Also what if the drive is shared with another service (such as the case of a SAN), and right when InfluxDB is measuring it, another service is saturating it, so that the InfluxDB gets a bad measurement. This would cause InfluxDB to not start. Randomly not starting a potentially critical service is also not a good idea.

We _strongly_ recommend running InfluxDB on dedicated locally attached SSDs. A SAN is precisely the sort of environment that has led to issues in the past. If InfluxDB is sharing IOPS in production, then wouldn't it be better to expose the resource contention before startup, rather than when the cluster is at full load and things fall apart?

> Thirdly, you can't know everyone's use case. InfluxDB might be run on systems which don't need massive disk performance. 

Which is why I said this is a configurable limit, that would be trivial to lower intentionally. However, when lowering the default it would require users to acknowledge they are running it on a low resource system. If a user is writing 2 points per second on a Raspberry Pi, great! Just drop the IOPS default and restart. 

> Fourthly, such a feature is not standard practice. You don't see databases such as MySQL, or PostgreSQL refusing to run because the drive they are running on isn't highly performant. https://en.wikipedia.org/wiki/Principle_of_least_astonishment

Very true. And when InfluxDB is 20 years mature I'm sure it will have all the rough edges rounded off and be darn near impossible to install and run incorrectly. Until then, we need crude and quick tools to reduce user surprise. You link to the principle of least astonishment. I believe that an informative aborted startup error on installation is far less astonishing than a panicked ticket to support after two weeks of runtime and then finding out that the entire setup is underpowered for the use case and cannot be rescued. 

> This seems like a really weak argument. While I don't work for your support, I can't imagine these are that common, or that time consuming to troubleshoot. At least not enough to justify implementing a feature that would likely result in a large amount of collateral damage.

I am the Director of Support for InfluxData. I know what causes us the most pain and frustration, as I live it daily. I'd rather prevent the issue than treat the symptoms later. 

> Instead of trying to guess when the user might have a problem due to insufficient hardware capacity, what about logging something when such is actually detected? For example, if the write queue, or read queue is backing up, or never/rarely reaches 0, then log a message.

We already have many informational messages like this in the logging, but they are not seen or heeded by too many novice users. I want the message to be accompanied by an impossible to miss signal like an aborted first startup. It's a sad truth that people don't read the logs until it's already in a bad state. 

@toni-moreno 
> How do you want put a IOPS limit if you can not say us how to prevent exceed this limit, based on known parameters as num input metrics or queries ?

Again, this is a configured limit, so all you have to do is raise it. Even pushed to its limits InfluxDB doesn't seem to use more than about 2000 IOPS, so we know that around 1000 is good for almost all use cases. Start there and let users drop that if they wish.

> IMHO the correct way to avoid support issues is just to give us more accurate information about IOPS vs Input Metrics / Queries.

There is no simple relationship, nor is there such a thing as a standard query or a standard metric. One user might have one write per second but the values are 100k strings, vs 10000 values per second that are integers. The IOPS load might not differ very much.
