### ISSUE TITLE
"query-log-enabled" defaults to yes contrary to config notes

### ISSUE THREAD

**Issue by Fohdeesha** [influxdata/influxdb#7504]
### Bug report

Apologies if this is as designed but "query-log-enabled" in /etc/influxdb/influxdb.conf is noted as logging sensitive data, and "#query-log-enabled = true" is commented out making it seem it is off, and needs to be uncommented to turn on. However it is on by default with no config needed. Manually uncommenting and changing to false is required to disable it.

__System info:__ 
Debian 8 Jessie
Influxdb 1.0.2

__Steps to reproduce:__

1. Install Influxdb and use it. Change all uncommented/active logging lines in the config to false
2. If you check the system's syslog it will still have quite a bit of query logspam. About 100mb a day on our system
3. To fix it, uncomment "query-log-enabled = true", change it to false

If query logging is designed to be active even with no setting whatsoever in the config file, I might suggest adding to the comment text above the commented out config line saying something along the lines of "query logging is active by default even when commented out, uncomment and set to false to disable"

**Comment by e-dard** [comment]
Hi @Fohdeesha, thanks for the report.

This is the expected behaviour. As is common with configuration files, we comment out the default settings, so that users can see what the defaults are by reading the config file.

I think a comment at the top of the file explaining the format to those who are not familiar with it would be beneficial. I'll add one.
