### ISSUE TITLE
cannot import trivial export file

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#7516]
### Bug report

**System info:** 

InfluxDB 1.0.2 OSS, Ubuntu 16.04

**Steps to reproduce:**

Save this as a text file:

```
# DDL
CREATE DATABASE db0
CREATE DATABASE db1
CREATE RETENTION POLICY rp1 ON db1 DURATION 1h REPLICATION 1

# DML
# CONTEXT-DATABASE:db0
# CONTEXT-RETENTION-POLICY:autogen
cpu,host=server1 value=33.3 1464026335000000000
cpu,host=server1 value=43.3 1464026395000000000
cpu,host=server1 value=63.3 1464026575000000000

# CONTEXT-DATABASE:db1
# CONTEXT-RETENTION-POLICY:rp1
cpu,host=server1 value=73.3 1464026335000000000
cpu,host=server1 value=83.3 1464026395000000000
cpu,host=server1 value=93.3 1464026575000000000
```

Then import it: `influx -import -path file.txt`

**Expected behavior:** 

The file would import and the data be readable.

**Actual behavior:** 

Although there are no errors on import:

```
$ influx -host XXXX -import -path first.txt 
2016/10/25 09:08:49 Processed 3 commands
2016/10/25 09:08:49 Processed 6 inserts
2016/10/25 09:08:49 Failed 0 inserts
```

And the databases were created, but they are empty:

```
> use db0
Using database db0
> show measurements
> show retention policies on db0
name    duration    shardGroupDuration  replicaN    default
autogen 0       168h0m0s        1       true

> show field keys
> show tag keys
> show series
> use db1
Using database db1
> show series
> show tag keys
> show measurements
> select * from rp1./.*/
> insert cpu,host=server1 value=93.3 1464026575000000000
> show measurements
name: measurements
------------------
name
cpu

> select * from rp1./.*/
> select * from autogen./.*/
name: cpu
---------
time            host    value
1464026575000000000 server1 93.3
```

**Comment by beckettsean** [comment]
@corylanou any thoughts?

Note that I can successfully import other data, it's just this use case that seems to fail.

Logs from the import show that the `db1` writes seem to be missing, although `db0` should have succeeded:

```
[httpd] 50.183.252.230 - - [25/Oct/2016:11:08:49 -0400] "GET /ping HTTP/1.1" 204 0 "-" "influxDB importer/v1.0.2" eeb49e56-9ac4-11e6-b887-000000000000 135
[query] 2016/10/25 11:08:49 CREATE DATABASE db0
[httpd] 50.183.252.230 - - [25/Oct/2016:11:08:49 -0400] "POST /query?db=&q=CREATE+DATABASE+db0 HTTP/1.1" 200 46 "-" "influxDB importer/v1.0.2" eebbdd5f-9ac4-11e6-b888-000000000000 5448
[query] 2016/10/25 11:08:49 CREATE DATABASE db1
[httpd] 50.183.252.230 - - [25/Oct/2016:11:08:49 -0400] "POST /query?db=&q=CREATE+DATABASE+db1 HTTP/1.1" 200 46 "-" "influxDB importer/v1.0.2" eed0783d-9ac4-11e6-b889-000000000000 5068
[query] 2016/10/25 11:08:49 CREATE RETENTION POLICY rp1 ON db1 DURATION 1h REPLICATION 1
[httpd] 50.183.252.230 - - [25/Oct/2016:11:08:49 -0400] "POST /query?db=&q=CREATE+RETENTION+POLICY+rp1+ON+db1+DURATION+1h+REPLICATION+1 HTTP/1.1" 200 46 "-" "influxDB importer/v1.0.2" eedf712d-9ac4-11e6-b88a-000000000000 18841
[httpd] 50.183.252.230 - - [25/Oct/2016:11:08:49 -0400] "POST /write?consistency=any&db=db1&precision=ns&rp=rp1 HTTP/1.1" 204 0 "-" "influxDB importer/v1.0.2" eef070cf-9ac4-11e6-b88b-000000000000 1081
[httpd] 50.183.252.230 - - [25/Oct/2016:11:08:54 -0400] "GET /ping HTTP/1.1" 204 0 "-" "InfluxDBShell/v1.0.2" f1c30136-9ac4-11e6-b88d-000000000000 119
[query] 2016/10/25 11:08:54 SHOW DIAGNOSTICS FOR registration
[httpd] 50.183.252.230 - - [25/Oct/2016:11:08:54 -0400] "POST /query?chunked=true&db=&epoch=ns&q=SHOW+DIAGNOSTICS+for+%27registration%27 HTTP/1.1" 200 51 "-" "InfluxDBShell/v1.0.2" f1cacc2c-9ac4-11e6-b88e-000000000000 4196
[query] 2016/10/25 11:08:59 SHOW DATABASES
[httpd] 50.183.252.230 - - [25/Oct/2016:11:08:59 -0400] "POST /query?chunked=true&db=&epoch=ns&q=show+databases HTTP/1.1" 200 156 "-" "InfluxDBShell/v1.0.2" f5185f64-9ac4-11e6-b88f-000000000000 2774
```

**Comment by mark-rushakoff** [comment]
`rp1` has duration 1h, and the timestamps are probably more than 1 hour old at time of import. `autogen` has infinite duration.

**Comment by beckettsean** [comment]
Excellent find, @mark-rushakoff, thanks for the extra eyes!

**Comment by beckettsean** [comment]
On second thought, that explains `db1`, but why are there no points persisted for `db0`, which is using the `autogen`, which has `duration = INF`

**Comment by jacktang** [comment]
"rp1 has duration 1h, and the timestamps are probably more than 1 hour old at time of import. " I am facing the same problem on how to import the historical data into influxdb.

**Comment by stromnet** [comment]
I got a similar problem, I think?
The FreeBSD package was so very nice to change it's DB dir on upgrade (without moving the old one...), thus after restart all new DBs where used..
Fortunately I could dump the old .tsm files, but now I fail to import them.

Sample file:
```
# CONTEXT-DATABASE:owfs2
# CONTEXT-RETENTION-POLICY:default
owfs_reading,alias=test,sensor=test1234,type=temperature value=26.190001 1496228086010000000
```

Manually create RP default: `create retention policy "default" on "owfs2" duration inf replication 1;`

Imported with `influx -database owfs2 -import -path owfs.test.export` claims 1 insert, but:
````
> use owfs2;
> show measurements;
name: measurements
name
----
owfs_reading

> select * from owfs_reading;
> show shards;
...
name: owfs2
id  database retention_policy shard_group start_time           end_time             expiry_time          owners
--  -------- ---------------- ----------- ----------           --------             -----------          ------
222 owfs2    default          222         2017-05-29T00:00:00Z 2017-06-05T00:00:00Z 2017-06-05T00:00:00Z
```
So some shard was screated, by the import, but apparently no data got in there.. The expiry_time looks suspicious too, shouldnt that be INF?

Now it gets a bit more weird, imo?:
```
> drop retention policy "default" on "owfs2";
> create retention policy "default" on "owfs2" duration inf replication 1 default;
> select * from owfs_reading;
>
```
...then re-run the import
```
> show shards;
....
name: owfs2
id  database retention_policy shard_group start_time           end_time             expiry_time          owners
--  -------- ---------------- ----------- ----------           --------             -----------          ------
223 owfs2    default          223         2017-05-29T00:00:00Z 2017-06-05T00:00:00Z 2017-06-05T00:00:00Z

> select * from owfs_reading;
name: owfs_reading
time                alias       sensor              type        value
----                -----       ------              ----        -----
1496228086010000000 TESTbedroom TEST28.AA6450000000 temperature 26.190001
```

So, making the RP the default one allows the data to be imported somehow?

Note: if i change my import file to use RP "autogen" instead of "default", all works as expected. But I'd rather not do that on the real data, since the compressed file is 1.1Gb..

**Comment by e-dard** [comment]
@stromnet The reason it seems like your data is missing is because, by default, the `influx` client will [query](https://docs.influxdata.com/influxdb/v1.2/query_language/data_exploration/#syntax) the `default` retention policy. When I say `default`, I mean the retention policy that is used if one is not explicitly provided within a command; I don't mean the retention policy you named `"default"`, which is not in fact the `default` policy.

You should find if you explicitly query your retention policy you will see the data. Something like:

```
> select * from "owfs2"."default"."owfs_reading";
name: owfs_reading
time                alias sensor   type        value
----                ----- ------   ----        -----
1496228086010000000 test  test1234 temperature 26.190001
>
```

> Why does re-creating my retention policy and making it `default` work?
Because when you come to query the data, Influx will be querying the same retention policy you wrote the data to.

> Can I change the retention policy that I insert my data to?
You can manually edit the file. You only need to change the `# CONTEXT-RETENTION-POLICY:default` line to be something like `# CONTEXT-RETENTION-POLICY:autogen` (if you want to use the retention policy that's automatically created as the `default`. This should be easy using a decent *nix editor, even if the file is several GB.

> What's with the `expiry_time` on the infinite duration retention policy?
The important thing here is that the `expiry_time` is to do with the shard group, not the retention policy. The retention policy's duration is infinite, which means the shard groups will never be deleted. 

The `expiry_time` value in the shard group is supposed to show a user when that shard group will be removed. We calculate that by taking the `end_time` value, and adding on the retention policy duration. In theory this should tell use when the group will be deleted from the system. Unfortunately we treat an infinite retention policy duration as `0`, so we end up displaying the `expiry_time` equal to the `end_time`. I think this is confusing and I'm going to see if we can do something about that in future releases.

Hope that helps!

**Comment by stromnet** [comment]
@e-dard: Thank you for a great explanation, now the behaviour makes sense.

While of course possible to edit a 24Gb file, it's not very practical. Seems that there is work in progress to improve this in future versions (#8352 / #8389), so I'll leave it at that and hope that the improvements gets in a release version soon :)
