### ISSUE TITLE
[Feature Request] Multiple HTTP Listeners

### ISSUE THREAD

**Issue by toni-moreno** [influxdata/influxdb#7525]
### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

**Proposal:** [Description of the feature]

add multiple  HTTP listeners in the same way we can configure multiple graphite/udp/collectd listeners.

**Desired behavior:** [What you would like to happen]

I need add more than one HTTP input with different HTTP configuration.

**Use case:** [Why is this important (helps with prioritizing requests)]

For security reasons we need add a port with HTTPS  for peripherals devices on a already working in production server configured with HTTP for already configured agents on internal devices.

In this scenario with current behaviour I will need to update  to use HTTPS all internal devices ( that is not really needed) previously  to deploy agents to the peripheral devices.

Thank you very much.

**Comment by jsternberg** [comment]
We talked about doing this in the past, but we decided that InfluxDB wasn't supposed to be an HTTP server and we didn't feel adding multiple HTTP listeners was useful. Can you install Nginx and set that up as a proxy? Nginx is designed to do this already and it's much better to use it than for us to add a setting for another HTTP listener.

**Comment by mhiller** [comment]
is this maybe a better feature add for telegraf ? Per the training i just attending telegraf design is to offload all "translation and additive features" from influxdb. If the intent is to remove the http server from influxdb itself, this seems like the logical next place.

**Comment by jsternberg** [comment]
I don't think this is the correct place for telegraf, but @sparrc may be able to comment better than me on that. I think Nginx is the correct place to go if you need multiple HTTP listeners for dealing with things like SSL. Nginx will be much better at being an HTTP server than we will ever be anyway.

If there's a situation where Nginx or Apache doesn't work, please comment. I'm going to close this for now since modifying the configuration file to allow multiple HTTP listeners would also introduce complications in the configuration file.
