### ISSUE TITLE
Influxdb query-timeout config - wrong return code?

### ISSUE THREAD

**Issue by discoduck2x** [influxdata/influxdb#7595]
Influx version: 1.0.2
os : centos 7

When configuring query-timeouts the return status code when influx kills a long running query shouldnt be **200 OK**.

See https://github.com/grafana/grafana/issues/6484 for more reference

**Comment by jsternberg** [comment]
The status code mostly just indicates if the query itself executed. Errors in query execution are returned as part of the JSON body and require parsing that JSON. Since query timeouts are an error during query execution and not the preparation, you get a 200 OK and the error shows up in the JSON body.

Does this make sense?

**Comment by bergquist** [comment]
I'm not aware of a good http status code for timeouts in underlying services. But responding with 200 containing an error message can be problematic...

 - Makes it harder to write generic http code (lets say I want to measure http response codes for all outgoing requests)
 - Reverse proxy caching becomes unreliable. 
 - Back pressure libs like https://github.com/Netflix/Hystrix will keep sending traffic.

Whats the upside to returning 200?
