### ISSUE TITLE
influxdb sum query wierd spikes and drops

### ISSUE THREAD

**Issue by p0nts** [influxdata/influxdb#7647]
I am using Icinga2 to push performance data into the influx database which is running the latest version (1.1.0) and parse the graph in grafana for visualisation.

I seem to be unable to debug the cause of spikes and drops inside graphs that are made with sum queries, for some reason it happens that sometimes the amount of total data is doubled, so it just doubles the amount of total memory and the next time it is normal again.

I have queried the database manualy in the timeframe the graph shows double data, but unfortunately the query does not.

Do I use the wrong query for sum?

**image with the spikes and query**
http:///shot.xsnews.nl/stefan/7f11996fb58a6e7d.png

**tried manual query but I do not see any double data**
http:///shot.xsnews.nl/stefan/ed95701d7e09016f.png
http:///shot.xsnews.nl/stefan/78e8e621f4ccb4be.png

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please send general questions to the influxdb@googlegroups.com mailing list.

Thanks.

**Comment by bijwaard** [comment]
Dear all,
I know this is an old issue, but I notice similar spikes in larger queries that use a sum() as well in influxdb 1.8.10 on ubuntu Linux. I use Grafana for display, but also get the same results when running the query directly in influxdb. Here are some graphs that show the spikes over cummulative gas usage (hourly measurements that are null when value didn't change) that is always increasing. The issue seems to appear when the time-range is longer than 7 days (here 30 days):
![image](https://user-images.githubusercontent.com/6523124/208053760-e55d99da-5476-4744-b493-9dbf149cd7b3.png)
![image](https://user-images.githubusercontent.com/6523124/208053979-c8855e93-b531-45ee-b3da-d00594cb197e.png)

Here is the same query when using mean() instead of sum():
![image](https://user-images.githubusercontent.com/6523124/208054107-56974283-5ae9-4468-90fb-4c3b10d238a9.png)
![image](https://user-images.githubusercontent.com/6523124/208054208-b53eb27d-6948-4005-89f1-de153f6d13d3.png)

I want to use the sum since to show the gas usage per time interval at different time-zoom levels, with mean this works when time-interval is 1 hour, but not when it is larger (then I get an average instead of a sum).
![image](https://user-images.githubusercontent.com/6523124/208054792-53c54346-e6a3-4adb-b1b6-bb2c8dfba470.png)
![image](https://user-images.githubusercontent.com/6523124/208054939-d094ec48-055b-4936-ab0c-c6ca1743bea5.png)
![image](https://user-images.githubusercontent.com/6523124/208055146-bc66ef12-dd78-4e60-809c-86ac620ef98f.png)
![image](https://user-images.githubusercontent.com/6523124/208055239-2ce79c8e-54d5-460f-86b9-ef8408971125.png)

Here are CSV files for the data of the first two graphs using sum() and mean().
- [Gas-data-2022-12-16 09 28 50-using-mean.csv](https://github.com/influxdata/influxdb/files/10243972/Gas-data-2022-12-16.09.28.50-using-mean.csv)
- [Gas-data-2022-12-16 09 28 21-using-sum.csv](https://github.com/influxdata/influxdb/files/10243974/Gas-data-2022-12-16.09.28.21-using-sum.csv)

Here is an influx session showing the actual data over the last 30 days with a simpler query:
- `select * from "Gas-usage" where time>=now()-30d and time <=now() `
- [influx-raw-30d.txt](https://github.com/influxdata/influxdb/files/10244042/influx-raw-30d.txt)


Kind regards,
Dennis
