### ISSUE TITLE
Support schemaful line protocol hint

### ISSUE THREAD

**Issue by philip-wernersbach** [influxdata/influxdb#7666]
https://github.com/philip-wernersbach/influx-mysql supports a "schemaful line protocol hint" that allows for optimizations when writing to schemaful databases. The schemaful line protocol hint is enabled by issuing a `POST /write?schemaful=true` HTTP request.

When the schemaful line protocol hint is enabled, the first point for each new measurement is parsed and considered to be the schema of the measurement instead of a point. For instance, for the following line protocol points:

```
cpu_load a='',b=0.0,c=0i 0
cpu_load a='hello world',b=1.0,c=2i 1000
disk_load value='' 0
disk_load value='loaded' 2001
```

When the schemaful line protocol hint is enabled, the above line protocol points indicate that `cpu_load` is a schemaful measurement that has a field `a` that is a string, a field `b` that is a floating point number, and a field `c` that is an integer. It also indicates that `disk_load` is a schemaful measurement that has a field `value` that is a string.

The above line protocol points also add a point to `cpu_load` with the fields `a='hello world',b=1.0,c=2i`, and a point to `disk_load` with the fields `value='loaded'`.

It would be awesome if InfluxDB could support this.

**Comment by e-dard** [comment]
@philip-wernersbach given that InfluxDB will create the field/tag types automatically based on the first instance of a tag/field value, what is it that your feature request would do that isn't already done in InfluxDB?

**Comment by jsternberg** [comment]
If I understand it correctly, it's for compatibility with his `influx-mysql` compatibility layer. I'm assuming this is needed for `influx-mysql` because mysql needs the schema upfront while we create the schema as we receive the points.

If that's the reason, I don't see any reason why we have to add this to the server. It doesn't make much sense for InfluxDB (schemas are per-shard, not actually per measurement) so we wouldn't be able to give the desired effect anyway. If this is just needed as some kind of compatibility layer, you can pretty safely just write the points as they were in your example and InfluxDB will be fine. I notice that in your input you set the schema point to zero. If you want to avoid having that point written (effectively discarded), you just need to set the retention policy duration so 1970-01-01 is a time that isn't included. We'll automatically drop points that occur before the retention policy duration. Otherwise, it's safe to just overwrite that point.

I don't think it would be a good idea for us to support a syntax that doesn't do anything in the open source version, but does something in a compatibility layer that connects to mysql.

If I'm wrong, please expand on your use case. Thanks.

**Comment by philip-wernersbach** [comment]
@jsternberg: Your use case is correct. MySQL is schemaful, so influx-mysql has to detect the schema somehow before pushing the points down to the MySQL SQL layer. The schemaful hint allows the user to specify the measurement schema upfront, which allows influx-mysql to bypass the costly (but 100% accurate) SQL schema detection logic.

If the InfluxDB internals have no need for this functionality, then that's cool, and that eliminates one of the reasons I made this issue.

The other reason is that I'd like to provide a drop-in transition path to InfluxDB, so that users of influx-mysql can transition to InfluxDB at any time if they so choose. I would personally prefer that the transition path from influx-mysql to InfluxDB not require tuning background settings such as the retention policy, since they're easy for end users to forget. But if that's the recommended transition path from InfluxData, then I'm fine with telling influx-mysql users that.

**Comment by jsternberg** [comment]
I think I'm going to close this then. If you want some way to make your line protocol compatible with ours, you can create a kind of special markup inside of comments. I know of some preprocessors that do that. So instead of the line protocol you specified, something like this:

```
#schema: cpu_load a='',b=0.0,c=0i 0
cpu_load a='hello world',b=1.0,c=2i 1000
disk_load value='' 0
disk_load value='loaded' 2001
```

The shorter the prefix for the comment, the easier it will be to preprocess and then proxy.

Otherwise, the other things I said work well.
