### ISSUE TITLE
Add an InfluxQL language server

### ISSUE THREAD

**Issue by philip-wernersbach** [influxdata/influxdb#7667]
One of the problems that I have in https://github.com/philip-wernersbach/influx-mysql is that InfluxQL is different enough from SQL that I have to transform the InfluxQL into SQL before I can pass it to MySQL. It would be nice if there was an InfluxQL language server that I could pass an InfluxQL query to, and get back an AST.

**Comment by jsternberg** [comment]
Is there a reason why the `influxql` library written in Go doesn't work?

**Comment by philip-wernersbach** [comment]
Can we reopen this to discuss more?

Anyways, the `influxql` library looks like a good starting point for this. Does it have a stable, published API? If not, I'd like to work with you to establish that. Also, I think it would useful to establish an "InfluxQL language server protocol" so that other InfluxDB tools can use it. I'd like input on what would be the most useful protocol to other people.

**Comment by jsternberg** [comment]
I don't think there's much to discuss. While we aren't promising the `influxql` library as stable since we don't promise that of anything within the repository, it's quite easy to just pin the dependency for that package. The stuff related to the AST (not the query engine, which is combined in the same package) is incredibly stable and rarely changes since there isn't a lot of work that needs to be done on changing the query language after we hit 1.0.

As for the server protocol, I'm not really sure I see any benefit to it. A server just complicates infrastructure and I don't see a clear benefit to any of the products we develop. If there's a third party product like yours that could benefit from it, you can make the server using the `influxql` package. If you develop a server that does this, feel free to share it with us and we can share it with anybody who asks about such a thing.

I'm willing to listen to reasons why this is something we should work on and if those reasons are convincing, we can considering reopening the issue.

There is #7521 that I created to split the parsing portion of that package from the query engine portion, but it's incredibly low priority at the moment.

I hope that helps.
