### ISSUE TITLE
write data successfully but there is no data in the db

### ISSUE THREAD

**Issue by vicanso** [influxdata/influxdb#7668]
1. Wrote data with time(ns) to the db successfully(the response status 204).
2. I used the influx tool to query the data, but not found.
3. I found that the system time of influxdb server has 20 minutes delay.

I want to ask,  when the write point's timestamp is later than influxdb server timestamp, the point will be lost? How many seconds later than influxdb server timestamp will the write point be lost?

**Comment by e-dard** [comment]
@vicanso what version of Influx are you using? My guess is you're using a version earlier than `1.1`. In those versions the default time upper bound on a query is the current time, which will be earlier than your point's timestamp if your server time is behind by 20 minutes. 

In 1.1 we changed the behaviour so that future points are returned by default. Regardless, your points have not been lost, they're just not being in the time range you're querying.

**Comment by vicanso** [comment]
@e-dard I see. My influx version is 1.0.1
