### ISSUE TITLE
[Feature Request] Write data only with Tag key and without Field Key

### ISSUE THREAD

**Issue by ZhukovAlexey** [influxdata/influxdb#7690]
### Feature Request

__Proposal:__ 

Sometimes there's a need to have a measurement with only one tag. Just do the count of events.

__Current behavior:__ 

`curl -i -XPOST 'http://vuis-test:8086/write?db=testdb' --data-binary 'LOANREPORT,credittype=IL 1481010806000000000'`

HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: dc2c3a47-bb8a-11e6-98a3-000000000000
X-Influxdb-Version: 1.1.0
Date: Tue, 06 Dec 2016 08:06:15 GMT
Content-Length: 97

{"error":"unable to parse 'LOANREPORT,credittype=IL 1481010806000000000': invalid field format"}

To have a success write we need to add fake field with value=1

`curl -i -XPOST 'http://vuis-test:8086/write?db=testdb' --data-binary 'LOANREPORT,credittype=IL value=1 1481010806000000000'`

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: f044f9d7-bb8a-11e6-98a6-000000000000
X-Influxdb-Version: 1.1.0
Date: Tue, 06 Dec 2016 08:06:49 GMT

__Desired behavior:__ 

Write should be successful without definition any Field Key.

__Use case:__ 

In my case there's only one tag and we want to do the COUNT(*) where tag_name='tag_value' to see how much of events happens. And just one tag, which is indexed, it's enough.

**Comment by ZhukovAlexey** [comment]
Oh, I see that COUNT() function work only with fields.

This would work 
`SELECT COUNT(value) FROM LOANREPORT WHERE credittype='IL'`

But doesn't with tag
`SELECT COUNT(credittype) FROM LOANREPORT WHERE credittype='IL'`

**Comment by jsternberg** [comment]
Yea, the storage engine only stores fields with a time. Tags are stored as part of metadata and can't be queried because they are indexing markers rather than fields written.

I don't think we have a way to just write a marker for a time period. You might want to just write a boolean true as a sentinel value instead. Then you can use `count()` on that field.

I'm going to close this. If you need any help with InfluxDB, ask your question on the InfluxDB [mailing list](https://groups.google.com/forum/#!forum/influxdb). If you want me to reopen this issue for whatever reason, just comment here and I'll reopen it.
