### ISSUE TITLE
Info about deleted data after DELETE/DROP comand

### ISSUE THREAD

**Issue by dstreppa** [influxdata/influxdb#7691]
### Feature Request
__Proposal:__ [Description of the feature]
After a DELETE/DROP comand an explanatory string shows the number of deleted data.

__Current behavior:__ [What currently happens]
> DELETE from trevano WHERE time>='2016-12-05T12:00:00Z' and time<='2016-12-06T00:00:00Z'

__Desired behavior:__ [What you would like to happen]
> DELETE from trevano WHERE time>='2016-12-05T12:00:00Z' and time<='2016-12-06T00:00:00Z'
>1000 samples deleted from measurement trevano

__Use case:__ [Why is this important (helps with prioritizing requests)]
To have a a fast idea of the deleted data. Considering the query above, if I receive as output "1000000 samples deleted from measurement trevano" instead of 1000 I can easily understand that I did an error.

**Comment by e-dard** [comment]
@dstreppa thanks for the request. Currently drops/deletes are reasonably cheap because of the data structures we use to store data in InfluxDB. We have do do some pruning and cleaning up, but we don't need to find all the relevant points/series and delete them one by one. As such it's not trivial to know how many points were dropped.

I think if we were going to add this feature we would have to query for the data internally before we did a delete/drop, so it seems like this is no different to you running the query and checking the output prior to the drop/delete command.

Maybe some other Influxers will have some input on this.

**Comment by dstreppa** [comment]
@e-dard thank you for the clear answer, I understand your point. I already do the check before and after the command to be sure.
