### ISSUE TITLE
Script to create source release tarball

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#7696]
As part of the release process, we should create a source tarball so that package maintainers can build directly from the source tarball, without retrieving dependencies as a separate step.

Requirements:

* The influxdb source directory should be in `src/github.com/influxdata/influxdb` within the tarball
* Go dependencies of influxdb should be in the vendor folder, i.e. `src/github.com/influxdata/influxdb/vendor` so that extracting the tarball to the GOPATH does not clobber any directories other than `influxdb`
  * https://github.com/sparrc/gdm/issues/20 tracks a new feature for gdm to save dependencies to the vendor folder
* The tarball does not contain any `.git` or other VCS folder
* The man pages in the tarball should be preprocessed with Asciidoc so that package maintainers can directly copy e.g. `influxd.1` to the operating system's man page directory
* In `cmd/influxd/main.go` and `cmd/influx/main.go`, we currently depend on the linker to populate the `version`, `commit`, and `branch` variables. After extracting the source tarball, package maintainers should be able to simply run e.g. `go build github.com/influxdata/influxdb/cmd/influxd` without needing to specify any other flags. I think the simplest way to achieve this would be to generate a separate .go file in the respective directories, with an `init` function that assigns the correct values to those variables. I'm open to other approaches to solving that problem.
* The tarball should be gzipped, and it may as well be at the highest level compression

cc @rossmcdonald

**Comment by drhpc** [comment]
Yeah, I am in the situation of a packager now. I downloaded the release tarball of version 1.3.5, extracted to $WORKSPACE/src/github.com/influxdata/influxdb, also fetched all dependencies in the traditional way, then packed up the whole workspace.

Expectation: I can take that workspace, extracted to some location on a target system, and build influxdb only with a go compiler being present. So far, I am failing to get any build rolling. I see several scripts, things that suppose that one should run containers on AWS to start with influxdb. Then, there is the build.py script. This one refuses any cooperation early on because it only works from a git repository where it can fetch version/branch information. I got the release tarball, why is that information not already there? Why are manpages not prepared?

For telegraph, I was able to simply start a build via
```
make VERSION=$version build
```
I would like to be able to do the same for influxdb. But the build.py is not very helpful:
```
 ./build.py --help
[ERROR] run: Command 'git rev-parse --abbrev-ref HEAD' failed with error: fatal: Not a git repository (or any parent up to mount point /srv/srcmirror_write)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
When the build only works from a git repo, why are there release tarballs at all?

**Comment by mark-rushakoff** [comment]
@drhpc see https://github.com/influxdata/influxdb/pull/8803 which is close to getting merged.

**Comment by drhpc** [comment]
@mark-rushakoff Skimming though that … can in be that you are always assuming build/deployment using Docker? We don't do that here. Just a plain hardware server that should run influxdb. Is the build supposed to be working in a plain filesystem prefix?

**Comment by mark-rushakoff** [comment]
@drhpc Assuming you have the influxdb repo checked out and your working directory is in that repo and you're on a machine with Docker, you should be able to run `./releng/source-tarball/build.bash -p $PWD/.git -s DESIRED_INFLUX_SHA -b NOMINAL_BRANCH_NAME -v NOMINAL_VERSION -o /path/to/output/dir`, to generate a source tarball. Then copy the tarball to the machine where you want to build from source, and run something like `mkdir /tmp/go && cd /tmp/go && tar xzf influxdb.tar.gz && GOPATH=$PWD go build github.com/influxdata/influxdb/cmd/influxd`.

The plan for influxdb 1.4 is that we will publish source tarballs that you can simply extract and run `go build`, in addition to the other artifacts you're used to.

**Comment by drhpc** [comment]
Hm, so that is the new picture (still don't see why Docker enters the picture, but I do see that I am from a different world and we're evaluating influxdb for a rather non-cloudy application, while everyone else runs it in Docker anyway, probably). And what would I do with the existing release tarball of version 1.3.5? Do these tarballs have a purpose?

So far I managed to get build.py run through when overriding the git hooks (like hardcoding version and branch). Now I wonder about installing and stumble over packaging of any sort requiring fpm. All I wanted is some equivalent to `configure && make && make install`. Old school stuff;-)

**Comment by mark-rushakoff** [comment]
We're using Docker in this case to minimize external dependencies and to ensure we're working with a reproducible, clean environment for every build.

Which release tarball are you downloading?

If you have `go` available, are you able to you follow the [CONTRIBUTING.md directions on building](https://github.com/influxdata/influxdb/blob/a40ef53b49837d90d4ca32499a253e96b3443dfe/CONTRIBUTING.md#build-and-test)?

```bash
go get github.com/sparrc/gdm

cd $GOPATH/src/github.com/influxdata/influxdb
gdm restore

go clean ./...
go install ./...
```

**Comment by drhpc** [comment]
Ah, I missed that document! Somehow it eluded my attempts to find hints about building. $GOPATH/bin/* is all I need, right (apart from the odd manpage)?  I am only the colleague who shall install the programs, someone else deals with the configuration. Out of principle (as scientists, and just generally;-), we want builds from source instead of provided binaries.

Then it seems I'm all set, thanks. I had the dependencies pre-collected with gdm and am intending to start from a tarball of the workspace with the deps extracted on the host system.

About the need for docker for a reproducible environment: In the HPC community, we make use of shell modules for this. Minimal software installed in the base system and everything else installed in separate prefixes that are pulled in by loading the modules into the shell session. The end result is probably not that different …

**Comment by mark-rushakoff** [comment]
>$GOPATH/bin/* is all I need, right (apart from the odd manpage)?

Yes, `go install ./...` should put `influx`, `influxd`, and the other commands in the `cmd` folder, all into $GOPATH/bin. If you haven't seen it yet, there's a Makefile in the `man` directory for building the manpages from asciidoc.

>intending to start from a tarball of the workspace with the deps extracted on the host system.

That should be sufficient.

**Comment by drhpc** [comment]
Thanks. For completeness, this is my build process now for the release:

1. Pre-Packaging (on a repository server)
```
wget https://github.com/influxdata/influxdb/archive/v1.3.5.tar.gz
tar=$PWD/influxdb-1.3.5.tar.gz
rm -rf influxdb-1.3.5.wrk
mkdir influxdb-1.3.5.wrk
cd influxdb-1.3.5.wrk
export GOPATH=$PWD
mkdir -p src/github.com/influxdata
cd       src/github.com/influxdata
tar -xf $tar
mv influxdb-1.3.5 influxdb
cd influxdb
gdm restore
cd $GOPATH
find . -name .git | xargs rm -rf
cd ..
tar -czf influxdb-1.3.5.wrk.tar.gz influxdb-1.3.5.wrk 
```

2. Installation (on another box, probably segregated from the internet proper)

```
wget $local_server/influxdb-1.3.5.wrk.tar.gz
tar -xf influxdb-1.3.5.wrk.tar.gz
cd influxdb-1.3.5.wrk
GOPATH=$PWD
PATH=$GOPATH/bin:$PATH
( cd src/github.com/influxdata/$package && go install -ldflags="-X main.version=1.3.5" ./... )
cp -v bin/* $install_prefix/bin
```
