### ISSUE TITLE
Database config was be invalid

### ISSUE THREAD

**Issue by visoeclipse** [influxdata/influxdb#7710]
code:
=========================
package demo

import (
	"time"
	"testing"
	"github.com/influxdata/influxdb/client/v2"
	"fmt"
	"math/rand"
)

var clusters = []string{"public", "private"}

func TestInfluxdb_udp(t *testing.T) {

	// Make client
	c, err := client.NewUDPClient(client.UDPConfig{Addr:"localhost:8089"})
	if err != nil {
		panic(err.Error())
	}
	// Create a new point batch
	bp, _ := client.NewBatchPoints(client.BatchPointsConfig{
		Database : "schedule",
		Precision : "s", 
	})

	var tx time.Duration
	for tx = 0; tx < 20; tx++ {
		for i := 0; i < 100; i++ {

			clusterIndex := rand.Intn(len(clusters))

			tags := map[string]string{
				"client_host": fmt.Sprintf("192.168.%d.%d", clusterIndex, rand.Intn(100)),
				"uuid" : fmt.Sprintf("%s", time.Now().Unix()),
			}

			fields := map[string]interface{}{
				"idle":   rand.Float64() * 100.0,
				"system": rand.Float64() * 100.0,
				"user":   rand.Float64() * 100.0,
			}

			point, err := client.NewPoint(
				"tasklist3",
				tags,
				fields,
				time.Now(), 
			)

			if err != nil {
				fmt.Println(err)
			}

			bp.AddPoint(point)
			err = c.Write(bp)

		}
	}

	fmt.Println(err)
}

=====

database: schedule

but, the data will insert into database  "udp".

**Comment by jsternberg** [comment]
Hello, this looks like a usage question about the server rather than a feature or bug. We only use the issue tracker for features or bugs. Can you send this question to the [mailing list](https://groups.google.com/forum/#!forum/influxdb) instead?

Also, before you send the question there, it would be helpful if you updated your question with the question you want to ask. I'm unclear what the problem or expected behavior is and the people on the mailing list will probably be confused too.

Thanks. If it turns out this is a bug in the server, feel free to comment on the issue and I can reopen it.
