### ISSUE TITLE
why add "Connection: close" to http response while query data from influxdb

### ISSUE THREAD

**Issue by runner-mei** [influxdata/influxdb#7725]
tcp connections is too much on my pc, connection state is TIME_WAIT, like this:
TCP    127.0.0.1:8086        127.0.0.1:49335        TIME_WAIT       0

add "Connection: close" to http response:
https://github.com/influxdata/influxdb/blob/master/services/httpd/handler.go#L416

**Comment by jsternberg** [comment]
The reason is because we use the ResponseWriter's [CloseNotify](https://godoc.org/net/http#CloseNotifier) to tell us when the connection is killed. We do this because it's the only way for us to know if the client has left and we should prematurely kill the query output. A slight prevention against denial-of-service attacks and conserves server resources.

But that method is incompatible with reusing connections so we send back `Connection: close` to prevent the client from trying to reuse it and causing the server to hang. See [this comment](https://github.com/golang/go/issues/13165).

At some point, I think we're planning to switch to use HTTP 2.0 where this problem will go away and we'll be able to do both pipelining and close notify, but we aren't there yet.
