### ISSUE TITLE
collectd: can not specify multiple typesdb location

### ISSUE THREAD

**Issue by matwey** [influxdata/influxdb#7753]
__System info:__

* influxdb 1.1.0
* Linux x86_64

I would like to have a way to specify two file locations for typesdb.
My current ```collectd``` config uses two typesdb:
```
TypesDB     "/usr/share/collectd/types.db" "/opt/custom_types.db"
```

I would like to migrate this to influxdb and need to provide both typesdb-s.

**Comment by mark-rushakoff** [comment]
The collectd `typesdb` config option can accept a directory which will be walked recursively to find multiple typesdb files.  Since your db files are in separate directories, I would expect you could create a new directory with symlinks to the db files and it would work as expected.

We've just merged PR #7750 clarifying that with a comment in the sample config.

It's unlikely that we will change the behavior of the config setting to accept multiple files as opposed to a single directory.
