### ISSUE TITLE
OOM hits when loading data

### ISSUE THREAD

**Issue by niclan** [influxdata/influxdb#7793]
### Bug report

__System info:__ Influx 1.1.1 on x86_64 Ubuntu 16.04.1 LTS.  1TB of SSD storage. 16GB of RAM. 

__Steps to reproduce:__

While experimenting with influxdb to qualify it for our workload:

1. Plain install of influxdb and ubuntu. 
2. Load historical data from rrd into influx - ~20K measurement lines at a time in each write call.
3. Memory consumption of InfluxDB increases monotonically.  After some hundreds or thousands of write calls OOM killer hits:

`
[74108.954708] Out of memory: Kill process 26923 (influxd) score 973 or sacrifice child
[74108.954771] Killed process 26923 (influxd) total-vm:24569348kB, anon-rss:15975800kB, file-rss:0kB
`

If I instead just load 10 point time series of all different measurement name and tag values to check for cardinality related memory usage it stops around 9GB.  Cardinality is just above 200K btw.

__Expected behavior:__ [What you expected to happen]

Memory usage should at some point not increase any more

__Actual behavior:__ [What actually happened]

OOM kill.

**Comment by desa** [comment]
@niclan Couple questions
1. What commands did you run for the plain install?
2. Can you describe your data shape in line protocol a bit more?
3. Over what time range does your historical data span?
4. Were the time stamps of the data you were writing monotonically increasing?

**Comment by niclan** [comment]
1. Inatalled

`# apt-get install influxdb`

```
# apt-cache policy influxdb
...
  Installed: 1.1.1-1
  Candidate: 1.1.1-1
  Version table:
 *** 1.1.1-1 500
        500 https://repos.influxdata.com/ubuntu xenial/stable amd64 Packages

```

Then I changed the config so that everything is on the TB SSD volume: /data1/influxdb/meta, .../data and .../wal

2. At the perl level:

  for all data in a rrd file:
```
        my $line =
          data2line($measurement,
                    \%data,
                    {
                     host => $host,
                     target => $targetid
                    },
                    $time
                   );

        push @lines, $line;
...
   my $e = $influx->write(join("\n",@lines),
                           database => 'test_db', precision => 's');

```

The majority of the rrd files is network interface traffic: Each line looking like this:

`if,host=ar3.br,target=ge-1/0/0.1046 inerrors=0.000000,innucastpackets=0.000000,inoctets=34676.858045,inucastpackets=188.680105,outdiscards=0.000000,outerrors=0.000000,outnucastpackets=0.000000,outoctets=142035.299420,outqlen=0.000000,outucastpackets=195.853806 1469695200
`

3. Up to 4 years.  I did not install any retention policy yet. As it is from rrd the older data is sparse.

4. Yes monotonically increasing.  8-12 simultaneous clients.

**Comment by desa** [comment]
@niclan So I think there may be a number of things that are causing the OOM. Independent of them, we probably shouldn't OOM, but the behavior isn't entirely unexpected.

Batches of 20k with 10 fields each ~200k fields/sec per client. If we assume that there's ~10 clients, that means that we're attempting to write roughly 2M fields/sec. That alone will put a bit of stress on InfluxDB. Currently, write throughput for InfluxDB usually tops out just below 1M fields/sec. Additionally, since there are concurrent clients, its possible that the points received by InfluxDB are slightly out of order.

The other issue that I see is that the default shard duration is 7 days. Backfilling 4 years of historical data is going to create ~208 shards over a relatively short period.

I would suggest dropping the batch size down to 1k so that with 10 fields each, we'd be writing 10k fields/sec per client. The 8-12 concurrent clients should work just fine.

If you're still experiencing issues after that, I'd recommend adding another retention policy with a longer shard duration to your database. I'd try shard durations on the order of 3-4 months and write all data older than 1y into that retention policy.

**Comment by niclan** [comment]
OK, thanks.  I guess we'll go forward with a typical work-load and no historical data and see how that goes. This will take some time due to some other things.

**Comment by desa** [comment]
Sounds good. Once you get around to it let me know if there are any other issues. For the time being I'm going to close this issue, if you're still seeing OOMs, I'll reopen it.
