### ISSUE TITLE
(Possibly) inconsistent tag treatment with subqueries

### ISSUE THREAD

**Issue by rkuchan** [influxdata/influxdb#7846]
### Bug report

Ubuntu 16.04, 1.3.0~n201701150800

__Steps to reproduce:__

1. Write some data:
Where `color` is a tag and `value` is a field.
```
> SELECT * FROM pillows
name: pillows
time                 color  value
----                 -----  -----
2017-01-16T19:27:10Z blue   2
2017-01-16T19:27:10Z yellow 12
2017-01-16T19:27:15Z blue   1
2017-01-16T19:27:15Z yellow 13
2017-01-16T19:27:20Z blue   3
2017-01-16T19:27:20Z yellow 15
2017-01-16T19:27:25Z blue   4
2017-01-16T19:27:25Z yellow 16
```
2. Run one query with a subquery and `GROUP BY *` in the main query:
```
> SELECT MEAN("last") FROM (SELECT LAST("value"),"color" FROM "pillows" WHERE time >= '2017-01-16T19:27:10Z' AND time <= '2017-01-16T19:27:25Z' GROUP BY time(10s)) GROUP BY *
name: pillows
time                 mean
----                 ----
1970-01-01T00:00:00Z 14.5
```
3.  Run another query with the same subquery and `GROUP BY` a specific tag key in the main query:
```
> SELECT MEAN("last") FROM (SELECT LAST("value"),"color" FROM "pillows" WHERE time >= '2017-01-16T19:27:10Z' AND time <= '2017-01-16T19:27:25Z' GROUP BY time(10s)) GROUP BY "color"
name: pillows
tags: color=blue
time                 mean
----                 ----
1970-01-01T00:00:00Z 2.5

name: pillows
tags: color=yellow
time                 mean
----                 ----
1970-01-01T00:00:00Z 14.5
```

__Expected behavior:__
Based on [this discussion](https://github.com/influxdata/influxdb/pull/7646#issuecomment-265547406) I would have expected InfluxDB to treat `color` as a field in both of the main queries. So I would have expected to get the result in the second step when I `GROUP BY *` and when I `GROUP BY color`.

__Actual behavior:__ 
I get different results depending on if I `GROUP BY *` or `GROUP BY color` in the main query. When I `GROUP BY *` InfluxDB can't find any tags to group by because all tags have been converted to fields in the subquery (I think). But, when I `GROUP BY color`, InfluxDB applies that clause to both the subquery and the main query so I end up with `color` being treated as a tag.

I don't love that tags get turned into fields but besides that, I don't find the behavior I described above to be consistent. I'm also just getting acquainted with subqueries so there could be an easy explanation for this 😬

**Comment by jsternberg** [comment]
I am of the opinion this is a bug. The output from the first one is definitely the correct behavior. I think I might know the issue.

The intended behavior is that a grouping must occur at every level of the subquery for it to carry the tags with it to the next level. I don't even know how you got a tag in the last query since it should have been wiped out by the inner subquery not including it. The general philosophy is "what would happen if this were done with a `SELECT ... INTO ...`?" I think there's at least one situation where the subquery is able to do more functionality (which I can't remember, sorry), but the functionality shouldn't differ. An overall good way to test if the output of a specific query should work would be to do this:

```
CREATE DATABASE tmp12345
SELECT (inner query) INTO tmp12345.autogen.:MEASUREMENT FROM (inner query) WHERE (time clause from outer query)
SELECT (outer query)
DROP DATABASE tmp12345
```

The main thing is that the time clause from the outer query propagates to the inner query which wouldn't happen if you separate them. I'll start looking into why this is happening.
