### ISSUE TITLE
Alias field key backreference when using wildcard

### ISSUE THREAD

**Issue by corentingi** [influxdata/influxdb#7858]
### Feature Request

__Proposal:__
Hi!
Would it be practical to add a back-reference feature in alias __AS__ clause when using wildcards or regex?
`SELECT mean(*) AS :FIELD FROM measurementname ...`
Tell me what you think about this.

__Current behavior:__
This is not possible at the moment and the field name is concatenated with the functions.
This could be possible with two steps but would not be flexible.
(Listing all field keys and then building the query from this list)

__Desired behavior:__
The query `SELECT mean(*) AS :FIELD FROM measurementname ...` would replace `:FIELD` with the matched field key for each matched fields

__Use case:__
This would be great for __continuous queries__ so that the field key is not changed when resampling.
To re-use queries in Grafana for example.

__Current workaround:__
For the moment, you have to list all the fields with an external script and build fixed continuous queries.
It works fine as long as you don't add fields too often.

**Comment by einhirn** [comment]
This wouldn't even need a big change in syntax - at least in v1.2 there already is 
`       select mean(*) as "colname" from tablename [...]`
resulting in `colname_` being prepended to all original column names. Currently using
`       as ""`
results in the default behaviour of `mean_` being prepended, maybe this could just be changed to not prepending anything?

Of course there still is the problem of field key changing in continuous queries, because most aggregation functions only work for numeric values (int or float) - strings get dropped. I'd use something like "last" or "first" for string values and "mean" only for numerics - preferrably without having to spell out every measurement with all it's fields in continuous queries...

**Comment by mihaidraghici98** [comment]
I am interested in adding this feature. Saw similar feature request but no answer. Why using empty string for AS can't have the behavior of not appending the alias at all? I have tried AS "\n" which miraculously will be an empty string in the legend but the "_" (underscore) will still be there.

**Comment by BenoitPoulet** [comment]
Hello;

Same need here.
