### ISSUE TITLE
Set shard duration  less than 1h will fail

### ISSUE THREAD

**Issue by vicanso** [influxdata/influxdb#7939]
I want to set `shard duration 30m`,  the `influxl ql` run sucessfully (version 1.1.1 and 1.2.0), then run `show retention policies`. In version 1.1.1, the shardGroupDuration is correct, but in version 1.2.0, it's 1h0m0s instead of 30m0s.

### version 1.1.1

```
create retention policy "two-weeks" on "mydb" duration 1h replication 1 shard duration 30m

show retention policies on "mydb"

name		duration	shardGroupDuration	replicaN	default
----		--------	------------------	--------	-------
autogen		0s	        168h0m0s	         1		    true
two-weeks	1h0m0s	        30m0s		         1		    false
```

###  version 1.2.0

```
create retention policy "two-weeks" on "mydb" duration 1h replication 1 shard duration 30m

show retention policies on "mydb"

name      duration shardGroupDuration replicaN default
----      -------- ------------------ -------- -------
autogen   0s       168h0m0s           1        true
two-weeks 1h0m0s   1h0m0s             1        false
```

**Comment by mark-rushakoff** [comment]
It looks like the minimum shard group duration is set to 1h as of https://github.com/influxdata/influxdb/pull/7672. The PR title was "Enforce minimum shard duration when creating retention policies" but the changelog entry says "RP should not allow `INF` or `0` as a shard duration." A 30m shard group duration seems reasonable in many cases, so I'm not sure if the 1h minimum was fully thought out, especially since the changelog didn't specify that the minimum RP is now 1h. @corylanou?

**Comment by corylanou** [comment]
There was no specification for 1h in the original issue,  it was derived from what the minimum retention policy could be.  

https://github.com/influxdata/influxdb/blob/master/services/meta/data.go#L34
