### ISSUE TITLE
Derivatives getting a total when know tx and rx bytes.

### ISSUE THREAD

**Issue by psyciknz** [influxdata/influxdb#7960]
I've got a table with
time, host, direction and value
1,hosta,upload,100
2,hosta,download,500
3,hosta,upload,150
4,hosta,download,1000

So a host can have upload and download bytes, to get the amount of change for graphing I use derivatives.
If I wanted totals for both of these ie download difference 500 + upload difference 50 = 550 total.  As what I seem to get is 100 - 500 + 150 + 1000 - so it really fluctuates as it takes both the upload and download directions at the same time.

I've kind of fixed it by grouping by direction:  
SELECT non_negative_derivative(mean("value"), 1m) FROM "lan" WHERE $timeFilter GROUP BY time(1m), "host", "direction" fill(none) 
But I'd rather combine the two values and get a total bytes for 1m.

DB is influxdb

**Comment by sethm** [comment]
Hello,

I think you can achieve what you're looking for with a subquery. I am making two assumptions based on your test data:

1. I assume that you receive your measurements once per minute.

2. I assume that your upload measurement and download measurement alternate by one minute, as in your test data.

The query I've come up with is:

```sql
SELECT SUM(bandwidth) AS bandwith FROM 
    (SELECT NON_NEGATIVE_DERIVATIVE(MIN("value"), 2m) AS bandwidth 
        FROM lan WHERE $timeFilter
        GROUP BY host, direction, time(2m) FILL(none)) 
WHERE $timeFilter
GROUP BY time(5m), host FILL(none)
```

The inner query will select the rate of change of "value" per two minutes (since you get one upload and one download measurement every two minutes), grouped by host and direction. The outer query then sums the upload + download rate of change into one value per host. I chose "5m" as the group by arbitrarily, any value more than 4m should work. Your reports may need different groupings.

**Comment by psyciknz** [comment]
If, unlike my test data, the upload and download were same minute, does it change you query much?

So you'd group by 1m instead of 2m, is that correct?

**Comment by sethm** [comment]
Yes, that's correct. If they're both within the same minute, you can group by 1m.
