### ISSUE TITLE
[Query Fuzz] Fill(none) in query hangs

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#8067]
This issue was found by fuzzing the database with a query generator tool. It may be possible to simplify the query to help identify the root cause.

##### Dataset
```
$ curl https://s3.amazonaws.com/noaa.water-database/NOAA_data.txt -o NOAA_data.txt
$ influx -import -path=NOAA_data.txt
```

##### Query

```
USE NOAA_water_database

SELECT  "pH" / "degrees", "degrees" FROM  "average_temperature" GROUP BY "pq" FILL(none)
```

##### Result

The query hangs. Heap remains very low, no CPU activity.

See attached `SIGQUIT` on the server.

If you remove the `FILL(none)` the query returns fine. If  you change the query to:
```
SELECT  "pH" / "degrees", "degrees" FROM  "average_temperature" GROUP BY "pq" FILL(null)
```

it also returns fine.

[1488220500085551134-freeze.txt](https://github.com/influxdata/influxdb/files/804771/1488220500085551134-freeze.txt)

**Comment by jsternberg** [comment]
The issue seems to be because of a mismatch between auxiliary iterators.

All auxiliary iterators are read from the same source and have to be read with each other. `pH` seems to be an empty value so it returns a null point for everything. That causes `FILL(null)` to want to skip everything since it produces no values. But the `degrees` part of the query _does_ want to return a value. Since the expression iterator tries to skip past all of the points, but the second field has not read the first point yet, that causes the query to hang on a goroutine (why there is no cpu usage).
