### ISSUE TITLE
Have an option to return large numbers in json as standard format instead of scientific notation

### ISSUE THREAD

**Issue by prli** [influxdata/influxdb#8077]
### Feature Request

__Proposal:__ For /query API endpoint, have a parameter which can be used to choose to return large number in standard notation instead of scientific notation.

__Current behavior:__ Currently the /query API will return any large number (more than ~6 digits) in scientific notation.

__Desired behavior:__ I would like to have the option to receive json in standard format, similar to the option to get prettified json ("pretty=true")

__Use case:__ Working with the json (charting, calculations, transformations) sometimes require a change to standard form. It is nice to have the option to just receive the format as standard to start with. http://stackoverflow.com/questions/38434044/influxdb-select-query-integer-formatting

**Comment by jsternberg** [comment]
I'm currently watching this issue related to this: golang/go#6384. It seems like this issue changes things so anything that be represented as an integer is represented as an integer.

It looks like this is already in go 1.8 and so we should automatically retrieve that change. 1.2.0 is built with go 1.7.x (not sure which version exactly) and that won't change since we don't switch minor releases of Go for patch releases. But, we should be incrementing the Go version for 1.3 after we test to make sure it works properly.

Can you try compiling the master branch with go 1.8 in the meantime to see if it matches what you need?

**Comment by jsternberg** [comment]
I think this is done because of the change to Go. We do not plan to make any further changes.
