### ISSUE TITLE
csv columns include irrelevant headers

### ISSUE THREAD

**Issue by connor4312** [influxdata/influxdb#8096]
### Bug report

__System info:__InfluxDB 1.2.0

__Steps to reproduce:__

1. Create some users or retention policies
2. Use `show users` with an `Accept: text/csv` header

__Expected behavior:__ The csv output would mirror the JSON output, containing `user` and `admin` columns:

```json
{
  "results": [
    {
      "series": [
        {
          "columns": [
            "user",
            "admin"
          ],
          "values": [
            [
              "john",
              true
            ],
            [
              "steve",
              false
            ]
          ]
        }
      ]
    }
  ]
}
```

In CSV, I would expect this to be:

```
user,admin
john,true
steve,false
```

__Actual behavior:__ The output includes empty `name` and `tags` columns:

```
name,tags,user,admin
,,john,true
,,steve,false
```

__Additional info:__ This appears to be the case in other statements too, like `show measurements`. In this case those prefix columns actually conflict with other columns:

```
name,tags,name,duration,shardGroupDuration,replicaN,default
,,autogen,0s,168h0m0s,replicaN,true
,,7d,168h0m0s,24h0m0s,replicaN,false
```

I stumbled upon this while implementing csv support in [node-influx](https://github.com/node-influx/node-influx). There's a [script](https://github.com/node-influx/node-influx/blob/5.0.6/test/create-fixtures.js#L23) that I use to automatically generate fixtures, you can see the results in [this folder](https://github.com/node-influx/node-influx/tree/5.0.6/test/fixture/v1.2.0).

**Comment by jsternberg** [comment]
Hm, it seems to me that this happens because the JSON won't emit a name or tags section if they are empty, but I have it so the CSV always emits those. I could make it so it doesn't omit names or tags when neither of those are present.

It might present some other difficulties though. I think if the name is present we have to include a column for tags (even if there aren't any) mostly because there could be. We can be reasonably certain that if there is no name though that there are no tags and can omit both of them.

**Comment by jsternberg** [comment]
It also looks like CSV doesn't work for some outputs. For example, `SHOW STATS` will do a recoverable panic.
