### ISSUE TITLE
Inserting data with retention policy does not work with timestamp

### ISSUE THREAD

**Issue by jeromegn** [influxdata/influxdb#8109]
### Bug report

__System info:__
- InfluxDB 1.1.1 (installed via Homebrew)
- macOS Sierra 10.12.3 (16D32)

__Steps to reproduce:__

Open the influx CLI and run:

```
> CREATE DATABASE testing
> USE testing
> CREATE RETENTION POLICY hello ON testing DURATION 24h REPLICATION 1
> SHOW RETENTION POLICIES
name	duration	shardGroupDuration	replicaN	default
----	--------	------------------	--------	-------
autogen	0s		168h0m0s		1		true
hello	24h0m0s		1h0m0s			1		false
> INSERT INTO hello foo,foo_id=bar total=0.0 1488740963835
Using retention policy hello
> SELECT * FROM hello.foo
> SELECT * FROM testing.hello.foo
```

It yields no results even though no error was raised.

__Expected behavior:__

I expected data to be inserted properly with the retention policy.

__Actual behavior:__

No data inserted.

__Additional info:__

Some logs:

```
[httpd] ::1 - - [08/Mar/2017:11:23:23 -0600] "POST /write?consistency=all&db=testing&precision=ns&rp=hello HTTP/1.1" 204 0 "-" "InfluxDBShell/v1.1.1" eed9146f-0423-11e7-8563-000000000000 91
[query] 2017/03/08 11:23:35 SELECT * FROM testing.hello.foo
[httpd] ::1 - - [08/Mar/2017:11:23:35 -0600] "POST /query?chunked=true&db=testing&epoch=ns&q=select+%2A+from+hello.foo HTTP/1.1" 200 51 "-" "InfluxDBShell/v1.1.1" f6097e2a-0423-11e7-8565-000000000000 900
```

Edit: Sorry, submitted too quickly by mistake.

**Comment by jwilder** [comment]
@jeromegn Your time precision is off.  `1488740963835` should be in nanoseconds.  It's getting dropped because that time is actually `1970-01-01 00:24:48.740963835 +0000 UTC`.  Since your `hello` retention policy is `24hr`, you are writing too far into the past for that retention period.

Adding 6 zeros onto that timestamp (`1488740963835000000`) creates a date at `2017-03-05 19:09:23.835 +0000 UTC` which might be what you were trying to do.

**Comment by jeromegn** [comment]
@jwilder Oh, that makes some sense. I wish InfluxDB returned an error though. For instance, it does return an error if the retention policy does not exist.
