### ISSUE TITLE
Allow manual triggering of CQs

### ISSUE THREAD

**Issue by dgnorton** [influxdata/influxdb#8115]
### Feature Request

Up until 1.1, InfluxDB had an HTTP endpoint that allowed triggering CQs manually. This endpoint was added during development of the CQ service, for debugging purposes and early troubleshooting. It wasn't intended to be part of the API and was eventually removed. However, manually triggering CQs is useful in some cases (e.g., running CQs on recently imported historic data) and we should add this feature in a way that's consistent with other query operations, as part of the query language.

__Proposal:__

Add an `EXECUTE CONTINUOUS QUERY` statement to InfluxQL.

__Syntax:__
```
execute_continuous_query_stmt = "EXECUTE CONTINUOUS QUERY" query_name on_clause
                                [ where_clause ] .
```
With the semantic restriction that the `where_clause` may only contain a time range. Expressions filtering on tags, fields, etc. will return an error.

__Examples:__

Trigger a continuous query to run for the current time:
```
EXECUTE CONTINUOUS QUERY mycq ON mydb
```
Trigger a continuous query to run for the past 60 days:
```
EXECUTE CONTINUOUS QUERY mycq ON mydb WHERE time > now() - 60d
```
Trigger a continuous query to run for a 30 day block in the past:
```
EXECUTE CONTINUOUS QUERY mycq ON mydb WHERE time > now() - 60d and time < now - 30d
```

**Comment by JeremySTX** [comment]
This would be very useful to us also. Our data collection system, **by design**, does not guarantee to upload data in real time, so the CQ facility in its current form will miss some measurements.  (Most are uploaded within a few minutes of being collected but it's not unusual for there to be a delay in excess of an hour or more, possibly even a couple of weeks in extreme cases.  The lateness of the data does not reduce its usefulness for analysis.)

The current workaround is to run a SELECT INTO query to handle historical data, but this can quickly become an application maintenance nightmare: the same SELECT INTO has to be written for the CQ and for any application logic or ad-hoc scripts that load measurements into InfluxDB.

Incidentally, I would prefer that the `EXECUTE CONTINUOUS QUERY` feature would **allow selection on tags** as well as by time range.  (We can manage if it does not, but it's going to be rather inefficient without tag selection.)

**Comment by dgnorton** [comment]
@JeremySTX The CQ would still filter on the tags / fields as it was originally created. The time range specified in the `WHERE` clause of the `EXECUTE CONTINUOUS QUERY` statement would just be used to run the CQ over the specified time period. E.g., 
```
CREATE CONTINUOUS QUERY mycq ON mydb
BEGIN
   SELECT mean(value) INTO mean_value FROM cpu WHERE region = 'east' GROUP BY time(1h)
END
```
Followed by:
```
EXECUTE CONTINUOUS QUERY mycq ON mydb WHERE time > now() - 1d
```
Would execute:
```
SELECT mean(value) INTO mean_value FROM cpu WHERE time > now() - 1d and region = 'east' GROUP BY time(1h)
```
Does that address your concern with selection on tags?

**Comment by jsternberg** [comment]
I've been thinking we should have something like this, but was thinking `BACKFILL`. I think this syntax is probably better and I think it fills a niche the previously removed HTTP endpoint didn't address. The previous endpoint could only execute the current now interval while this can be used for backfilling data.

👍 from me.

Although, in the long term, I would like all continuous queries to be continuously updated through the intelligent rollups proposal. That's likely not going to get done soon though since it's quite difficult.

**Comment by JeremySTX** [comment]
@dgnorton The CQ I am writing is independent of tags.  We are monitoring a couple of thousand devices and each device's unique ID is a tag in the measurement. The CQ will process a thousand or so devices each run (every 10 minutes at the moment, but that may change).  Only a small percentage of devices will upload "historical" data outside the time range  of the CQ's normal processing cycle.

**Comment by gunnaraasen** [comment]
I also like this proposal and think adding tag selection would be useful, but that might be better handled as a separate feature request.

**Comment by intelfx** [comment]
This would be very useful in my usecase of collecting and aggregating netflow data. The flows are not guaranteed to come in-order and they can sometimes be significantly delayed by lengthy reverse DNS resolution.

**Comment by dgnorton** [comment]
Any thoughts on when it should return? I.e., should it kick off the CQ and return immediately or wait for the CQ to complete?

**Comment by jsternberg** [comment]
I'm not convinced this should run through the CQ subsystem to begin with. It seems fine to me if it looked up the SELECT query from the CQ metadata and just ran the command directly through the query engine. That's effectively what CQ's do anyway.

That way, you wouldn't have to mess with the CQ code very much and wouldn't have to track the request as it goes through the CQ service.

**Comment by pauldix** [comment]
+1 to what @jsternberg said

**Comment by JeremySTX** [comment]
Perhaps the way to do this is to look at it a bit differently.  The same result could be achieved by allowing the user to define "named queries" which have placeholder symbols in the WHERE clause. These queries are stored in the database (like a CQ) and invoked when required by the application, substituting actual values for the placeholders.

With such a mechanism in place, a CQ becomes a mechanism to invoke the named query on a regular basis, and the same query can be run ad-hoc.

For example,

1. a new command e.g. `CREATE QUERY stored-query-name AS query...`
2. a new command e.g. `RUN stored-query-name WITH param=value,...`(and note this functionality would have be accessible via the HTTP API so that applications can invoke it as required)
2. a variant to the CREATE CONTINUOUS QUERY syntax, e.g.
 `CREATE CONTINUOUS QUERY cqname RUN stored-query-name`

Of course the fine details of the syntax and mechanism would have to be worked out but I think it might be workable.

Regards,
Jeremy Begg

**Comment by dugwood** [comment]
@JeremySTX, @intelfx: isn't your need fulfilled with a combination of `EVERY` and `FOR`? See my comment here: https://github.com/influxdata/influxdb/issues/6932#issuecomment-383429731

@dgnorton's suggestion is really useful for debugging continuous queries when writing these, else you need to wait for the `EVERY` or run the request by hand (and maybe it won't return exactly what you expect).

**Comment by JeremySTX** [comment]
@dugwood, EVERY and FOR don't do it for us because of the unpredictable delay between the measurement being recorded by a device and being uploaded to the database.  As I noted in my earlier comments, the delay could be anything between a few minutes (typical) to several hours (not uncommon) and several weeks (not so common. but entirely possible).  To write a CQ with EVERY and FOR to cover that time range is simply not reasonable.  Hence my suggestion that the CQ be redefined as a mechanism to invoke a previously defined stored SELECT INTO query at some regular interval (EVERY and FOR), and that same stored query can be invoked by the application when new data is uploaded.

(Note that in our application we are not using Telegraf or any of the other Tick stack packages.  We have our own HTTP API for receiving batches of measurement data which is then written to the InfluxDB database.)

**Comment by dugwood** [comment]
@JeremySTX thanks for clearing that up. Same as in #6932 for @davidh-ssec. I added the comment because at first I was looking for resampling, and it's not obvious in the documentation that the delay could be handled with resampling. I think other people end up on those issues' pages, so it's worth noting.

And I don't know any application that can send the data exactly before the CQ runs... there's always a delay for the very last measurement sent as opposed to the exact second at which the CQ is run, so this delay would benefit all sources (HTTP API in your case, Telegraf with log parser for me, and so on).

**Comment by ainguyen-cpi** [comment]
I'm having the same issue when the network in device was down and data couldn't be sent on time. We keep those unsent data in the device so when the network is up again, it picks up the last timestamp and continues sending data over. However, network can be down for several days and like what JeremySTX said, writing a CQ using EVERY and FOR with a long time range is not really efficient (our data is 1s data so executing downsampling query for a long time range will takes most of cpu/memory, which possibly leads to server shutdown. We experienced this before when doing the database backup).

Thus, it would be nice if this feature request will be implemented. 
Thanks.

**Comment by JeremySTX** [comment]
Does the Flux language and InfluxDB 2.0 handle this ?

**Comment by djhoese** [comment]
@dgnorton Can we get some details on the `1.x` label? Is this a `wontfix` or something that users can hope for in a `1.x` release?

**Comment by dgnorton** [comment]
@djhoese the `1.x` label is used to separate issues found while running any 1.x release. Doesn't mean `wontfix`. However, I don't think manual triggering of CQs will be added in 1.x so I'm going to close this particular issue as `wontfix`.

@JeremySTX 2.0 has "tasks"
