### ISSUE TITLE
[bug] simple query becomes extremely slow when nested

### ISSUE THREAD

**Issue by daveselan** [influxdata/influxdb#8120]
InfluxDB shell version: 1.3.0~n201703100800

I'm wanting to get a count of unique hosts and was hoping to do it by nesting a GROUP BY query with a select count.  It works but is typically 30x or more slower when nested.

**Normal query runs under 2 seconds:**

```
% time influx -database testdb -execute 'SELECT last("cpu_time") FROM "host_cpu" WHERE "group" =~ /^dev$/ AND "job" =~ /^test/ AND time > now() - 1h GROUP BY "host"' | tail

name: host_cpu
tags: host=host233
time       last
1489158241 3.4

name: host_cpu
tags: host=host234
time       last
1489158241 22.3


_real	0m1.400s
user	0m0.014s
sys	0m0.008s_
----       -----
```

**Same query now wrapped takes 56 seconds:**

```
% time influx -database testdb -execute 'SELECT count(last) FROM (SELECT last("cpu_time") FROM "host_cpu" WHERE "group" =~ /^dev$/ AND "job" =~ /^test/ AND time > now() - 1h GROUP BY "host")' | tail

name: host_cpu
time count
0    40


_real	0m56.615s
user	0m0.007s
sys	0m0.008s_
----       -----
```

Maybe I'm missing something?

Thanks,
Dave

**Comment by e-dard** [comment]
@CarusDave thanks for the report. Can you provide us with information about how big the `testdb` database is? Do you know how many series, measurements and overall points there are?

**Comment by CarusDave** [comment]
Here's some database stats.

name: database
tags: database=testdb
numMeasurements numMeasurementsDropped numSeries numSeriesDropped
--------------- ---------------------- --------- ----------------
6               0                      13386006  2211227

name: write
pointReq  pointReqLocal req    subWriteDrop subWriteOk writeDrop writeError writeOk writeTimeout
--------  ------------- ---    ------------ ---------- --------- ---------- ------- ------------
303133578 303133578     130978 0            130978     0         0          126586  1987

name: httpd
tags: bind=:8086
authFail clientError pingReq pointsWrittenDropped pointsWrittenFail pointsWrittenOK queryReq queryReqDurationNs queryRespBytes req     reqActive reqDurationNs   serverError statusReq writeReq writeReqActive writeReqBytes writeReqDurationNs
-------- ----------- ------- -------------------- ----------------- --------------- -------- ------------------ -------------- ---     --------- -------------   ----------- --------- -------- -------------- ------------- ------------------
0        51          914938  0                    9326212           278013215       65679    476014555981052    459533751      1052026 8         569808323813185 1986        0         71409    1              167069956644  93708359091745

name: runtime
Alloc       Frees        HeapAlloc   HeapIdle    HeapInUse   HeapObjects HeapReleased HeapSys      Lookups Mallocs      NumGC NumGoroutine PauseTotalNs Sys          TotalAlloc
-----       -----        ---------   --------    ---------   ----------- ------------ -------      ------- -------      ----- ------------ ------------ ---          ----------
62311512920 224718463518 62311512920 26340433920 75669823488 400858492   17094418432  102010257408 6694638 225119322010 4629  449          117459935487 107798802440 27723063002424

name: queryExecutor
queriesActive queriesExecuted queriesFinished queryDurationNs
------------- --------------- --------------- ---------------
7             65667           65660           475725355636766

Thanks,
Dave

**Comment by jsternberg** [comment]
Slightly related to #3880 as that would make this query unnecessary, but we still need to look into the query performance anyway even if #3880 is implemented.

**Comment by jsternberg** [comment]
Is there any way we can have access to the data you're using? I tried using `influx_stress` to generate a simple database with the defaults and I'm not seeing the speed issue. I'm seeing the `last()` call alone taking longer (most likely due to memory allocations).

If the data is private, we can provide you with a place to send us your data so you don't have to post it publicly.

**Comment by CarusDave** [comment]
Thanks for looking into this. I was also thinking it was memory related partly due to the huge size of the memory index for this instance, though we are sitting at 40% system memory utilisation. 

We know we are pushing the boundaries a bit with the numbers of tags, and a few of them could contain 0.5mil unique values within the retention policy we are using, but a requirement for our particular use case.
The data is private, but I can give you more details on this particular schema that might help you?

So in the meantime, I decided to troubleshoot a few things. Indeed, I found that by reducing the database size and hence the memory footprint (20x smaller), this query ran very much faster. Actually the nested count now runs slightly faster than the group select on it's own (maybe expected).


### Here are the latest info on the smaller database (not sure how to get the nice table)

% time influx -database testdb2 -execute 'SELECT count(last) FROM (SELECT last("cpu_time") FROM "host_cpu" WHERE "group" =~ /^dev$/ AND "job" =~ /^test/ AND time > now() - 1h GROUP BY "host")' | tail

name: host_cpu
time count
0    40

**real	0m0.117s
user	0m0.012s
sys	0m0.000s**


name: database
tags: database=testdb2
numMeasurements numMeasurementsDropped numSeries numSeriesDropped
--------------- ---------------------- --------- ----------------
5               0                      807676    0

name: write
pointReq pointReqLocal req   subWriteDrop subWriteOk writeDrop writeError writeOk writeTimeout
-------- ------------- ---   ------------ ---------- --------- ---------- ------- ------------
15141795 15141795      12834 0            12834      0         0          12242   0


Thanks,
Dave
