### ISSUE TITLE
Add support for cumulative counts

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#813]
We should have an aggregate function that will return cumulative counts. For example, say we're grouping by 5m. The first 5m has 2 points, the second 5m has 1, and the last 5m has 3. A query like this:
```sql
select count(value) from events group by time(5m)
```

Would produce three points with values 2, 1, and 3. The cumulative output should produce three points with values 2, 3, and 6.

The tricky part is that most people want this type of cumulative function on the output of continuous queries. So they would have to handle reading the last cumulative value from the continuous query output instead of having it from what was computed before.

**Comment by rtuin** [comment]
I'm new to influxdb and a way to count the cumulative of values would be very useful.
Can someone point me to more info on these continuous queries mentioned above? I think I'm looking in the wrong places for it.

**Comment by beckettsean** [comment]
@rtuin continuous queries are partially documented here: http://influxdb.com/docs/v0.9/concepts/continuous_queries.html but the docs are already out of date (see #2267). Right now there are no cumulative counts built into the query engine. Continuous queries are a great use case for cumulative counts, but they are not a good way to create cumulative counts.

**Comment by e-dard** [comment]
ping @corylanou - is this one to remove `help-wanted ` while waiting on the engine refactor?

**Comment by corylanou** [comment]
Removing help wanted tag while query engine is going through refactoring.

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.

**Comment by jwilder** [comment]
This may be fixed now via #7388

Something like `select cumulative_sum(count(value)) from events ... group by time(5m)` might work.
