### ISSUE TITLE
[BUG] Enable Collectd But No Data

### ISSUE THREAD

**Issue by lin-credible** [influxdata/influxdb#8140]
### Bug report
__System info:__
InfluxDB: 1.2.0
OS: CentOS 7.3.1611 (core)

__Steps to reproduce:__

1. [First Step]
enable the collectd
```
[[collectd]]
  enabled = true
  bind-address = "192.168.20.60:25826"
  database = "collectd"
  retention-policy = ""
  typesdb = "/usr/local/share/collectd/"
  security-level = "none"
  batch-size = 5000
  batch-pending = 10
  batch-timeout = "10s"
  read-buffer = 0
```
2. [Second Step]
start influxdb
`service influxd restart`

3. [Third Step]
```
> show databases;
name: databases
name
----
_internal
telegraf
chronograf
collectd

> use collectd;
Using database collectd
> show measurements;
>
>
```
**nothing**

__Additional info:__ 

`collectd`:
```
[root@collectd ~]# tcpdump -i ens33 -p -n dst port 25826
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ens33, link-type EN10MB (Ethernet), capture size 65535 bytes
17:39:44.611045 IP 192.168.20.49.54299 > 192.168.20.60.25826: UDP, length 1342
17:39:44.611925 IP 192.168.20.49.54299 > 192.168.20.60.25826: UDP, length 1328
^C
2 packets captured
2 packets received by filter
0 packets dropped by kernel
```

`influxdb`:
```
[root@influxdb ~]# tcpdump -i ens33 -p -n port 25826
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ens33, link-type EN10MB (Ethernet), capture size 65535 bytes
17:39:47.507320 IP 192.168.20.49.54299 > 192.168.20.60.25826: UDP, length 1342
17:39:47.508334 IP 192.168.20.49.54299 > 192.168.20.60.25826: UDP, length 1328
^C
2 packets captured
2 packets received by filter
0 packets dropped by kernel
```

SHOW STATS:
```
name: collectd
tags: bind=192.168.20.60:25826
batchesTx batchesTxFail bytesRx droppedPointsInvalid pointsParseFail pointsRx pointsTx readFail
--------- ------------- ------- -------------------- --------------- -------- -------- --------
0         0             50432   0                    0               0        0        0
```

```
service influxd status -l
Redirecting to /bin/systemctl status  -l influxd.service
● influxdb.service - InfluxDB is an open-source, distributed, time series database
   Loaded: loaded (/usr/lib/systemd/system/influxdb.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-03-15 18:00:21 CST; 36s ago
     Docs: https://docs.influxdata.com/influxdb/
 Main PID: 41490 (influxd)
   CGroup: /system.slice/influxdb.service
           └─41490 /usr/bin/influxd -config /etc/influxdb/influxdb.conf

Mar 15 18:00:57 192.168.20.60 influxd[41490]: 2017/03/15 18:00:57 unable to find "memory" in TypesDB
Mar 15 18:00:57 192.168.20.60 influxd[41490]: 2017/03/15 18:00:57 unable to find "memory" in TypesDB
Mar 15 18:00:57 192.168.20.60 influxd[41490]: 2017/03/15 18:00:57 unable to find "cpu" in TypesDB
Mar 15 18:00:57 192.168.20.60 influxd[41490]: 2017/03/15 18:00:57 unable to find "cpu" in TypesDB
Mar 15 18:00:57 192.168.20.60 influxd[41490]: 2017/03/15 18:00:57 unable to find "cpu" in TypesDB
Mar 15 18:00:57 192.168.20.60 influxd[41490]: 2017/03/15 18:00:57 unable to find "cpu" in TypesDB
Mar 15 18:00:57 192.168.20.60 influxd[41490]: 2017/03/15 18:00:57 unable to find "cpu" in TypesDB
Mar 15 18:00:57 192.168.20.60 influxd[41490]: 2017/03/15 18:00:57 unable to find "cpu" in TypesDB
Mar 15 18:00:57 192.168.20.60 influxd[41490]: 2017/03/15 18:00:57 unable to find "cpu" in TypesDB
Mar 15 18:00:57 192.168.20.60 influxd[41490]: 2017/03/15 18:00:57 unable to find "cpu" in TypesDB
```

Is there something wrong???

**Comment by lin-credible** [comment]
I copied the `types.db` file to collectd. and I fixed it.

[types.db](https://github.com/collectd/collectd/blob/master/src/types.db)

**Comment by edgiru** [comment]
System info:
InfluxDB: 1.3.5
OS: Ubuntu Server 16.04.3 x64 (GNU/Linux 4.4.0-93-generic x86_64)

Not work collectd no data


Steps to reproduce:

**1. [First Step]**
enable the collectd

[[collectd]]
  enabled = true
  bind-address = ":25826"
  database = "collectd"
  retention-policy = ""
  typesdb = "/usr/share/collectd/types.db"
  security-level = "none"
  auth-file = "/etc/collectd/auth_file"
  batch-size = 5000
  batch-pending = 10
  batch-timeout = "10s"
  read-buffer = 0

**2. [Second Step]**  sudo systemctl status influxdb

● influxdb.service - InfluxDB is an open-source, distributed, time series database
   Loaded: loaded (/lib/systemd/system/influxdb.service; enabled; vendor preset: enabled)
   Active: active (running) since Пт 2017-09-01 14:11:22 MSK; 8s ago
  Docs: https://docs.influxdata.com/influxdb/
  Main PID: 8220 (influxd)
  Tasks: 9
  Memory: 82.4M
  CPU: 13.181s
  CGroup: /system.slice/influxdb.service
           └─8220 /usr/bin/influxd -config /etc/influxdb/influxdb.conf

сен 01 14:11:22 edgi-server influxd[8220]: [I] 2017-09-01T11:11:22Z /var/lib/influxdb/data/_internal/monitor/1 opened in 74.211
сен 01 14:11:22 edgi-server influxd[8220]: [I] 2017-09-01T11:11:22Z /var/lib/influxdb/data/_internal/monitor/2 opened in 75.823
сен 01 14:11:22 edgi-server influxd[8220]: [I] 2017-09-01T11:11:22Z /var/lib/influxdb/data/_internal/monitor/3 opened in 82.227
сен 01 14:11:22 edgi-server influxd[8220]: [I] 2017-09-01T11:11:22Z /var/lib/influxdb/data/_internal/monitor/4/000000001-000000
сен 01 14:11:22 edgi-server influxd[8220]: [I] 2017-09-01T11:11:22Z reading file /var/lib/influxdb/wal/_internal/monitor/4/_108
сен 01 14:11:22 edgi-server influxd[8220]: [I] 2017-09-01T11:11:22Z /var/lib/influxdb/data/_internal/monitor/5/000000002-000000
сен 01 14:11:22 edgi-server influxd[8220]: [I] 2017-09-01T11:11:22Z reading file /var/lib/influxdb/wal/_internal/monitor/5/_000
сен 01 14:11:22 edgi-server influxd[8220]: [I] 2017-09-01T11:11:22Z /var/lib/influxdb/data/_internal/monitor/4 opened in 35.932
сен 01 14:11:22 edgi-server influxd[8220]: [I] 2017-09-01T11:11:22Z /var/lib/influxdb/data/_internal/monitor/5 opened in 55.546
сен 01 14:11:27 edgi-server influxd[8220]: [I] 2017-09-01T11:11:27Z reading file /var/lib/influxdb/wal/_internal/monitor/7/_000

**3. [Third Step]**  sudo systemctl status collectd

● collectd.service - Statistics collection and monitoring daemon
   Loaded: loaded (/lib/systemd/system/collectd.service; enabled; vendor preset: enabled)
   Active: active (running) since Пт 2017-09-01 01:47:14 MSK; 12h ago
     Docs: man:collectd(1)
           man:collectd.conf(5)
           https://collectd.org
  Process: 3310 ExecStartPre=/usr/sbin/collectd -t (code=exited, status=0/SUCCESS)
 Main PID: 3321 (collectd)
    Tasks: 12
   Memory: 8.9M
      CPU: 5min 36.715s
   CGroup: /system.slice/collectd.service
           └─3321 /usr/sbin/collectd

сен 01 01:47:14 edgi-server collectd[3321]: plugin_load: plugin "write_graphite" successfully loaded.
сен 01 01:47:14 edgi-server collectd[3321]: [2017-09-01 01:47:14] plugin_load: plugin "write_http" successfully loaded.
сен 01 01:47:14 edgi-server collectd[3321]: plugin_load: plugin "write_http" successfully loaded.
сен 01 01:47:14 edgi-server collectd[3321]: plugin_load: plugin "write_kafka" successfully loaded.
сен 01 01:47:14 edgi-server collectd[3321]: [2017-09-01 01:47:14] plugin_load: plugin "write_kafka" successfully loaded.
сен 01 01:47:14 edgi-server collectd[3321]: [2017-09-01 01:47:14] Systemd detected, trying to signal readyness.
сен 01 01:47:14 edgi-server collectd[3321]: Systemd detected, trying to signal readyness.
сен 01 01:47:14 edgi-server systemd[1]: Started Statistics collection and monitoring daemon.
сен 01 01:47:14 edgi-server collectd[3321]: [2017-09-01 01:47:14] Initialization complete, entering read-loop.
сен 01 01:47:14 edgi-server collectd[3321]: Initialization complete, entering read-loop.

**4. [the fourth step]** 

> show databases
name: databases
name
----
_internal
openhab
collectd

> use collectd;
Using database collectd
> show measurements;
>
>
nothing


types.db already copied from this topic no fixed
