### ISSUE TITLE
[v1.2] Improve `influx_inspect export` parameter validation

### ISSUE THREAD

**Issue by kostasb** [influxdata/influxdb#8209]
With v1.2 `influx_inspect export` creates databases with the source retention policy name, and names retention policies using the shard id.  

Show shards:

```
name: telegraf
id database retention_policy shard_group start_time           end_time             expiry_time          owners
-- -------- ---------------- ----------- ----------           --------             -----------          ------
2  telegraf autogen          2           2017-03-13T00:00:00Z 2017-03-20T00:00:00Z 2017-03-20T00:00:00Z 
8  telegraf autogen          8           2017-03-20T00:00:00Z 2017-03-27T00:00:00Z 2017-03-27T00:00:00Z 
24 telegraf autogen          24          2017-03-27T00:00:00Z 2017-04-03T00:00:00Z 2017-04-03T00:00:00Z 

```

```
influx_inspect export -datadir telegraf -waldir telegraf -out dump.txt
```

Results:

```
# INFLUXDB EXPORT: 1677-09-21T01:47:35+01:34 - 2262-04-12T01:47:16+02:00
# DDL
CREATE DATABASE autogen WITH NAME "2"
CREATE DATABASE autogen WITH NAME "8"
# DML
# CONTEXT-DATABASE:autogen
# CONTEXT-RETENTION-POLICY:2
# writing tsm data
cpu,cpu=cpu-total,host=ubuntu16 usage_guest=0 1489754854000000000
...
```

**Comment by mark-rushakoff** [comment]
The root cause appears to be a combination of user error and insufficient validation in the tool.

The expected `datadir` and `waldir` arguments should be (e.g.) `~/.influxdb/data` and `~/.influxdb/wal`, but were instead provided as (presumably) `~/.influxdb/data/telegraf` and `~/.influxdb/wal/telegraf`. The sub-data and sub-wal directories should have been rejected during validation but were not.

It does not look like we have any tests covering the directory structure of the export command.
