### ISSUE TITLE
Or against two fields returns incorrect result when some values not present

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#8252]
If you have two fields `a` and `b` on measurement `foo`. Then you have points where a is set or both a and b are set or just b is set. When you have filters in the `WHERE` clause on those fields, the results returned will be incorrect.

To reproduce and see behavior in the CLI:

```
> create database test
> use test
Using database test
> insert foo a=3
> insert foo a=2,b=5
> insert foo a=4
> insert foo b=3
> select * from foo
name: foo
time                a b
----                - -
1491340640166342532 3 
1491340650223407506 2 5
1491340661844277686 4 
1491340665602537847   3
> select * from foo where a > 2
name: foo
time                a b
----                - -
1491340640166342532 3 
1491340661844277686 4 
> select * from foo where a > 2 or b > 3
name: foo
time                a b
----                - -
1491340650223407506 2 5
> 
```

Notice that the last query `select * from foo where a > 2 or b > 3` should have returned three records:

```
time                a b
----                - -
1491340640166342532 3 
1491340650223407506 2 5
1491340661844277686 4 
```

The `a` records that matched the where clause weren't present because `b` wasn't there. Similarly, if we had asked for `a > 2 or b > 2` it leaves out the record where b is set to 3 and a isn't set.

**Comment by jsternberg** [comment]
This issue brings up a more broad question about how null should be handled, especially in boolean expressions. I think previously we have not implicitly cast null to false and that's what has created the current behavior. At the moment, this isn't really defined very well so there's a bunch of inconsistency. For example, looking at the code, `null OR true` will return `null` and `true OR null` will return `false`. Obviously, that's incorrect. But should we be implicitly casting `null` to false for boolean expressions and maybe more? It would certainly make the logic a lot easier to deal with.

The comparison operators are likely less controversial, but what happens when you have something like `false = null`?

**Comment by pauldix** [comment]
We could either have `null` evaluate to false, or like Go we could have it evaluate to whatever the zero value is. In the case of the numeric comparisons I had above, they would return the same results, which would be correct and not the current behavior.

Even if we don't evaluate `null` to some value, it still doesn't make sense that `null > 2 OR 3 > 2` would evaluate to `null`. The left hand would be false because `null` isn't greater than 2 and the right hand would be true so the entire statement should evaluate to true.

**Comment by jsternberg** [comment]
Hm, I'm not sure I'm in favor of the zero value thing since, while I like it in Go, it does produce some problems in that the empty string is different than the string not being present. At the same time, we have no way to check for the difference anyway and missing tag values are treated as if they were the empty string so that might be more consistent for fields too.

I agree that comparisons do seem like they are different. As a side note, we do not appear to support comparison operators for strings, but we also don't produce any message that indicates that's why it failed.

**Comment by pauldix** [comment]
Ok, so I guess in the context of expression evaluation, `null` should evaluate to false unless we later add an expression `is null` or `= null`.

I logged #8265 for the string issue.
