### ISSUE TITLE
master: aggregate with group by time returns buckets through the minimum time

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#8266]
Given a setup with a few values:

```
> create database test
> use test
Using database test
> insert m,k1=v1 n=1
> insert m,k1=v1 n=10
> insert m,k1=v1 n=100
> insert m,k2=v2 n=2
> insert m,k2=v2 n=20
> insert m,k2=v2 n=200
```
On 1.2 at fad4784f9e0c0eeab0cc8ca3d7e976aeaa9ffbc7, group by time returns few points, as expected (when using aggregates such as top, bottom, or mean):

```
> select bottom(n, 2) from m where time < now() group by time(3650d)
name: m
time                 bottom
----                 ------
2009-12-22T00:00:00Z 1
2009-12-22T00:00:00Z 2
```

On master at 03338c69b5661b49fd5734c250bc95f486504cc7, the same queries return points through the minimum time:

```
> select bottom(n, 2) from m where time < now() group by time(3650d)
name: m
time                           bottom
----                           ------
1677-09-21T00:12:43.145224193Z
1687-09-19T00:12:43.145224193Z
1697-09-16T00:12:43.145224193Z
1707-09-15T00:12:43.145224193Z
1717-09-12T00:12:43.145224193Z
1727-09-10T00:12:43.145224193Z
1737-09-07T00:12:43.145224193Z
1747-09-05T00:12:43.145224193Z
1757-09-02T00:12:43.145224193Z
1767-08-31T00:12:43.145224193Z
1777-08-28T00:12:43.145224193Z
1787-08-26T00:12:43.145224193Z
1797-08-23T00:12:43.145224193Z
1807-08-22T00:12:43.145224193Z
1817-08-19T00:12:43.145224193Z
1827-08-17T00:12:43.145224193Z
1837-08-14T00:12:43.145224193Z
1847-08-12T00:12:43.145224193Z
1857-08-09T00:12:43.145224193Z
1867-08-07T00:12:43.145224193Z
1877-08-04T00:12:43.145224193Z
1887-08-02T00:12:43.145224193Z
1897-07-30T00:12:43.145224193Z
1907-07-29T00:12:43.145224193Z
1917-07-26T00:12:43.145224193Z
1927-07-24T00:12:43.145224193Z
1937-07-21T00:12:43.145224193Z
1947-07-19T00:12:43.145224193Z
1957-07-16T00:12:43.145224193Z
1967-07-14T00:12:43.145224193Z
1977-07-11T00:12:43.145224193Z
1987-07-09T00:12:43.145224193Z
1997-07-06T00:12:43.145224193Z
2007-07-04T00:12:43.145224193Z
2009-12-22T00:00:00Z           1
2009-12-22T00:00:00Z           2
```

**Comment by mark-rushakoff** [comment]
Bisected, looks like this behavior was introduced in commit 347b01814e1df47acf78b01f0e23ccafcba136b5.

cc @jsternberg

**Comment by jsternberg** [comment]
I'm sure there's something more that has to be fixed, but this is missing a bottom limit so the query says to find the bottom 2 points every 10 years from 1677 is correct.

The time for the points that do exist are weird though. They should be normalized to be in the 2007 bucket right above it.

**Comment by timhallinflux** [comment]
@jsternberg -- if there aren't any points, why are we displaying a time index?

**Comment by jsternberg** [comment]
The default for any time grouping is to use `fill(none)`. Since there's a grouping and the bottom time interval is set to the beginning of time, you get a grouping of 10 years since the first time we can record.

Normally, we throw an error if there isn't any time condition in the where clause, but since there is one, it accepts the query. The intention was to make queries like `WHERE time > now() - 10m` work without a problem, but the same rule also makes it so `time < now()` works too.

**Comment by timhallinflux** [comment]
@jsternberg how is it that the first time we can record is prior to the unix epoch time?  that seems a little odd.

**Comment by jsternberg** [comment]
We allow negative timestamps so `MinInt64` ends up somewhere around 1677. I'm not keen on trying to support older than that though since then we wouldn't be able to use `int64`.

**Comment by jsternberg** [comment]
I've looked into this a bit more and I think this story of diffs tells us what happened here. Here's the section of code that is incorrect, but I'm not sure in what way yet:

```go
        if !b.selector || !b.opt.Interval.IsZero() {
                if expr.Name != "top" && expr.Name != "bottom" {
                        itr = NewIntervalIterator(itr, b.opt)
                }
                if !b.opt.Interval.IsZero() && b.opt.Fill != NoFill {
                        itr = NewFillIterator(itr, expr, b.opt)
                }
        }
```

So this is run after many of the iterators are created and both `top()` and `bottom()` get run through here. If there is a time grouping or it's an aggregate, this section of code gets executed. Since we're using a time grouping, the fill iterator gets included. But, the interval iterator (the piece of code that normalizes the times to be the beginning of the interval) is skipped over for `top()` and `bottom()`. I wasn't sure of the specific reason, so I looked at blame. The commit that came up was subqueries, but that change was mostly because the code got moved and the indentation had changed. No meaningful code change. The previous time it was changed was to fix a bug and here's the diff for that.

```go
-                       if expr.Name != "top" && expr.Name != "bottom" {
-                               itr = NewIntervalIterator(itr, opt)
-                       }
-                       if !opt.Interval.IsZero() && opt.Fill != NoFill {
-                               itr = NewFillIterator(itr, expr, opt)
+                       if !selector || !opt.Interval.IsZero() {
+                               if expr.Name != "top" && expr.Name != "bottom" {
+                                       itr = NewIntervalIterator(itr, opt)
+                               }
+                               if !opt.Interval.IsZero() && opt.Fill != NoFill {
+                                       itr = NewFillIterator(itr, expr, opt)
+                               }
                        }
```

This one tells a more contradictory and confusing story. It looks like the interval iterator was used for all selectors all the time and we weren't supposed to do that. Before we made it so all selectors show their actual time, `top()` and `bottom()` had already been excepted so they showed their proper time. So it's unclear if that condition is still needed because `top()` and `bottom()` would just get treated like another selector now instead of being treated specially.

So the underlying question is: If there is a time grouping, should `top()` and `bottom()` normalize the points times to the beginning of the interval like the other selectors or should it not use the fill iterator? Or maybe both. I'm uncertain how useful fill is with `top()` or `bottom()` queries to begin with at the moment.

Thoughts?

**Comment by jsternberg** [comment]
@pauldix can you take a look at the comment above? Thanks.

**Comment by pauldix** [comment]
@jsternberg I don't think `fill` is very useful with `top` and `bottom`. Also, I thought the default fill option was `fill(null)` on any group by time query?

**Comment by jsternberg** [comment]
`fill(null)` is the default. Do you think `top()` should normalize the time to be the beginning of the interval or keep the times of the individual points?

**Comment by pauldix** [comment]
probably keep the times of the original points. That's what most people want. It's also the behavior if you don't specify a group by time.
