### ISSUE TITLE
Make default timestamp precision a system configuration

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/influxdb#8331]
### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

__Proposal:__  Make the default timestamp precision a system configuration.  This is related to, but not not the same as issue #6041 .    That issue proposes changing the internal result, or a more advanced feature for auto-detecting precision when no explicit value is provided from the user.  

__Current behavior:__ Currently the precision for a timestamp is determined by either a user parameter or, if no parameter is given, by a hard-coded default of nano-seconds.  

__Desired behavior:__ At installation/config time, the user should have the opportunity to select the default precision.  This value will be used in place of the hard-coded nano-second "n" setting.  To ensure backward-compatibility, the value at install/upgrade time should remain as "n", and then educated users may access this setting later if they desire.  Documentation and/or prompting could also be added to highlight this new capability.  

I also propose two new values for the precision value, whether given as a default config or as a parameter: 

--auto: influxdb will auto-detect the precision as that which evaluates the time stamp closest to the current UTC.  (can be delivered as a solution to #6041 )

--unknown: not useful as a run-time parameter, this will cause all writes to fail until a valid precision is provided either by configuration or at runtime.  

__Use case:__ new users tend to make a mistake in sending time with seconds-since-epoch precision when the default is nano-seconds.  There are also performance gains (better compression) to be made in setting a coarser precision than nano, so that a user may want to have seconds be the system default to ensure the best performance.

**Comment by maksa** [comment]
From the new user POV nanoseconds was really an unfortunate choice for default, but I suppose that removing this default would break other people's code and after going through Swift 2 -> Swift 3 conversions for two projects I have developed visceral disdain for code breaking language changes.
 
My 2c:
Add the ability to specify the unit "in-place" by appending it to the number, e.g.: 123456s. Add real rfc3339 support, i.e. the ability to specify the timestamp as 2017-03-21T13:00:00.00. If only date is specifed assume zeroes for everything else (along the lines of Go philosophy). Another nice thing would be to free the timestamp from the position, i.e. currently (from what I've seen) the system relies on the timestamp to be the last thing specified. I'd use the @ character to explicitly specify it, so that the timestamp can be wherever one wants it to be. 

This would result in something like this:

insert @2017-09-12T11:33:01.00 pressure,point='east' value=190 

or:

insert pressure,point='east' value=190 1425337200s

(Again, in order not to break existing user code it should tolerate the timestamp at the end without the @ modifier, and assume nanoseconds if no unit is specified).

Also, separate precision for input from output format, they should be two different things and changing one shouldn't affect the other, probably by introducing timeformat setting or similar.

Alternatively, a lot of confusion about this would be removed by updating the documentation and adding more usage samples - nowhere in the official docs can one find the sample for adding a point with a user supplied timestamp. It's a FAQ candidate at least.

**Comment by adamGSQL** [comment]
in-line specifiers are certainly useful for app-generated info, and I would support that type of RFC.  But they won't work for sources where the data format is easily controlled (e.g. server logs) and like you said they are not back-compatible.  

This proposal is really a combination of code + documentation change.  First, to provide 'auto'  precision as an option, and then to make the default setting + installation + usage docs consistent to educate the user about selecting a default precision.
