### ISSUE TITLE
Influxdb query error

### ISSUE THREAD

**Issue by sLuvpreet33** [influxdata/influxdb#8379]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Influxdb v 1.2.2

Hi, Influxdb is not behaving properly.
I query for the data in the previous 5 minutes, but it is returning me too much data and that too from all the time today.

See in the picture, I have queried the data only of previous 5 minutes. The time of query was 18:02, and it has returned me data from 14:41 , which is nowhere near the previous 5 minutes.

I have to see this data in the map and this data is very crucial for me. Can you tell me what is wrong here, me or influxdb ?

![screenshot from 2017-05-08 18-02-17](https://cloud.githubusercontent.com/assets/23127804/25914125/d1e3b118-35da-11e7-9bc9-e16f52135b48.png)

**Comment by jsternberg** [comment]
Which time zone are you in and have you checked the time on the server?

**Comment by sLuvpreet33** [comment]
I am in Indian Time Zone.

Well, the thing is that the time zone definitely matters in this query. But another thing is, it must return the dataset only from a span of 5 minutes. You can see that it is sending data which is having very different time values, it is giving me values of almost last 6-7 hours(I can't show that in screenshot), while it should return data from past 5mins only.

**Comment by jsternberg** [comment]
So if you're in the Indian Time Zone, Google is telling me that's +5:30 GMT at the moment. So 18:02 your time would show up as about 12:32 in GMT. Since you don't have an end time on your query (`time <= now()`) and you aren't using a time grouping (`GROUP BY time(...)`), that selects all points both since 12:32 and forever in the future. I think if you add the upper time bound it will make more sense. It appears you are writing points into the future somewhere from what I see.

**Comment by sLuvpreet33** [comment]
yeah, It solved the issue.
Thanks.
