### ISSUE TITLE
Selecting 'time' or 'sequence_number' columns not possible

### ISSUE THREAD

**Issue by hvt** [influxdata/influxdb#84]
The following queries do not result in the behavior I would expect:

```
select time from test
```

Results in: 'Field time doesn't exist in series test'.

And also:

```
select sequence_number from test
```

Results in: 'Field sequence_number doesn't exist in series test'.

**Comment by jianwu** [comment]
Can't select time is a surprise for me as well. For my use case, I periodically incrementally sync time serial data from other system, so I need to know what's the max(time) already synced in the influxdb. But unfortunately it doesn't work. I know we can use the "limit 1" trick as a workaround. but it's just not a nature way which makes the code un-necessary complex. Any specific reason to drop this support.

**Comment by feliksik** [comment]
I do not understand well why the behavior of "select time from foo" is undefined; could it not select all time fields of all entries? 

Anyway, I would like grafana to show the last time since a host was seen. So I was expecting something like "select (now()-time) from foo limit 1", but this doesn't seem possible. Is this usecase possible some other way?

**Comment by petterbrodin-goodtech** [comment]
I think I have the exact same problem as @feliksik 

In Grafana, I want to compare the now() value to the most recent value from a sensor to see if the values are stale or current.

**Comment by TiddoLangerak** [comment]
I have the same problem as @jianwu. I have a sync task that periodically puts data in InfluxDB, where I manually set the time field of each entry. Since the time is set manually the `max(time)` doesn't necessarily correspond with the last inserted entry, and as such the `limit 1` trick doesn't work. In order to get the result I want I now need to duplicate the `time` field, on which I can query.

I don't really understand why querying on `time` or `sequence_number` would be problematic, as @jvshahid described. These are meta fields and thus they are (implicitly) present on all points. Therefore I think the only logical behaviour is to consider *all* points in a series if you query on them, just like @feliksik already suggested.

**Comment by pauldix** [comment]
@TiddoLangerak this issue is related to a version that is two years old and no longer supported. The current version, 1.1, doesn't support sequence numbers. However, you can write down to nanosecond scale timestamps within a series so you have plenty of room to work with. The limit query should work as you'd want.

**Comment by tkiraly** [comment]
@feliksik did you find any workaround for this use case?

**Comment by feliksik** [comment]
@tkiraly I'm no longer using influxdb at the moment.

**Comment by Swantu** [comment]
Im also looking for a way to query time. The timeframe is selected by Grafana dynamically, and I want to do math like average/mean... of my data. The math works for the values, but when I want to do math with the time (e.g. first and last timepoint toget a timeframe), I get stuck :(
