### ISSUE TITLE
select query doesn't give result

### ISSUE THREAD

**Issue by rajkumar1994tec** [influxdata/influxdb#8410]
### Bug report

__System info:__ [Include InfluxDB v1.2.0, CentoOS 7.2, and other relevant details]

__Steps to reproduce:__

1.try to select values from a result of an subquery with time in where class ..It supports other operators like <,> etc but doesn't support = operator for time field .

2. Sample Query : select * from (select sum(taskcount) from qos_wmsrstasks where time >  now() - 1h group by time(1m)) where time=1495267560000000000

3. [Sample SubQuery Result : ]
time                                   taskcount
1495267260000000000 22
1495267320000000000 18
1495267380000000000 60
1495267440000000000 36
1495267500000000000 18
**1495267560000000000 26**
1495267620000000000 120
1495267680000000000 220
1495267740000000000 144

__Expected behavior:__ [ i want result taskcount 26 to printed]

__Actual behavior:__ [it returns nothing]

**Comment by rajkumar1994tec** [comment]
@jsternberg Can u please respond for this ?

**Comment by jsternberg** [comment]
Hm, we may need to rethink how we deal with the time selections. What actually happens with time selection is that it chooses the most restrictive time interval that's in any of the queries. So the outer query has `time=1495267560000000000` so it uses that for the inner query rather than the actual time interval.

We may want to consider making it a bit smarter to accommodate `group by time(1m)`.
