### ISSUE TITLE
TZ() does not change result timestamps

### ISSUE THREAD

**Issue by M0ebiu5** [influxdata/influxdb#8460]
Tested influxdb version: 1.3.0~n201705270801
OS: linux 4.4.0 

I've expected that the new timezone feature adjusts the timestamps of the result according to the provided timezone. In my installation, the timestamp is always the same, no matter which time zone string  i feed into tz().

Example query:
`select *,last(accuracy) from presence group by beacon tz('America/Phoenix')`

**Comment by jsternberg** [comment]
I would guess this is an annoying time zone issue. Thanks for bringing it up.

Are you using the `influx` client? Unfortunately, the `influx` client requests points in `epoch` format and those get returned as unix timestamps (which don't contain location information). Then the client doesn't know which time zone was used and it restores the points from the epoch in the UTC time zone.

Can you confirm this is an issue with the `influx` client? I've got an idea to fix it if it is.

**Comment by M0ebiu5** [comment]
Yes, i've tested it with the influx client, but also with the node-red influxdb node - where i would use the tz functionality: [https://github.com/mblackstock/node-red-contrib-influxdb](https://github.com/mblackstock/node-red-contrib-influxdb). 

Does this mean that the influxdb node also needs an adaption?

**Comment by jsternberg** [comment]
Yes, anything that does requests with `epoch=1` would need to be adapted. I don't personally think it would be a good idea to have InfluxDB return anything other than UTC when using `epoch`.

One thing with your query is that the `TZ()` call doesn't necessarily do anything on the server since there isn't a `GROUP BY time()` so you can easily load the time in whichever time zone you want with or without `TZ()`.

**Comment by jsternberg** [comment]
I'm actually not sure if there's a simple way to deal with this.

My original idea was to include the time zone name for the query in the response, but that won't work because it's possible to have two queries with two different time zones.

It seems like the `influx` client, by default, will use `epoch=1` by default and will print the unix timestamp in nanoseconds. This format ignores the time zone because that information isn't preserved. But, when you use `> precision rfc3339` it will output in the correct time zone which is correct. I've tested this out on my local machine.

Since this works correctly, I don't think there's a resolution to this. The `influx` client appears to have the correct behavior. I'm not sure about the library you're using, but I hope I've given you enough help so you can figure out the proper place to load the time zone.

Is there anything else you need help with?

**Comment by M0ebiu5** [comment]
The node-red client does not use the epoch=1 - the results are like ' 2017-06-07T10:09:55.314Z'.
Could you please explain, how i can get the results with another timezone? Why do i have to group by time? Whats the easiest way to simply add 2 hours to all of the results?
Thanks for your help!

**Comment by jsternberg** [comment]
Can you share with me the exact way you are getting your result? Just a simple test where you write some data and use a query along with the programs/code you are using to do that.

**Comment by M0ebiu5** [comment]
There is basically no more code, than the query statement...
The actual use case is: i get data from owntracks via mqtt and store it into influxdb. The timestamp is not part of the insert statement - the db handles it and it is in GMT.

Now i query the last position of each beacon with `select *,last(accuracy) from presence group by beacon`.

The result is in GMT, but should have a 2 hours offset. So i think that the underlying influxdb node lib does not consider the timezone. To compensate that, i tried to append the tz() to the query - without success.

I dont want to waste your time - i will sometimes understand how tz() is supposed to work...

**Comment by jsternberg** [comment]
Ok, just one final question. Can you show me how you are running the query and the output of it? I just want to make sure that everything is, in fact, working correctly.

**Comment by M0ebiu5** [comment]
Running the query in influx works, if i switch the precision to rfc3339. 
```
> select time,last(acc) from presence  group by Beacon tz('America/Phoenix')
name: presence
tags: Beacon=client1
time                                last
----                                ----
2017-06-07T03:09:55.314727977-07:00 64

name: presence
tags: Beacon=client2
time                                last
----                                ----
2017-06-06T10:55:35.242472955-07:00 19
```

```
> select time,last(acc) from presence  group by Beacon tz('Europe/Paris')
name: presence
tags: Beacon=client1
time                                last
----                                ----
2017-06-07T12:09:55.314727977+02:00 64

name: presence
tags: Beacon=client2
time                                last
----                                ----
2017-06-06T19:55:35.242472955+02:00 19 
```

If i use epoch time format in the influx client - the time is never adapted. Also no error is thrown.

From my point of view, it would be clearer and more logical to also adapt the epoch time. The current behavior produces 2 different results with the same query - depending on which time output format i chose (or the tz() feature should not be allowed with epoch time format).

About the influxdb node library: i think there is already a request to adapt the library to the tz() feature.
Many thanks for your help!

**Comment by jsternberg** [comment]
For the record, the reason why we shouldn't adapt the `epoch` time is because the time zone information is separate from the time. All of the times have the same unix timestamp regardless of which time zone they are in. Time zones are mostly a display function.

The primary reason to include `TZ()` even with queries that use `epoch` is because it affects how we group different time intervals. If you do `GROUP BY time(1d)`, you'll get a midnight within your time zone as a start time rather than midnight at UTC as the start time.

I hope that helped.

**Comment by paulsalibe** [comment]
I know I am a little late to this but i am having the same issue now and don't entirely follow this solution. Where would `GROUP BY time(1d)` be incorporated into this? In the query? Thanks
