### ISSUE TITLE
Nightly build memory issue

### ISSUE THREAD

**Issue by oiooj** [influxdata/influxdb#8479]
### OS
CentOS 7.2

### influxDB version
InfluxDB v1.3.0~n201705270801 (git: master 3b08f65a20863266ac7775818931c537deb0507e)

![image](https://user-images.githubusercontent.com/2253095/27028452-6af19f84-4f97-11e7-96ed-8bb6511d83e9.png)

The black is `1.3.0` and the blue is `1.2.4`.
The server has 128G mem,  I restart at last.

I rollback to version `1.2.4`

**Comment by jwilder** [comment]
We need more information in order to diagnose what is going on.  Can you update the issue description with the instructions listed in our [issue template](https://github.com/influxdata/influxdb/blob/master/.github/ISSUE_TEMPLATE.md)?

A heap profile while memory is increasing or high would be useful.
