### ISSUE TITLE
Too many open files InfluxDB v1.3.1, macOS 10.12 Sierra, Python v3.6

### ISSUE THREAD

**Issue by johncarmack1984** [influxdata/influxdb#8618]
### Bug report

__System info: InfluxDB v1.3.1 (homebrew install) & macOS 10 Sierra (most recent version), Python v3.6

__Steps to reproduce:__

1. Collate Quandl wiki (available here: https://www.quandl.com/product/WIKIP/WIKI/PRICES-Quandl-End-Of-Day-Stocks-Info) into Pandas DataFrame
```
import csv
import pandas as pd
import numpy as np
from influxdb import DataFrameClient

print ("Placing WIKI csv into Pandas DataFrame...")
wiki = pd.read_csv('WIKI_PRICES_212b326a081eacca455e13140d7bb9db.csv')
print ("...done!")
print ("Converting date strings to timestamps...")
wiki['date'] = pd.DatetimeIndex(wiki['date'])
print ("...done!")
```
2. Pick one stock's returns and attempt to insert into database

```
print ("Initializing database connection...")
host = 'localhost'
port = 8086
user = 'root'
password = 'root'
dbname = 'quandlwiki'
client = DataFrameClient(host, port, user, password, dbname)
print ("...done!")
print ("Cleaning up previous data...")
client.drop_database(dbname)
client.create_database(dbname)
print ("...done!")
print ("Inserting rows into database...")
client.write_points(wiki[wiki.ticker=='AAPL'].drop('ticker', axis=1).set_index('date'), "AAPL")
print ("...done!")
```
__Expected behavior: insertion of 1000+ rows into database

__Actual behavior: insertion fails and console/python outputs the following 
```
InfluxDBServerError: b'{"error":"[shard 20973] open /usr/local/var/influxdb/data/quandlwiki/autogen/20973: too many open files"}\n'
```

**Comment by e-dard** [comment]
Hi @johncarmack1984,

Looking at that shard ID (`20973`) it's possible you have many shards on your system, which would lead to many open files. You may not have your `ulimit` set high enough. 

Would you be able to provide some further details? Specifically:

```
curl -o vars.txt "http://localhost:8086/debug/vars" 
iostat -xd 1 30 > iostat.txt
influx -execute "show shards" > shards.txt
influx -execute "show stats" > stats.txt
influx -execute "show diagnostics" > diagnostics.txt

Plus the result of $ ulimit -n.
```


You can drag and drop all the files as an issue comment. If you're concerned about exposing stats, shards or diagnostics then you can email those to my first name as it appears on my Github profile page `@influxdb.com`

**Comment by johncarmack1984** [comment]
Oddly enough, the issue went away. I didn't even change anything in the code, just for some reason uninstalling and reinstalling for the third time did the trick.

Thanks for asking after the problem. :)

**Comment by johncarmack1984** [comment]
Whoops. Spoke too soon. Now I'm getting a server timeout, but way further into the process.

Here's the requested info: 

[diagnostics.txt](https://github.com/influxdata/influxdb/files/1170638/diagnostics.txt)
[shards.txt](https://github.com/influxdata/influxdb/files/1170641/shards.txt)
[stats.txt](https://github.com/influxdata/influxdb/files/1170639/stats.txt)
[vars.txt](https://github.com/influxdata/influxdb/files/1170640/vars.txt)

```
$ ulimit -n
2560
```

**Comment by e-dard** [comment]
@johncarmack1984 

You have around 2,400 shards on your system. Each shard needs one (or usually more) file descriptors open at any given time. 

An immediate bandaid would be to increase the number of file descriptors your OS will allow you to have open (currently it's 2,560 which is probably why you're hitting that and Influx is panicking).

You can usually set that by doing something like `ulimit -n 12345`.  Some OSes only respect that setting in the current shell; you would have to check how to raise it permanently. 

A longer terms solution though will be to consider changing your shard group duration so that you reduce the number of shards on your system. This will also increase performance, since fewer shards is usually better than many.

It looks like you have a lot of historical data. Do you ever need to drop old data or are you keeping it all around? 

If you have a retention policy with an infinite duration (which is default) then I would consider changing your shard duration to something much much longer than 7 days. See [these docs](https://docs.influxdata.com/influxdb/v1.3/concepts/schema_and_data_layout/#shard-group-duration-overview) for more information. We also have the [Community website](https://community.influxdata.com) where you can get advice about how best to tune InfluxDB for your data use-case.

Let me know if adjusting your `ulimit` fixes the issue and if so I'll close this out.
