### ISSUE TITLE
How to specify the timestamp precision when using UDP

### ISSUE THREAD

**Issue by vgoklani** [influxdata/influxdb#8746]
Hi,

How do I specify the timestamp precision format when inserting via UDP? 

Is there a way to set the default precision to milliseconds (say in the config file)? 

How much of a reduction should I expect in the memory footprint using milliseconds vs nanoseconds?

**Comment by jsternberg** [comment]
You cannot specify the precision for UDP. You can configure the UDP service to have a default precision. So the configuration is on the server and has to be specified for everyone rather than being per-connection.

I'm not sure about the answer to the last question. If you never use anything lower than the precision specified, I guess you would save 9 bytes if you set the precision to seconds or 6 bytes if you set it to milliseconds.

I hope that helps. If you have more questions, https://community.influxdata.com is a much better place to ask. Thanks.

**Comment by vgoklani** [comment]
Thanks for the response. How do I configure the UDP service to have a default precision?

**Comment by jsternberg** [comment]
If you generate a configuration file with `influxd config`, you'll see this:

```
[[udp]]
  enabled = false
  bind-address = ":8089"
  database = "udp"
  retention-policy = ""
  batch-size = 5000
  batch-pending = 10
  read-buffer = 0
  batch-timeout = "1s"
  precision = ""
```

I think you just need to modify the precision there.
