### ISSUE TITLE
Restore top-level `error` key in query response

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#8765]
I'm not sure which PR introduced this behavior, but given an invalid query such as `SELECT bottom(f) FROM m`, we used to (i.e. 1.3.4 and earlier) return the error in JSON as:

```
{"error":"error parsing query: invalid number of arguments for bottom, expected at least 2, got 1"}
```

and now on master the error JSON is:

```
{"results":[{"statement_id":0,"error":"invalid number of arguments for bottom, expected at least 2, got 1"}]}
```

The newer format is more specific, which is more helpful when using multiple statements in a single query, but this change is breaking for any clients that depended on the behavior of `error` being a key at the top level.

Assuming we want to keep the more specific error, my recommendation is to still return the first error as a top-level `error` for 1.4 but deprecate it, so that clients have the entire 1.4 lifecycle to switch to handling errors nested inside `results`. In 1.5 we can fully remove the top-level `error` key.

If we decide not to restore the top-level `error` key, then we need to call it out as a breaking change in the changelog.

**Comment by jsternberg** [comment]
I have a few questions that come to my mind that may greatly influence how we think about this or what we do.

First, if there is an error preparing a query to execute, should it prevent any query from executing? So if I do:

```
CREATE DATABASE db0;
SELECT count(value), host FROM cpu;
```

The above is considered invalid because the second statement is not valid. Should the create database be prevented or should execution only be aborted after the second command is attempted to be run? I think SQL might do the former, but I'm not actually sure if that's the case.

Another question is how much we care about chunked responses. Chunked responses have been a continuous mess throughout the entire time. It would be possible for me to keep the current architecture and propagate the error to the top level, but only for non-chunked responses. Maybe we could do that and list the breaking change in chunked responses and then do better with the result output refactor?

The rationale for why this change was made is I wanted to separate the parser from the logic of the query engine. So the parser handles the grammar alone, but the validations come from attempting to execute the actual query. That way, it would be possible to use the `influxql` package to parse the following: `SELECT mean(value) FROM cpu GROUP BY time(1m)` and then rewrite the AST condition to include the time range without receiving a parsing error. If possible, I would like to keep that since combining the validation with a query to the execution of the query also makes it less likely that the validation will have an error.

**Comment by jsternberg** [comment]
For context, I tried this in Postgres and came out with something similar to the new method:

```
# update users set username = 'foo' where id = 1; select count(*), id from users;
UPDATE 1
ERROR:  column "users.id" must appear in the GROUP BY clause or be used in an aggregate function
```

This one had what could likely be considered a compilation error. You can statically determine that `users.id` was going to be wrong here, but it's syntactically valid SQL. But, the update command still ran.

To be fair, I can do syntactically invalid SQL and Postgres appears to be fine with that. It still runs the first command and then fails on the second one with a syntax error. So we don't necessarily have to emulate everything Postgres does.

I do think it might be good to propagate the error to the top level for non-chunked responses, leave chunked responses in the dust, and finally get to making a new output encoding that doesn't have these same problems and is properly defined.
