### ISSUE TITLE
Which commit version change the engine-store to TSM?

### ISSUE THREAD

**Issue by treedom** [influxdata/influxdb#8772]
### Feature Request
__Proposal : users can choose multi engine-store(maybe TSM, rockDB...) individual
__Current behavior : can not becase not convergence
__Desired behavior:converge unified engine API even user can alter a new engine-store
__Use case:becase the tsdb query sometimes is very individual and need to be optimized

**Comment by jsternberg** [comment]
TSM has been the default since some version before 1.0.

At the moment, we do not support any other storage backend. It would be too difficult to support multiple backends and there wouldn't be much of a point since it would just result in dividing development time between multiple implementations. Before 1.0, the decision was made to create our own backend because the existing backends weren't fast enough for our needs.
