### ISSUE TITLE
[1.3.5] Drops series doesn't works as intended ?

### ISSUE THREAD

**Issue by Orybon** [influxdata/influxdb#8806]
### Bug report

__System info: InfluxDB 1.3.0 & docker

__Steps to reproduce:_

1. Insert telegraf datas
2. Try to drop series of a specific host (that doesn't exist anymore so no new datas) using http api

__Expected behavior: Series should be dropped

__Actual behavior: Series aren't dropped

__Additional info: HTTP respoonse is  - {"results":[{"statement_id":0}]}

When i launch this command : 

```
 curl -X POST 'localhost:8086/query?db=[db-name]' --data-urlencode 'q=DROP SERIES WHERE host = "2008R2SP1"'
```
i got the following result : 
```
{"results":[{"statement_id":0}]}
```

But when i show the series in influx shell i still have the data i tried to delete : 

```
> show series
key
---
win_cpu,host=2008R2SP1,instance=0,objectname=Processor,server_env=infra,server_os_type=windows,server_os_version=2008R2SP1,server_owner=###,server_project=iaas,server_role=templatewin
win_cpu,host=2008R2SP1,instance=1,objectname=Processor,server_env=infra,server_os_type=windows,server_os_version=2008R2SP1,server_owner=###,server_project=iaas,server_role=templatewin
```

Is this a known issue or did i do something wrong ?

**Comment by rbetts** [comment]
First - the quoting here can be a little confusing.  You should quote tag key and tag value as `"host" = '2008R2SP1'`. 

However, there were two issues related to drop and delete resolved in 1.3.1 and 1.3.4:
https://github.com/influxdata/influxdb/issues/8531
https://github.com/influxdata/influxdb/issues/8677

**Comment by Orybon** [comment]
Thank you for your answer.

When i use this command as you suggested : 
curl -X POST 'localhost:8086/query?db=[db_name]' --data-urlencode 'q=DROP SERIES WHERE "host" = '2008R2SP1''

I got this response : 
{"error":"error parsing query: invalid duration"}

I tried to update to 1.3.5, the result is the same.

**Comment by rbetts** [comment]
The invalid duration is annoying - and confused me too.  Here's a working example: https://asciinema.org/a/rC9qZjJiL4hloSNtlScTChSAo

**Comment by jsternberg** [comment]
Just to note, bash treats quotes differently than standard programming languages. As an example:

```bash
$ echo a''b
ab
```

So since you surround your command with a single quote, you are getting two quoted bodies concatenated together. You have `'q=DROP SERIES WHERE "host" = '`, followed by `2008R2SP1`, then followed by `''`. So the final query gets sent to the server without any quotes. Use double quotes and you will be fine.

I'm going to close this issue as it appears to not be an issue in the software and we cannot change how the quotes work at the moment.
