### ISSUE TITLE
Is  there a way to update the value by time? 

### ISSUE THREAD

**Issue by whidbey** [influxdata/influxdb#8831]
Is  there a way to update the value by time? 
I search again and can see some results says I have to delete the data and insert again.

insert  example,a=1,b=3,c=4 value="x=1;y=2;z=3" time=1111111111111111
if I need to change the "a" or "value",
I will have to 
delete example where time=11111111111111111
insert  example,a=2,b=4,c=5value="x=1;y=2;z=3" time=1111111111111111
like this.

is that  high efficiency in realtime updates?

**Comment by e-dard** [comment]
Hi! We try and keep GitHub Issues for  actionable bug reports or feature requests. Please post general questions on the InfluxData community site: https://community.influxdata.com

Thanks.

@whidbey to briefly answer your question though, "realtime updates" implies that you are adding new data over time, as you receive it. Thus each data point would have a different timestamp—you wouldn't be writing the data with the same timestamp.

I would try exploring the Community site because it looks like you're confusing values (fields) with tags. In your examples you're actually inserting two different series—the latter would not replace the former.

**Comment by whidbey** [comment]
thanks.
