### ISSUE TITLE
CREATE DATABASE doesn't create retention policies as documented

### ISSUE THREAD

**Issue by rbetts** [influxdata/influxdb#8839]
Per: https://docs.influxdata.com/influxdb/v1.1/query_language/database_management/#create-a-database-with-create-database  

I expect this command to create a retention policy named `foo`.

```
> drop database db4
> create database "db4" with duration 3h replication 1 shard duration 1h name "foo"
> show retention policies
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
autogen 0s       168h0m0s           1        true
```

See also: https://github.com/influxdata/kapacitor/issues/1565

**Comment by nathanielc** [comment]
In addition I ran into this unexpected behavior.

Kapacitor allows users to create a database with a named retention policy when they are outputing data to InfluxDB from within a task.

Kapacitor's implementation of this feature was to issue a `CREATE DATABASE "dbname" WITH NAME "rpname"` query. If the database doesn't exist its created, if it does exist then nothing happens. But if the database exists but with a different named retention policy an error occurs. I assumed that the query would just create the new retention policy on the existing database because of the idempotent nature of the query.

```
> drop database bar
> create database bar with name autogen
> create database bar with name oneday
ERR: retention policy conflicts with an existing policy
>
```

**Comment by e-dard** [comment]
@nathanielc off the top of my head, I think one reason for this was that when you create a database, the created retention policy becomes the default retention policy. 

If your second command succeeded then for consistent behaviour reasons, `oneday` would have to become the new default RP, ousting `autogen`. 

That doesn't seem to fit well with the concept of creating a database, since subsequent invocations of the create database command result in different retention policies being used.

**Comment by ngraf** [comment]
I could not reproduce the issue.

Maybe you should try explicitly name your database like this?

      > show retention policies on "db4"
