### ISSUE TITLE
SELECT  query neither reports error, nor returns results

### ISSUE THREAD

**Issue by wavicle** [influxdata/influxdb#8841]
### Bug report

__System info:__ 
InfluxDB v1.3.5 (git: HEAD 9d9001036d3585cf21925c13a57881bc6c8dcc7e)
InfluxDB shell version: 1.3.5 (this is what 'influxdb --version' returns)
Ubuntu 17 (Zesty Zapus)

__Steps to reproduce:__
1. Enable the Telegraf plugin (I was using Telegraf when I ran into this issue)
2. On the InfluxDB client (same issue on HTTP API too) say 'USE telegraf'
3. Confirm that a simple query works: SELECT * FROM ntpq
4. The following queries must EITHER work or report errors, but they do neither:

- SELECT host FROM ntpq
- SELECT "host" FROM "ntpq"

__Expected behavior:__ If the query is valid, return results, else return clear and actionable error messages. This might be a configuration issue or a syntax issue, but in any case a clear message must be returned. 

__Actual behavior:__ Query returned nothing (neither error nor results)

*** I tried this using the HTTP API too. Following is an example:

**I tried:**
curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=telegraf" --data-urlencode "q=SELECT \"host\" FROM \"ntpq\" LIMIT 1"

**And I got:**
{
    "results": [
        {
            "statement_id": 0
        }
    ]
}

**Comment by wavicle** [comment]
I revised up the description. I probably experienced issue #7992 (which is closed already). 

The following query does not work because it contains all tags (host is a _tag_):
SELECT host FROM ntpq

However, when a _value_ is selected with a _tag_, the query works:
SELECT delay, host FROM ntpq 

Shouldn't InfluxDB report an error when someone searches for tags alone? This behavior seems misleading to me.

**Comment by jsternberg** [comment]
I've thought about that. We can likely add a warning for these types of queries.

**Comment by ExplodingCabbage** [comment]
@jsternberg Adding a warning makes sense if there's actually a good reason for the current behaviour, but as I note at https://github.com/influxdata/influxdb/issues/5548#issuecomment-362642869, I can't see one. It would be better to just make these queries work, unless there's some profound obstacle to doing that which I'm missing.

**Comment by jsternberg** [comment]
There is a reason, but it's not necessarily intuitive because it doesn't match with how indexing works in a typical SQL database. You can't select tags since tags are metadata about the field and are not actually a data point themselves. So when you write a point with tags, there is no point in the database that can be found. It's purely metadata that is used for efficiently accessing the field which is actual data. Tags are a thing that you can select with a point, but they don't have any meaning outside of that.

As an example, in a typical SQL database you could have a table only columns that are indexed. But, in InfluxDB, you can't do this:

```
insert cpu,host=server01
```

Since there is no field, you can't do this. While tags have some overlap with how indexed fields work in SQL, they are not the same.

I'm sorry for this confusion and if there is a way we can clarify the documentation to make this easier to understand, we are open to improving that to reduce the confusion for people new to the database.

**Comment by dongleiw** [comment]
remain same problem with influxdb (1.7.7).
InfluxDB SHALL report an error when someone searches for tags alone.
