### ISSUE TITLE
Retention policy does not work

### ISSUE THREAD

**Issue by hjdr4** [influxdata/influxdb#8871]
Using InfluxDB 1.3.5 on a single node.

I expect my data is deleted if it's older than the retention policy that is configured:

```
InfluxDB shell version: 1.3.5
> show retention policies on cadvisor;
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
autogen 2h0m0s   1h0m0s             1        true
```

Waiting some hours...

I still have older data:
![image](https://user-images.githubusercontent.com/2270634/30815257-ea9cb4da-a212-11e7-9951-0c6b4cb8a740.png)

Did I miss something ?

**Comment by e-dard** [comment]
@hjdr4 could you provide the InfluxDB server logs?

**Comment by e-dard** [comment]
Thanks. The HTTP stuff might have been useful. I was interested in where the writes were going.

Could you also do the following:

```
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all"

curl -o vars.txt "http://localhost:8086/debug/vars"
```

Obviously you'll need to adjust `localhost` to work with your docker networking stuff.

**Comment by hjdr4** [comment]
[profiles.tar.gz](https://github.com/influxdata/influxdb/files/1337902/profiles.tar.gz)
[vars.txt](https://github.com/influxdata/influxdb/files/1337905/vars.txt)

**Comment by e-dard** [comment]
@hjdr4 according to the `shards.txt` file in that profile, your current shard on `cadvisor` has a duration of 7 days. You have another database called `ride` that has a shard duration of 1 hour.

I think might have got your databases / retention policies muddled up?

**Comment by e-dard** [comment]
Also, it's worth remembering that, as pointed out in the [docs](https://docs.influxdata.com/influxdb/v1.3/query_language/database_management/#retention-policy-management) `DURATION` determines how long InfluxDB will keep the shard data around for, `SHARD DURATION` determines how long a time-span each shard has, before a new shard is created.

**Comment by hjdr4** [comment]
I did'nt muddle anything.
`ride` database does not have data so I cannot tell if retention is working.

About `cadvisor`, I have 
```
show retention policies on cadvisor;
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
autogen 2h0m0s   1h0m0s             1        true
```
It's a copy/paste from the terminal. So if you see other duration somewhere else, you have the problem : it's configured at some place but not at some others, this is inconsistent.
The questions now are what happened and can I reconcile things ?

**Comment by hjdr4** [comment]
Just to be sure, I created the `cadvisor` database with default policy, put data into it, then changed the policy. I expect changing the policy does apply to the first shard even if it was created with another policy.

**Comment by e-dard** [comment]
@hjdr4 I think I understand what's going on.

My assumption is that you altered the retention policy rather than creating it with the 1h duration.

When it was initially created it would have had the default retention policy, which has a `SHARD DURATION` of 7 days, and a retention period (`DURATION`) of infinity.

Altering a retention policy only applies to new shards as they're created. However, your next shard isn't due to be created for another 7 days...

In 7 days time you should find that a new shard is created with your new durations.

**Comment by jwilder** [comment]
@hjdr4 Your current `cadvisor` shards have a duration of 7d.  It's likely this shard was created _before_ you altered the duration.

```
id	database	retention_policy	shard_group	start_time		end_time		expiry_time		owners	
99	cadvisor	autogen			99		2017-09-25T00:00:00Z	2017-10-02T00:00:00Z	2017-10-03T00:00:00Z		
```

Altering the retention policy does not affect existing shards.  It will only affect new shards that are created after the alter statement has been applied.  Since this shard range is 7d and won't rollover until `2017-10-03T00:00:00Z`, it won't be deleted until them.  After that time, your new shards should have a duration of `2h` and will be removed more quickly.

If you don't need that data, you could `drop shard 99` which will cause it to get recreated w/ the new policy.

Alternatively, you could manually delete the data with a `delete from <meas> where time < ...` which would remove the old data, but the shard would still not rollover until the current `end_time`.

**Comment by hjdr4** [comment]
Thank you for pointing out this behaviour.

Doc needs updates in this case. https://docs.influxdata.com/influxdb/v1.3/query_language/database_management/#modify-retention-policies-with-alter-retention-policy does not tell about this behavior and while I get the technical reasons, this is not obvious when using `alter retention policy`.

Also, I live in a Docker world where I can't control the order of deployments.
In my monitoring stack, I have a "helper" container that creates cadvisor database and changes retention policy. But cAdvisor probes may be trying to push to Influxdb before the database even exists.
Unless I can atomicaly create database/set policy, there is always a chance the database get data before the policy is changed. From the doc, `CREATE DATABASE` has no policy option.

Is there anything I can do ?

**Comment by e-dard** [comment]
@hjdr4 [sure](https://docs.influxdata.com/influxdb/v1.3/query_language/database_management/#create-database)

```
CREATE DATABASE "cadvisor" WITH DURATION 1h SHARD DURATION 1h
```

**Comment by hjdr4** [comment]
I'm blind T_T. The doc has everything about `create database`.

So a little warning in the doc about `alter retention policy` could be nice. For the rest, it should be alright for me.

Issue may be closed.

Thank you!

**Comment by koallen** [comment]
Hi, I came across this issue running into the same situation as described by the issue author. Have you guys updated the doc? I didn't see anything in the v1.7 doc mentioning this.
