### ISSUE TITLE
Optimize SELECTs on measurements with a large number of fields

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/influxdb#8898]
### Feature Request

__Proposal:__ Currently, InfluxDB does not handle queries for a large number of fields in a memory efficient way.

__Current behavior:__

In a `SELECT *` query, iterator construction will create all of the cursors for a single series key in one iteration. If there are 1000 fields, the query engine will create 1000 cursors in each iteration. This can quickly exhaust all memory available on an instance.

There also does not currently seem to be a mechanism in the results JSON output to return partial results for a subset of the queried fields.

__Desired behavior:__

The query engine should limit the number of cursors created when there are a large number of selected fields in a query.

__Use case:__

There are a few use cases that legitimately require a large number of fields (mostly scientific). The typical use case is to handle cases where a large number of field keys were created by accident. Since field keys are not able to be deleted easily, any subsequent `SELECT *` query on a database with a high number of fields will use a large number amount of memory.

**Comment by jsternberg** [comment]
I think we will likely have to just have some way to forbid that type of query with wildcards. At least with influxql, I don't think there's any way to change the number of cursors it creates for fields in the manner described because selecting multiple fields is essentially running a join operation between fields within the same series key and measurement.

The join is implicit, but it's there.
