### ISSUE TITLE
'Which' not in dependencies

### ISSUE THREAD

**Issue by JohanDroz** [influxdata/influxdb#8900]
### Bug report

__System info:__ InfluxDB 1.3.6

__Steps to reproduce:__

I was creating a container with influxdb with a fedora 26 base. It doesn't come with many "standard utilities" such as which.
Thus this part of the post install script will fail :
if [[ -f /etc/redhat-release ]]; then
    # RHEL-variant logic
    **which systemctl &>/dev/null**
    if [[ $? -eq 0 ]]; then
	install_systemd
    else
	# Assuming sysv
	install_init
	install_chkconfig
    fi

__Additional info:__ We can resolve this by installing which before installing influx.

**Comment by phemmer** [comment]
Alternatively, since this is obviously a bash script, you could do `command -v systemctl`, since `command` is a bash built-in. Or `systemctl --version`.

And since we're on the subject, the use of `$?` is unnecessary.

```
if command -v systemctl >/dev/null; then
  install_systemd
else
 ...
```

**Comment by CMajeri** [comment]
@phemmer You're right, but the issue is that this is from the postinstall script of the RPM package. This isn't a homebrew install script :)
It assumes `which` is installed, but it might not be in small environments i.e. a container.

Assuming I run a fedora container that comes without `which`, I'd expect a `dnf install` to install the systemd service file (yes, running systemd in a container is a peculiar use-case, but it's a valid one nonetheless :).

I admit that environments without `which` that use systemd are very rare, which might be why this has gone unnoticed for so long.

**Comment by phemmer** [comment]
@CMajeri 
> This isn't a homebrew install script

Actually it is: https://github.com/influxdata/influxdb/blob/master/scripts/post-install.sh#L48

**Comment by CMajeri** [comment]
I meant it's from influx, @JohanDroz didn't write it himself!
