### ISSUE TITLE
Docker Build issue: "stat /root/go/src/github.com/influxdata/influxdb/build.py: no such file or directory"

### ISSUE THREAD

**Issue by valexandersaulys** [influxdata/influxdb#8905]
So when I try to build a container using ``bash build.sh --nightly``, I get the following error once I try to start up the docker container.

```
$ docker run -t influxdb-builder:latest   # I take the name from the output on the above command
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/root/go/src/github.com/influxdata/influxdb/build.py\": stat /root/go/src/github.com/influxdata/influxdb/build.py: no such file or directory".
```

What am I doing wrong? I feel like its something really obvious.

Running Docker 17.09.0-ce-mac32 (19506) on MacOS 10.12.6 at the moment.

**Comment by valexandersaulys** [comment]
I also tried with ``docker build https://github.com/influxdata/influxdb.git`` and got the same error

**Comment by valexandersaulys** [comment]
Is it looking for ``/root/go/src/github.com/influxdata/influxdb/build.py`` on my local computer or inside of the docker container?

**Comment by jsternberg** [comment]
If you are using Mac OS X, are you using docker machine or native docker? If you are using docker machine, the volume mounting that happens inside of `build.sh` might not be working correctly because it mounts the VM's folder (which doesn't exist) rather than your local folder.

It might work if you install the latest version of Docker for Mac OS X which runs natively on your computer instead of in a VM.
