### ISSUE TITLE
InfluxDB sends points to subscriber out of order

### ISSUE THREAD

**Issue by phemmer** [influxdata/influxdb#8932]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Version: 7948bef
OS: Linux & OS-X

__Steps to reproduce:__

1. Create a subscription
2. Write data at a high rate on a single connection

__Expected behavior:__ [What you expected to happen]
Subscriber should receive all points on a single connection in the same order they were sent to InfluxDB

__Actual behavior:__ [What actually happened]
Subscriber receives points on multiple connections in random order.

__Additional info:__ [Include gist of relevant config, logs, etc.]
Reproduction script:
```
#!/usr/bin/env bash
exec 3>/dev/tcp/127.0.0.1/8086

for (( i=0; i<10; i++ )); do
	printf 'POST /write?db=test HTTP/1.1
Host: localhost:8086
Content-Length: 11

test v=%04d' "$i" >&3
done
sleep 1
```

To create a simple subscriber you can use kapacitor with the following script:
```
stream|from()|log()
```

Example output:

```
ts=2017-10-05T22:22:09.862-04:00 lvl=info msg=point service=kapacitor task_master=main task=test node=log2 prefix= name=test db=test rp=autogen group=   field_v=0 time=2017-10-06T02:22:09.862056903Z
ts=2017-10-05T22:22:09.864-04:00 lvl=info msg=point service=kapacitor task_master=main task=test node=log2 prefix= name=test db=test rp=autogen group=   field_v=1 time=2017-10-06T02:22:09.863365282Z
ts=2017-10-05T22:22:09.864-04:00 lvl=info msg=point service=kapacitor task_master=main task=test node=log2 prefix= name=test db=test rp=autogen group=   field_v=2 time=2017-10-06T02:22:09.863850344Z
ts=2017-10-05T22:22:09.865-04:00 lvl=info msg=point service=kapacitor task_master=main task=test node=log2 prefix= name=test db=test rp=autogen group=   field_v=3 time=2017-10-06T02:22:09.864284198Z
ts=2017-10-05T22:22:09.867-04:00 lvl=info msg=point service=kapacitor task_master=main task=test node=log2 prefix= name=test db=test rp=autogen group=   field_v=5 time=2017-10-06T02:22:09.865453762Z
ts=2017-10-05T22:22:09.867-04:00 lvl=info msg=point service=kapacitor task_master=main task=test node=log2 prefix= name=test db=test rp=autogen group=   field_v=4 time=2017-10-06T02:22:09.864872075Z
ts=2017-10-05T22:22:09.868-04:00 lvl=info msg=point service=kapacitor task_master=main task=test node=log2 prefix= name=test db=test rp=autogen group=   field_v=7 time=2017-10-06T02:22:09.866741838Z
ts=2017-10-05T22:22:09.869-04:00 lvl=info msg=point service=kapacitor task_master=main task=test node=log2 prefix= name=test db=test rp=autogen group=   field_v=6 time=2017-10-06T02:22:09.865846108Z
ts=2017-10-05T22:22:09.870-04:00 lvl=info msg=point service=kapacitor task_master=main task=test node=log2 prefix= name=test db=test rp=autogen group=   field_v=9 time=2017-10-06T02:22:09.8678495Z
ts=2017-10-05T22:22:09.870-04:00 lvl=info msg=point service=kapacitor task_master=main task=test node=log2 prefix= name=test db=test rp=autogen group=   field_v=8 time=2017-10-06T02:22:09.867383893Z
```

If you do a packet capture, you can see that InfluxDB is opening multiple connections to kapacitor, and is sending the points over them all. This leads to race conditions in the processing of those requests since the points are no longer sequential.

**Comment by jsternberg** [comment]
Is the example script you have given meant to be a pipelined HTTP request? It looks like it is writing one point per batch, but writing them using the same TCP connection. Is that correct?

**Comment by phemmer** [comment]
That is correct.
This is the minimum reproducible example. Though in my specific case it's not one point, but thousands of points. My client buffers up to X kb of data, or up to the completion 1 work unit (which is a bunch of points all generated at the same time), and then dumps the buffer to InfluxDB. So when I generate enough points to fill the buffer and send a second batch, this second batch gets sent to the subscriber before the first one.

**Comment by jsternberg** [comment]
Are you using TCP or UDP for the subscriber to send points?

**Comment by phemmer** [comment]
TCP. Exactly the same as this test case. Multiple requests on a single connection.

**Comment by phemmer** [comment]
TCP.
*(deleted previous comment, missed the "subscriber" portion of the question)*

**Comment by jsternberg** [comment]
I'm going to make a guess. I haven't tried it out, but I can see a way where this would happen. InfluxDB seems to keep the writes in order if you are using pipelining to write them, but then it might use multiple connections if the previous http connection hasn't been finished yet for some reason. So it would be pretty easy for InfluxDB to open multiple connections for a single connection and then write them to Kapacitor who would have no idea what the ordering is supposed to be.

The Go client is supposed to take over this, but the default HTTP client in Go only appears to use a persistent connection if it is available.

We might need to modify how the InfluxDB client writes these requests to keep requests in the same batch with each other. I'm not yet sure how we would do that though.

**Comment by jwilder** [comment]
@phemmer Try setting:

```
[subscriber]
write-concurrency = 1
```

If you have a high write rate, it's possible that you can have points dropped because the subscription write path to kapacitor is not able to keep up.

**Comment by rbetts** [comment]
@phemmer was the setting sufficient? In thinking about this more internally, we have some preference for leaving the behavior as is. In general, asserting that the delivery order from influxdb -> kapacitor should be identical to the delivery order from client -> database  create a tighter coupling than we want at the ingest tier. Clustered InfluxDB would not be able to meet the same ordering promise (from the client's perspective) in many cases regardless.

We have created a docs issue to explain the current behavior more clearly:
https://github.com/influxdata/docs.influxdata.com/issues/1319

**Comment by phemmer** [comment]
Setting `write-concurrency = 1` is not something I want to do as I do send multiple independent streams of data from different sources to influxdb that do not need to be multiplexed into a single subscriber connection (potentially causing a bottleneck).

I don't use influxdb clustering, so I'm not sure how it works, but even assuming there's some sort of layer-7 load balancing going on before the InfluxDB nodes, it should be simple enough to create persistence so that the same TCP connection always goes to the same InfluxDB node.

**Comment by jsternberg** [comment]
@phemmer what if we made it possible for a user-provided id to run sequentially?

I think it would be possible to ensure that requests made to the same node (which it would in pipelining) would run sequentially, but the problem is that many http client libraries automatically recycle and pipeline connections if the server does not specify `Connection: close`. So you could have two separate requests that aren't intentionally being pipelined shared with the entire application. I do not think we want to make those types of subscriptions move more slowly because we accidentally believe them to be related to each other.

But, if the user provided a key, we could provide a named lock and ensure that the write concurrency was one for that specific lock. Maybe we could automatically generate one on request and the user could provide the id for each request after the initial request.

This is just a random idea and I am not sure how feasible it would be with clustering. For example, requests made to different nodes that use the lock would not be able to be locked themselves, but maybe just writing that as a caveat the user has to understand is enough?

**Comment by phemmer** [comment]
> I do not think we want to make those types of subscriptions move more slowly because we accidentally believe them to be related to each other.

That's a good point.

> But, if the user provided a key, we could provide a named lock and ensure that the write concurrency was one for that specific lock.

That seems feasible.
Something that might be simpler: What about instead of a lock, a channel index? I don't know how the InfluxDB code works in regards to subscribers, but I imagine each subscriber gets its own channel which the points are sent across. What about when an index key is provided that a new subscriber is created with an automatic `write-concurrency = 1`, and then all points with the given index key are sent to that subscriber's chan.

However this does seem like it's getting fairly deep into edge case territory.

**Comment by jwilder** [comment]
Some background on this.  @phemmer you actually logged an issue about data loss under high ingest rate around the time of 1.0: https://github.com/influxdata/influxdb/issues/7330.  At that time, we processed writes sequentially to each subscriber.  The issue was that if the injest rate was too high, we'd have to drop points if the subscriber was not able to keep up to prevent a big backlog in the server and the channel filling up.  Essentially, there are N writers into a channel, but only 1 reader from that channel.  The "fix" for that issue at the time was to add concurrent readers and the `write-concurrency` setting: https://github.com/influxdata/influxdb/pull/7407.  This does introduce the possibility for points to be sent out of order.

On the reading side, we don't currently coalesce writes to subscribers.  If you have lots of small batches, we still end up sending those as small batches whereas we could group them up into larger batches and send them with fewer requests.  This would improve throughput to some extent with a single reader.

IIRC, this push model was originally designed with UDP as the only transport.  We added HTTP in a little after (#6655).  Dropping points was the intended behavior since UDP isn't reliable.  Given that, there are several parts of the current code path that we allowed for dropping points.   Honestly, I think we're trying to make subscriptions do things that they were not originally designed and if we want in-order, at-least-once delivery semantics that can keep up with DBs injest rate, we need to consider a different design that can support that.
