### ISSUE TITLE
[Question] Does Influx support rate of decay/expected end date type forumulas?

### ISSUE THREAD

**Issue by evanrich** [influxdata/influxdb#8936]
Perhaps stackoverflow would be better for this question, so if it is, feel free to close this, but I wasn't able to find anything on google to answer my question.  

I'm wondering if Influx supports a rate of decay (or predicted end date) type metric.   Basically, say I have the following time series data for disk free space)

9/1/17   100MB
9/2/17   98 MB
9/3/17   95 MB
...etc

Is there a way that I can have influx spit out an expected end date when that number will hit 0?     I'm trying to figure out how to graph when available storage on a NAS will hit 0, but I'm not seeing a function to plot this, and I'm not entirely sure of what functions I would need in influx to support this.   Basically, I'm looking for a predictive interpolation given existing data points of when a value will reach zero.   Is this supported?

**Comment by e-dard** [comment]
Hi @evanrich we don't have a feature to do this. Normally we close questions, and ask that they be sent to the [Community Site](https://community.influxdata.com), but in this case I'll leave it open as a feature request. Thanks again.

**Comment by nathanielc** [comment]
@evanrich A slight variant of what you want is possible via the [Holt Winters](https://docs.influxdata.com/influxdb/v1.3/query_language/functions/#holt-winters) function.

You can use the holt-winters function to predict out a fixed length of time, say one week. Then if the prediction cross zero in that week you could take action. So instead of asking when does this trend cross zero, you are asking does this trend cross zero within the next week. You can increase that length of time to as far as you feel your prediction can be accurate.

Since you are probably wanting to take action based on whether its predicted to cross zero or not you may want to consider using Kapacitor. [Here](https://github.com/influxdata/kapacitor/blob/master/CHANGELOG.md#holt-winters-forecasting) is a simple example. The example is predicting to 100% full, instead of 0% empty but that is essentially the same thing and can easily be modified.
