### ISSUE TITLE
Allow configurable times for compactions

### ISSUE THREAD

**Issue by alexdaviesjump** [influxdata/influxdb#8973]
### Feature Request

__Proposal:__ 
During compactions for us, the RSS of our process doubles (from ~60G to ~120G). This has been consistent behavior through Influx versions and is expected. We have accounted for this, but its important to make sure that there are no really intensive queries running at the same time to avoid overloading the box and the OOM killer getting involved.

__Current behavior:__ 
Compaction occur every X hours (we have x=24). I think right now its a function of the start time of the process, i.e. fairly arbitrary.

__Desired behavior:__ 
Ensure compactions run at a certain time, with minimal risk of other action taking RAM on the box

The ideal thing would be a config option that specifies the times (in the timezone locally on the box) can run. So you could say compaction_start=03:00 or perhaps compaction_start=02:00,14:00 if your shards are set to 12h. Handling the case that more compactions are required than we have times for would need to be handled in some sane way. 

__Use case:__ 
The OOM killer firing on a production box is bad: restart time is fairly slow. 

Briefly discussed with @e-dard as something worth considering.

**Comment by jwilder** [comment]
Compactions run continuously to keep the shard in a state that queries are performant and don't fill up the disk.  

> Compaction occur every X hours (we have x=24). I think right now its a function of the start time of the process, i.e. fairly arbitrary.

This isn't quite correct.  They run all the time as data is written to the shard and various criteria for each level is met.  There are two settings that can be specified that control when we determine if a shard is cold or not.

```
cache-snapshot-write-cold-duration = "10m0s"
````

This setting controls when we will snapshot everything in the cache/WAL to a TSM file if the cache is still below the `cache-snapshot-memory-size` threshold.  (i.e. there is 3MB of lingering data in the cache, and writes have moved to a new shard).

```
compact-full-write-cold-duration = "4h0m0s"
```

This settings controls how long we'll wait before we run one last full compaction on the shard to get it into a fully optimized state for queries and long term storage.  Full and level compactions _do_ run while the shard is hot on subsets of TSM files in the shard.  This last one just compacts everything one last time if needed.

Master/1.4 currently has a lot of optimizations to reduce memory usage during compactions.  That last compaction in prior releases was expensive at times.  If you are seeing RSS double w/ current nightlies, that would not be expected and I'd like to follow up to see what is the root cause.

**Comment by alexdaviesjump** [comment]
Agreed, and its far from proven that the big jump in RSS we are seeing is a compaction. 

We shall do some more digging before assuming that is the problem (and if it is, the solution might be to figure out why so much memory is being used!)

**Comment by alexdaviesjump** [comment]
I think that what we saw was not a compaction, so closing this. The 1.4 branch does seem to handle compactions very well.
