### ISSUE TITLE
Please do not delete old versions from package repositories

### ISSUE THREAD

**Issue by davidgubler** [influxdata/influxdb#9229]
### Bug report

__System info:__ Ubuntu 16.04

__Steps to reproduce:__

Please do not remove old package versions from the repositories. Currently, both the Debian and Ubuntu repositories only contain the latest version:
https://repos.influxdata.com/ubuntu/pool/stable/i/influxdb/
https://repos.influxdata.com/debian/pool/stable/i/influxdb/

This is a serious pain for system administrators because we may need to revert to an older version after an upgrade, if the new version causes issues.

(Yes I am aware that there are ways to recover previously installed package files on Debian/Ubuntu systems, but that is not a proper solution and doesn't always work)

**Comment by jsternberg** [comment]
This is common with APT repositories. If you want to downgrade to an older version, I would recommend saving the old deb file (usually they will be automatically kept in `/var/cache/apt/archives`) and using that debian file. The actual debian files themselves are kept there.

Apt repositories do not usually keep older versions. They usually just keep the latest version that is intended for download. Here's an elasticsearch issue describing the same problem: https://github.com/elastic/elasticsearch/issues/21943

And here is ansible with a similar problem: https://github.com/ansible/ansible/issues/23143

I'll let the packaging team look at this though. if you know of any solutions to this problem, feel free to comment in this issue.

**Comment by ainguyen** [comment]
I guess we can modify the instruction in download page a little to get old version:
```
wget https://dl.influxdata.com/influxdb/releases/influxdb_1.4.2_amd64.deb
sudo dpkg -i influxdb_1.4.2_amd64.deb
```
You can change the name of package in the url. I tried:
`wget https://dl.influxdata.com/influxdb/releases/influxdb_1.2.4_amd64.deb`
and it worked

**Comment by jsternberg** [comment]
It looks like the download page shows the method using `dpkg` rather than the APT repository so I'm going to close this issue. APT doesn't really allow pinning to specific versions and when they say pinning, they're talking about pinning which repository you are downloading the package from rather than just choosing the latest of the available repositories.

The influxdb package doesn't have any package dependencies so the automatic dependency resolution that apt adds doesn't help to install the influxdb package anyway. I recommend installing the debian package directly with dpkg if you need to use a specific version.
