### ISSUE TITLE
Spaces and backslash characters problem in BASH variable with HTTP API

### ISSUE THREAD

**Issue by sanchomuzax** [influxdata/influxdb#9236]
X-Influxdb-Version: 1.3.7

I'm using the HTTP API for writing the tehe for my InfluxDB. I would like to use spaces special characters for tag keys. I tried to use the `\` backslash character. It's working if I create a direct writing. But I would like to add the value of the keys with a variable in the BASH script.

Example, if the tag value is "write space":

~~~
#!/bin/sh

# this line is working
curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'stringtest,tag=write\ space value='1''

# this line wrong, why? or how will be ready?
mytag="write\ space"
curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'stringtest,tag='$mytag' value='1''
~~~

**Comment by jsternberg** [comment]
I'm not sure your bash is correct. This works for me.

```bash
$ mytag="write\ space"
$ curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary "stringtest,tag=$mytag value=1"
```

Notice how I use double quotes in the curl command. This means that bash handles the substitutions. Your current one is a bit weird because of how the quotes interface with bash and how bash concatenates strings.

It ends up doing something like this:

```
'stringtest,tag=' + $mytag + ' value=' + 1 + ''
```

This gives you `stringtest,tag=write\\` as the first argument and `space value=1` as a second argument because of how bash argument parsing works. Notice how your reference to `$mytag` is _not_ in any kind of quotes, so the space gets parsed into multiple arguments rather than staying as a single argument. The quotes prevent this from happening. This is the same reason why you can't do something like this safely in bash:

```
GIT_DIR=$(git rev-parse --show-toplevel)
if [ $GIT_DIR = "/path/to/dir" ]; then
    ...
fi
```

Bash will mess up if `GIT_DIR` resolves to an empty string and will try to do this:

```
if [ = "/path/to/dir" ]; then
    ...
fi
```

Instead of what you would expect which is this:

```
if [ "" = "/path/to/dir" ]; then
   ...
fi
```

I hope that makes sense. Since this is an issue with bash usage, I'm going to close this issue since it does not directly relate to InfluxDB. If you need more help, you can ask the question on our [community](https://community.influxdata.com) or if you need more bash specific help without InfluxDB, stackoverflow has generally been helpful for me.

**Comment by sanchomuzax** [comment]
Thank you for your help! The use of quotation marks is the good solution.
