### ISSUE TITLE
Don't record  internal statistics default

### ISSUE THREAD

**Issue by oiooj** [influxdata/influxdb#9238]
Can we don't record  internal statistics default, set `store-enabled = false` default.

```
[monitor]
  # Whether to record statistics internally.
  # store-enabled = false

  # The destination database for recorded statistics
  # store-database = "_internal"

  # The interval at which to record statistics
  # store-interval = "10s"

```

Also need to fix code, The statistics makes low performance.

![image](https://user-images.githubusercontent.com/2253095/34089296-fef06b98-e3e9-11e7-9665-b4def73b3bce.png)

![image](https://user-images.githubusercontent.com/2253095/34089320-2cf60bc4-e3ea-11e7-812d-c6e926cc4fb7.png)

![image](https://user-images.githubusercontent.com/2253095/34089338-43e1b2c0-e3ea-11e7-8e62-fbedf95fe0fa.png)

If approved, I'll pull a request to fix this.

**Comment by jsternberg** [comment]
This is unlikely to happen. The default already has it on and it would likely be a breaking change to modify that. Further, it's usually beneficial to have the monitor enabled by default if we get any questions about performance. While it may sacrifice some performance, it does make support easier and that's usually a good tradeoff.

On the other hand, if you can look at the monitor code and find areas to improve the performance or maybe add an optional area to batch more points rather than write them to the database immediately, that would certainly be a non breaking change improvement and very much appreciated.

**Comment by jsternberg** [comment]
This default is not going to change. Thank you for filing the issue though and the option to disable the internal storage always exists if it helps your system be more performant.
