### ISSUE TITLE
Need to be able to disconnect dead clients

### ISSUE THREAD

**Issue by phemmer** [influxdata/influxdb#9248]
### Feature Request

__Proposal:__
InfluxDB needs to have a way to detect and disconnect dead (or possibly even idle) clients.

__Current behavior:__
If a client has an open connection to InfluxDB, but that client ungracefully disconnects (e.g. crash or network disconnection), the socket on influxDB's side remains open forever. Eventually the server can accumulate hundreds or thousands of these sockets, exhausting available file descriptors.

__Desired behavior:__
InfluxDB either needs to support configuration of [TCP KeepAlive](https://golang.org/pkg/net/#TCPConn.SetKeepAlive), and/or the server needs a simple configuration parameter for a request timeout where it closes the connection after idle for X seconds).

According to the documentation, version 0.8 had a `read-timeout` parameter that satisfied this requirement: https://docs.influxdata.com/influxdb/v0.8/advanced_topics/configuration_options/

__Use case:__
If a client has an open connection to InfluxDB, but that client ungracefully disconnects (e.g. crash or network disconnection), the socket on influxDB's side remains open forever. Eventually the server can accumulate hundreds or thousands of these sockets, exhausting available file descriptors.

**Comment by jsternberg** [comment]
I think there might be another issue somewhere where this issue was requested (maybe by you?) at some point, but the request here is that we need a `read-timeout` somewhere and (possibly in addition as a separate request) we need a way to manage existing connected clients for administrators to manage connections.

**Comment by jimis** [comment]
Reproduced with influxdb-1.7.8 on Ubuntu. Yes, this can create an ever-increasing number of TCP connections in ESTABLISHED state, since `influxd` will never know they are dead. The solution is indeed to turn on `SO_KEEPALIVE` after `accept()`.

Can you reopen this issue?

**Comment by jimis** [comment]
This has been fixed in InfluxDB-1.8.0, all incoming connections have KEEPALIVE timers turned on, and they expire without piling up. It has been verified in production environment with many new inactive connections per second.

I believe this is because 1.8.0 has been compiled with Go 1.13 which adds support for configuring TCP KEEPALIVE and defaults to having it on. From the [Go 1.13 release notes](https://golang.org/doc/go1.13):
> The new field ListenConfig.KeepAlive specifies the keep-alive period for network connections accepted by the listener. If this field is 0 (the default) TCP keep-alives will be enabled.

Thank you, you can close this ticket (lets all pretend that it was open in the first place...)

**Comment by prashanthjbabu** [comment]
@jimis Great RCA! thanks a lot for this ! it really helped.
