### ISSUE TITLE
Unix domain socket doesn't have the right file permission

### ISSUE THREAD

**Issue by Mailerm** [influxdata/influxdb#9266]
## Bug report
**System info:** Ubuntu 16.04

Steps to reproduce:

1. install influxdb by 
````sh
curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/lsb-release
echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
````
2. edit `/etc/influxdb/influxdb.conf` enable http service over unix domain socket

3. restart influxdb

influxdb default run with user `influxdb` and create unix domain socket `influxdb.sock` without write permission, finally it will cause nginx could connect this socket!

so i have 2 chooses:
1. custom influxdb to run with root or my nginx user group.
2. or execute `chmod a+x influxdb.sock` evenytime influxdb restart.

**Comment by jsternberg** [comment]
Can you show me the output of `ls -l /var/run/influxdb.sock`?

**Comment by jsternberg** [comment]
Ok, I think I misunderstood this question. The problem is that the unix socket created by InfluxDB is 0755 and that doesn't allow writes or queries from those outside of the `influxdb` group when attempting to use nginx as a query.

I'm going to switch this to a feature request since this isn't a bug in the packaging or the software as I thought it was. But, it might be nice to be able to call the equivalent of `chmod` and `chown` on the socket that is created automatically which could probably be added as an extra configuration option.
