### ISSUE TITLE
Cannot add anymore hosts to influxdb

### ISSUE THREAD

**Issue by gallart** [influxdata/influxdb#9292]
### Bug report

__System info:__

Gentoo Linux / InfluxDB 1.4.2 / Telegraf 1.5

__Steps to reproduce:__

1. Add new telegraf host

__Expected behavior:__ 

Host should push data into influxdb. And host should be visible in Influx DB.

__Actual behavior:__

New hosts are getting this answer from influxdb :

```
HTTP/1.1 204 No Content
```

And host is not present in InfluxDB database.

__Additional info:__ 

Our Influxdb has been working for months like a charm. This issue is only concerning new "hosts" we are starting `telegraf` on. Older hosts are still receiving data (but still returning 204 anyway).

We have about 600 working hosts registered.

Vars.txt : 
[vars.txt](https://github.com/influxdata/influxdb/files/1613384/vars.txt)

**Comment by jsternberg** [comment]
Hi, this looks like a support issue with Telegraf rather than a bug in the database itself. Please post the question to our [community](https://community.influxdata.com) forum as you will likely get more responsive help there. If over there they determine that this is a bug within InfluxDB or Telegraf that is causing the problem, you can then file an issue and we'll have more information to work off of to come to a resolution.

Thanks.
