### ISSUE TITLE
SHOW SERIES extremely slow and unacceptable on bigger DB

### ISSUE THREAD

**Issue by szibis** [influxdata/influxdb#9294]
Same behavior on 1.3.8 and 1.4.3pre0

On 1.4 we have simple info about DB cardinality:
```
cardinality estimation
----------------------
1856641
```
taking show series on this DB
```
show series  limit 1 offset 0 
```
shows 1 series as we expect but after almost 30 seconds !!!

```
real	0m29.573s
user	0m0.009s
sys	    0m0.007s
```
for
```
> show series  limit 100 offset 10
```
output in:
```
real	0m31.508s
user	0m0.000s
sys	    0m0.010s
```
for
```
show series limit 10000 offset 10
```
in time:
```
real	0m35.080s
user	0m0.148s
sys	    0m0.063s
```
Always more than 30 second

We have other DB with more tags and it takes even 7 minutes to get 1 series from a schema which is totally inefficient.

It is no different how big limit we take, it is always building whole series list on the backend?

Is there any way to improve metadata queries in influxdb, cache, some configuration improvements?

**Comment by szibis** [comment]
What is really strange is that I just remove second big DB in another setup.

Two DB first with 270k cardinality (stays) and second with 800k cardinality (removed).

Now SHOW SERIES times on DB that left drops into 1 minute from 7.5 minutes.

Is this some cache/memory splitting problem between multiple DB's on same influx setup?

**Comment by benbjohnson** [comment]
@szibis We don't maintain a sorted list of series keys in the system so when a `SHOW SERIES` is executed, the server has to sort all the keys before returning a result. Unfortunately, `LIMIT` and `OFFSET` require that sorted list too so the system has to sort the entire 1.8M keys before returning a result — even if the result is only one key.

We don't maintain the sorted list in-memory because it incurs extra cost during inserts and typically `SHOW SERIES` is usually executed infrequently.

What's your use case for `SHOW SERIES`?

**Comment by ivanich** [comment]
@benbjohnson Our case is influxgraph for graphite compatibility, it heavily uses show series in order to build index, so when number of series in influxdb ~1M query executes ~2-5 minutes which is longer than default influxgraph timeout og 120 sec.

**Comment by Kiddinglife** [comment]
select * from some_db limit 1 crashes my dbserver.....
I am wondering if the guys making influxdb knows the meanings of limit in sql.
I saw this PR 4 years ago where someone else had already come up with the same issue. But it has not been solved out so far! really dispointed!!!  
[PR](https://github.com/influxdata/influxdb/issues/364)

I have decided to move to mysql....
