### ISSUE TITLE
enable operators within functions

### ISSUE THREAD

**Issue by willguxy** [influxdata/influxdb#9357]
### Feature Request
__Version:__ 1.4.2

__Proposal:__ enable operators within functions

__Current behavior:__ math calculations within functions are not working

__Desired behavior:__ make the calculations within functions work as they used to be

__Use case:__ For example, if I want to get something like `moving_average(1 / "x", 24)`, it wouldn't be feasible without allowing `1 / "x"` within this function call. If I swap the order of operation such as `1 / moving_average("x", 24)`, the result would not be the same

**Comment by jsternberg** [comment]
You can use subqueries for this. Unfortunately, since there is a workaround and adding this functionality directly would be quite involved with influxql, we aren't currently planning on native support for this in the future. IFQL will have better support for this type of functionality so you don't have to use awkward workarounds like a subquery for something that should be simple.

`SELECT moving_average(reciprocal, 24) from (SELECT 1 / x FROM blahblah)`
