### ISSUE TITLE
Influx storage directory needs permissions changes

### ISSUE THREAD

**Issue by ping2nomula** [influxdata/influxdb#9359]
Hi there,

We have a requirement that is, store the influx data to file store. We have got the file store with different permissions other than influxdb:influxdb.

I have changed influxdb script in /etc/init.d folder to add required USER and GROUP values. But influx is failing to start if i change folder permissions as per User and group values.

I am using Ubuntu 16. 

Error details:
Jan 23 15:49:13 qvmrs-dev systemd[1]: influxdb.service: Main process exited, code=exited, status=1/FAILURE
Jan 23 15:49:13 qvmrs-dev systemd[1]: influxdb.service: Unit entered failed state.
Jan 23 15:49:13 qvmrs-dev systemd[1]: influxdb.service: Failed with result 'exit-code'.
Jan 23 15:49:13 qvmrs-dev systemd[1]: influxdb.service: Service hold-off time over, scheduling restart.
Jan 23 15:49:13 qvmrs-dev systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
Jan 23 15:49:13 qvmrs-dev systemd[1]: influxdb.service: Start request repeated too quickly.
Jan 23 15:49:13 qvmrs-dev systemd[1]: Failed to start InfluxDB is an open-source, distributed, time series database.

Request your help.

Thanks
anka

**Comment by jsternberg** [comment]
Which file are you modifying? If you are modifying `/etc/init.d/influxdb`, that file is likely never being called. The `systemd` file location is at `/lib/systemd/system/influxdb.service` and that gets installed by default on Ubuntu 16 because that system uses systemd.

To my knowledge, the `/etc/init.d/influxdb` file shouldn't even exist since I didn't think it got installed, but I may be reading the package incorrectly. Can you look and see if there is an `influxdb.service` file anywhere on your system and try modifying the user and group in there instead if you haven't already?

**Comment by russorat** [comment]
closing due to lack of response.
