### ISSUE TITLE
Error parsing query...with multiple SELECT statements

### ISSUE THREAD

**Issue by vishket** [influxdata/influxdb#9363]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

Latest InfluxDB - InfluxDB shell version: 1.2.2
OS: centos-release-7-4.1708.el7.centos.x86_64
Grafana frontend:  Grafana v4.6.2

I have a measurement called "ProcessTimes" (time taken by different processes to complete) and I want to extract the % of records that are above a pre defined limit/threshold value. I use a query like...

SELECT COUNT(value) * 100 / (SELECT COUNT(*) FROM ProcessTimes)
FROM ProcessTimes
WHERE value > 300

...and want to send the returned value to the Kibana single stat dashboard. But I get an error stating:
message:"error parsing query: found SELECT, expected identifier, string, number, bool at line 1, char 30"

Example: 
ProcessTime(secs): 200, 120, 150, 500
SELECT COUNT(value) * 100 / (SELECT COUNT(*) FROM ProcessTime)
FROM ProcessTime
WHERE value > 300;

...should return 75 

__Actual behavior:__ [What actually happened]
message:"error parsing query: found SELECT, expected identifier, string, number, bool at line 1, char 30"

__Steps to reproduce:__

1. Install influxDB on CentOS
2. Install Grafana. Add & configure InfluxDB datasource. Validate if connection is ok.
3. Create a new DB and measurement with integer value records
4. Query data using above provided query

__Expected behavior:

I want it to return the percentage of records whose value is above a certain threshold

__Actual behavior:__ [What actually happened]

message:"error parsing query: found SELECT, expected identifier, string, number, bool at line 1, char 30"

__Additional info:__ [Include gist of relevant config, logs, etc.]

If I replace my second SELECT statement with an integer, it works fine. 
SELECT COUNT(value) * 100 / (4)
FROM ProcessTime
WHERE value > 300;

Returns 75

Doesn't seem to be liking the second SELECT statement

**Comment by jsternberg** [comment]
You can't use select in that way. Select can only be used in the `FROM` section of a query and cannot be used as an expression itself.

Unfortunately, I do not think the query you are trying to do is possible under the existing system. I tried another way that I thought might work, but it doesn't. This would require more advanced join functionality than we currently have.

I think Kapacitor might have the capability of doing this kind of join functionality though and Kapacitor would be able to process the points and write it back to the database (which you could then query). I'm going to close this issue because we do not currently have plans to add this functionality to influxql, but I would suggest taking the question to our [community](https://community.influxdata.com) website and seeing if they can help you get that set up.
