### ISSUE TITLE
start_time on new shard group is signficantly in the past.

### ISSUE THREAD

**Issue by jasonsokolowski** [influxdata/influxdb#9367]
When creating a new retention policy, on a new database, inserting data. The new shard created has a start time significantly in the past. Is this the desired behavior? If I want my shard duration to be 10 years, it's now reduced to effectively 6 years with new data starting today.

This database will be storing stock pricing / volume information.

__System info:__ InfluxDB 1.4.2 - Debian 9

__Steps to reproduce:__

1. CREATE DATABASE test;
2. CREATE RETENTION POLICY "inf_10y" ON "test" DURATION INF REPLICATION 1 SHARD DURATION 520w DEFAULT;

__Expected behavior:__ 

```
id database retention_policy shard_group start_time           end_time             expiry_time          owners
-- -------- ---------------- ----------- ----------           --------             -----------          ------
44 test  inf_10y          44          2018-02-28T00:00:00Z 2028-02-05T00:00:00Z 2028-02-05T00:00:00Z 
```
__Actual behavior:__ 

start_time is four years in the past, wasting full shard duration.

```
id database retention_policy shard_group start_time           end_time             expiry_time          owners
-- -------- ---------------- ----------- ----------           --------             -----------          ------
44 test  inf_10y          44          2014-02-17T00:00:00Z 2024-02-05T00:00:00Z 2024-02-05T00:00:00Z 

```

**Comment by jsternberg** [comment]
Yes, this is expected behavior. Time durations are on regular intervals starting from the Go zero value (which is January 1, 1900) which is at zero. This also has the side effect that pretty much every shard group ends up starting on a Monday because January 1, 1900 is a Monday. Although you will find some parts of the system such as the query engine treat January 1, 1970 as the epoch since they use the Unix timestamp instead.

As an example: https://play.golang.org/p/AXy1jVyJmsE

Sorry if this behavior is confusing.

**Comment by jasonsokolowski** [comment]
Interesting, thanks for the info. So for stock data, I should just set it to a 100 years or something? Is there any side effect to having essentially an infinite shard duration?

**Comment by jsternberg** [comment]
I'm actually not sure. One problem with setting a large shard duration is that dropping old shards or moving old data to some cold storage location (which is a feature we are looking to add in the future) becomes impossible since the shard will always remain hot. It also means data can't be sharded, but that really only matters in the enterprise version anyway which has clustering. Unless you are taking advantage of shards, there isn't much downside to just ignoring that they exist and setting the duration to something very large.

It might be better to ask on our [community](https://community.influxdata.com) forum though. Our support people spend more time there answering community questions like this one and they have much more experience with managing support clusters. They might know something about this that I am unfamiliar with.
