### ISSUE TITLE
Feature Request: Local TimeZone support in shell queries

### ISSUE THREAD

**Issue by wrossmorrow** [influxdata/influxdb#9479]
If it isn't already included, it would be nice to include local timezone support in time-filtered queries. For example, a simple "`local_now()`" function that returns the local time (for me, `now()-8h`). Shouldn't a wrapper around `now()` be fairly easy? Or even `now("America/Los_Angeles")`? Let me know if I'm missing something, I'm new to `influxdb`. (I've seen the advice to write everything to UTC.)

**Comment by jsternberg** [comment]
An issue with this is that you would need to specify to the server which time zone your query is in. The server has no way of knowing the time zone without that. On the other hand, adding the ability to specify the local time zone in an HTTP request in a separate place other than the query may make it easier for editing queries in something like Grafana/Chronograf. Grafana/Chronograf could be set to use a global time zone and then something like `tz(local)` could be used (or something else).

Also, `now()` will still return the current time so adding `local_now()` wouldn't really do anything. It only matters if you have something like `today()` where time zones would matter since it involves truncating the time to some kind of offset.

**Comment by dandv** [comment]
Please add a [CLI argument](https://docs.influxdata.com/influxdb/v1.6/tools/shell/#influx-arguments) to set the timezone in which the time is reported, similar to the `precision` argument. Invocation could be something like,

    influx -precision rfc3339 -tz America/Chicago

**Comment by dandv** [comment]
Please reconsider marking this issue as stale.

**Comment by paradoxon82** [comment]
I second that. It would be a really useful feature.

**Comment by codemiha** [comment]
This feature would be indeed handy to have

**Comment by PatrickGlatz** [comment]
Would be really nice to have
