### ISSUE TITLE
Implement truncate function for influxQL

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#9627]
__Proposal:__ add a `truncate` function which truncates a number to the specified number of decimal places

this would be useful for formatting values returned from agg functions

**Comment by jsternberg** [comment]
I'm not sure this issue is named correctly. Truncate is usually associated with truncating a float to an integer, not to a specific number of decimal spaces. So if you look at this play example (https://play.golang.org/p/yelnb9q5MkZ), you'll see the functionality. `floor()` always goes down, `ceil()` always goes up, `truncate()` will go down for positive numbers and up for negative numbers to get the integer component. All of these are probably useful and, I didn't actually realize there was a difference between floor and truncate until I just looked it up.

But when it comes to decimal points, I think this might be better named as a format function like `printf`. I think that's useful, but we also have to be careful to call it that. To get this kind of functionality, we would likely have to have a string output since I don't think there's a way to have a float with only 3 decimals of precision.

So maybe we should discuss having something similar to one of these?

```
SELECT printf('%.3f', x) FROM cpu
```

Or maybe `fmt` or something else.
