### ISSUE TITLE
Have problem querying data with http api(curl -G) when using curl -g and having slash in the query

### ISSUE THREAD

**Issue by GitGaryHuang** [influxdata/influxdb#9656]
I was trying to collecting data from influxdb by http api.
The database was created by heapster as i was using k8s cluster for experiment.
I found that there are slashes in most measurements as the picture below.

![image](https://user-images.githubusercontent.com/34566427/38092142-066ab93c-339a-11e8-96b7-04d7f606a428.png)

When I want to query data from such measurements by curl -G,  the error comes.

[root@k8s-master ~]# curl -G 'http://192.168.224.133:31818/query?pretty=true' --data-urlencode "db=k8s"  --data-urlencode "q=SELECT * FROM "cpu/usage""
{
    "error": "error parsing query: found /, expected ; at line 1, char 18"
}

I have tried many ways but all failed as you can see.

[root@k8s-master ~]# curl -G 'http://192.168.224.133:31818/query?pretty=true' --data-urlencode "db=k8s"  --data-urlencode "q=SELECT * FROM "cpu%2Fusage""
{
    "error": "error parsing query: found %, expected ; at line 1, char 18"
}
[root@k8s-master ~]# curl -G 'http://192.168.224.133:31818/query?pretty=true' --data-urlencode "db=k8s"  --data-urlencode "q=SELECT * FROM "cpu'/usage""
> ^C
[root@k8s-master ~]# curl -G 'http://192.168.224.133:31818/query?pretty=true' --data-urlencode "db=k8s"  --data-urlencode "q=SELECT * FROM "cpu'\'usage""
{
    "error": "error parsing query: found \\, expected ; at line 1, char 18"
}

I don't know how to deal with the slash "/" when I use the curl instruction and for some reason the curl instruction must be used in my problem.

**Comment by mark-rushakoff** [comment]
You do need to double quote the measurement because of the slash in the name. You're running into problems with your shell handling the entire `"q=SELECT * FROM "cpu/usage""` string.

Try ` ... --data-urlencode 'q=SELECT * FROM "cpu/usage"'` (single quotes on the outside), or try escaping the interior double quotes: `... --data-urlencode "q=SELECT * FROM \"cpu/usage\""`.  Use `curl -v` to see what curl is sending to the influxdb instance.
