### ISSUE TITLE
build failed.

### ISSUE THREAD

**Issue by crazy-canux** [influxdata/influxdb#9693]
influxdb-1.5.2

query/math.go:41:5: cannot use MathValuer literal (type MathValuer) as type influxql.CallValuer in assignment:
        MathValuer does not implement influxql.CallValuer (wrong type for Call method)
                have Call(string, []interface {}) (interface {}, bool)
                want Call(string, []influxql.Expr) (interface {}, bool)

**Comment by dgnorton** [comment]
@crazy-canux did you run `gdm restore` before building? I ran the build locally and it worked.
```
git checkout v1.5.2rc2 && gdm restore && go build ./...
```

**Comment by jsternberg** [comment]
That function isn't in 1.5.2. Are you sure you're not compiling from master?

If you're compiling from master, we have switched to using [dep](https://github.com/golang/dep) so run `dep ensure` before compiling.

The reason why I know this is because that function was added to a recent version of the influxql library for a feature that is going to be in 1.6 and the signature was also changed after the initial merge. So it looks  like you're compiling influxdb from master, but the influxql dependency is older.

I'm going to close this. If you continue to have problems compiling from source, comment and I'll try to help you out.
