### ISSUE TITLE
RATE function or values per second combined with :interval: template variable

### ISSUE THREAD

**Issue by lunemec** [influxdata/influxdb#9776]
Hello,
I'm not sure if this is a feature request or if this kind of functionality already exists.
I looked at #3976 and #4081.

First what I'm trying to accomplish: create a dashboard showing different groupings of requests/s hitting our servers. I'm using `SELECT sum("count") / 60 AS "requests per second" FROM "mydb"."autogen"."queries" WHERE time > :dashboardTime: GROUP BY time(1m), "server" FILL(0)`.
 
However this query gets slower and slower when showing large timespans because it returns data with 1 minute resolution.

My question is, can I somehow use `:interval:` template variable to group data again for the display?

EDIT: sorry my mistake, I'm using influx together with chronograf.

**Comment by dgnorton** [comment]
@lunemec Since this is more of a question, would you post it to the [InfluxData community site](https://community.influxdata.com/)? Then, if it turns out to be a bug / feature request post here with a link to the discussion on the community site and we'll reopen this issue and take it from there. Thanks!

**Comment by lunemec** [comment]
Hi, the question is posted here: https://community.influxdata.com/t/influx-queery-requests-success-rate/1858/6

But I didn’t get a response, maybe try creating new thread and link it here.
