### ISSUE TITLE
Bug Report ... influxdb crashes on query 

### ISSUE THREAD

**Issue by mohankchandrashekar** [influxdata/influxdb#9798]
### Directions
_GitHub Issues are reserved for actionable bug reports and feature requests._
_General questions should be sent to the [InfluxDB Community Site](https://community.influxdata.com)._

_Before opening an issue, search for similar bug reports or feature requests on GitHub Issues._
_If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
_Erase the other section and everything on and above this line._

### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
influxdb-1.5.0-1.x86_64

__Steps to reproduce:__

1. [First Step]
   > show SERIES from /HUGE.*/ where host =~ /^jtcl.*/ limit 10
ERR: %!s(<nil>)
> show SERIES from /HUGEPAGES/ where host =~ /^jtcl.*/ limit 10
ERR: Post http://localhost:8086/query?chunked=true&db=nmon_phx2&epoch=ns&q=show+SERIES+from+%2FHUGEPAGES%2F+where+host+%3D~+%2F%5Ejtcl.%2A%2F+limit+10: dial tcp 127.0.0.1:8086: getsockopt: connection refused

__Expected behavior:__ [What you expected to happen]

Influxdb should not crash.

__Actual behavior:__ [What actually happened]

when the query: show SERIES from /HUGEPAGES/ where host =~ /^jtcl.*/ limit 10 is run the influxdb can't find any series and instead of reporting "No records" it crashes. 

__Additional info:__ [Include gist of relevant config, logs, etc.]

ts=2018-05-02T14:40:57.644251Z lvl=info msg="Executing query" log_id=07pK99mW000 service=query query="SELECT \"key\" FROM nmon_phx2.days90._series WHERE (_name =~ /HUGE.*/) AND (host =~ /^jtcl.*/) LIMIT 10"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x91bb66]

goroutine 12032 [running]:
github.com/influxdata/influxdb/tsdb.SeriesIDIterators.Close(0xc4e63e2000, 0xc, 0x10, 0x411ec5, 0x413e4c)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:205 +0x66
github.com/influxdata/influxdb/tsdb.(*seriesIDMergeIterator).Close(0xc4a13a7c20, 0x180, 0x17f)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:368 +0x41
github.com/influxdata/influxdb/tsdb.IntersectSeriesIDIterators(0x0, 0x0, 0x12c3a40, 0xc4a13a7c20, 0x7fcf1b5640af, 0x6)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:418 +0x6e
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xc49239c940, 0x1, 0x1, 0xc42015d360, 0x7fcf1b5640af, 0x6, 0x3fff51, 0x12cae00, 0xc4e6992ea0, 0xc4e52256e0, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:1779 +0x38b
github.com/influxdata/influxdb/tsdb.IndexSet.measurementSeriesByExprIterator(0xc49239c940, 0x1, 0x1, 0xc42015d360, 0x7fcf1b5640af, 0x6, 0x3fff51, 0x12cae00, 0xc4e6992ea0, 0xc4a0338960, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:1704 +0x130
github.com/influxdata/influxdb/tsdb.IndexSet.MeasurementSeriesByExprIterator(0xc49239c940, 0x1, 0x1, 0xc42015d360, 0x7fcf1b5640af, 0x6, 0x3fff51, 0x12cae00, 0xc4e6992ea0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:1689 +0xec
github.com/influxdata/influxdb/tsdb.(*seriesPointIterator).readSeriesKeys(0xc499821340, 0x7fcf1b5640af, 0x6, 0x3fff51, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:747 +0xb6
github.com/influxdata/influxdb/tsdb.(*seriesPointIterator).Next(0xc499821340, 0x0, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:714 +0x425
github.com/influxdata/influxdb/query.(*floatSortedMergeIterator).pop(0xc4e01d5fb0, 0x2, 0xffffffffffffffff, 0xc514a97600)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:370 +0x115
github.com/influxdata/influxdb/query.(*floatSortedMergeIterator).Next(0xc4e01d5fb0, 0x0, 0xc495e8e190, 0x0)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:359 +0x2b
github.com/influxdata/influxdb/query.(*floatInterruptIterator).Next(0xc46fb0ece0, 0x0, 0x1, 0xc514a97600)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:852 +0x4f
github.com/influxdata/influxdb/query.(*floatInterruptIterator).Next(0xc46fb0ed20, 0xaef6a3, 0xaf0399, 0xc514a97610)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:852 +0x4f
github.com/influxdata/influxdb/query.(*floatInterruptIterator).Next(0xc46fb0ed40, 0xaf03b2, 0xc4d74e60f0, 0xe22180)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:852 +0x4f
github.com/influxdata/influxdb/query.(*floatFastDedupeIterator).Next(0xc46fb0ed60, 0x458670, 0xc4763fffd8, 0xc514a97730)
        /go/src/github.com/influxdata/influxdb/query/iterator.go:1517 +0x48
github.com/influxdata/influxdb/query.(*floatLimitIterator).Next(0xc42009e3c0, 0xc514a97798, 0xafd01d, 0x0)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:589 +0x37
github.com/influxdata/influxdb/query.(*bufFloatIterator).Next(0xc46fb0ede0, 0x0, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:90 +0x95
github.com/influxdata/influxdb/query.(*floatAuxIterator).stream(0xc4dfbff470)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:956 +0x32
created by github.com/influxdata/influxdb/query.(*floatAuxIterator).Start
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:936 +0x3f

**Comment by nothing2see** [comment]
We actually just started to experience a similar issue, except when running delete's from series. Hourly we have a job that runs that cleans out old hosts that have no reported into infuxdb in 7 days, and we remove all metrics about those hosts. Starting yesterday, with an upgrade to 1.5.2, from 1.4.3. I've turned off all the delete's that were running each hour and it's been stable for me since then.

ts=2018-05-02T06:59:13.295820Z lvl=info msg="Finished compacting files" log_id=07oqP21l000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=07ovCtfW000 op_name=tsm1_compact_group groups=8 files=1 duration=1637.372ms
ts=2018-05-02T06:59:13.295834Z lvl=info msg="TSM compaction (end)" log_id=07oqP21l000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=07ovCtfW000 op_name=tsm1_compact_group op_event=end op_elapsed=1637.379ms
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x91c0c6]

goroutine 9775223 [running]:
github.com/influxdata/influxdb/tsdb.SeriesIDIterators.Close(0xc472484200, 0xf, 0x10, 0x0, 0xc44d3e19c0)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:205 +0x66
github.com/influxdata/influxdb/tsdb.(*seriesIDMergeIterator).Close(0xc4724764b0, 0xc44d3e19d8, 0x3)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:368 +0x41
github.com/influxdata/influxdb/tsdb.(*filterUndeletedSeriesIDIterator).Close(0xc42ae61460, 0xc4202e54a0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:294 +0x34
panic(0xce65c0, 0x13059a0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/influxdata/influxdb/tsdb.(*seriesIDMergeIterator).Next(0xc4724764b0, 0xc44d3e1c88, 0xadbb9f, 0xc431d5ce10, 0xc44d3e1c58, 0x4123c7)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:381 +0xd7
github.com/influxdata/influxdb/tsdb.(*filterUndeletedSeriesIDIterator).Next(0xc42ae61460, 0x3a970, 0x3a980, 0xc4af57e000, 0xc420024000, 0x7fd164da3c78)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:299 +0x38
github.com/influxdata/influxdb/tsdb.(*seriesIteratorAdapter).Next(0xc42ae61480, 0x0, 0x2710, 0xc4af57e000, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:104 +0x49
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).DeleteSeriesRange(0xc440aea6c0, 0x12c6ae0, 0xc42ae61480, 0x8000000000000002, 0x7ffffffffffffffe, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1268 +0xeb
github.com/influxdata/influxdb/tsdb.(*Shard).DeleteSeriesRange(0xc42dabf6c0, 0x12c6ae0, 0xc42ae61480, 0x8000000000000002, 0x7ffffffffffffffe, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/shard.go:696 +0x8e
github.com/influxdata/influxdb/tsdb.(*Store).DeleteSeries.func1(0xc42dabf6c0, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/store.go:1167 +0x584
github.com/influxdata/influxdb/tsdb.(*Store).walkShards.func1(0xc49719eb40, 0xc45674a420, 0xc42dabf6c0)
        /go/src/github.com/influxdata/influxdb/tsdb/store.go:816 +0x48
created by github.com/influxdata/influxdb/tsdb.(*Store).walkShards
        /go/src/github.com/influxdata/influxdb/tsdb/store.go:815 +0x87

**Comment by nothing2see** [comment]
@dgnorton Yeah, looks like my tag issue is the same as #9849. However, the crashing of influxd seems to be independent of that. I realize now the original post and my first comment are not related to the influx client issue in my second comment. That first one is actually influxd dying with a panic. In my case, it's when doing a large delete from series.

I am running 1.5.2 and have restarted since the upgrade, but it still crashes.
