### ISSUE TITLE
Build custom indicators over timeseries with InfluxDB 

### ISSUE THREAD

**Issue by HornKild** [influxdata/influxdb#9809]
Hello,

I'm new with InfluxDB and I was wondering if it is possible to build custom query to calculate inficators over a timeserie ? My plan is to store large amount of price series from stocks in order to calculate moving average and other indicators with a very fast database engine. 

But with issue #77 I can see that it is not something possible with InfluxDB whereas it is possible with MYSQL (link to stackoverflow). 

Am'I missing something ?

Thanks,

https://stackoverflow.com/questions/16121023/calculating-a-moving-average-mysql
https://github.com/influxdata/influxdb/issues/77

**Comment by dgnorton** [comment]
@HornKild InfluxDB supports [moving average](https://docs.influxdata.com/influxdb/v1.5/query_language/functions/#moving-average). If you need a function not currently supported by InfluxDB, take a look at [Kapacitor](https://www.influxdata.com/time-series-platform/kapacitor/).

The [InfluxData community site](https://community.influxdata.com/) is the best place to ask usage questions and then create an issue if it turns out to be a bug or missing feature.
