### ISSUE TITLE
Histogram with logarithmic scaled buckets (or self-defined)

### ISSUE THREAD

**Issue by mradamczyk** [influxdata/influxdb#984]
Recently I've found *histogram* aggregate function. It's useful, but even more useful could be such a function but with logarithmic-scaled buckets (or defined ones). For example:

1-2ms, 2-4ms, 4-8ms, 8-16ms, 16-32ms, ...

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
