### ISSUE TITLE
influx_inspect deletetsm: Can't delete last measurement

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/influxdb#9929]
### Bug report

__System info:__ master on 31-may-2018, MacOS

__Steps to reproduce:__

1. List measurements in some TSM file containing only one measurement `influx_inspect dumptsm -all data/db/autogen/1/000000001-000000001.tsm`
2. Delete only measurement from that TSM file `influx_inspect deletetsm -measurement "m" data/db/autogen/1/000000001-000000001.tsm`
3. List measurements in that TSM file `influx_inspect dumptsm -all data/db/autogen/1/000000001-000000001.tsm`

__Expected behavior:__
Measurement does not exist in TSM file, or TSM file is deleted.

__Actual behavior:__
Measurement still exists. Error message "deletetsm: no values written".

Tested with TSM file containing 4 measurements, deleted oldest-to-newest. Tested again with TSM file containing 3 measurements, deleted newest-to-oldest.

**Comment by davidby-influx** [comment]
I believe the fix for this is to check for [ErrNoValues](https://github.com/influxdata/influxdb/blob/5fda409f39be40c0624fd1aaf38b63411b517725/tsdb/engine/tsm1/writer.go#L108) being returned from [WriteIndex](https://github.com/influxdata/influxdb/blob/5fda409f39be40c0624fd1aaf38b63411b517725/tsdb/engine/tsm1/writer.go#L712) and not treat that as an error [here](https://github.com/influxdata/influxdb/blob/5fda409f39be40c0624fd1aaf38b63411b517725/cmd/influx_inspect/deletetsm/deletetsm.go#L134)
