### ISSUE TITLE
Aggregate functions to return percentage of values larger or smaller than X

### ISSUE THREAD

**Issue by abh** [influxdata/influxdb#993]
One of my use cases is "percentage of value X that were larger than X". I can "fake it" by calculating a bunch of percentiles and looking at those, but it'd be nice to have a specific aggregate function to help with this.

**Comment by beckettsean** [comment]
As mentioned in my [post to the mailing list](https://groups.google.com/d/msg/influxdb/CkKzZoXDgiU/5E-vDNVGCwAJ) we are experimenting with simplifying our open GitHub Issues. This feature request has been rolled into an [aggregate issue](https://github.com/influxdata/influxdb/issues/5930) for all function requests, so that we can close this issue until we are ready to work on it. 

You may continue to make comments here. Closing the issue does not mean we are rejecting this idea.
