### ISSUE TITLE
Publish nightly build of InfluxDB to Quay

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/influxdb#9995]
__Proposal:__ 
Having a nightly tagged as nightly  -- like Chronograf see below -- for InfluxDB will allow us to integrate this into a "nightly" sandbox.  Essentially, we want to provide an option for folks to use either a stable build or a nightly build of our bits through a standard set of docker containers.

<img width="1416" alt="screen shot 2018-06-22 at 9 06 41 am" src="https://user-images.githubusercontent.com/23535264/41788359-3dcdeb76-7600-11e8-8124-1985205419ca.png">

__Current behavior:__ 
Nightly builds are produced, but not published to Quay.

__Desired behavior:__ 
Publish nightly build to Quay using a consistent tag name: nightly

__Use case:__ 
Leverage [Sandbox](https://github.com/influxdata/sandbox) infrastructure built to allow for rapid exploration....

**Comment by jsternberg** [comment]
The influxdb nightlies are apparently built on some old infrastructure on builds.influxdata.com. We will likely need to add GPG signing to it if we want to use those actual binaries.

We could do this in one of two ways. The first is to built from the actual nightly binaries. The second is to just build it from "master" nightly directly into a docker image. Both of these would work, but the first is likely more "correct". The second is probably easier though since doing this properly would likely require modifying the build on builds.influxdata.com.

Thoughts?

**Comment by jsternberg** [comment]
I have configured the build server to build and push the `nightly` and `nightly-alpine` images at 8:20 AM UTC every day. This should run after the nightly builds have succeeded. They will get pushed to quay.io and will not be available from the standard docker repository.

If you want these images, use these commands:

```
docker pull quay.io/influxdb/influxdb:nightly
```

OR

```
docker pull quay.io/influxdb/influxdb:nightly-alpine
```

I'm going to close this as it is set up and the images are there. I've tested the Jenkinsfile in a branch, but it hasn't technically run as a nightly yet. I'll check that it succeeded tomorrow morning. If it isn't working properly, I'll reopen this. Otherwise, I'm assuming it works since it worked in testing and the image is pushed.
